use KenticoCMS_PRD_prod3K7
GO 
if exists (select name from sys.tables where name = 'TEST_K7K8_View_EDW_RewardProgram_Joined' )
BEGIN
    DROP Table TEST_K7K8_View_EDW_RewardProgram_Joined
END
GO


--****************************************************
Select DISTINCT top 150 
     Published
    ,SiteName
    ,ClassName
    ,ClassDisplayName
    ,NodeID
    ,NodeAliasPath
    ,NodeName
    ,NodeAlias
    ,NodeClassID
    ,NodeParentID
    ,NodeLevel
    ,NodeACLID
    ,NodeSiteID
    ,NodeGUID
    ,NodeOrder
    ,IsSecuredNode
    ,NodeCacheMinutes
    ,NodeSKUID
    ,NodeDocType
    ,NodeHeadTags
    ,NodeBodyElementAttributes
    ,NodeInheritPageLevels
    ,RequiresSSL
    ,NodeLinkedNodeID
    ,NodeOwner
    ,NodeCustomData
    ,NodeGroupID
    ,NodeLinkedNodeSiteID
    ,NodeTemplateID
    ,NodeWireframeTemplateID
    ,NodeWireframeComment
    ,NodeTemplateForAllCultures
    ,NodeInheritPageTemplate
    ,NodeWireframeInheritPageLevels
    ,NodeAllowCacheInFileSystem
    ,DocumentID
    ,DocumentName
    ,DocumentNamePath
    ,DocumentModifiedWhen
    ,DocumentModifiedByUserID
    ,DocumentForeignKeyValue
    ,DocumentCreatedByUserID
    ,DocumentCreatedWhen
    ,DocumentCheckedOutByUserID
    ,DocumentCheckedOutWhen
    ,DocumentCheckedOutVersionHistoryID
    ,DocumentPublishedVersionHistoryID
    ,DocumentWorkflowStepID
    ,DocumentPublishFrom
    ,DocumentPublishTo
    ,DocumentUrlPath
    ,DocumentCulture
    ,DocumentNodeID
    ,DocumentPageTitle
    ,DocumentPageKeyWords
    ,DocumentPageDescription
    ,DocumentShowInSiteMap
    ,DocumentMenuItemHideInNavigation
    ,DocumentMenuCaption
    ,DocumentMenuStyle
    ,DocumentMenuItemImage
    ,DocumentMenuItemLeftImage
    ,DocumentMenuItemRightImage
    ,DocumentPageTemplateID
    ,DocumentMenuJavascript
    ,DocumentMenuRedirectUrl
    ,DocumentUseNamePathForUrlPath
    ,DocumentStylesheetID
    ,DocumentContent
    ,DocumentMenuClass
    ,DocumentMenuStyleOver
    ,DocumentMenuClassOver
    ,DocumentMenuItemImageOver
    ,DocumentMenuItemLeftImageOver
    ,DocumentMenuItemRightImageOver
    ,DocumentMenuStyleHighlighted
    ,DocumentMenuClassHighlighted
    ,DocumentMenuItemImageHighlighted
    ,DocumentMenuItemLeftImageHighlighted
    ,DocumentMenuItemRightImageHighlighted
    ,DocumentMenuItemInactive
    ,DocumentCustomData
    ,DocumentExtensions
    ,DocumentCampaign
    ,DocumentTags
    ,DocumentTagGroupID
    ,DocumentWildcardRule
    ,DocumentWebParts
    ,DocumentRatingValue
    ,DocumentRatings
    ,DocumentPriority
    ,DocumentType
    ,DocumentLastPublished
    ,DocumentUseCustomExtensions
    ,DocumentGroupWebParts
    ,DocumentCheckedOutAutomatically
    ,DocumentTrackConversionName
    ,DocumentConversionValue
    ,DocumentSearchExcluded
    ,DocumentLastVersionName
    ,DocumentLastVersionNumber
    ,DocumentIsArchived
    ,DocumentLastVersionType
    ,DocumentLastVersionMenuRedirectUrl
    ,DocumentHash
    ,DocumentLogVisitActivity
    ,DocumentGUID
    ,DocumentWorkflowCycleGUID
    ,DocumentSitemapSettings
    ,DocumentIsWaitingForTranslation
    ,DocumentSKUName
    ,DocumentSKUDescription
    ,DocumentSKUShortDescription
    ,DocumentWorkflowActionStatus
    ,SKUID
    ,SKUNumber
    ,SKUName
    ,SKUDescription
    ,SKUPrice
    ,SKUEnabled
    ,SKUDepartmentID
    ,SKUManufacturerID
    ,SKUInternalStatusID
    ,SKUPublicStatusID
    ,SKUSupplierID
    ,SKUAvailableInDays
    ,SKUGUID
    ,SKUImagePath
    ,SKUWeight
    ,SKUWidth
    ,SKUDepth
    ,SKUHeight
    ,SKUAvailableItems
    ,SKUSellOnlyAvailable
    ,SKUCustomData
    ,SKUOptionCategoryID
    ,SKUOrder
    ,SKULastModified
    ,SKUCreated
    ,SKUSiteID
    ,SKUPrivateDonation
    ,SKUNeedsShipping
    ,SKUMaxDownloads
    ,SKUValidUntil
    ,SKUProductType
    ,SKUMaxItemsInOrder
    ,SKUMaxPrice
    ,SKUValidity
    ,SKUValidFor
    ,SKUMinPrice
    ,SKUMembershipGUID
    ,SKUConversionName
    ,SKUConversionValue
    ,SKUBundleInventoryType
    ,SKUMinItemsInOrder
    ,SKURetailPrice
    ,SKUParentSKUID
    ,SKUAllowAllVariants
    ,SKUInheritsTaxClasses
    ,SKUInheritsDiscounts
    ,SKUTrackInventory
    ,SKUShortDescription
    ,SKUEproductFilesCount
    ,SKUBundleItemsCount
    ,SKUInStoreFrom
    ,SKUReorderAt
    ,NodeOwnerFullName
    ,NodeOwnerUserName
    ,NodeOwnerEmail
    ,RewardProgramID
    ,RewardProgramName
    ,RewardProgramPeriodEnd
    ,ProgramDescription
    ,RewardProgramPeriodStart
INTO KenticoCMS_PRD_prod3K7.dbo.TEST_K7K8_View_EDW_RewardProgram_Joined
FROM
KenticoCMS_PRD_prod3K7.dbo.View_EDW_RewardProgram_Joined;
--****************************************************
use KenticoCMS_PRD_prod3K8
GO 
if exists (select name from sys.tables where name = 'TEST_K7K8_View_EDW_RewardProgram_Joined' )
BEGIN
    DROP Table TEST_K7K8_View_EDW_RewardProgram_Joined
END
GO


--****************************************************
Select DISTINCT top 150 
     Published
    ,SiteName
    ,ClassName
    ,ClassDisplayName
    ,NodeID
    ,NodeAliasPath
    ,NodeName
    ,NodeAlias
    ,NodeClassID
    ,NodeParentID
    ,NodeLevel
    ,NodeACLID
    ,NodeSiteID
    ,NodeGUID
    ,NodeOrder
    ,IsSecuredNode
    ,NodeCacheMinutes
    ,NodeSKUID
    ,NodeDocType
    ,NodeHeadTags
    ,NodeBodyElementAttributes
    ,NodeInheritPageLevels
    ,RequiresSSL
    ,NodeLinkedNodeID
    ,NodeOwner
    ,NodeCustomData
    ,NodeGroupID
    ,NodeLinkedNodeSiteID
    ,NodeTemplateID
    ,NodeWireframeTemplateID
    ,NodeWireframeComment
    ,NodeTemplateForAllCultures
    ,NodeInheritPageTemplate
    ,NodeWireframeInheritPageLevels
    ,NodeAllowCacheInFileSystem
    ,DocumentID
    ,DocumentName
    ,DocumentNamePath
    ,DocumentModifiedWhen
    ,DocumentModifiedByUserID
    ,DocumentForeignKeyValue
    ,DocumentCreatedByUserID
    ,DocumentCreatedWhen
    ,DocumentCheckedOutByUserID
    ,DocumentCheckedOutWhen
    ,DocumentCheckedOutVersionHistoryID
    ,DocumentPublishedVersionHistoryID
    ,DocumentWorkflowStepID
    ,DocumentPublishFrom
    ,DocumentPublishTo
    ,DocumentUrlPath
    ,DocumentCulture
    ,DocumentNodeID
    ,DocumentPageTitle
    ,DocumentPageKeyWords
    ,DocumentPageDescription
    ,DocumentShowInSiteMap
    ,DocumentMenuItemHideInNavigation
    ,DocumentMenuCaption
    ,DocumentMenuStyle
    ,DocumentMenuItemImage
    ,DocumentMenuItemLeftImage
    ,DocumentMenuItemRightImage
    ,DocumentPageTemplateID
    ,DocumentMenuJavascript
    ,DocumentMenuRedirectUrl
    ,DocumentUseNamePathForUrlPath
    ,DocumentStylesheetID
    ,DocumentContent
    ,DocumentMenuClass
    ,DocumentMenuStyleOver
    ,DocumentMenuClassOver
    ,DocumentMenuItemImageOver
    ,DocumentMenuItemLeftImageOver
    ,DocumentMenuItemRightImageOver
    ,DocumentMenuStyleHighlighted
    ,DocumentMenuClassHighlighted
    ,DocumentMenuItemImageHighlighted
    ,DocumentMenuItemLeftImageHighlighted
    ,DocumentMenuItemRightImageHighlighted
    ,DocumentMenuItemInactive
    ,DocumentCustomData
    ,DocumentExtensions
    ,DocumentCampaign
    ,DocumentTags
    ,DocumentTagGroupID
    ,DocumentWildcardRule
    ,DocumentWebParts
    ,DocumentRatingValue
    ,DocumentRatings
    ,DocumentPriority
    ,DocumentType
    ,DocumentLastPublished
    ,DocumentUseCustomExtensions
    ,DocumentGroupWebParts
    ,DocumentCheckedOutAutomatically
    ,DocumentTrackConversionName
    ,DocumentConversionValue
    ,DocumentSearchExcluded
    ,DocumentLastVersionName
    ,DocumentLastVersionNumber
    ,DocumentIsArchived
    ,DocumentLastVersionType
    ,DocumentLastVersionMenuRedirectUrl
    ,DocumentHash
    ,DocumentLogVisitActivity
    ,DocumentGUID
    ,DocumentWorkflowCycleGUID
    ,DocumentSitemapSettings
    ,DocumentIsWaitingForTranslation
    ,DocumentSKUName
    ,DocumentSKUDescription
    ,DocumentSKUShortDescription
    ,DocumentWorkflowActionStatus
    ,SKUID
    ,SKUNumber
    ,SKUName
    ,SKUDescription
    ,SKUPrice
    ,SKUEnabled
    ,SKUDepartmentID
    ,SKUManufacturerID
    ,SKUInternalStatusID
    ,SKUPublicStatusID
    ,SKUSupplierID
    ,SKUAvailableInDays
    ,SKUGUID
    ,SKUImagePath
    ,SKUWeight
    ,SKUWidth
    ,SKUDepth
    ,SKUHeight
    ,SKUAvailableItems
    ,SKUSellOnlyAvailable
    ,SKUCustomData
    ,SKUOptionCategoryID
    ,SKUOrder
    ,SKULastModified
    ,SKUCreated
    ,SKUSiteID
    ,SKUPrivateDonation
    ,SKUNeedsShipping
    ,SKUMaxDownloads
    ,SKUValidUntil
    ,SKUProductType
    ,SKUMaxItemsInOrder
    ,SKUMaxPrice
    ,SKUValidity
    ,SKUValidFor
    ,SKUMinPrice
    ,SKUMembershipGUID
    ,SKUConversionName
    ,SKUConversionValue
    ,SKUBundleInventoryType
    ,SKUMinItemsInOrder
    ,SKURetailPrice
    ,SKUParentSKUID
    ,SKUAllowAllVariants
    ,SKUInheritsTaxClasses
    ,SKUInheritsDiscounts
    ,SKUTrackInventory
    ,SKUShortDescription
    ,SKUEproductFilesCount
    ,SKUBundleItemsCount
    ,SKUInStoreFrom
    ,SKUReorderAt
    ,NodeOwnerFullName
    ,NodeOwnerUserName
    ,NodeOwnerEmail
    ,RewardProgramID
    ,RewardProgramName
    ,RewardProgramPeriodEnd
    ,ProgramDescription
    ,RewardProgramPeriodStart
INTO KenticoCMS_PRD_prod3K8.dbo.TEST_K7K8_View_EDW_RewardProgram_Joined
FROM
KenticoCMS_PRD_prod3K8.dbo.View_EDW_RewardProgram_Joined;
--****************************************************
GO

select top 100 * from KenticoCMS_PRD_prod3K7.dbo.TEST_K7K8_View_EDW_RewardProgram_Joined order by NodeID, NodeParentID;

select top 100 * from KenticoCMS_PRD_prod3K8.dbo.TEST_K7K8_View_EDW_RewardProgram_Joined order by NodeID, NodeParentID;

--update HFit_EDW_K7K8_TestDDL set Passed = 1 where VIEW_NAME = 'View_EDW_RewardProgram_Joined'; 