'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace SVC_Gateway
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DS_SecureAttach", [Namespace]:="http://schemas.datacontract.org/2004/07/EcmSecureAttachWCF2"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DS_SecureAttach
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CSField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CompanyIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DisabledField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EncPWField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RepoIDField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CS() As String
            Get
                Return Me.CSField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CSField, value) <> true) Then
                    Me.CSField = value
                    Me.RaisePropertyChanged("CS")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CustomerID() As String
            Get
                Return Me.CompanyIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CompanyIDField, value) <> true) Then
                    Me.CompanyIDField = value
                    Me.RaisePropertyChanged("CustomerID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Disabled() As Boolean
            Get
                Return Me.DisabledField
            End Get
            Set
                If (Me.DisabledField.Equals(value) <> true) Then
                    Me.DisabledField = value
                    Me.RaisePropertyChanged("Disabled")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EncPW() As String
            Get
                Return Me.EncPWField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EncPWField, value) <> true) Then
                    Me.EncPWField = value
                    Me.RaisePropertyChanged("EncPW")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RepoID() As String
            Get
                Return Me.RepoIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RepoIDField, value) <> true) Then
                    Me.RepoIDField = value
                    Me.RaisePropertyChanged("RepoID")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CompositeType", [Namespace]:="http://schemas.datacontract.org/2004/07/EcmSecureAttachWCF2"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CompositeType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BoolValueField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StringValueField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BoolValue() As Boolean
            Get
                Return Me.BoolValueField
            End Get
            Set
                If (Me.BoolValueField.Equals(value) <> true) Then
                    Me.BoolValueField = value
                    Me.RaisePropertyChanged("BoolValue")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StringValue() As String
            Get
                Return Me.StringValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StringValueField, value) <> true) Then
                    Me.StringValueField = value
                    Me.RaisePropertyChanged("StringValue")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="SVC_Gateway.IService1")>  _
    Public Interface IService1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/ValidateUserLogin", ReplyAction:="http://tempuri.org/IService1/ValidateUserLoginResponse")>  _
        Function ValidateUserLogin(ByVal UID As String, ByVal EncPW As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/ValidateGatewayLogin", ReplyAction:="http://tempuri.org/IService1/ValidateGatewayLoginResponse")>  _
        Function ValidateGatewayLogin(ByVal CustomerID As String, ByVal RepoID As String, ByVal EncPW As String, ByRef RC As Boolean, ByRef RtnMsg As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/getSecureKey", ReplyAction:="http://tempuri.org/IService1/getSecureKeyResponse")>  _
        Function getSecureKey(ByVal CustomerID As String, ByVal RepoID As String, ByVal LoginPassword As String, ByRef RC As Boolean, ByRef RetMsg As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/PopulateCombo", ReplyAction:="http://tempuri.org/IService1/PopulateComboResponse")>  _
        Function PopulateCombo(ByVal CS As String, ByVal CustomerID As String, ByRef RC As Boolean, ByRef RetTxt As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/DeleteExistingConnection", ReplyAction:="http://tempuri.org/IService1/DeleteExistingConnectionResponse")>  _
        Function DeleteExistingConnection(ByVal ConnStr As String, ByVal CustomerID As String, ByVal EncPW As String, ByVal RepoID As String, ByVal CS As String, ByVal Disabled As Boolean, ByRef RC As Boolean, ByRef RtnMsg As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/PopulateGrid", ReplyAction:="http://tempuri.org/IService1/PopulateGridResponse")>  _
        Function PopulateGrid(ByVal CS As String, ByVal CustomerID As String, ByVal EncPW As String, ByRef RC As Boolean, ByRef RetTxt As String) As SVC_Gateway.DS_SecureAttach()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/saveConnection", ReplyAction:="http://tempuri.org/IService1/saveConnectionResponse")>  _
        Function saveConnection(ByVal ConnStr As String, ByVal CustomerID As String, ByVal EncPW As String, ByVal RepoID As String, ByVal CS As String, ByVal Disabled As Boolean, ByVal isThesaurus As Boolean, ByRef RC As Boolean, ByRef RtnMsg As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/AttachToSecureLoginDB", ReplyAction:="http://tempuri.org/IService1/AttachToSecureLoginDBResponse")>  _
        Function AttachToSecureLoginDB(ByVal ConnStr As String, ByRef RC As Boolean, ByRef RtnMsg As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetData", ReplyAction:="http://tempuri.org/IService1/GetDataResponse")>  _
        Function GetData(ByVal value As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction:="http://tempuri.org/IService1/GetDataUsingDataContractResponse")>  _
        Function GetDataUsingDataContract(ByVal composite As SVC_Gateway.CompositeType) As SVC_Gateway.CompositeType
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IService1Channel
        Inherits SVC_Gateway.IService1, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Service1Client
        Inherits System.ServiceModel.ClientBase(Of SVC_Gateway.IService1)
        Implements SVC_Gateway.IService1
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ValidateUserLogin(ByVal UID As String, ByVal EncPW As String) As Boolean Implements SVC_Gateway.IService1.ValidateUserLogin
            Return MyBase.Channel.ValidateUserLogin(UID, EncPW)
        End Function
        
        Public Function ValidateGatewayLogin(ByVal CustomerID As String, ByVal RepoID As String, ByVal EncPW As String, ByRef RC As Boolean, ByRef RtnMsg As String) As Boolean Implements SVC_Gateway.IService1.ValidateGatewayLogin
            Return MyBase.Channel.ValidateGatewayLogin(CustomerID, RepoID, EncPW, RC, RtnMsg)
        End Function
        
        Public Function getSecureKey(ByVal CustomerID As String, ByVal RepoID As String, ByVal LoginPassword As String, ByRef RC As Boolean, ByRef RetMsg As String) As String Implements SVC_Gateway.IService1.getSecureKey
            Return MyBase.Channel.getSecureKey(CustomerID, RepoID, LoginPassword, RC, RetMsg)
        End Function
        
        Public Function PopulateCombo(ByVal CS As String, ByVal CustomerID As String, ByRef RC As Boolean, ByRef RetTxt As String) As String Implements SVC_Gateway.IService1.PopulateCombo
            Return MyBase.Channel.PopulateCombo(CS, CustomerID, RC, RetTxt)
        End Function
        
        Public Function DeleteExistingConnection(ByVal ConnStr As String, ByVal CustomerID As String, ByVal EncPW As String, ByVal RepoID As String, ByVal CS As String, ByVal Disabled As Boolean, ByRef RC As Boolean, ByRef RtnMsg As String) As Boolean Implements SVC_Gateway.IService1.DeleteExistingConnection
            Return MyBase.Channel.DeleteExistingConnection(ConnStr, CustomerID, EncPW, RepoID, CS, Disabled, RC, RtnMsg)
        End Function
        
        Public Function PopulateGrid(ByVal CS As String, ByVal CustomerID As String, ByVal EncPW As String, ByRef RC As Boolean, ByRef RetTxt As String) As SVC_Gateway.DS_SecureAttach() Implements SVC_Gateway.IService1.PopulateGrid
            Return MyBase.Channel.PopulateGrid(CS, CustomerID, EncPW, RC, RetTxt)
        End Function
        
        Public Function saveConnection(ByVal ConnStr As String, ByVal CustomerID As String, ByVal EncPW As String, ByVal RepoID As String, ByVal CS As String, ByVal Disabled As Boolean, ByVal isThesaurus As Boolean, ByRef RC As Boolean, ByRef RtnMsg As String) As Boolean Implements SVC_Gateway.IService1.saveConnection
            Return MyBase.Channel.saveConnection(ConnStr, CustomerID, EncPW, RepoID, CS, Disabled, isThesaurus, RC, RtnMsg)
        End Function
        
        Public Function AttachToSecureLoginDB(ByVal ConnStr As String, ByRef RC As Boolean, ByRef RtnMsg As String) As Boolean Implements SVC_Gateway.IService1.AttachToSecureLoginDB
            Return MyBase.Channel.AttachToSecureLoginDB(ConnStr, RC, RtnMsg)
        End Function
        
        Public Function GetData(ByVal value As Integer) As String Implements SVC_Gateway.IService1.GetData
            Return MyBase.Channel.GetData(value)
        End Function
        
        Public Function GetDataUsingDataContract(ByVal composite As SVC_Gateway.CompositeType) As SVC_Gateway.CompositeType Implements SVC_Gateway.IService1.GetDataUsingDataContract
            Return MyBase.Channel.GetDataUsingDataContract(composite)
        End Function
    End Class
End Namespace
