USE [ECM.Library.FS];
GO
ALTER INDEX ALL ON dbo.DataSOurce REBUILD WITH(FILLFACTOR = 80, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON);
EXEC sp_fulltext_database 
     'enable';
ALTER FULLTEXT CATALOG ftCatalog REBUILD WITH ACCENT_SENSITIVITY = OFF;