'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace SVCclcDownload
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CompositeType", [Namespace]:="http://schemas.datacontract.org/2004/07/RestoreWCF"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CompositeType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BoolValueField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StringValueField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BoolValue() As Boolean
            Get
                Return Me.BoolValueField
            End Get
            Set
                If (Me.BoolValueField.Equals(value) <> true) Then
                    Me.BoolValueField = value
                    Me.RaisePropertyChanged("BoolValue")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StringValue() As String
            Get
                Return Me.StringValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StringValueField, value) <> true) Then
                    Me.StringValueField = value
                    Me.RaisePropertyChanged("StringValue")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="SVCclcDownload.IService1")>  _
    Public Interface IService1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/ckTest", ReplyAction:="http://tempuri.org/IService1/ckTestResponse")>  _
        Function ckTest(ByVal EncCS As String, ByVal UserID As String, ByVal RC As Boolean) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/ckTest", ReplyAction:="http://tempuri.org/IService1/ckTestResponse")>  _
        Function ckTestAsync(ByVal EncCS As String, ByVal UserID As String, ByVal RC As Boolean) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/getServiceVersion", ReplyAction:="http://tempuri.org/IService1/getServiceVersionResponse")>  _
        Function getServiceVersion() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/getServiceVersion", ReplyAction:="http://tempuri.org/IService1/getServiceVersionResponse")>  _
        Function getServiceVersionAsync() As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/cleanRestoreQue", ReplyAction:="http://tempuri.org/IService1/cleanRestoreQueResponse")>  _
        Function cleanRestoreQue(ByVal request As SVCclcDownload.cleanRestoreQueRequest) As SVCclcDownload.cleanRestoreQueResponse
        
        'CODEGEN: Generating message contract since the operation has multiple return values.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/cleanRestoreQue", ReplyAction:="http://tempuri.org/IService1/cleanRestoreQueResponse")>  _
        Function cleanRestoreQueAsync(ByVal request As SVCclcDownload.cleanRestoreQueRequest) As System.Threading.Tasks.Task(Of SVCclcDownload.cleanRestoreQueResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/ExecuteSqlNewConn", ReplyAction:="http://tempuri.org/IService1/ExecuteSqlNewConnResponse")>  _
        Function ExecuteSqlNewConn(ByVal request As SVCclcDownload.ExecuteSqlNewConnRequest) As SVCclcDownload.ExecuteSqlNewConnResponse
        
        'CODEGEN: Generating message contract since the operation has multiple return values.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/ExecuteSqlNewConn", ReplyAction:="http://tempuri.org/IService1/ExecuteSqlNewConnResponse")>  _
        Function ExecuteSqlNewConnAsync(ByVal request As SVCclcDownload.ExecuteSqlNewConnRequest) As System.Threading.Tasks.Task(Of SVCclcDownload.ExecuteSqlNewConnResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/getFileParameters", ReplyAction:="http://tempuri.org/IService1/getFileParametersResponse")>  _
        Function getFileParameters(ByVal request As SVCclcDownload.getFileParametersRequest) As SVCclcDownload.getFileParametersResponse
        
        'CODEGEN: Generating message contract since the operation has multiple return values.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/getFileParameters", ReplyAction:="http://tempuri.org/IService1/getFileParametersResponse")>  _
        Function getFileParametersAsync(ByVal request As SVCclcDownload.getFileParametersRequest) As System.Threading.Tasks.Task(Of SVCclcDownload.getFileParametersResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/getRestoreFileSourceGuid", ReplyAction:="http://tempuri.org/IService1/getRestoreFileSourceGuidResponse")>  _
        Function getRestoreFileSourceGuid(ByVal request As SVCclcDownload.getRestoreFileSourceGuidRequest) As SVCclcDownload.getRestoreFileSourceGuidResponse
        
        'CODEGEN: Generating message contract since the operation has multiple return values.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/getRestoreFileSourceGuid", ReplyAction:="http://tempuri.org/IService1/getRestoreFileSourceGuidResponse")>  _
        Function getRestoreFileSourceGuidAsync(ByVal request As SVCclcDownload.getRestoreFileSourceGuidRequest) As System.Threading.Tasks.Task(Of SVCclcDownload.getRestoreFileSourceGuidResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/getPreviewFileSourceGuid", ReplyAction:="http://tempuri.org/IService1/getPreviewFileSourceGuidResponse")>  _
        Function getPreviewFileSourceGuid(ByVal request As SVCclcDownload.getPreviewFileSourceGuidRequest) As SVCclcDownload.getPreviewFileSourceGuidResponse
        
        'CODEGEN: Generating message contract since the operation has multiple return values.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/getPreviewFileSourceGuid", ReplyAction:="http://tempuri.org/IService1/getPreviewFileSourceGuidResponse")>  _
        Function getPreviewFileSourceGuidAsync(ByVal request As SVCclcDownload.getPreviewFileSourceGuidRequest) As System.Threading.Tasks.Task(Of SVCclcDownload.getPreviewFileSourceGuidResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/ckRestoreFilesToProcess", ReplyAction:="http://tempuri.org/IService1/ckRestoreFilesToProcessResponse")>  _
        Function ckRestoreFilesToProcess(ByVal request As SVCclcDownload.ckRestoreFilesToProcessRequest) As SVCclcDownload.ckRestoreFilesToProcessResponse
        
        'CODEGEN: Generating message contract since the operation has multiple return values.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/ckRestoreFilesToProcess", ReplyAction:="http://tempuri.org/IService1/ckRestoreFilesToProcessResponse")>  _
        Function ckRestoreFilesToProcessAsync(ByVal request As SVCclcDownload.ckRestoreFilesToProcessRequest) As System.Threading.Tasks.Task(Of SVCclcDownload.ckRestoreFilesToProcessResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/ckPreviewFileToProcess", ReplyAction:="http://tempuri.org/IService1/ckPreviewFileToProcessResponse")>  _
        Function ckPreviewFileToProcess(ByVal EncCS As String, ByVal UserID As String, ByVal RC As Boolean) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/ckPreviewFileToProcess", ReplyAction:="http://tempuri.org/IService1/ckPreviewFileToProcessResponse")>  _
        Function ckPreviewFileToProcessAsync(ByVal EncCS As String, ByVal UserID As String, ByVal RC As Boolean) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/writeImageSourceDataFromDbWriteToFile", ReplyAction:="http://tempuri.org/IService1/writeImageSourceDataFromDbWriteToFileResponse")>  _
        Function writeImageSourceDataFromDbWriteToFile(ByVal request As SVCclcDownload.writeImageSourceDataFromDbWriteToFileRequest) As SVCclcDownload.writeImageSourceDataFromDbWriteToFileResponse
        
        'CODEGEN: Generating message contract since the operation has multiple return values.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/writeImageSourceDataFromDbWriteToFile", ReplyAction:="http://tempuri.org/IService1/writeImageSourceDataFromDbWriteToFileResponse")>  _
        Function writeImageSourceDataFromDbWriteToFileAsync(ByVal request As SVCclcDownload.writeImageSourceDataFromDbWriteToFileRequest) As System.Threading.Tasks.Task(Of SVCclcDownload.writeImageSourceDataFromDbWriteToFileResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/writeAttachmentFromDbWriteToFile", ReplyAction:="http://tempuri.org/IService1/writeAttachmentFromDbWriteToFileResponse")>  _
        Function writeAttachmentFromDbWriteToFile(ByVal request As SVCclcDownload.writeAttachmentFromDbWriteToFileRequest) As SVCclcDownload.writeAttachmentFromDbWriteToFileResponse
        
        'CODEGEN: Generating message contract since the operation has multiple return values.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/writeAttachmentFromDbWriteToFile", ReplyAction:="http://tempuri.org/IService1/writeAttachmentFromDbWriteToFileResponse")>  _
        Function writeAttachmentFromDbWriteToFileAsync(ByVal request As SVCclcDownload.writeAttachmentFromDbWriteToFileRequest) As System.Threading.Tasks.Task(Of SVCclcDownload.writeAttachmentFromDbWriteToFileResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/writeEmailFromDbToFile", ReplyAction:="http://tempuri.org/IService1/writeEmailFromDbToFileResponse")>  _
        Function writeEmailFromDbToFile(ByVal request As SVCclcDownload.writeEmailFromDbToFileRequest) As SVCclcDownload.writeEmailFromDbToFileResponse
        
        'CODEGEN: Generating message contract since the operation has multiple return values.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/writeEmailFromDbToFile", ReplyAction:="http://tempuri.org/IService1/writeEmailFromDbToFileResponse")>  _
        Function writeEmailFromDbToFileAsync(ByVal request As SVCclcDownload.writeEmailFromDbToFileRequest) As System.Threading.Tasks.Task(Of SVCclcDownload.writeEmailFromDbToFileResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetData", ReplyAction:="http://tempuri.org/IService1/GetDataResponse")>  _
        Function GetData(ByVal value As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetData", ReplyAction:="http://tempuri.org/IService1/GetDataResponse")>  _
        Function GetDataAsync(ByVal value As Integer) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction:="http://tempuri.org/IService1/GetDataUsingDataContractResponse")>  _
        Function GetDataUsingDataContract(ByVal composite As SVCclcDownload.CompositeType) As SVCclcDownload.CompositeType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction:="http://tempuri.org/IService1/GetDataUsingDataContractResponse")>  _
        Function GetDataUsingDataContractAsync(ByVal composite As SVCclcDownload.CompositeType) As System.Threading.Tasks.Task(Of SVCclcDownload.CompositeType)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="cleanRestoreQue", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class cleanRestoreQueRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public SecureID As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public SourceGuid As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2)>  _
        Public UserID As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=3)>  _
        Public SessionID As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=4)>  _
        Public RetMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SecureID As Integer, ByVal SourceGuid As String, ByVal UserID As String, ByVal SessionID As String, ByVal RetMsg As String)
            MyBase.New
            Me.SecureID = SecureID
            Me.SourceGuid = SourceGuid
            Me.UserID = UserID
            Me.SessionID = SessionID
            Me.RetMsg = RetMsg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="cleanRestoreQueResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class cleanRestoreQueResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public cleanRestoreQueResult As Boolean
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public RetMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal cleanRestoreQueResult As Boolean, ByVal RetMsg As String)
            MyBase.New
            Me.cleanRestoreQueResult = cleanRestoreQueResult
            Me.RetMsg = RetMsg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ExecuteSqlNewConn", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class ExecuteSqlNewConnRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public LocationID As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public UserID As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2)>  _
        Public MySql As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=3)>  _
        Public RetMsg As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=4)>  _
        Public SessionID As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal LocationID As Integer, ByVal UserID As String, ByVal MySql As String, ByVal RetMsg As String, ByVal SessionID As String)
            MyBase.New
            Me.LocationID = LocationID
            Me.UserID = UserID
            Me.MySql = MySql
            Me.RetMsg = RetMsg
            Me.SessionID = SessionID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ExecuteSqlNewConnResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class ExecuteSqlNewConnResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public ExecuteSqlNewConnResult As Boolean
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public RetMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ExecuteSqlNewConnResult As Boolean, ByVal RetMsg As String)
            MyBase.New
            Me.ExecuteSqlNewConnResult = ExecuteSqlNewConnResult
            Me.RetMsg = RetMsg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getFileParameters", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class getFileParametersRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public EncCS As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public TgtGuid As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2)>  _
        Public FileName As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=3)>  _
        Public fExt As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=4)>  _
        Public TgtTable As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=5)>  _
        Public RC As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EncCS As String, ByVal TgtGuid As String, ByVal FileName As String, ByVal fExt As String, ByVal TgtTable As String, ByVal RC As Boolean)
            MyBase.New
            Me.EncCS = EncCS
            Me.TgtGuid = TgtGuid
            Me.FileName = FileName
            Me.fExt = fExt
            Me.TgtTable = TgtTable
            Me.RC = RC
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getFileParametersResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class getFileParametersResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public FileName As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public fExt As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2)>  _
        Public RC As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal FileName As String, ByVal fExt As String, ByVal RC As Boolean)
            MyBase.New
            Me.FileName = FileName
            Me.fExt = fExt
            Me.RC = RC
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getRestoreFileSourceGuid", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class getRestoreFileSourceGuidRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public EncCS As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public UserID As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2)>  _
        Public RetGuids As System.Collections.Generic.Dictionary(Of String, String)
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=3)>  _
        Public RC As Boolean
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=4)>  _
        Public SessionID As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EncCS As String, ByVal UserID As String, ByVal RetGuids As System.Collections.Generic.Dictionary(Of String, String), ByVal RC As Boolean, ByVal SessionID As String)
            MyBase.New
            Me.EncCS = EncCS
            Me.UserID = UserID
            Me.RetGuids = RetGuids
            Me.RC = RC
            Me.SessionID = SessionID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getRestoreFileSourceGuidResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class getRestoreFileSourceGuidResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public RetGuids As System.Collections.Generic.Dictionary(Of String, String)
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public RC As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RetGuids As System.Collections.Generic.Dictionary(Of String, String), ByVal RC As Boolean)
            MyBase.New
            Me.RetGuids = RetGuids
            Me.RC = RC
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getPreviewFileSourceGuid", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class getPreviewFileSourceGuidRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public EncCS As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public UserID As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2)>  _
        Public RetGuids As System.Collections.Generic.Dictionary(Of String, String)
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=3)>  _
        Public RC As Boolean
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=4)>  _
        Public SessionID As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EncCS As String, ByVal UserID As String, ByVal RetGuids As System.Collections.Generic.Dictionary(Of String, String), ByVal RC As Boolean, ByVal SessionID As String)
            MyBase.New
            Me.EncCS = EncCS
            Me.UserID = UserID
            Me.RetGuids = RetGuids
            Me.RC = RC
            Me.SessionID = SessionID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getPreviewFileSourceGuidResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class getPreviewFileSourceGuidResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public RetGuids As System.Collections.Generic.Dictionary(Of String, String)
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public RC As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RetGuids As System.Collections.Generic.Dictionary(Of String, String), ByVal RC As Boolean)
            MyBase.New
            Me.RetGuids = RetGuids
            Me.RC = RC
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ckRestoreFilesToProcess", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class ckRestoreFilesToProcessRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public EncCS As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public UserID As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2)>  _
        Public RC As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EncCS As String, ByVal UserID As String, ByVal RC As Boolean)
            MyBase.New
            Me.EncCS = EncCS
            Me.UserID = UserID
            Me.RC = RC
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ckRestoreFilesToProcessResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class ckRestoreFilesToProcessResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public ckRestoreFilesToProcessResult As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public RC As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ckRestoreFilesToProcessResult As Integer, ByVal RC As Boolean)
            MyBase.New
            Me.ckRestoreFilesToProcessResult = ckRestoreFilesToProcessResult
            Me.RC = RC
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="writeImageSourceDataFromDbWriteToFile", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class writeImageSourceDataFromDbWriteToFileRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public EncCS As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public SourceGuid As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2)>  _
        Public FQN As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=3)>  _
        Public CompressedDataBuffer() As Byte
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=4)>  _
        Public OriginalSize As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=5)>  _
        Public CompressedSize As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=6)>  _
        Public RC As Boolean
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=7)>  _
        Public rMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EncCS As String, ByVal SourceGuid As String, ByVal FQN As String, ByVal CompressedDataBuffer() As Byte, ByVal OriginalSize As Integer, ByVal CompressedSize As Integer, ByVal RC As Boolean, ByVal rMsg As String)
            MyBase.New
            Me.EncCS = EncCS
            Me.SourceGuid = SourceGuid
            Me.FQN = FQN
            Me.CompressedDataBuffer = CompressedDataBuffer
            Me.OriginalSize = OriginalSize
            Me.CompressedSize = CompressedSize
            Me.RC = RC
            Me.rMsg = rMsg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="writeImageSourceDataFromDbWriteToFileResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class writeImageSourceDataFromDbWriteToFileResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public FQN As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public CompressedDataBuffer() As Byte
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2)>  _
        Public OriginalSize As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=3)>  _
        Public CompressedSize As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=4)>  _
        Public RC As Boolean
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=5)>  _
        Public rMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal FQN As String, ByVal CompressedDataBuffer() As Byte, ByVal OriginalSize As Integer, ByVal CompressedSize As Integer, ByVal RC As Boolean, ByVal rMsg As String)
            MyBase.New
            Me.FQN = FQN
            Me.CompressedDataBuffer = CompressedDataBuffer
            Me.OriginalSize = OriginalSize
            Me.CompressedSize = CompressedSize
            Me.RC = RC
            Me.rMsg = rMsg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="writeAttachmentFromDbWriteToFile", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class writeAttachmentFromDbWriteToFileRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public EncCS As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public RowID As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2)>  _
        Public FQN As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=3)>  _
        Public CompressedDataBuffer() As Byte
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=4)>  _
        Public OriginalSize As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=5)>  _
        Public CompressedSize As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=6)>  _
        Public RC As Boolean
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=7)>  _
        Public rMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EncCS As String, ByVal RowID As String, ByVal FQN As String, ByVal CompressedDataBuffer() As Byte, ByVal OriginalSize As Integer, ByVal CompressedSize As Integer, ByVal RC As Boolean, ByVal rMsg As String)
            MyBase.New
            Me.EncCS = EncCS
            Me.RowID = RowID
            Me.FQN = FQN
            Me.CompressedDataBuffer = CompressedDataBuffer
            Me.OriginalSize = OriginalSize
            Me.CompressedSize = CompressedSize
            Me.RC = RC
            Me.rMsg = rMsg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="writeAttachmentFromDbWriteToFileResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class writeAttachmentFromDbWriteToFileResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public FQN As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public CompressedDataBuffer() As Byte
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2)>  _
        Public OriginalSize As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=3)>  _
        Public CompressedSize As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=4)>  _
        Public RC As Boolean
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=5)>  _
        Public rMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal FQN As String, ByVal CompressedDataBuffer() As Byte, ByVal OriginalSize As Integer, ByVal CompressedSize As Integer, ByVal RC As Boolean, ByVal rMsg As String)
            MyBase.New
            Me.FQN = FQN
            Me.CompressedDataBuffer = CompressedDataBuffer
            Me.OriginalSize = OriginalSize
            Me.CompressedSize = CompressedSize
            Me.RC = RC
            Me.rMsg = rMsg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="writeEmailFromDbToFile", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class writeEmailFromDbToFileRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public EncCS As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public EmailGuid As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2)>  _
        Public SourceTypeCode As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=3)>  _
        Public CompressedDataBuffer() As Byte
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=4)>  _
        Public OriginalSize As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=5)>  _
        Public CompressedSize As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=6)>  _
        Public RC As Boolean
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=7)>  _
        Public rMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EncCS As String, ByVal EmailGuid As String, ByVal SourceTypeCode As String, ByVal CompressedDataBuffer() As Byte, ByVal OriginalSize As Integer, ByVal CompressedSize As Integer, ByVal RC As Boolean, ByVal rMsg As String)
            MyBase.New
            Me.EncCS = EncCS
            Me.EmailGuid = EmailGuid
            Me.SourceTypeCode = SourceTypeCode
            Me.CompressedDataBuffer = CompressedDataBuffer
            Me.OriginalSize = OriginalSize
            Me.CompressedSize = CompressedSize
            Me.RC = RC
            Me.rMsg = rMsg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="writeEmailFromDbToFileResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class writeEmailFromDbToFileResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public SourceTypeCode As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public CompressedDataBuffer() As Byte
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2)>  _
        Public OriginalSize As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=3)>  _
        Public CompressedSize As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=4)>  _
        Public RC As Boolean
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=5)>  _
        Public rMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SourceTypeCode As String, ByVal CompressedDataBuffer() As Byte, ByVal OriginalSize As Integer, ByVal CompressedSize As Integer, ByVal RC As Boolean, ByVal rMsg As String)
            MyBase.New
            Me.SourceTypeCode = SourceTypeCode
            Me.CompressedDataBuffer = CompressedDataBuffer
            Me.OriginalSize = OriginalSize
            Me.CompressedSize = CompressedSize
            Me.RC = RC
            Me.rMsg = rMsg
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IService1Channel
        Inherits SVCclcDownload.IService1, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Service1Client
        Inherits System.ServiceModel.ClientBase(Of SVCclcDownload.IService1)
        Implements SVCclcDownload.IService1
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ckTest(ByVal EncCS As String, ByVal UserID As String, ByVal RC As Boolean) As Integer Implements SVCclcDownload.IService1.ckTest
            Return MyBase.Channel.ckTest(EncCS, UserID, RC)
        End Function
        
        Public Function ckTestAsync(ByVal EncCS As String, ByVal UserID As String, ByVal RC As Boolean) As System.Threading.Tasks.Task(Of Integer) Implements SVCclcDownload.IService1.ckTestAsync
            Return MyBase.Channel.ckTestAsync(EncCS, UserID, RC)
        End Function
        
        Public Function getServiceVersion() As String Implements SVCclcDownload.IService1.getServiceVersion
            Return MyBase.Channel.getServiceVersion
        End Function
        
        Public Function getServiceVersionAsync() As System.Threading.Tasks.Task(Of String) Implements SVCclcDownload.IService1.getServiceVersionAsync
            Return MyBase.Channel.getServiceVersionAsync
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SVCclcDownload_IService1_cleanRestoreQue(ByVal request As SVCclcDownload.cleanRestoreQueRequest) As SVCclcDownload.cleanRestoreQueResponse Implements SVCclcDownload.IService1.cleanRestoreQue
            Return MyBase.Channel.cleanRestoreQue(request)
        End Function
        
        Public Function cleanRestoreQue(ByVal SecureID As Integer, ByVal SourceGuid As String, ByVal UserID As String, ByVal SessionID As String, ByRef RetMsg As String) As Boolean
            Dim inValue As SVCclcDownload.cleanRestoreQueRequest = New SVCclcDownload.cleanRestoreQueRequest()
            inValue.SecureID = SecureID
            inValue.SourceGuid = SourceGuid
            inValue.UserID = UserID
            inValue.SessionID = SessionID
            inValue.RetMsg = RetMsg
            Dim retVal As SVCclcDownload.cleanRestoreQueResponse = CType(Me,SVCclcDownload.IService1).cleanRestoreQue(inValue)
            RetMsg = retVal.RetMsg
            Return retVal.cleanRestoreQueResult
        End Function
        
        Public Function cleanRestoreQueAsync(ByVal request As SVCclcDownload.cleanRestoreQueRequest) As System.Threading.Tasks.Task(Of SVCclcDownload.cleanRestoreQueResponse) Implements SVCclcDownload.IService1.cleanRestoreQueAsync
            Return MyBase.Channel.cleanRestoreQueAsync(request)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SVCclcDownload_IService1_ExecuteSqlNewConn(ByVal request As SVCclcDownload.ExecuteSqlNewConnRequest) As SVCclcDownload.ExecuteSqlNewConnResponse Implements SVCclcDownload.IService1.ExecuteSqlNewConn
            Return MyBase.Channel.ExecuteSqlNewConn(request)
        End Function
        
        Public Function ExecuteSqlNewConn(ByVal LocationID As Integer, ByVal UserID As String, ByVal MySql As String, ByRef RetMsg As String, ByVal SessionID As String) As Boolean
            Dim inValue As SVCclcDownload.ExecuteSqlNewConnRequest = New SVCclcDownload.ExecuteSqlNewConnRequest()
            inValue.LocationID = LocationID
            inValue.UserID = UserID
            inValue.MySql = MySql
            inValue.RetMsg = RetMsg
            inValue.SessionID = SessionID
            Dim retVal As SVCclcDownload.ExecuteSqlNewConnResponse = CType(Me,SVCclcDownload.IService1).ExecuteSqlNewConn(inValue)
            RetMsg = retVal.RetMsg
            Return retVal.ExecuteSqlNewConnResult
        End Function
        
        Public Function ExecuteSqlNewConnAsync(ByVal request As SVCclcDownload.ExecuteSqlNewConnRequest) As System.Threading.Tasks.Task(Of SVCclcDownload.ExecuteSqlNewConnResponse) Implements SVCclcDownload.IService1.ExecuteSqlNewConnAsync
            Return MyBase.Channel.ExecuteSqlNewConnAsync(request)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SVCclcDownload_IService1_getFileParameters(ByVal request As SVCclcDownload.getFileParametersRequest) As SVCclcDownload.getFileParametersResponse Implements SVCclcDownload.IService1.getFileParameters
            Return MyBase.Channel.getFileParameters(request)
        End Function
        
        Public Sub getFileParameters(ByVal EncCS As String, ByVal TgtGuid As String, ByRef FileName As String, ByRef fExt As String, ByVal TgtTable As String, ByRef RC As Boolean)
            Dim inValue As SVCclcDownload.getFileParametersRequest = New SVCclcDownload.getFileParametersRequest()
            inValue.EncCS = EncCS
            inValue.TgtGuid = TgtGuid
            inValue.FileName = FileName
            inValue.fExt = fExt
            inValue.TgtTable = TgtTable
            inValue.RC = RC
            Dim retVal As SVCclcDownload.getFileParametersResponse = CType(Me,SVCclcDownload.IService1).getFileParameters(inValue)
            FileName = retVal.FileName
            fExt = retVal.fExt
            RC = retVal.RC
        End Sub
        
        Public Function getFileParametersAsync(ByVal request As SVCclcDownload.getFileParametersRequest) As System.Threading.Tasks.Task(Of SVCclcDownload.getFileParametersResponse) Implements SVCclcDownload.IService1.getFileParametersAsync
            Return MyBase.Channel.getFileParametersAsync(request)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SVCclcDownload_IService1_getRestoreFileSourceGuid(ByVal request As SVCclcDownload.getRestoreFileSourceGuidRequest) As SVCclcDownload.getRestoreFileSourceGuidResponse Implements SVCclcDownload.IService1.getRestoreFileSourceGuid
            Return MyBase.Channel.getRestoreFileSourceGuid(request)
        End Function
        
        Public Sub getRestoreFileSourceGuid(ByVal EncCS As String, ByVal UserID As String, ByRef RetGuids As System.Collections.Generic.Dictionary(Of String, String), ByRef RC As Boolean, ByVal SessionID As String)
            Dim inValue As SVCclcDownload.getRestoreFileSourceGuidRequest = New SVCclcDownload.getRestoreFileSourceGuidRequest()
            inValue.EncCS = EncCS
            inValue.UserID = UserID
            inValue.RetGuids = RetGuids
            inValue.RC = RC
            inValue.SessionID = SessionID
            Dim retVal As SVCclcDownload.getRestoreFileSourceGuidResponse = CType(Me,SVCclcDownload.IService1).getRestoreFileSourceGuid(inValue)
            RetGuids = retVal.RetGuids
            RC = retVal.RC
        End Sub
        
        Public Function getRestoreFileSourceGuidAsync(ByVal request As SVCclcDownload.getRestoreFileSourceGuidRequest) As System.Threading.Tasks.Task(Of SVCclcDownload.getRestoreFileSourceGuidResponse) Implements SVCclcDownload.IService1.getRestoreFileSourceGuidAsync
            Return MyBase.Channel.getRestoreFileSourceGuidAsync(request)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SVCclcDownload_IService1_getPreviewFileSourceGuid(ByVal request As SVCclcDownload.getPreviewFileSourceGuidRequest) As SVCclcDownload.getPreviewFileSourceGuidResponse Implements SVCclcDownload.IService1.getPreviewFileSourceGuid
            Return MyBase.Channel.getPreviewFileSourceGuid(request)
        End Function
        
        Public Sub getPreviewFileSourceGuid(ByVal EncCS As String, ByVal UserID As String, ByRef RetGuids As System.Collections.Generic.Dictionary(Of String, String), ByRef RC As Boolean, ByVal SessionID As String)
            Dim inValue As SVCclcDownload.getPreviewFileSourceGuidRequest = New SVCclcDownload.getPreviewFileSourceGuidRequest()
            inValue.EncCS = EncCS
            inValue.UserID = UserID
            inValue.RetGuids = RetGuids
            inValue.RC = RC
            inValue.SessionID = SessionID
            Dim retVal As SVCclcDownload.getPreviewFileSourceGuidResponse = CType(Me,SVCclcDownload.IService1).getPreviewFileSourceGuid(inValue)
            RetGuids = retVal.RetGuids
            RC = retVal.RC
        End Sub
        
        Public Function getPreviewFileSourceGuidAsync(ByVal request As SVCclcDownload.getPreviewFileSourceGuidRequest) As System.Threading.Tasks.Task(Of SVCclcDownload.getPreviewFileSourceGuidResponse) Implements SVCclcDownload.IService1.getPreviewFileSourceGuidAsync
            Return MyBase.Channel.getPreviewFileSourceGuidAsync(request)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SVCclcDownload_IService1_ckRestoreFilesToProcess(ByVal request As SVCclcDownload.ckRestoreFilesToProcessRequest) As SVCclcDownload.ckRestoreFilesToProcessResponse Implements SVCclcDownload.IService1.ckRestoreFilesToProcess
            Return MyBase.Channel.ckRestoreFilesToProcess(request)
        End Function
        
        Public Function ckRestoreFilesToProcess(ByVal EncCS As String, ByVal UserID As String, ByRef RC As Boolean) As Integer
            Dim inValue As SVCclcDownload.ckRestoreFilesToProcessRequest = New SVCclcDownload.ckRestoreFilesToProcessRequest()
            inValue.EncCS = EncCS
            inValue.UserID = UserID
            inValue.RC = RC
            Dim retVal As SVCclcDownload.ckRestoreFilesToProcessResponse = CType(Me,SVCclcDownload.IService1).ckRestoreFilesToProcess(inValue)
            RC = retVal.RC
            Return retVal.ckRestoreFilesToProcessResult
        End Function
        
        Public Function ckRestoreFilesToProcessAsync(ByVal request As SVCclcDownload.ckRestoreFilesToProcessRequest) As System.Threading.Tasks.Task(Of SVCclcDownload.ckRestoreFilesToProcessResponse) Implements SVCclcDownload.IService1.ckRestoreFilesToProcessAsync
            Return MyBase.Channel.ckRestoreFilesToProcessAsync(request)
        End Function
        
        Public Function ckPreviewFileToProcess(ByVal EncCS As String, ByVal UserID As String, ByVal RC As Boolean) As Integer Implements SVCclcDownload.IService1.ckPreviewFileToProcess
            Return MyBase.Channel.ckPreviewFileToProcess(EncCS, UserID, RC)
        End Function
        
        Public Function ckPreviewFileToProcessAsync(ByVal EncCS As String, ByVal UserID As String, ByVal RC As Boolean) As System.Threading.Tasks.Task(Of Integer) Implements SVCclcDownload.IService1.ckPreviewFileToProcessAsync
            Return MyBase.Channel.ckPreviewFileToProcessAsync(EncCS, UserID, RC)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SVCclcDownload_IService1_writeImageSourceDataFromDbWriteToFile(ByVal request As SVCclcDownload.writeImageSourceDataFromDbWriteToFileRequest) As SVCclcDownload.writeImageSourceDataFromDbWriteToFileResponse Implements SVCclcDownload.IService1.writeImageSourceDataFromDbWriteToFile
            Return MyBase.Channel.writeImageSourceDataFromDbWriteToFile(request)
        End Function
        
        Public Sub writeImageSourceDataFromDbWriteToFile(ByVal EncCS As String, ByVal SourceGuid As String, ByRef FQN As String, ByRef CompressedDataBuffer() As Byte, ByRef OriginalSize As Integer, ByRef CompressedSize As Integer, ByRef RC As Boolean, ByRef rMsg As String)
            Dim inValue As SVCclcDownload.writeImageSourceDataFromDbWriteToFileRequest = New SVCclcDownload.writeImageSourceDataFromDbWriteToFileRequest()
            inValue.EncCS = EncCS
            inValue.SourceGuid = SourceGuid
            inValue.FQN = FQN
            inValue.CompressedDataBuffer = CompressedDataBuffer
            inValue.OriginalSize = OriginalSize
            inValue.CompressedSize = CompressedSize
            inValue.RC = RC
            inValue.rMsg = rMsg
            Dim retVal As SVCclcDownload.writeImageSourceDataFromDbWriteToFileResponse = CType(Me,SVCclcDownload.IService1).writeImageSourceDataFromDbWriteToFile(inValue)
            FQN = retVal.FQN
            CompressedDataBuffer = retVal.CompressedDataBuffer
            OriginalSize = retVal.OriginalSize
            CompressedSize = retVal.CompressedSize
            RC = retVal.RC
            rMsg = retVal.rMsg
        End Sub
        
        Public Function writeImageSourceDataFromDbWriteToFileAsync(ByVal request As SVCclcDownload.writeImageSourceDataFromDbWriteToFileRequest) As System.Threading.Tasks.Task(Of SVCclcDownload.writeImageSourceDataFromDbWriteToFileResponse) Implements SVCclcDownload.IService1.writeImageSourceDataFromDbWriteToFileAsync
            Return MyBase.Channel.writeImageSourceDataFromDbWriteToFileAsync(request)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SVCclcDownload_IService1_writeAttachmentFromDbWriteToFile(ByVal request As SVCclcDownload.writeAttachmentFromDbWriteToFileRequest) As SVCclcDownload.writeAttachmentFromDbWriteToFileResponse Implements SVCclcDownload.IService1.writeAttachmentFromDbWriteToFile
            Return MyBase.Channel.writeAttachmentFromDbWriteToFile(request)
        End Function
        
        Public Sub writeAttachmentFromDbWriteToFile(ByVal EncCS As String, ByVal RowID As String, ByRef FQN As String, ByRef CompressedDataBuffer() As Byte, ByRef OriginalSize As Integer, ByRef CompressedSize As Integer, ByRef RC As Boolean, ByRef rMsg As String)
            Dim inValue As SVCclcDownload.writeAttachmentFromDbWriteToFileRequest = New SVCclcDownload.writeAttachmentFromDbWriteToFileRequest()
            inValue.EncCS = EncCS
            inValue.RowID = RowID
            inValue.FQN = FQN
            inValue.CompressedDataBuffer = CompressedDataBuffer
            inValue.OriginalSize = OriginalSize
            inValue.CompressedSize = CompressedSize
            inValue.RC = RC
            inValue.rMsg = rMsg
            Dim retVal As SVCclcDownload.writeAttachmentFromDbWriteToFileResponse = CType(Me,SVCclcDownload.IService1).writeAttachmentFromDbWriteToFile(inValue)
            FQN = retVal.FQN
            CompressedDataBuffer = retVal.CompressedDataBuffer
            OriginalSize = retVal.OriginalSize
            CompressedSize = retVal.CompressedSize
            RC = retVal.RC
            rMsg = retVal.rMsg
        End Sub
        
        Public Function writeAttachmentFromDbWriteToFileAsync(ByVal request As SVCclcDownload.writeAttachmentFromDbWriteToFileRequest) As System.Threading.Tasks.Task(Of SVCclcDownload.writeAttachmentFromDbWriteToFileResponse) Implements SVCclcDownload.IService1.writeAttachmentFromDbWriteToFileAsync
            Return MyBase.Channel.writeAttachmentFromDbWriteToFileAsync(request)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SVCclcDownload_IService1_writeEmailFromDbToFile(ByVal request As SVCclcDownload.writeEmailFromDbToFileRequest) As SVCclcDownload.writeEmailFromDbToFileResponse Implements SVCclcDownload.IService1.writeEmailFromDbToFile
            Return MyBase.Channel.writeEmailFromDbToFile(request)
        End Function
        
        Public Sub writeEmailFromDbToFile(ByVal EncCS As String, ByVal EmailGuid As String, ByRef SourceTypeCode As String, ByRef CompressedDataBuffer() As Byte, ByRef OriginalSize As Integer, ByRef CompressedSize As Integer, ByRef RC As Boolean, ByRef rMsg As String)
            Dim inValue As SVCclcDownload.writeEmailFromDbToFileRequest = New SVCclcDownload.writeEmailFromDbToFileRequest()
            inValue.EncCS = EncCS
            inValue.EmailGuid = EmailGuid
            inValue.SourceTypeCode = SourceTypeCode
            inValue.CompressedDataBuffer = CompressedDataBuffer
            inValue.OriginalSize = OriginalSize
            inValue.CompressedSize = CompressedSize
            inValue.RC = RC
            inValue.rMsg = rMsg
            Dim retVal As SVCclcDownload.writeEmailFromDbToFileResponse = CType(Me,SVCclcDownload.IService1).writeEmailFromDbToFile(inValue)
            SourceTypeCode = retVal.SourceTypeCode
            CompressedDataBuffer = retVal.CompressedDataBuffer
            OriginalSize = retVal.OriginalSize
            CompressedSize = retVal.CompressedSize
            RC = retVal.RC
            rMsg = retVal.rMsg
        End Sub
        
        Public Function writeEmailFromDbToFileAsync(ByVal request As SVCclcDownload.writeEmailFromDbToFileRequest) As System.Threading.Tasks.Task(Of SVCclcDownload.writeEmailFromDbToFileResponse) Implements SVCclcDownload.IService1.writeEmailFromDbToFileAsync
            Return MyBase.Channel.writeEmailFromDbToFileAsync(request)
        End Function
        
        Public Function GetData(ByVal value As Integer) As String Implements SVCclcDownload.IService1.GetData
            Return MyBase.Channel.GetData(value)
        End Function
        
        Public Function GetDataAsync(ByVal value As Integer) As System.Threading.Tasks.Task(Of String) Implements SVCclcDownload.IService1.GetDataAsync
            Return MyBase.Channel.GetDataAsync(value)
        End Function
        
        Public Function GetDataUsingDataContract(ByVal composite As SVCclcDownload.CompositeType) As SVCclcDownload.CompositeType Implements SVCclcDownload.IService1.GetDataUsingDataContract
            Return MyBase.Channel.GetDataUsingDataContract(composite)
        End Function
        
        Public Function GetDataUsingDataContractAsync(ByVal composite As SVCclcDownload.CompositeType) As System.Threading.Tasks.Task(Of SVCclcDownload.CompositeType) Implements SVCclcDownload.IService1.GetDataUsingDataContractAsync
            Return MyBase.Channel.GetDataUsingDataContractAsync(composite)
        End Function
    End Class
End Namespace
