/** ADD THE NEW INTEGER INVOICE NUMBER COLUMN **/
Alter table DM_F_POS_SALES add INVOICE_NUMBER_INT int null
go

update DBO.DM_F_POS_SALES
	SET INVOICE_NUMBER_INT = cast(INVOICE_NUMBER as int)
	where INVOICE_NUMBER is not null 
	and isnumeric(INVOICE_NUMBER) = 1 
go

CREATE NONCLUSTERED INDEX [PI_INVOICE_NUMBER_INT] ON [dbo].[DM_F_POS_SALES] 
(
	[INVOICE_NUMBER_INT] ASC
)
go

drop trigger [dbo].[DM_F_POS_SALES_Insert]
go
/** ADD TRIGGER TO KEEP THE INVOICE NUMBER IN SYNC **/
Create TRIGGER [dbo].[DM_F_POS_SALES_Insert]
   ON [dbo].[DM_F_POS_SALES]
   after insert
 AS
 BEGIN
   IF ( @@ROWCOUNT = 0 )
                 Return
   IF TRIGGER_NESTLEVEL() > 1
                 Return
    BEGIN TRY
		UPDATE DM_F_POS_SALES
			SET INVOICE_NUMBER_INT = cast(INVOICE_NUMBER as int)
			FROM DataSource t
			JOIN inserted i
			ON 
			t.POS_SALE_KEY = i.POS_SALE_KEY		
	END TRY
	BEGIN CATCH
		UPDATE DM_F_POS_SALES
		SET INVOICE_NUMBER_INT = NULL
		FROM DataSource t
		JOIN inserted i
		ON 
		t.POS_SALE_KEY = i.POS_SALE_KEY
	END CATCH   
END


/** TESTING DATA */
SELECT TOP 10 * FROM DBO.DM_F_POS_SALES where INVOICE_NUMBER is not null
GO
update DBO.DM_F_POS_SALES
	SET INVOICE_NUMBER_INT = cast(INVOICE_NUMBER as int)
	where POS_SALE_KEY in (3680594
	,3680595
	,3680596
	,3680597
	,3680598)

/** TESTING DATA */
SELECT TOP 10 * FROM DBO.DM_F_POS_SALES 
where INVOICE_NUMBER is not null
AND ISNUMERIC(INVOICE_NUMBER) != 1
GO
update DBO.DM_F_POS_SALES
	SET INVOICE_NUMBER_INT = cast(INVOICE_NUMBER as int)
	where POS_SALE_KEY in (3539743
	,3519358
	,3361680
	,3391684
	,3525236)
