USE [SMART]
GO

/****** Object:  View [dbo].[GLOBAL_POS]    Script Date: 09/23/2010 14:43:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER OFF
GO
DROP view [dbo].[GLOBAL_POS_V2] 
GO
CREATE view [dbo].[GLOBAL_POS_V2] AS

SELECT
 	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2' AND P.MANUFACTURER_NAME LIKE 'HIR%') THEN 'STDMHM'
		ELSE P.SRC_SYS_ID END	AS SRC_SYS_ID,
	CASE WHEN (P.SRC_SYS_ID='BPCSEU') THEN 'EMEA'
		 WHEN (P.SRC_SYS_ID='BPCSRI') THEN 'BAG'
		 WHEN (P.SRC_SYS_ID='BPCSCO') THEN 'BAG'
		 WHEN (P.SRC_SYS_ID='BPCSMH') THEN 'BAG'
		 WHEN (P.SRC_SYS_ID='BPCSAL') THEN 'BAG'
		 WHEN (P.SRC_SYS_ID='STDMWP') THEN 'BAG'
		 WHEN (P.SRC_SYS_ID='THERMX') THEN 'BAG'
		 WHEN (P.SRC_SYS_ID='ASIASR') THEN 'APAC'
	ELSE
	 	 'UNKNOWN'
	END	AS DIVISION_GRP,

	CASE WHEN (P.SRC_SYS_ID='BPCSEU') THEN 'Cable'
		 WHEN (P.SRC_SYS_ID='BPCSRI') THEN 'Americas'
		 WHEN (P.SRC_SYS_ID='BPCSCO') THEN 'Americas'
		 WHEN (P.SRC_SYS_ID='BPCSMH') THEN 'Mohawk'
		 WHEN (P.SRC_SYS_ID='BPCSAL') THEN 'AMD'
		 WHEN (P.SRC_SYS_ID='STDMWP') THEN 'WPW'
		 WHEN (P.SRC_SYS_ID='THERMX') THEN 'Thermax'
		 WHEN (P.SRC_SYS_ID='ASIASR') THEN 'BAP'
	ELSE
	 	 'UNKNOWN'
	END	AS BUSINESSUNIT_GRP,
		   P.SRC_SYS_ID_POS,
		P.DISTRIBUTOR_NAME,
		P.MANUFACTURER_NAME,
		CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN ANXTPR.REPORT_ENDING_DATE ELSE P.REPORT_ENDING_DATE END REPORT_ENDING_DATE,
		P.BRANCH_ID,
		--PI.FinishFlg Item_Finish_Flag,
		PI.RecapClass1	AMERICAS_SALESINCENTIVE_RECAP_1,
		PI.RecapClass2	AMERICAS_SALESINCENTIVE_RECAP_2,
	CASE WHEN P.COST_CURRENCY_EXCHANGE_USD > 0 THEN 
		CASE WHEN P.DISTRIBUTOR_NAME IN ('ANIXTER-CH', 'ANIXTER-JP', 'ANIXTER-BY', 'ANIXTER-IS') THEN P.EXTENDED_COST * 1000 ELSE P.EXTENDED_COST END * P.COST_CURRENCY_EXCHANGE_USD ELSE 
		CASE WHEN P.DISTRIBUTOR_NAME IN ('ANIXTER-CH', 'ANIXTER-JP', 'ANIXTER-BY', 'ANIXTER-IS') THEN 
			P.EXTENDED_COST * 1000 
		ELSE 
			P.EXTENDED_COST 
		END 
	END SALES_EXTENDED_AMT_USD,
	P.QUANTITY SALES_QUANTITY,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN TRD1.FISCAL_YEAR ELSE TRD1.FISCAL_YEAR END REPORT_ENDING_FISCAL_YEAR,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN TRD1.FISCAL_QUARTER ELSE TRD1.FISCAL_QUARTER END REPORT_ENDING_FISCAL_QUARTER,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN TRD1.FISCAL_PERIOD ELSE TRD.FISCAL_PERIOD END REPORT_ENDING_FISCAL_PERIOD,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN TRD1.FISCAL_PERIOD_NAME ELSE TRD.FISCAL_PERIOD_NAME END REPORT_ENDING_PERIOD_FISCAL_NAME,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN TRD1.YEAR ELSE TRD.YEAR END REPORT_ENDING_CALENDAR_YEAR,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN TRD1.QUARTER ELSE TRD.QUARTER END REPORT_ENDING_CALENDAR_QUARTER,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN TRD1.MONTH ELSE TRD.MONTH END REPORT_ENDING_CALENDAR_MONTH,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN TRD1.MONTH_NAME ELSE TRD.MONTH_NAME END REPORT_ENDING_CALENDAR_MONTH_NAME,
	
	dbo.nCurrentMoSalesAmtOrQty(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.sReportEndingcalendarMonth(P.SRC_SYS_ID_POS,TRD1.MONTH,TRD.MONTH), dbo.nSalesExtendedAmtUsd(P.DISTRIBUTOR_NAME,P.EXTENDED_COST,P.COST_CURRENCY_EXCHANGE_USD)) as Current_Month_Sales_Extended_Amount,
	dbo.nYearToDateExtendedSalesAmtOrQty(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.nSalesExtendedAmtUsd(P.DISTRIBUTOR_NAME,P.EXTENDED_COST,P.COST_CURRENCY_EXCHANGE_USD)) as Year_To_Date_Extended_Sales_Amount,
	dbo.nPrevYearToDateSalesAmtOrQty(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.sReportEndingcalendarMonth(P.SRC_SYS_ID_POS,TRD1.MONTH,TRD.MONTH), dbo.nSalesExtendedAmtUsd(P.DISTRIBUTOR_NAME,P.EXTENDED_COST,P.COST_CURRENCY_EXCHANGE_USD)) as Previous_Year_To_date_Sales_Amount,
	dbo.nSalesExtendedAmtYoYchange(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.sReportEndingcalendarMonth(P.SRC_SYS_ID_POS,TRD1.MONTH,TRD.MONTH), dbo.nSalesExtendedAmtUsd(P.DISTRIBUTOR_NAME,P.EXTENDED_COST,P.COST_CURRENCY_EXCHANGE_USD)) as Sales_Extended_Amount_YoY_Change ,
	
	dbo.nCurrentMoSalesAmtOrQty(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.sReportEndingcalendarMonth(P.SRC_SYS_ID_POS,TRD1.MONTH,TRD.MONTH), P.QUANTITY) as Current_Month_Quantity,
	dbo.nYearToDateExtendedSalesAmtOrQty(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR),  P.QUANTITY ) as Year_To_Date_Extended_Quantity,
	dbo.nPrevYearToDateSalesAmtOrQty(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.sReportEndingcalendarMonth(P.SRC_SYS_ID_POS,TRD1.MONTH,TRD.MONTH),  P.QUANTITY) as Previous_Year_To_date_Quantity,
	dbo.nSalesExtendedAmtYoYchange(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.sReportEndingcalendarMonth(P.SRC_SYS_ID_POS,TRD1.MONTH,TRD.MONTH),  P.QUANTITY) as Sales_Quantity_YoY_Change
						
from	dbo.DM_F_POS_SALES as P
LEFT OUTER JOIN POSCleansingTable PI ON P.SRC_SYS_ID = PI.SRC_SYS_ID AND P.MANUFACTURER_PART_NUMBER = PI.VendorPartNumber
LEFT OUTER JOIN XREF_DISTRIBUTOR D ON P.SRC_SYS_ID_POS = D.SRC_SYS_ID_POS AND ((P.DISTRIBUTOR_NAME = D.POS_ACCOUNT_NAME) OR (D.DIV_C = P.DISTRIBUTOR_NAME))
LEFT OUTER JOIN XREF_ANIXTER_INFO ANX ON P.DISTRIBUTOR_NAME = ANX.DISTRIBUTOR_NAME
LEFT OUTER JOIN TPR_POS_ANIXTER_V2 ANXTPR ON P.SRC_SYS_ID_POS = ANXTPR.SRC_SYS_ID AND P.INVOICE_NUMBER = ANXTPR.INVOICE_NUMBER AND P.DISTRIBUTOR_PART_NUMBER = ANXTPR.DISTRIBUTOR_PART_NUMBER AND P.EXTENDED_COST = ANXTPR.EXTENDED_UNIT_COST
JOIN DM_D_CALENDAR T ON T.TIME_KEY=P.TIME_KEY
LEFT OUTER JOIN DM_D_CALENDAR TRD ON TRD.TIME_KEY=convert(VARCHAR(10),P.REPORT_ENDING_DATE,112)
LEFT OUTER JOIN DM_D_CALENDAR TRD1 ON TRD1.TIME_KEY=convert(VARCHAR(10),ANXTPR.REPORT_ENDING_DATE,112)

WHERE P.CURRENT_IND = 'Y' AND (P.SRC_SYS_ID = 'BPCSAL' OR P.SRC_SYS_ID = 'STDMWP'OR P.SRC_SYS_ID = 'STDMHM' OR P.SRC_SYS_ID = 'STDMLB')

UNION ALL
SELECT
 	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2' AND P.MANUFACTURER_NAME LIKE 'HIR%') THEN 'STDMHM'
		ELSE P.SRC_SYS_ID END	AS SRC_SYS_ID,
	CASE WHEN (P.SRC_SYS_ID='BPCSEU') THEN 'EMEA'
		 WHEN (P.SRC_SYS_ID='BPCSRI') THEN 'BAG'
		 WHEN (P.SRC_SYS_ID='BPCSCO') THEN 'BAG'
		 WHEN (P.SRC_SYS_ID='BPCSMH') THEN 'BAG'
		 WHEN (P.SRC_SYS_ID='BPCSAL') THEN 'BAG'
		 WHEN (P.SRC_SYS_ID='STDMWP') THEN 'BAG'
		 WHEN (P.SRC_SYS_ID='THERMX') THEN 'BAG'
		 WHEN (P.SRC_SYS_ID='ASIASR') THEN 'APAC'
	ELSE
	 	 'UNKNOWN'
	END	AS DIVISION_GRP,

	CASE WHEN (P.SRC_SYS_ID='BPCSEU') THEN 'Cable'
		 WHEN (P.SRC_SYS_ID='BPCSRI') THEN 'Americas'
		 WHEN (P.SRC_SYS_ID='BPCSCO') THEN 'Americas'
		 WHEN (P.SRC_SYS_ID='BPCSMH') THEN 'Mohawk'
		 WHEN (P.SRC_SYS_ID='BPCSAL') THEN 'AMD'
		 WHEN (P.SRC_SYS_ID='STDMWP') THEN 'WPW'
		 WHEN (P.SRC_SYS_ID='THERMX') THEN 'Thermax'
		 WHEN (P.SRC_SYS_ID='ASIASR') THEN 'BAP'
	ELSE
	 	 'UNKNOWN'
	END	AS BUSINESSUNIT_GRP,
		P.SRC_SYS_ID_POS,
		P.DISTRIBUTOR_NAME,
		P.MANUFACTURER_NAME,
		CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN ANXTPR.REPORT_ENDING_DATE ELSE P.REPORT_ENDING_DATE END REPORT_ENDING_DATE,
		P.BRANCH_ID,
	   	--PI.FinishFlg Item_Finish_Flag,
		PI.RecapClass1	AMERICAS_SALESINCENTIVE_RECAP_1,
		PI.RecapClass2	AMERICAS_SALESINCENTIVE_RECAP_2,
	CASE WHEN P.COST_CURRENCY_EXCHANGE_USD > 0 THEN 
		CASE WHEN P.DISTRIBUTOR_NAME IN ('ANIXTER-CH', 'ANIXTER-JP', 'ANIXTER-BY', 'ANIXTER-IS') THEN P.EXTENDED_COST * 1000 ELSE P.EXTENDED_COST END * P.COST_CURRENCY_EXCHANGE_USD ELSE 
		CASE WHEN P.DISTRIBUTOR_NAME IN ('ANIXTER-CH', 'ANIXTER-JP', 'ANIXTER-BY', 'ANIXTER-IS') THEN 
			P.EXTENDED_COST * 1000 
		ELSE 
			P.EXTENDED_COST 
		END 
		END SALES_EXTENDED_AMT_USD,
		P.QUANTITY SALES_QUANTITY,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN TRD1.FISCAL_YEAR ELSE TRD1.FISCAL_YEAR END REPORT_ENDING_FISCAL_YEAR,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN TRD1.FISCAL_QUARTER ELSE TRD1.FISCAL_QUARTER END REPORT_ENDING_FISCAL_QUARTER,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN TRD1.FISCAL_PERIOD ELSE TRD.FISCAL_PERIOD END REPORT_ENDING_FISCAL_PERIOD,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN TRD1.FISCAL_PERIOD_NAME ELSE TRD.FISCAL_PERIOD_NAME END REPORT_ENDING_PERIOD_FISCAL_NAME,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN TRD1.YEAR ELSE TRD.YEAR END REPORT_ENDING_CALENDAR_YEAR,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN TRD1.QUARTER ELSE TRD.QUARTER END REPORT_ENDING_CALENDAR_QUARTER,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN TRD1.MONTH ELSE TRD.MONTH END REPORT_ENDING_CALENDAR_MONTH,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN TRD1.MONTH_NAME ELSE TRD.MONTH_NAME END REPORT_ENDING_CALENDAR_MONTH_NAME,
	
	dbo.nCurrentMoSalesAmtOrQty(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.sReportEndingcalendarMonth(P.SRC_SYS_ID_POS,TRD1.MONTH,TRD.MONTH), dbo.nSalesExtendedAmtUsd(P.DISTRIBUTOR_NAME,P.EXTENDED_COST,P.COST_CURRENCY_EXCHANGE_USD)) as Current_Month_Sales_Extended_Amount,
	dbo.nYearToDateExtendedSalesAmtOrQty(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.nSalesExtendedAmtUsd(P.DISTRIBUTOR_NAME,P.EXTENDED_COST,P.COST_CURRENCY_EXCHANGE_USD)) as Year_To_Date_Extended_Sales_Amount,
	dbo.nPrevYearToDateSalesAmtOrQty(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.sReportEndingcalendarMonth(P.SRC_SYS_ID_POS,TRD1.MONTH,TRD.MONTH), dbo.nSalesExtendedAmtUsd(P.DISTRIBUTOR_NAME,P.EXTENDED_COST,P.COST_CURRENCY_EXCHANGE_USD)) as Previous_Year_To_date_Sales_Amount,
	dbo.nSalesExtendedAmtYoYchange(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.sReportEndingcalendarMonth(P.SRC_SYS_ID_POS,TRD1.MONTH,TRD.MONTH), dbo.nSalesExtendedAmtUsd(P.DISTRIBUTOR_NAME,P.EXTENDED_COST,P.COST_CURRENCY_EXCHANGE_USD)) as Sales_Extended_Amount_YoY_Change, 
	
	dbo.nCurrentMoSalesAmtOrQty(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.sReportEndingcalendarMonth(P.SRC_SYS_ID_POS,TRD1.MONTH,TRD.MONTH), P.QUANTITY) as Current_Month_Quantity,
	dbo.nYearToDateExtendedSalesAmtOrQty(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR),  P.QUANTITY ) as Year_To_Date_Extended_Quantity,
	dbo.nPrevYearToDateSalesAmtOrQty(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.sReportEndingcalendarMonth(P.SRC_SYS_ID_POS,TRD1.MONTH,TRD.MONTH),  P.QUANTITY) as Previous_Year_To_date_Quantity,
	dbo.nSalesExtendedAmtYoYchange(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.sReportEndingcalendarMonth(P.SRC_SYS_ID_POS,TRD1.MONTH,TRD.MONTH),  P.QUANTITY) as Sales_Quantity_YoY_Change
	
from	dbo.DM_F_POS_SALES as P
LEFT OUTER JOIN POSCleansingTable PI ON P.SRC_SYS_ID = PI.SRC_SYS_ID AND (P.MANUFACTURER_PART_NUMBER = PI.VendorPartNumber OR (P.DISTRIBUTOR_PART_NUMBER = PI.VendorPartNumber AND P.MANUFACTURER_PART_NUMBER != PI.VendorPartNumber))
LEFT OUTER JOIN XREF_DISTRIBUTOR D ON P.SRC_SYS_ID_POS = D.SRC_SYS_ID_POS AND ((P.DISTRIBUTOR_NAME = D.POS_ACCOUNT_NAME) OR (D.DIV_C = P.DISTRIBUTOR_NAME))
LEFT OUTER JOIN XREF_ANIXTER_INFO ANX ON P.DISTRIBUTOR_NAME = ANX.DISTRIBUTOR_NAME
LEFT OUTER JOIN TPR_POS_ANIXTER_V2 ANXTPR ON P.SRC_SYS_ID_POS = ANXTPR.SRC_SYS_ID AND P.INVOICE_NUMBER = ANXTPR.INVOICE_NUMBER AND P.DISTRIBUTOR_PART_NUMBER = ANXTPR.DISTRIBUTOR_PART_NUMBER AND P.EXTENDED_COST = ANXTPR.EXTENDED_UNIT_COST
JOIN DM_D_CALENDAR T ON T.TIME_KEY=P.TIME_KEY
LEFT OUTER JOIN DM_D_CALENDAR TRD ON TRD.TIME_KEY=convert(VARCHAR(10),P.REPORT_ENDING_DATE,112)
LEFT OUTER JOIN DM_D_CALENDAR TRD1 ON TRD1.TIME_KEY=convert(VARCHAR(10),ANXTPR.REPORT_ENDING_DATE,112)

WHERE P.CURRENT_IND = 'Y' AND (P.SRC_SYS_ID = 'THERMX')

UNION ALL
SELECT
 	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2' AND P.MANUFACTURER_NAME LIKE 'HIR%') THEN 'STDMHM'
			 WHEN (P.SRC_SYS_ID IN ('BPCSCE', 'BPCSCN')) THEN 'BPCSCO'
			 WHEN (GB.PREFIX_PURCHASE_GROUP IN ('BEDPT')) THEN 'TRAPEZ'
		ELSE P.SRC_SYS_ID END	AS SRC_SYS_ID,
	CASE WHEN (P.SRC_SYS_ID='BPCSEU') THEN 'EMEA'
		 WHEN (P.SRC_SYS_ID IN ('BPCSRI','BPCSCE', 'BPCSCN', 'BPCSCO','BPCSMH','BPCSAL','STDMWP','THERMX')) THEN 'BAG'
		 WHEN (P.SRC_SYS_ID='ASIASR') THEN 'APAC'
	ELSE
	 	 'UNKNOWN'
	END	AS DIVISION_GRP,
	CASE WHEN (P.SRC_SYS_ID='BPCSEU') THEN 'Cable'
		 WHEN (P.SRC_SYS_ID='BPCSRI') THEN 'Americas'
		 WHEN (P.SRC_SYS_ID IN ('BPCSCO', 'BPCSCE', 'BPCSCN')) THEN 'Americas'
		 WHEN (P.SRC_SYS_ID='BPCSMH') THEN 'Mohawk'
		 WHEN (P.SRC_SYS_ID='BPCSAL') THEN 'AMD'
		 WHEN (P.SRC_SYS_ID='STDMWP') THEN 'WPW'
		 WHEN (P.SRC_SYS_ID='THERMX') THEN 'Thermax'
		 WHEN (P.SRC_SYS_ID='ASIASR') THEN 'BAP'
	ELSE
	 	 'UNKNOWN'
	END	AS BUSINESSUNIT_GRP,
		P.SRC_SYS_ID_POS,
		P.DISTRIBUTOR_NAME,
		P.MANUFACTURER_NAME,
		CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN ANXTPR.REPORT_ENDING_DATE ELSE P.REPORT_ENDING_DATE END REPORT_ENDING_DATE,
		P.BRANCH_ID,
		PI.RecapClass1	AMERICAS_SALESINCENTIVE_RECAP_1,
		PI.RecapClass2	AMERICAS_SALESINCENTIVE_RECAP_2,
	CASE WHEN P.COST_CURRENCY_EXCHANGE_USD > 0 THEN 
		CASE WHEN P.DISTRIBUTOR_NAME IN ('ANIXTER-CH', 'ANIXTER-JP', 'ANIXTER-BY', 'ANIXTER-IS') THEN P.EXTENDED_COST * 1000 ELSE P.EXTENDED_COST END * P.COST_CURRENCY_EXCHANGE_USD ELSE 
		CASE WHEN P.DISTRIBUTOR_NAME IN ('ANIXTER-CH', 'ANIXTER-JP', 'ANIXTER-BY', 'ANIXTER-IS') THEN 
			P.EXTENDED_COST * 1000 
		ELSE 
			P.EXTENDED_COST 
		END 
		END SALES_EXTENDED_AMT_USD,
		P.QUANTITY SALES_QUANTITY,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN	TRD1.FISCAL_YEAR ELSE TRD1.FISCAL_YEAR END REPORT_ENDING_FISCAL_YEAR,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN 	TRD1.FISCAL_QUARTER ELSE TRD1.FISCAL_QUARTER END REPORT_ENDING_FISCAL_QUARTER,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN 	TRD1.FISCAL_PERIOD ELSE TRD.FISCAL_PERIOD END REPORT_ENDING_FISCAL_PERIOD,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN 	TRD1.FISCAL_PERIOD_NAME ELSE TRD.FISCAL_PERIOD_NAME END REPORT_ENDING_PERIOD_FISCAL_NAME,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN 	TRD1.YEAR ELSE TRD.YEAR END REPORT_ENDING_CALENDAR_YEAR,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN 	TRD1.QUARTER ELSE TRD.QUARTER END REPORT_ENDING_CALENDAR_QUARTER,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN 	TRD1.MONTH ELSE TRD.MONTH END REPORT_ENDING_CALENDAR_MONTH,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN 	TRD1.MONTH_NAME ELSE TRD.MONTH_NAME END REPORT_ENDING_CALENDAR_MONTH_NAME,
	
	dbo.nCurrentMoSalesAmtOrQty(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.sReportEndingcalendarMonth(P.SRC_SYS_ID_POS,TRD1.MONTH,TRD.MONTH), dbo.nSalesExtendedAmtUsd(P.DISTRIBUTOR_NAME,P.EXTENDED_COST,P.COST_CURRENCY_EXCHANGE_USD)) as Current_Month_Sales_Extended_Amount,
	dbo.nYearToDateExtendedSalesAmtOrQty(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.nSalesExtendedAmtUsd(P.DISTRIBUTOR_NAME,P.EXTENDED_COST,P.COST_CURRENCY_EXCHANGE_USD)) as Year_To_Date_Extended_Sales_Amount,
	dbo.nPrevYearToDateSalesAmtOrQty(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.sReportEndingcalendarMonth(P.SRC_SYS_ID_POS,TRD1.MONTH,TRD.MONTH), dbo.nSalesExtendedAmtUsd(P.DISTRIBUTOR_NAME,P.EXTENDED_COST,P.COST_CURRENCY_EXCHANGE_USD)) as Previous_Year_To_date_Sales_Amount,
	dbo.nSalesExtendedAmtYoYchange(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.sReportEndingcalendarMonth(P.SRC_SYS_ID_POS,TRD1.MONTH,TRD.MONTH), dbo.nSalesExtendedAmtUsd(P.DISTRIBUTOR_NAME,P.EXTENDED_COST,P.COST_CURRENCY_EXCHANGE_USD)) as Sales_Extended_Amount_YoY_Change ,
	
	dbo.nCurrentMoSalesAmtOrQty(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.sReportEndingcalendarMonth(P.SRC_SYS_ID_POS,TRD1.MONTH,TRD.MONTH), P.QUANTITY) as Current_Month_Quantity,
	dbo.nYearToDateExtendedSalesAmtOrQty(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR),  P.QUANTITY ) as Year_To_Date_Extended_Quantity,
	dbo.nPrevYearToDateSalesAmtOrQty(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.sReportEndingcalendarMonth(P.SRC_SYS_ID_POS,TRD1.MONTH,TRD.MONTH),  P.QUANTITY) as Previous_Year_To_date_Quantity,
	dbo.nSalesExtendedAmtYoYchange(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.sReportEndingcalendarMonth(P.SRC_SYS_ID_POS,TRD1.MONTH,TRD.MONTH),  P.QUANTITY) as Sales_Quantity_YoY_Change
	
from	dbo.DM_F_POS_SALES as P
LEFT OUTER JOIN POSCleansingTable PI ON P.SRC_SYS_ID = PI.SRC_SYS_ID AND P.MANUFACTURER_PART_NUMBER = PI.VendorPartNumber
LEFT OUTER JOIN XREF_DISTRIBUTOR D ON P.SRC_SYS_ID_POS = D.SRC_SYS_ID_POS AND ((P.DISTRIBUTOR_NAME = D.POS_ACCOUNT_NAME) OR (D.DIV_C = P.DISTRIBUTOR_NAME))
LEFT OUTER JOIN XREF_ANIXTER_INFO ANX ON P.DISTRIBUTOR_NAME = ANX.DISTRIBUTOR_NAME
LEFT OUTER JOIN TPR_POS_ANIXTER_V2 ANXTPR ON P.SRC_SYS_ID_POS = 'AXT_V2' AND P.SRC_SYS_ID_POS = ANXTPR.SRC_SYS_ID AND P.INVOICE_NUMBER = ANXTPR.INVOICE_NUMBER AND P.DISTRIBUTOR_PART_NUMBER = ANXTPR.DISTRIBUTOR_PART_NUMBER AND P.EXTENDED_COST = ANXTPR.EXTENDED_UNIT_COST
LEFT OUTER JOIN TPR_POS_GRAYBAR GB ON LEFT(P.SRC_SYS_ID_POS, 5) = 'RI_GB' AND P.SRC_SYS_ID_POS = GB.SRC_SYS_ID AND P.INVOICE_NUMBER = CAST(GB.INVOICE_NBR AS VARCHAR(50)) AND P.DISTRIBUTOR_PART_NUMBER = GB.ITEM_DESCR_1 AND P.EXTENDED_COST = GB.NET_EXTENDED_COST
LEFT OUTER JOIN XREF_POSTALCODE PC ON LEFT(P.SHIP_TO_CUSTOMER_POSTAL_CODE, 3) = PC.PostalCodePrefix AND P.COUNTRY_CODE = 'US'
JOIN DM_D_CALENDAR T ON T.TIME_KEY=P.TIME_KEY
LEFT OUTER JOIN DM_D_CALENDAR TRD ON TRD.TIME_KEY=convert(VARCHAR(10),P.REPORT_ENDING_DATE,112)
LEFT OUTER JOIN DM_D_CALENDAR TRD1 ON TRD1.TIME_KEY=convert(VARCHAR(10),ANXTPR.REPORT_ENDING_DATE,112)


WHERE P.CURRENT_IND = 'Y' AND P.SRC_SYS_ID = 'BPCSRI'


UNION ALL
SELECT
 	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2' AND P.MANUFACTURER_NAME LIKE 'HIR%') THEN 'STDMHM'
			 WHEN (P.SRC_SYS_ID IN ('BPCSCE', 'BPCSCN')) THEN 'BPCSCO'
		ELSE P.SRC_SYS_ID END	AS SRC_SYS_ID,
	CASE WHEN (P.SRC_SYS_ID='BPCSEU') THEN 'EMEA'
		 WHEN (P.SRC_SYS_ID IN ('BPCSRI','BPCSCE', 'BPCSCN', 'BPCSCO','BPCSMH','BPCSAL','STDMWP','THERMX')) THEN 'BAG'
		 WHEN (P.SRC_SYS_ID='ASIASR') THEN 'APAC'
	ELSE
	 	 'UNKNOWN'
	END	AS DIVISION_GRP,
	CASE WHEN (P.SRC_SYS_ID='BPCSEU') THEN 'Cable'
		 WHEN (P.SRC_SYS_ID='BPCSRI') THEN 'Americas'
		 WHEN (P.SRC_SYS_ID IN ('BPCSCO', 'BPCSCE', 'BPCSCN')) THEN 'Americas'
		 WHEN (P.SRC_SYS_ID='BPCSMH') THEN 'Mohawk'
		 WHEN (P.SRC_SYS_ID='BPCSAL') THEN 'AMD'
		 WHEN (P.SRC_SYS_ID='STDMWP') THEN 'WPW'
		 WHEN (P.SRC_SYS_ID='THERMX') THEN 'Thermax'
		 WHEN (P.SRC_SYS_ID='ASIASR') THEN 'BAP'
	ELSE
	 	 'UNKNOWN'
	END	AS BUSINESSUNIT_GRP,
		P.SRC_SYS_ID_POS,
		P.DISTRIBUTOR_NAME,
		P.MANUFACTURER_NAME,
		CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN ANXTPR.REPORT_ENDING_DATE ELSE P.REPORT_ENDING_DATE END REPORT_ENDING_DATE,
		P.BRANCH_ID,
		PI.RecapClass1	AMERICAS_SALESINCENTIVE_RECAP_1,
		PI.RecapClass2	AMERICAS_SALESINCENTIVE_RECAP_2,
	CASE WHEN P.COST_CURRENCY_EXCHANGE_USD > 0 THEN 
		CASE WHEN P.DISTRIBUTOR_NAME IN ('ANIXTER-CH', 'ANIXTER-JP', 'ANIXTER-BY', 'ANIXTER-IS') THEN P.EXTENDED_COST * 1000 ELSE P.EXTENDED_COST END * P.COST_CURRENCY_EXCHANGE_USD ELSE 
		CASE WHEN P.DISTRIBUTOR_NAME IN ('ANIXTER-CH', 'ANIXTER-JP', 'ANIXTER-BY', 'ANIXTER-IS') THEN 
			P.EXTENDED_COST * 1000 
		ELSE 
			P.EXTENDED_COST 
		END 
		END SALES_EXTENDED_AMT_USD,
		P.QUANTITY SALES_QUANTITY,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN	TRD1.FISCAL_YEAR ELSE TRD1.FISCAL_YEAR END REPORT_ENDING_FISCAL_YEAR,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN 	TRD1.FISCAL_QUARTER ELSE TRD1.FISCAL_QUARTER END REPORT_ENDING_FISCAL_QUARTER,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN 	TRD1.FISCAL_PERIOD ELSE TRD.FISCAL_PERIOD END REPORT_ENDING_FISCAL_PERIOD,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN 	TRD1.FISCAL_PERIOD_NAME ELSE TRD.FISCAL_PERIOD_NAME END REPORT_ENDING_PERIOD_FISCAL_NAME,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN 	TRD1.YEAR ELSE TRD.YEAR END REPORT_ENDING_CALENDAR_YEAR,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN 	TRD1.QUARTER ELSE TRD.QUARTER END REPORT_ENDING_CALENDAR_QUARTER,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN 	TRD1.MONTH ELSE TRD.MONTH END REPORT_ENDING_CALENDAR_MONTH,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN 	TRD1.MONTH_NAME ELSE TRD.MONTH_NAME END REPORT_ENDING_CALENDAR_MONTH_NAME,
	
	dbo.nCurrentMoSalesAmtOrQty(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.sReportEndingcalendarMonth(P.SRC_SYS_ID_POS,TRD1.MONTH,TRD.MONTH), dbo.nSalesExtendedAmtUsd(P.DISTRIBUTOR_NAME,P.EXTENDED_COST,P.COST_CURRENCY_EXCHANGE_USD)) as Current_Month_Sales_Extended_Amount,
	dbo.nYearToDateExtendedSalesAmtOrQty(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.nSalesExtendedAmtUsd(P.DISTRIBUTOR_NAME,P.EXTENDED_COST,P.COST_CURRENCY_EXCHANGE_USD)) as Year_To_Date_Extended_Sales_Amount,
	dbo.nPrevYearToDateSalesAmtOrQty(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.sReportEndingcalendarMonth(P.SRC_SYS_ID_POS,TRD1.MONTH,TRD.MONTH), dbo.nSalesExtendedAmtUsd(P.DISTRIBUTOR_NAME,P.EXTENDED_COST,P.COST_CURRENCY_EXCHANGE_USD)) as Previous_Year_To_date_Sales_Amount,
	dbo.nSalesExtendedAmtYoYchange(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.sReportEndingcalendarMonth(P.SRC_SYS_ID_POS,TRD1.MONTH,TRD.MONTH), dbo.nSalesExtendedAmtUsd(P.DISTRIBUTOR_NAME,P.EXTENDED_COST,P.COST_CURRENCY_EXCHANGE_USD)) as Sales_Extended_Amount_YoY_Change, 
	
	dbo.nCurrentMoSalesAmtOrQty(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.sReportEndingcalendarMonth(P.SRC_SYS_ID_POS,TRD1.MONTH,TRD.MONTH), P.QUANTITY) as Current_Month_Quantity,
	dbo.nYearToDateExtendedSalesAmtOrQty(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR),  P.QUANTITY ) as Year_To_Date_Extended_Quantity,
	dbo.nPrevYearToDateSalesAmtOrQty(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.sReportEndingcalendarMonth(P.SRC_SYS_ID_POS,TRD1.MONTH,TRD.MONTH),  P.QUANTITY) as Previous_Year_To_date_Quantity,
	dbo.nSalesExtendedAmtYoYchange(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.sReportEndingcalendarMonth(P.SRC_SYS_ID_POS,TRD1.MONTH,TRD.MONTH),  P.QUANTITY) as Sales_Quantity_YoY_Change
	
from	dbo.DM_F_POS_SALES as P

LEFT OUTER JOIN POSCleansingTable PI ON P.SRC_SYS_ID = PI.SRC_SYS_ID AND P.MANUFACTURER_PART_NUMBER = PI.VendorPartNumber
LEFT OUTER JOIN XREF_DISTRIBUTOR D ON P.SRC_SYS_ID_POS = D.SRC_SYS_ID_POS AND ((P.DISTRIBUTOR_NAME = D.POS_ACCOUNT_NAME) OR (D.DIV_C = P.DISTRIBUTOR_NAME))
LEFT OUTER JOIN XREF_ANIXTER_INFO ANX ON P.DISTRIBUTOR_NAME = ANX.DISTRIBUTOR_NAME
LEFT OUTER JOIN TPR_POS_ANIXTER_V2 ANXTPR ON P.SRC_SYS_ID_POS = ANXTPR.SRC_SYS_ID AND P.INVOICE_NUMBER = ANXTPR.INVOICE_NUMBER AND P.DISTRIBUTOR_PART_NUMBER = ANXTPR.DISTRIBUTOR_PART_NUMBER AND P.EXTENDED_COST = ANXTPR.EXTENDED_UNIT_COST
LEFT OUTER JOIN XREF_POSTALCODE PC ON LEFT(P.SHIP_TO_CUSTOMER_POSTAL_CODE, 3) = PC.PostalCodePrefix AND P.COUNTRY_CODE = 'US'
JOIN DM_D_CALENDAR T ON T.TIME_KEY=P.TIME_KEY
LEFT OUTER JOIN DM_D_CALENDAR TRD ON TRD.TIME_KEY=convert(VARCHAR(10),P.REPORT_ENDING_DATE,112)
LEFT OUTER JOIN DM_D_CALENDAR TRD1 ON TRD1.TIME_KEY=convert(VARCHAR(10),ANXTPR.REPORT_ENDING_DATE,112)
WHERE P.CURRENT_IND = 'Y' AND (P.SRC_SYS_ID IN ('BPCSCO', 'BPCSCE','BPCSCN'))


UNION ALL

SELECT
 	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2' AND P.MANUFACTURER_NAME LIKE 'HIR%') THEN 'STDMHM'
		ELSE P.SRC_SYS_ID END	AS SRC_SYS_ID,
	CASE WHEN (P.SRC_SYS_ID='BPCSEU') THEN 'EMEA'
		 WHEN (P.SRC_SYS_ID='BPCSRI') THEN 'BAG'
		 WHEN (P.SRC_SYS_ID='BPCSCO') THEN 'BAG'
		 WHEN (P.SRC_SYS_ID='BPCSMH') THEN 'BAG'
		 WHEN (P.SRC_SYS_ID='BPCSAL') THEN 'BAG'
		 WHEN (P.SRC_SYS_ID='STDMWP') THEN 'BAG'
		 WHEN (P.SRC_SYS_ID='THERMX') THEN 'BAG'
		 WHEN (P.SRC_SYS_ID='ASIASR') THEN 'APAC'
	ELSE
	 	 'UNKNOWN'
	END	AS DIVISION_GRP,
	CASE WHEN (P.SRC_SYS_ID='BPCSEU') THEN 'Cable'
		 WHEN (P.SRC_SYS_ID='BPCSRI') THEN 'Americas'
		 WHEN (P.SRC_SYS_ID='BPCSCO') THEN 'Americas'
		 WHEN (P.SRC_SYS_ID='BPCSMH') THEN 'Mohawk'
		 WHEN (P.SRC_SYS_ID='BPCSAL') THEN 'AMD'
		 WHEN (P.SRC_SYS_ID='STDMWP') THEN 'WPW'
		 WHEN (P.SRC_SYS_ID='THERMX') THEN 'Thermax'
		 WHEN (P.SRC_SYS_ID='ASIASR') THEN 'BAP'
	ELSE
	 	 'UNKNOWN'
	END	AS BUSINESSUNIT_GRP,
		P.SRC_SYS_ID_POS,
		P.DISTRIBUTOR_NAME,
		P.MANUFACTURER_NAME,
		CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN ANXTPR.REPORT_ENDING_DATE ELSE P.REPORT_ENDING_DATE END REPORT_ENDING_DATE,
		P.BRANCH_ID,
		PI.RecapClass1	AMERICAS_SALESINCENTIVE_RECAP_1,
		PI.RecapClass2	AMERICAS_SALESINCENTIVE_RECAP_2,
	CASE WHEN P.COST_CURRENCY_EXCHANGE_USD > 0 THEN 
		CASE WHEN P.DISTRIBUTOR_NAME IN ('ANIXTER-CH', 'ANIXTER-JP', 'ANIXTER-BY', 'ANIXTER-IS') THEN P.EXTENDED_COST * 1000 ELSE P.EXTENDED_COST END * P.COST_CURRENCY_EXCHANGE_USD ELSE 
		CASE WHEN P.DISTRIBUTOR_NAME IN ('ANIXTER-CH', 'ANIXTER-JP', 'ANIXTER-BY', 'ANIXTER-IS') THEN 
			P.EXTENDED_COST * 1000 
		ELSE 
			P.EXTENDED_COST 
		END 
		END SALES_EXTENDED_AMT_USD,
		P.QUANTITY SALES_QUANTITY,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN TRD1.FISCAL_YEAR ELSE TRD1.FISCAL_YEAR END REPORT_ENDING_FISCAL_YEAR,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN TRD1.FISCAL_QUARTER ELSE TRD1.FISCAL_QUARTER END REPORT_ENDING_FISCAL_QUARTER,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN TRD1.FISCAL_PERIOD ELSE TRD.FISCAL_PERIOD END REPORT_ENDING_FISCAL_PERIOD,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN TRD1.FISCAL_PERIOD_NAME ELSE TRD.FISCAL_PERIOD_NAME END REPORT_ENDING_PERIOD_FISCAL_NAME,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN TRD1.YEAR ELSE TRD.YEAR END REPORT_ENDING_CALENDAR_YEAR,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN TRD1.QUARTER ELSE TRD.QUARTER END REPORT_ENDING_CALENDAR_QUARTER,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN TRD1.MONTH ELSE TRD.MONTH END REPORT_ENDING_CALENDAR_MONTH,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN TRD1.MONTH_NAME ELSE TRD.MONTH_NAME END REPORT_ENDING_CALENDAR_MONTH_NAME,
	
	dbo.nCurrentMoSalesAmtOrQty(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.sReportEndingcalendarMonth(P.SRC_SYS_ID_POS,TRD1.MONTH,TRD.MONTH), dbo.nSalesExtendedAmtUsd(P.DISTRIBUTOR_NAME,P.EXTENDED_COST,P.COST_CURRENCY_EXCHANGE_USD)) as Current_Month_Sales_Extended_Amount,
	dbo.nYearToDateExtendedSalesAmtOrQty(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.nSalesExtendedAmtUsd(P.DISTRIBUTOR_NAME,P.EXTENDED_COST,P.COST_CURRENCY_EXCHANGE_USD)) as Year_To_Date_Extended_Sales_Amount,
	dbo.nPrevYearToDateSalesAmtOrQty(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.sReportEndingcalendarMonth(P.SRC_SYS_ID_POS,TRD1.MONTH,TRD.MONTH), dbo.nSalesExtendedAmtUsd(P.DISTRIBUTOR_NAME,P.EXTENDED_COST,P.COST_CURRENCY_EXCHANGE_USD)) as Previous_Year_To_date_Sales_Amount,
	dbo.nSalesExtendedAmtYoYchange(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.sReportEndingcalendarMonth(P.SRC_SYS_ID_POS,TRD1.MONTH,TRD.MONTH), dbo.nSalesExtendedAmtUsd(P.DISTRIBUTOR_NAME,P.EXTENDED_COST,P.COST_CURRENCY_EXCHANGE_USD)) as Sales_Extended_Amount_YoY_Change, 
	
	dbo.nCurrentMoSalesAmtOrQty(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.sReportEndingcalendarMonth(P.SRC_SYS_ID_POS,TRD1.MONTH,TRD.MONTH), P.QUANTITY) as Current_Month_Quantity,
	dbo.nYearToDateExtendedSalesAmtOrQty(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR),  P.QUANTITY ) as Year_To_Date_Extended_Quantity,
	dbo.nPrevYearToDateSalesAmtOrQty(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.sReportEndingcalendarMonth(P.SRC_SYS_ID_POS,TRD1.MONTH,TRD.MONTH),  P.QUANTITY) as Previous_Year_To_date_Quantity,
	dbo.nSalesExtendedAmtYoYchange(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.sReportEndingcalendarMonth(P.SRC_SYS_ID_POS,TRD1.MONTH,TRD.MONTH),  P.QUANTITY) as Sales_Quantity_YoY_Change
	
from	dbo.DM_F_POS_SALES as P

LEFT OUTER JOIN POSCleansingTable PI ON P.SRC_SYS_ID = PI.SRC_SYS_ID AND P.MANUFACTURER_PART_NUMBER = PI.VendorPartNumber
LEFT OUTER JOIN XREF_DISTRIBUTOR D ON P.SRC_SYS_ID_POS = D.SRC_SYS_ID_POS AND ((P.DISTRIBUTOR_NAME = D.POS_ACCOUNT_NAME) OR (D.DIV_C = P.DISTRIBUTOR_NAME))
LEFT OUTER JOIN XREF_ANIXTER_INFO ANX ON P.DISTRIBUTOR_NAME = ANX.DISTRIBUTOR_NAME
LEFT OUTER JOIN TPR_POS_ANIXTER_V2 ANXTPR ON P.SRC_SYS_ID_POS = ANXTPR.SRC_SYS_ID AND P.INVOICE_NUMBER = ANXTPR.INVOICE_NUMBER AND P.DISTRIBUTOR_PART_NUMBER = ANXTPR.DISTRIBUTOR_PART_NUMBER AND P.EXTENDED_COST = ANXTPR.EXTENDED_UNIT_COST
JOIN DM_D_CALENDAR T ON T.TIME_KEY=P.TIME_KEY
LEFT OUTER JOIN dbo.DM_D_CALENDAR TRD ON TRD.TIME_KEY=convert(VARCHAR(10),P.REPORT_ENDING_DATE,112)
LEFT OUTER JOIN DM_D_CALENDAR TRD1 ON TRD1.TIME_KEY=convert(VARCHAR(10),ANXTPR.REPORT_ENDING_DATE,112)

WHERE P.CURRENT_IND = 'Y' AND P.SRC_SYS_ID = 'BPCSMH'

UNION ALL

SELECT
 	P.SRC_SYS_ID	AS SRC_SYS_ID,
	CASE WHEN (P.SRC_SYS_ID='BPCSEU') THEN 'EMEA'
		 WHEN (P.SRC_SYS_ID='BPCSRI') THEN 'BAG'
		 WHEN (P.SRC_SYS_ID='BPCSCO') THEN 'BAG'
		 WHEN (P.SRC_SYS_ID='BPCSMH') THEN 'BAG'
		 WHEN (P.SRC_SYS_ID='BPCSAL') THEN 'BAG'
		 WHEN (P.SRC_SYS_ID='STDMWP') THEN 'BAG'
		 WHEN (P.SRC_SYS_ID='THERMX') THEN 'BAG'
		 WHEN (P.SRC_SYS_ID='ASIASR') THEN 'APAC'
	ELSE
	 	 'UNKNOWN'
	END	AS DIVISION_GRP,

	CASE WHEN (P.SRC_SYS_ID='BPCSEU') THEN 'Cable'
		 WHEN (P.SRC_SYS_ID='BPCSRI') THEN 'Americas'
		 WHEN (P.SRC_SYS_ID='BPCSCO') THEN 'Americas'
		 WHEN (P.SRC_SYS_ID='BPCSMH') THEN 'Mohawk'
		 WHEN (P.SRC_SYS_ID='BPCSAL') THEN 'AMD'
		 WHEN (P.SRC_SYS_ID='STDMWP') THEN 'WPW'
		 WHEN (P.SRC_SYS_ID='THERMX') THEN 'Thermax'
		 WHEN (P.SRC_SYS_ID='ASIASR') THEN 'BAP'
	ELSE
	 	 'UNKNOWN'
	END	AS BUSINESSUNIT_GRP,
		P.SRC_SYS_ID_POS,
		P.DISTRIBUTOR_NAME,
		P.MANUFACTURER_NAME,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN ANXTPR.REPORT_ENDING_DATE ELSE P.REPORT_ENDING_DATE END REPORT_ENDING_DATE,
		P.BRANCH_ID,
		PI.RecapClass1	AMERICAS_SALESINCENTIVE_RECAP_1,
		PI.RecapClass2	AMERICAS_SALESINCENTIVE_RECAP_2,
	CASE WHEN P.COST_CURRENCY_EXCHANGE_USD > 0 THEN 
		CASE WHEN P.DISTRIBUTOR_NAME IN ('ANIXTER-CH', 'ANIXTER-JP', 'ANIXTER-BY', 'ANIXTER-IS') THEN P.EXTENDED_COST * 1000 ELSE P.EXTENDED_COST END * P.COST_CURRENCY_EXCHANGE_USD ELSE 
		CASE WHEN P.DISTRIBUTOR_NAME IN ('ANIXTER-CH', 'ANIXTER-JP', 'ANIXTER-BY', 'ANIXTER-IS') THEN 
			P.EXTENDED_COST * 1000 
		ELSE 
			P.EXTENDED_COST 
		END 
		END SALES_EXTENDED_AMT_USD,
		P.QUANTITY SALES_QUANTITY,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN	TRD1.FISCAL_YEAR ELSE TRD1.FISCAL_YEAR END REPORT_ENDING_FISCAL_YEAR,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN 	TRD1.FISCAL_QUARTER ELSE TRD1.FISCAL_QUARTER END REPORT_ENDING_FISCAL_QUARTER,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN 	TRD1.FISCAL_PERIOD ELSE TRD.FISCAL_PERIOD END REPORT_ENDING_FISCAL_PERIOD,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN 	TRD1.FISCAL_PERIOD_NAME ELSE TRD.FISCAL_PERIOD_NAME END REPORT_ENDING_PERIOD_FISCAL_NAME,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN 	TRD1.YEAR ELSE TRD.YEAR END REPORT_ENDING_CALENDAR_YEAR,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN 	TRD1.QUARTER ELSE TRD.QUARTER END REPORT_ENDING_CALENDAR_QUARTER,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN 	TRD1.MONTH ELSE TRD.MONTH END REPORT_ENDING_CALENDAR_MONTH,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN 	TRD1.MONTH_NAME ELSE TRD.MONTH_NAME END REPORT_ENDING_CALENDAR_MONTH_NAME,
	
	dbo.nCurrentMoSalesAmtOrQty(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.sReportEndingcalendarMonth(P.SRC_SYS_ID_POS,TRD1.MONTH,TRD.MONTH), dbo.nSalesExtendedAmtUsd(P.DISTRIBUTOR_NAME,P.EXTENDED_COST,P.COST_CURRENCY_EXCHANGE_USD)) as Current_Month_Sales_Extended_Amount,
	dbo.nYearToDateExtendedSalesAmtOrQty(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.nSalesExtendedAmtUsd(P.DISTRIBUTOR_NAME,P.EXTENDED_COST,P.COST_CURRENCY_EXCHANGE_USD)) as Year_To_Date_Extended_Sales_Amount,
	dbo.nPrevYearToDateSalesAmtOrQty(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.sReportEndingcalendarMonth(P.SRC_SYS_ID_POS,TRD1.MONTH,TRD.MONTH), dbo.nSalesExtendedAmtUsd(P.DISTRIBUTOR_NAME,P.EXTENDED_COST,P.COST_CURRENCY_EXCHANGE_USD)) as Previous_Year_To_date_Sales_Amount,
	dbo.nSalesExtendedAmtYoYchange(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.sReportEndingcalendarMonth(P.SRC_SYS_ID_POS,TRD1.MONTH,TRD.MONTH), dbo.nSalesExtendedAmtUsd(P.DISTRIBUTOR_NAME,P.EXTENDED_COST,P.COST_CURRENCY_EXCHANGE_USD)) as Sales_Extended_Amount_YoY_Change, 
	
	dbo.nCurrentMoSalesAmtOrQty(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.sReportEndingcalendarMonth(P.SRC_SYS_ID_POS,TRD1.MONTH,TRD.MONTH), P.QUANTITY) as Current_Month_Quantity,
	dbo.nYearToDateExtendedSalesAmtOrQty(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR),  P.QUANTITY ) as Year_To_Date_Extended_Quantity,
	dbo.nPrevYearToDateSalesAmtOrQty(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.sReportEndingcalendarMonth(P.SRC_SYS_ID_POS,TRD1.MONTH,TRD.MONTH),  P.QUANTITY) as Previous_Year_To_date_Quantity,
	dbo.nSalesExtendedAmtYoYchange(dbo.sReportEndingCalendarYear(P.SRC_SYS_ID_POS,TRD1.YEAR,TRD.YEAR), dbo.sReportEndingcalendarMonth(P.SRC_SYS_ID_POS,TRD1.MONTH,TRD.MONTH),  P.QUANTITY) as Sales_Quantity_YoY_Change
	
from	dbo.DM_F_POS_SALES as P

LEFT OUTER JOIN POSCleansingTable PI ON P.SRC_SYS_ID = PI.SRC_SYS_ID AND P.MANUFACTURER_PART_NUMBER = PI.VendorPartNumber
JOIN DM_D_CALENDAR T ON T.TIME_KEY=P.TIME_KEY
LEFT OUTER JOIN DM_D_CALENDAR TRD ON TRD.TIME_KEY=convert(VARCHAR(10),P.REPORT_ENDING_DATE,112)
LEFT OUTER JOIN XREF_DISTRIBUTOR D ON P.SRC_SYS_ID_POS = D.SRC_SYS_ID_POS AND ((P.DISTRIBUTOR_NAME = D.POS_ACCOUNT_NAME) OR (D.DIV_C = P.DISTRIBUTOR_NAME))
LEFT OUTER JOIN XREF_ANIXTER_INFO ANX ON P.DISTRIBUTOR_NAME = ANX.DISTRIBUTOR_NAME
LEFT OUTER JOIN TPR_POS_ANIXTER_V2 ANXTPR ON P.SRC_SYS_ID_POS = ANXTPR.SRC_SYS_ID AND P.INVOICE_NUMBER = ANXTPR.INVOICE_NUMBER AND P.DISTRIBUTOR_PART_NUMBER = ANXTPR.DISTRIBUTOR_PART_NUMBER AND P.EXTENDED_COST = ANXTPR.EXTENDED_UNIT_COST
LEFT OUTER JOIN DM_D_CALENDAR TRD1 ON TRD1.TIME_KEY=convert(VARCHAR(10),ANXTPR.REPORT_ENDING_DATE,112)

WHERE P.CURRENT_IND = 'Y' AND (P.SRC_SYS_ID = 'BPCSEU' OR P.SRC_SYS_ID = 'ASIASR')

GO


