
/* ftiFullText Index Rebuild */
ALTER FULLTEXT CATALOG ftEmailCatalog REBUILD WITH ACCENT_SENSITIVITY=OFF
go
ALTER FULLTEXT CATALOG ftCatalog REBUILD WITH ACCENT_SENSITIVITY=OFF
go
EXEC sp_updatestats
go