SELECT
DAY(GETDATE()) AS DAY,
MONTH(GETDATE()) AS MONTH,
YEAR(GETDATE()) AS YEAR,
DATENAME(WEEKDAY, GETDATE()) AS DATENAMEWeekDay,
DATEPART(M, GETDATE()) AS DATEPART,
DATEPART(WEEKDAY, GETDATE()) AS DatePartWeekDay,
DATENAME(MONTH, GETDATE()) AS DateNameMonth