SELECT
TRY_CAST('PATRICK' AS INT) TryCast,
TRY_CONVERT(DATETIME, '13/2/2999', 112) AS TryConvert,
PARSE('Saturday, 26 May 2012' AS DATETIME USING 'en-US') AS Parse,
TRY_PARSE('Patricks BirthDay' AS DATETIME USING 'en-US') AS TryParse