USE [master]
GO

/****** Object:  Database [ECM.SecureLogin]    Script Date: 7/26/2017 6:55:59 AM ******/
CREATE DATABASE [ECM.SecureLogin] ON  PRIMARY 
( NAME = N'ECM.SecureLogin', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\ECM.SecureLogin.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ECM.SecureLogin_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\ECM.SecureLogin_1.ldf' , SIZE = 24384KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ECM.SecureLogin] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ECM.SecureLogin].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ECM.SecureLogin] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ECM.SecureLogin] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ECM.SecureLogin] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ECM.SecureLogin] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ECM.SecureLogin] SET ARITHABORT OFF 
GO

ALTER DATABASE [ECM.SecureLogin] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ECM.SecureLogin] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ECM.SecureLogin] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ECM.SecureLogin] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ECM.SecureLogin] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ECM.SecureLogin] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ECM.SecureLogin] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ECM.SecureLogin] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ECM.SecureLogin] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ECM.SecureLogin] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ECM.SecureLogin] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ECM.SecureLogin] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ECM.SecureLogin] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ECM.SecureLogin] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ECM.SecureLogin] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ECM.SecureLogin] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ECM.SecureLogin] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ECM.SecureLogin] SET RECOVERY FULL 
GO

ALTER DATABASE [ECM.SecureLogin] SET  MULTI_USER 
GO

ALTER DATABASE [ECM.SecureLogin] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ECM.SecureLogin] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ECM.SecureLogin] SET  READ_WRITE 
GO


