USE [master]
GO

/****** Object:  Database [EcmGateway]    Script Date: 7/26/2017 6:57:12 AM ******/
CREATE DATABASE [EcmGateway] ON  PRIMARY 
( NAME = N'EcmGateway', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\EcmGateway.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'EcmGateway_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\EcmGateway_1.ldf' , SIZE = 8384KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [EcmGateway] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EcmGateway].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EcmGateway] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EcmGateway] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EcmGateway] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EcmGateway] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EcmGateway] SET ARITHABORT OFF 
GO

ALTER DATABASE [EcmGateway] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EcmGateway] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EcmGateway] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EcmGateway] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EcmGateway] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EcmGateway] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EcmGateway] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EcmGateway] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EcmGateway] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EcmGateway] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EcmGateway] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EcmGateway] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EcmGateway] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EcmGateway] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EcmGateway] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EcmGateway] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EcmGateway] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EcmGateway] SET RECOVERY FULL 
GO

ALTER DATABASE [EcmGateway] SET  MULTI_USER 
GO

ALTER DATABASE [EcmGateway] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EcmGateway] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EcmGateway] SET  READ_WRITE 
GO


