USE [master]
GO


if not exists (select 1 from sys.databases where name = 'ECM.Library.FS')
begin
CREATE DATABASE [ECM.Library.FS]
	CONTAINMENT = NONE
 	ON  PRIMARY 
( NAME = N'ECM.Library.FS', 
		FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\ECM.Library.FS.mdf' , 
		SIZE = 4096KB , 
		MAXSIZE = UNLIMITED, 
		FILEGROWTH = 2048KB )
 LOG ON 
( NAME = N'ECM.Library.FS_log', 
		FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\ECM.Library.FS_log.ldf' , 
		SIZE = 4096KB , 
		MAXSIZE = 2048GB , 
		FILEGROWTH = 10%)
end
GO

ALTER DATABASE [ECM.Library.FS] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ECM.Library.FS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ECM.Library.FS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET ARITHABORT OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ECM.Library.FS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ECM.Library.FS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ECM.Library.FS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ECM.Library.FS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET RECOVERY FULL 
GO

ALTER DATABASE [ECM.Library.FS] SET  MULTI_USER 
GO

ALTER DATABASE [ECM.Library.FS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ECM.Library.FS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET FILESTREAM( NON_TRANSACTED_ACCESS = FULL, DIRECTORY_NAME = N'FG_ECM_FileStream' ) 
GO

ALTER DATABASE [ECM.Library.FS] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ECM.Library.FS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ECM.Library.FS] SET  READ_WRITE 
GO
