USE [master]
GO

/****** Object:  Database [ECM.Library.FS]    Script Date: 7/26/2017 6:50:36 AM ******/
CREATE DATABASE [ECM.Library.FS] ON  PRIMARY 
( NAME = N'ECM.Library.FS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\ECM.Library.FS.mdf' , SIZE = 9168896KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB ), 
 FILEGROUP [ECM_fg_filestream] CONTAINS FILESTREAM  DEFAULT
( NAME = N'fs_filestream', FILENAME = N'C:\ECM.Library.FS_2.SqlSvrFS' , MAXSIZE = UNLIMITED)
 LOG ON 
( NAME = N'ECM.Library.FS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\ECM.Library.FS_1.ldf' , SIZE = 149477760KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ECM.Library.FS] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ECM.Library.FS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ECM.Library.FS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET ARITHABORT OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ECM.Library.FS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ECM.Library.FS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ECM.Library.FS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ECM.Library.FS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET RECOVERY FULL 
GO

ALTER DATABASE [ECM.Library.FS] SET  MULTI_USER 
GO

ALTER DATABASE [ECM.Library.FS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ECM.Library.FS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ECM.Library.FS] SET  READ_WRITE 
GO


