USE [master]
GO

/****** Object:  Database [ECM.Thesaurus]    Script Date: 7/26/2017 6:56:45 AM ******/
CREATE DATABASE [ECM.Thesaurus] ON  PRIMARY 
( NAME = N'ECM.Thesaurus', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\ECM.Thesaurus.mdf' , SIZE = 144384KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ECM.Thesaurus_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\ECM.Thesaurus_1.ldf' , SIZE = 757248KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ECM.Thesaurus] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ECM.Thesaurus].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ECM.Thesaurus] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ECM.Thesaurus] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ECM.Thesaurus] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ECM.Thesaurus] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ECM.Thesaurus] SET ARITHABORT OFF 
GO

ALTER DATABASE [ECM.Thesaurus] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ECM.Thesaurus] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ECM.Thesaurus] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ECM.Thesaurus] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ECM.Thesaurus] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ECM.Thesaurus] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ECM.Thesaurus] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ECM.Thesaurus] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ECM.Thesaurus] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ECM.Thesaurus] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ECM.Thesaurus] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ECM.Thesaurus] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ECM.Thesaurus] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ECM.Thesaurus] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ECM.Thesaurus] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ECM.Thesaurus] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ECM.Thesaurus] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ECM.Thesaurus] SET RECOVERY FULL 
GO

ALTER DATABASE [ECM.Thesaurus] SET  MULTI_USER 
GO

ALTER DATABASE [ECM.Thesaurus] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ECM.Thesaurus] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ECM.Thesaurus] SET  READ_WRITE 
GO


