USE [master]
GO

/****** Object:  Database [ECM.Hive]    Script Date: 7/28/2017 11:31:06 AM ******/
CREATE DATABASE [ECM.Hive] ON  PRIMARY 
( NAME = N'ECM.Hive', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\ECM.Hive.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ECM.Hive_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\ECM.Hive_log.ldf' , SIZE = 2560KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ECM.Hive] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ECM.Hive].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ECM.Hive] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ECM.Hive] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ECM.Hive] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ECM.Hive] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ECM.Hive] SET ARITHABORT OFF 
GO

ALTER DATABASE [ECM.Hive] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ECM.Hive] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ECM.Hive] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ECM.Hive] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ECM.Hive] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ECM.Hive] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ECM.Hive] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ECM.Hive] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ECM.Hive] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ECM.Hive] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ECM.Hive] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ECM.Hive] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ECM.Hive] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ECM.Hive] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ECM.Hive] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ECM.Hive] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ECM.Hive] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ECM.Hive] SET RECOVERY FULL 
GO

ALTER DATABASE [ECM.Hive] SET  MULTI_USER 
GO

ALTER DATABASE [ECM.Hive] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ECM.Hive] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ECM.Hive] SET  READ_WRITE 
GO


