'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace SVCFS
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CompositeType", [Namespace]:="http://schemas.datacontract.org/2004/07/EcmClcArchiveWcfFS"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CompositeType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BoolValueField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StringValueField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BoolValue() As Boolean
            Get
                Return Me.BoolValueField
            End Get
            Set
                If (Me.BoolValueField.Equals(value) <> true) Then
                    Me.BoolValueField = value
                    Me.RaisePropertyChanged("BoolValue")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StringValue() As String
            Get
                Return Me.StringValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StringValueField, value) <> true) Then
                    Me.StringValueField = value
                    Me.RaisePropertyChanged("StringValue")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="SVCFS.IService1")>  _
    Public Interface IService1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetData", ReplyAction:="http://tempuri.org/IService1/GetDataResponse")>  _
        Function GetData(ByVal value As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction:="http://tempuri.org/IService1/GetDataUsingDataContractResponse")>  _
        Function GetDataUsingDataContract(ByVal composite As SVCFS.CompositeType) As SVCFS.CompositeType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/UploadFile", ReplyAction:="http://tempuri.org/IService1/UploadFileResponse")>  _
        Sub UploadFile(ByVal fileData As System.IO.Stream)
        
        'CODEGEN: Generating message contract since the operation RemoteFileUpload is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/RemoteFileUpload", ReplyAction:="http://tempuri.org/IService1/RemoteFileUploadResponse")>  _
        Function RemoteFileUpload(ByVal request As SVCFS.RemoteFileUploadMsg) As SVCFS.RemoteFileUploadResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/UploadZippedFile", ReplyAction:="http://tempuri.org/IService1/UploadZippedFileResponse")>  _
        Sub UploadZippedFile(ByVal data As System.IO.FileStream)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="RemoteFileUploadMsg", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class RemoteFileUploadMsg
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public FileCrc As String
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public FileGuid As String
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public FileLength As Long
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public FileName As String
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public FileType As String
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public UID As String
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public bCompressed As Boolean
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public data As System.IO.Stream
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal FileCrc As String, ByVal FileGuid As String, ByVal FileLength As Long, ByVal FileName As String, ByVal FileType As String, ByVal UID As String, ByVal bCompressed As Boolean, ByVal data As System.IO.Stream)
            MyBase.New
            Me.FileCrc = FileCrc
            Me.FileGuid = FileGuid
            Me.FileLength = FileLength
            Me.FileName = FileName
            Me.FileType = FileType
            Me.UID = UID
            Me.bCompressed = bCompressed
            Me.data = data
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RemoteFileUploadResponse
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IService1Channel
        Inherits SVCFS.IService1, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Service1Client
        Inherits System.ServiceModel.ClientBase(Of SVCFS.IService1)
        Implements SVCFS.IService1
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetData(ByVal value As Integer) As String Implements SVCFS.IService1.GetData
            Return MyBase.Channel.GetData(value)
        End Function
        
        Public Function GetDataUsingDataContract(ByVal composite As SVCFS.CompositeType) As SVCFS.CompositeType Implements SVCFS.IService1.GetDataUsingDataContract
            Return MyBase.Channel.GetDataUsingDataContract(composite)
        End Function
        
        Public Sub UploadFile(ByVal fileData As System.IO.Stream) Implements SVCFS.IService1.UploadFile
            MyBase.Channel.UploadFile(fileData)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SVCFS_IService1_RemoteFileUpload(ByVal request As SVCFS.RemoteFileUploadMsg) As SVCFS.RemoteFileUploadResponse Implements SVCFS.IService1.RemoteFileUpload
            Return MyBase.Channel.RemoteFileUpload(request)
        End Function
        
        Public Sub RemoteFileUpload(ByVal FileCrc As String, ByVal FileGuid As String, ByVal FileLength As Long, ByVal FileName As String, ByVal FileType As String, ByVal UID As String, ByVal bCompressed As Boolean, ByVal data As System.IO.Stream)
            Dim inValue As SVCFS.RemoteFileUploadMsg = New SVCFS.RemoteFileUploadMsg()
            inValue.FileCrc = FileCrc
            inValue.FileGuid = FileGuid
            inValue.FileLength = FileLength
            inValue.FileName = FileName
            inValue.FileType = FileType
            inValue.UID = UID
            inValue.bCompressed = bCompressed
            inValue.data = data
            Dim retVal As SVCFS.RemoteFileUploadResponse = CType(Me,SVCFS.IService1).RemoteFileUpload(inValue)
        End Sub
        
        Public Sub UploadZippedFile(ByVal data As System.IO.FileStream) Implements SVCFS.IService1.UploadZippedFile
            MyBase.Channel.UploadZippedFile(data)
        End Sub
    End Class
End Namespace
