
USE [SMART]
/****** Object:  Index [_dta_index_MIRROR_DM_D_CUSTOMER_12_736109763__K1_K11_K33_10_12_13_14_15_16_17_18_19_20_21_22_23_24_25_26_27_28_29_30_31_32]    Script Date: 06/18/2011 11:44:55 ******/
CREATE NONCLUSTERED INDEX [_dta_index_MIRROR_DM_D_CUSTOMER_12_736109763__K1_K11_K33_10_12_13_14_15_16_17_18_19_20_21_22_23_24_25_26_27_28_29_30_31_32] ON [dbo].[MIRROR_DW_DM_D_CUSTOMER] 
(
	[CUSTOMER_KEY] ASC,
	[CUSTOMER_NBR] ASC,
	[CUST_TYPE_KEY] ASC
)
INCLUDE ( [UPDATE_DTTM],
[NAME],
[BILL_ADDR_LN1],
[BILL_ADDR_LN2],
[BILL_ADDR_LN3],
[BILL_CITY],
[BILL_STATE_CD],
[BILL_POSTAL_CD],
[BILL_COUNTRY_CD],
[COMPANY_NBR],
[ROUTE_CD],
[SALES_PERSON],
[DIVISION],
[REGION],
[SALES_CUST_NBR],
[TERRITORY],
[PREFIX_CD],
[FREIGHT_TERM_CD],
[SHIPPING_OFFICER],
[CUST_HOLD_CD],
[HEAD_CORP_PRNT],
[CORP_PRNT]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


USE [SMART]
/****** Object:  Index [_dta_index_MIRROR_DM_D_CUSTOMER_12_736109763__K33_K11_K1_10_12_13_14_15_16_17_18_19_20_21_22_23_24_25_26_27_28_29_30_31_32]    Script Date: 06/18/2011 11:44:55 ******/
CREATE NONCLUSTERED INDEX [_dta_index_MIRROR_DM_D_CUSTOMER_12_736109763__K33_K11_K1_10_12_13_14_15_16_17_18_19_20_21_22_23_24_25_26_27_28_29_30_31_32] ON [dbo].[MIRROR_DW_DM_D_CUSTOMER] 
(
	[CUST_TYPE_KEY] ASC,
	[CUSTOMER_NBR] ASC,
	[CUSTOMER_KEY] ASC
)
INCLUDE ( [UPDATE_DTTM],
[NAME],
[BILL_ADDR_LN1],
[BILL_ADDR_LN2],
[BILL_ADDR_LN3],
[BILL_CITY],
[BILL_STATE_CD],
[BILL_POSTAL_CD],
[BILL_COUNTRY_CD],
[COMPANY_NBR],
[ROUTE_CD],
[SALES_PERSON],
[DIVISION],
[REGION],
[SALES_CUST_NBR],
[TERRITORY],
[PREFIX_CD],
[FREIGHT_TERM_CD],
[SHIPPING_OFFICER],
[CUST_HOLD_CD],
[HEAD_CORP_PRNT],
[CORP_PRNT]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


USE [SMART]
/****** Object:  Index [AK_DM_D_CUSTOMER]    Script Date: 06/18/2011 11:44:55 ******/
CREATE NONCLUSTERED INDEX [AK_DM_D_CUSTOMER] ON [dbo].[MIRROR_DW_DM_D_CUSTOMER] 
(
	[SRC_SYS_ID] ASC,
	[CUSTOMER_NBR] ASC,
	[CURRENT_IND] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


USE [SMART]
/****** Object:  Index [CustKeyBillAddEtcI]    Script Date: 06/18/2011 11:44:55 ******/
CREATE NONCLUSTERED INDEX [CustKeyBillAddEtcI] ON [dbo].[MIRROR_DW_DM_D_CUSTOMER] 
(
	[CUSTOMER_KEY] ASC,
	[BILL_ADDR_LN1] ASC,
	[BILL_ADDR_LN2] ASC,
	[BILL_ADDR_LN3] ASC,
	[BILL_CITY] ASC,
	[BILL_STATE_CD] ASC,
	[BILL_POSTAL_CD] ASC,
	[BILL_COUNTRY_CD] ASC,
	[NAME] ASC,
	[CUSTOMER_NBR] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


USE [SMART]
/****** Object:  Index [CustKeyCustNbrI]    Script Date: 06/18/2011 11:44:55 ******/
CREATE NONCLUSTERED INDEX [CustKeyCustNbrI] ON [dbo].[MIRROR_DW_DM_D_CUSTOMER] 
(
	[CUSTOMER_KEY] ASC,
	[CUSTOMER_NBR] ASC
)
INCLUDE ( [EFF_START_DTTM],
[EFF_END_DTTM],
[CURRENT_IND],
[DELETE_IND],
[INFERRED_IND],
[UPDATE_DTTM],
[NAME],
[BILL_ADDR_LN1],
[BILL_ADDR_LN2],
[BILL_ADDR_LN3],
[BILL_CITY],
[BILL_STATE_CD],
[BILL_POSTAL_CD],
[BILL_COUNTRY_CD],
[COMPANY_NBR],
[ROUTE_CD],
[SALES_PERSON],
[DIVISION],
[REGION],
[SALES_CUST_NBR],
[TERRITORY],
[PREFIX_CD],
[FREIGHT_TERM_CD],
[SHIPPING_OFFICER],
[CUST_HOLD_CD],
[HEAD_CORP_PRNT],
[CORP_PRNT],
[CUST_TYPE_KEY],
[CHECKSUM_KEY]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


USE [SMART]
/****** Object:  Index [CustKeyNameCustNbrI]    Script Date: 06/18/2011 11:44:55 ******/
CREATE NONCLUSTERED INDEX [CustKeyNameCustNbrI] ON [dbo].[MIRROR_DW_DM_D_CUSTOMER] 
(
	[CUSTOMER_KEY] ASC,
	[NAME] ASC,
	[CUSTOMER_NBR] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


USE [SMART]
/****** Object:  Index [CustKeySrcSysCustNbrI]    Script Date: 06/18/2011 11:44:55 ******/
CREATE NONCLUSTERED INDEX [CustKeySrcSysCustNbrI] ON [dbo].[MIRROR_DW_DM_D_CUSTOMER] 
(
	[CUSTOMER_KEY] ASC,
	[SRC_SYS_ID] ASC,
	[CUSTOMER_NBR] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


USE [SMART]
/****** Object:  Index [CustTypSrcCustNbrI]    Script Date: 06/18/2011 11:44:55 ******/
CREATE NONCLUSTERED INDEX [CustTypSrcCustNbrI] ON [dbo].[MIRROR_DW_DM_D_CUSTOMER] 
(
	[CUST_TYPE_KEY] ASC,
	[SRC_SYS_ID] ASC,
	[CUSTOMER_NBR] ASC,
	[CUSTOMER_KEY] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


USE [SMART]
/****** Object:  Index [DM_D_CUSTOMER_CustKeyCustNbrI]    Script Date: 06/18/2011 11:44:55 ******/
CREATE NONCLUSTERED INDEX [DM_D_CUSTOMER_CustKeyCustNbrI] ON [dbo].[MIRROR_DW_DM_D_CUSTOMER] 
(
	[CUSTOMER_KEY] ASC,
	[CUSTOMER_NBR] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


USE [SMART]
/****** Object:  Index [MIRROR_DW_DM_D_CUSTOMER]    Script Date: 06/18/2011 11:44:55 ******/
CREATE NONCLUSTERED INDEX [MIRROR_DW_DM_D_CUSTOMER] ON [dbo].[MIRROR_DW_DM_D_CUSTOMER] 
(
	[CUSTOMER_KEY] ASC
)
INCLUDE ( [UPDATE_DTTM]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


USE [SMART]
/****** Object:  Index [NmCustKeyCustNbr]    Script Date: 06/18/2011 11:44:55 ******/
CREATE NONCLUSTERED INDEX [NmCustKeyCustNbr] ON [dbo].[MIRROR_DW_DM_D_CUSTOMER] 
(
	[NAME] ASC,
	[CUSTOMER_KEY] ASC,
	[CUSTOMER_NBR] ASC,
	[SRC_SYS_ID] ASC,
	[CUST_TYPE_KEY] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


USE [SMART]
/****** Object:  Index [PI01_MIRROR_DM_D_CUSTOMER]    Script Date: 06/18/2011 11:44:55 ******/
CREATE NONCLUSTERED INDEX [PI01_MIRROR_DM_D_CUSTOMER] ON [dbo].[MIRROR_DW_DM_D_CUSTOMER] 
(
	[CUST_TYPE_KEY] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


USE [SMART]
/****** Object:  Index [PI11_MIRROR_DM_D_CUSTOMER]    Script Date: 06/18/2011 11:44:55 ******/
CREATE NONCLUSTERED INDEX [PI11_MIRROR_DM_D_CUSTOMER] ON [dbo].[MIRROR_DW_DM_D_CUSTOMER] 
(
	[CUSTOMER_KEY] ASC,
	[CUSTOMER_NBR] ASC,
	[CUST_TYPE_KEY] ASC
)
INCLUDE ( [UPDATE_DTTM],
[BILL_ADDR_LN1],
[BILL_ADDR_LN2],
[BILL_ADDR_LN3],
[BILL_CITY],
[BILL_STATE_CD],
[BILL_POSTAL_CD],
[BILL_COUNTRY_CD],
[COMPANY_NBR],
[ROUTE_CD],
[SALES_PERSON],
[SALES_CUST_NBR],
[TERRITORY],
[PREFIX_CD],
[FREIGHT_TERM_CD],
[SHIPPING_OFFICER],
[CUST_HOLD_CD],
[HEAD_CORP_PRNT],
[CORP_PRNT]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/******************************************************/



USE [SMART]
/****** Object:  Index [CI01_MIRROR_DW_DM_D_CALENDAR]    Script Date: 06/18/2011 11:47:09 ******/
CREATE NONCLUSTERED INDEX [CI01_MIRROR_DW_DM_D_CALENDAR] ON [dbo].[MIRROR_DW_DM_D_CALENDAR] 
(
	[TIME_KEY] ASC
)
INCLUDE ( [UPDATE_DTTM]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


USE [SMART]
/****** Object:  Index [FiscYrTKeyFiscPeriodEtcI]    Script Date: 06/18/2011 11:47:09 ******/
CREATE NONCLUSTERED INDEX [FiscYrTKeyFiscPeriodEtcI] ON [dbo].[MIRROR_DW_DM_D_CALENDAR] 
(
	[FISCAL_YEAR] ASC,
	[TIME_KEY] ASC,
	[FISCAL_PERIOD] ASC,
	[FISCAL_PERIOD_NAME] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


USE [SMART]
/****** Object:  Index [FscPrdDtTKeyFiscYrI]    Script Date: 06/18/2011 11:47:09 ******/
CREATE NONCLUSTERED INDEX [FscPrdDtTKeyFiscYrI] ON [dbo].[MIRROR_DW_DM_D_CALENDAR] 
(
	[FISCAL_PERIOD] ASC,
	[DATE] ASC,
	[TIME_KEY] ASC,
	[FISCAL_YEAR] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


USE [SMART]
/****** Object:  Index [Pi12_MIRROR_DW_DM_D_CALENDAR]    Script Date: 06/18/2011 11:47:09 ******/
CREATE NONCLUSTERED INDEX [Pi12_MIRROR_DW_DM_D_CALENDAR] ON [dbo].[MIRROR_DW_DM_D_CALENDAR] 
(
	[TIME_KEY] ASC
)
INCLUDE ( [UPDATE_DTTM],
[DATE],
[FISCAL_YEAR],
[FISCAL_QUARTER],
[FISCAL_PERIOD],
[FISCAL_PERIOD_NAME],
[DAY_OF_WEEK],
[WEEKEND_FLG],
[HOLIDAY_FLG]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


USE [SMART]
/****** Object:  Index [TimeKeyFiscPerStrtDtEtcI]    Script Date: 06/18/2011 11:47:09 ******/
CREATE NONCLUSTERED INDEX [TimeKeyFiscPerStrtDtEtcI] ON [dbo].[MIRROR_DW_DM_D_CALENDAR] 
(
	[TIME_KEY] ASC,
	[FISCAL_PER_START_DT] ASC,
	[FISCAL_YEAR] ASC,
	[FISCAL_PERIOD] ASC,
	[DATE] ASC,
	[DAY_OF_WEEK] ASC,
	[FISCAL_PERIOD_NAME] ASC,
	[FISCAL_QUARTER] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


USE [SMART]
/****** Object:  Index [TimeKeyFiscQtrFiscYearI]    Script Date: 06/18/2011 11:47:09 ******/
CREATE NONCLUSTERED INDEX [TimeKeyFiscQtrFiscYearI] ON [dbo].[MIRROR_DW_DM_D_CALENDAR] 
(
	[TIME_KEY] ASC,
	[FISCAL_QUARTER] ASC,
	[FISCAL_YEAR] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


USE [SMART]
/****** Object:  Index [TimeKeyFiscYearFiscPeriodDateDOWEtcI]    Script Date: 06/18/2011 11:47:09 ******/
CREATE NONCLUSTERED INDEX [TimeKeyFiscYearFiscPeriodDateDOWEtcI] ON [dbo].[MIRROR_DW_DM_D_CALENDAR] 
(
	[TIME_KEY] ASC,
	[FISCAL_YEAR] ASC,
	[FISCAL_PERIOD] ASC,
	[DATE] ASC,
	[DAY_OF_WEEK] ASC,
	[FISCAL_PERIOD_NAME] ASC,
	[FISCAL_QUARTER] ASC,
	[WEEKEND_FLG] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


USE [SMART]
/****** Object:  Index [TKeyDtFiscYearEtcI]    Script Date: 06/18/2011 11:47:09 ******/
CREATE NONCLUSTERED INDEX [TKeyDtFiscYearEtcI] ON [dbo].[MIRROR_DW_DM_D_CALENDAR] 
(
	[TIME_KEY] ASC,
	[DATE] ASC,
	[FISCAL_YEAR] ASC,
	[FISCAL_PERIOD] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/******************************************************/

CREATE NONCLUSTERED INDEX [PI_MIRROR_DW_CUST_TYPE] ON [dbo].[MIRROR_DW_DM_D_CUSTOMER_TYPE] 
(
	[CUST_TYPE_KEY] ASC,
	[CUSTOMER_TYPE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


CREATE NONCLUSTERED INDEX [PI_MIRROR_CUST_TYPE] ON [dbo].[MIRROR_DM_D_CUSTOMER_TYPE] 
(
	[CUST_TYPE_KEY] ASC,
	[CUSTOMER_TYPE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/******************************************************/
USE [SMART]
/****** Object:  Index [_dta_index_DM_H_ITEM_11_165575628__K6_K3_K31_K9_1_2_4_5_7_8_10_11_12_13_14_15_16_17_18_19_20_21_22_23_24_25_26_27_28_29_30]    Script Date: 06/18/2011 11:52:03 ******/
CREATE NONCLUSTERED INDEX [_dta_index_DM_H_ITEM_11_165575628__K6_K3_K31_K9_1_2_4_5_7_8_10_11_12_13_14_15_16_17_18_19_20_21_22_23_24_25_26_27_28_29_30] ON [dbo].[MIRROR_DW_DM_H_ITEM] 
(
	[CURRENT_IND] ASC,
	[SRC_SYS_ID] ASC,
	[HIERARCHY_ID] ASC,
	[ITEM_NBR] ASC
)
INCLUDE ( [ITEM_HIERARCHY_KEY],
[RUN_ID],
[EFF_START_DTTM],
[EFF_END_DTTM],
[DELETE_IND],
[UPDATE_DTTM],
[LEVEL01_CD],
[LEVEL01_NAME],
[LEVEL02_CD],
[LEVEL02_NAME],
[LEVEL03_CD],
[LEVEL03_NAME],
[LEVEL04_CD],
[LEVEL04_NAME],
[LEVEL05_CD],
[LEVEL05_NAME],
[LEVEL06_CD],
[LEVEL06_NAME],
[LEVEL07_CD],
[LEVEL07_NAME],
[LEVEL08_CD],
[LEVEL08_NAME],
[LEVEL09_CD],
[LEVEL09_NAME],
[LEVEL10_CD],
[LEVEL10_NAME],
[CHECKSUM_KEY]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


USE [SMART]
/****** Object:  Index [AK_DM_H_ITEM]    Script Date: 06/18/2011 11:52:03 ******/
CREATE NONCLUSTERED INDEX [AK_DM_H_ITEM] ON [dbo].[MIRROR_DW_DM_H_ITEM] 
(
	[SRC_SYS_ID] ASC,
	[CURRENT_IND] ASC,
	[ITEM_NBR] ASC,
	[HIERARCHY_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


USE [SMART]
/****** Object:  Index [CurIndHierDelIndSrcSysItmNbrI]    Script Date: 06/18/2011 11:52:03 ******/
CREATE NONCLUSTERED INDEX [CurIndHierDelIndSrcSysItmNbrI] ON [dbo].[MIRROR_DW_DM_H_ITEM] 
(
	[CURRENT_IND] ASC,
	[HIERARCHY_ID] ASC,
	[DELETE_IND] ASC,
	[SRC_SYS_ID] ASC,
	[ITEM_NBR] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


USE [SMART]
/****** Object:  Index [HierCurIndDelIndItmNbISrcSysI]    Script Date: 06/18/2011 11:52:03 ******/
CREATE NONCLUSTERED INDEX [HierCurIndDelIndItmNbISrcSysI] ON [dbo].[MIRROR_DW_DM_H_ITEM] 
(
	[HIERARCHY_ID] ASC,
	[CURRENT_IND] ASC,
	[DELETE_IND] ASC,
	[ITEM_NBR] ASC,
	[SRC_SYS_ID] ASC
)
INCLUDE ( [LEVEL01_NAME],
[LEVEL02_CD]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


USE [SMART]
/****** Object:  Index [SrcHierCurIndDelEtcI]    Script Date: 06/18/2011 11:52:03 ******/
CREATE NONCLUSTERED INDEX [SrcHierCurIndDelEtcI] ON [dbo].[MIRROR_DW_DM_H_ITEM] 
(
	[SRC_SYS_ID] ASC,
	[HIERARCHY_ID] ASC,
	[CURRENT_IND] ASC,
	[DELETE_IND] ASC,
	[ITEM_NBR] ASC,
	[LEVEL01_NAME] ASC,
	[LEVEL02_CD] ASC
)
INCLUDE ( [ITEM_HIERARCHY_KEY]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

/******************************************************/

USE [SMART]
/****** Object:  Index [CI01_MIRROR_DM_L_HIERARCHY]    Script Date: 06/18/2011 11:53:08 ******/
CREATE NONCLUSTERED INDEX [CI01_MIRROR_DM_L_HIERARCHY] ON [dbo].[MIRROR_DW_DM_L_HIERARCHY] 
(
	[HIERARCHY_ID] ASC
)
INCLUDE ( [UPDATE_DTTM]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


USE [SMART]
/****** Object:  Index [PI01_MIRROR_DM_L_HIERARCHY]    Script Date: 06/18/2011 11:53:08 ******/
CREATE NONCLUSTERED INDEX [PI01_MIRROR_DM_L_HIERARCHY] ON [dbo].[MIRROR_DW_DM_L_HIERARCHY] 
(
	[HIERARCHY_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


USE [SMART]
/****** Object:  Index [PI02_MIRROR_DM_L_HIERARCHY]    Script Date: 06/18/2011 11:53:08 ******/
CREATE NONCLUSTERED INDEX [PI02_MIRROR_DM_L_HIERARCHY] ON [dbo].[MIRROR_DW_DM_L_HIERARCHY] 
(
	[NAME] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

/*******************************************/
[MIRROR_DW_DM_F_SALES_SUMMARY]USE [SMART]
/****** Object:  Index [CI01_SalesSummary]    Script Date: 06/18/2011 11:54:41 ******/
CREATE NONCLUSTERED INDEX [CI01_SalesSummary] ON [dbo].[MIRROR_DW_DM_F_SALES_SUMMARY] 
(
	[RECORD_KEY] ASC
)
INCLUDE ( [UPDATE_DTTM]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


USE [SMART]
/****** Object:  Index [SrcCustAmtEtcI]    Script Date: 06/18/2011 11:54:41 ******/
CREATE NONCLUSTERED INDEX [SrcCustAmtEtcI] ON [dbo].[MIRROR_DW_DM_F_SALES_SUMMARY] 
(
	[SRC_SYS_ID] ASC,
	[CUST_SALE_AMT] ASC,
	[TIME_KEY] ASC,
	[CUSTOMER_KEY] ASC,
	[ITEM_KEY] ASC
)
INCLUDE ( [INTER_SALE_AMT],
[INTRA_SALE_AMT],
[SND_ADJUST_AMT],
[OTH_ADJUST_AMT],
[CREDIT_RMA_AMT],
[TO_EUR_RATE]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


USE [SMART]
/****** Object:  Index [SrcItKeyTimeKeyCustKeyI]    Script Date: 06/18/2011 11:54:41 ******/
CREATE NONCLUSTERED INDEX [SrcItKeyTimeKeyCustKeyI] ON [dbo].[MIRROR_DW_DM_F_SALES_SUMMARY] 
(
	[SRC_SYS_ID] ASC,
	[ITEM_KEY] ASC,
	[TIME_KEY] ASC,
	[CUSTOMER_KEY] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


USE [SMART]
/****** Object:  Index [SrcTKeyItKeyInvEtcI]    Script Date: 06/18/2011 11:54:41 ******/
CREATE NONCLUSTERED INDEX [SrcTKeyItKeyInvEtcI] ON [dbo].[MIRROR_DW_DM_F_SALES_SUMMARY] 
(
	[SRC_SYS_ID] ASC,
	[TIME_KEY] ASC,
	[ITEM_KEY] ASC,
	[INVOICE_NBR] ASC,
	[CUSTOMER_KEY] ASC
)
INCLUDE ( [CUST_SALE_AMT],
[INTER_SALE_AMT],
[INTRA_SALE_AMT],
[FREIGHT_AMT],
[SND_ADJUST_AMT],
[OTH_ADJUST_AMT],
[CREDIT_RMA_AMT],
[LOC_RMCC_AMT],
[TO_EUR_RATE],
[TRX_TYPE]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


USE [SMART]
/****** Object:  Index [TimeKeySrcCustKeyItemKey]    Script Date: 06/18/2011 11:54:41 ******/
CREATE NONCLUSTERED INDEX [TimeKeySrcCustKeyItemKey] ON [dbo].[MIRROR_DW_DM_F_SALES_SUMMARY] 
(
	[TIME_KEY] ASC,
	[SRC_SYS_ID] ASC,
	[CUSTOMER_KEY] ASC,
	[ITEM_KEY] ASC
)
INCLUDE ( [CUST_SALE_AMT],
[INTER_SALE_AMT],
[INTRA_SALE_AMT],
[SND_ADJUST_AMT],
[OTH_ADJUST_AMT],
[CREDIT_RMA_AMT],
[ALLOWANCE_AMT],
[LOC_FSTD_CST_AMT]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

/*********************************************/
USE [SMART]
/****** Object:  Index [_dta_index_MIRROR_DM_D_ITEM_CLASS_12_160107711__K1_9_10_15_21]    Script Date: 06/18/2011 11:56:00 ******/
CREATE NONCLUSTERED INDEX [_dta_index_MIRROR_DM_D_ITEM_CLASS_12_160107711__K1_9_10_15_21] ON [dbo].[MIRROR_DW_DM_D_ITEM_CLASS] 
(
	[ITEM_CLASS_KEY] ASC
)
INCLUDE ( [UPDATE_DTTM],
[ITEM_CLASS],
[SCPG],
[PRODUCT_GRP]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


USE [SMART]
/****** Object:  Index [AK_DM_D_ITEM_CLASS]    Script Date: 06/18/2011 11:56:00 ******/
CREATE NONCLUSTERED INDEX [AK_DM_D_ITEM_CLASS] ON [dbo].[MIRROR_DW_DM_D_ITEM_CLASS] 
(
	[SRC_SYS_ID] ASC,
	[ITEM_CLASS] ASC,
	[CURRENT_IND] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


USE [SMART]
/****** Object:  Index [CI01_MIRROR_DM_D_ITEM_CLASS ]    Script Date: 06/18/2011 11:56:00 ******/
CREATE NONCLUSTERED INDEX [CI01_MIRROR_DM_D_ITEM_CLASS ] ON [dbo].[MIRROR_DW_DM_D_ITEM_CLASS] 
(
	[ITEM_CLASS_KEY] ASC
)
INCLUDE ( [UPDATE_DTTM]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


USE [SMART]
/****** Object:  Index [IX_01]    Script Date: 06/18/2011 11:56:00 ******/
CREATE NONCLUSTERED INDEX [IX_01] ON [dbo].[MIRROR_DW_DM_D_ITEM_CLASS] 
(
	[ITEM_CLASS] ASC
)
INCLUDE ( [SRC_SYS_ID],
[CURRENT_IND],
[DELETE_IND],
[STD_OR_SPC_FLG]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


