SELECT SUM(NET_BILLING_AMT) as _Master FROM GLOBAL_BI WHERE Fiscal_Period='06' AND FISCAL_YEAR='2011'
GO
SELECT SUM(NET_BILLING_AMT) as _MIRROR FROM GLOBAL_BI_MIRROR WHERE Fiscal_Period='06' AND FISCAL_YEAR='2011'
GO

SELECT SUM(NET_BILLING_AMT) as Master_P1of3 FROM vGLOBAL_BI_EXTRACT_Master_P1of3 WHERE Fiscal_Period='06' AND FISCAL_YEAR='2011'
GO 
SELECT SUM(NET_BILLING_AMT) as Mirror_P1of3 FROM vGLOBAL_BI_EXTRACT_MIRROR_P1of3 WHERE Fiscal_Period='06' AND FISCAL_YEAR='2011'
GO

SELECT SUM(NET_BILLING_AMT) as Master_P2of3 FROM vGLOBAL_BI_EXTRACT_Master_P2of3 WHERE Fiscal_Period='06' AND FISCAL_YEAR='2011'
GO
SELECT SUM(NET_BILLING_AMT) as MIRROR_P2of3 FROM vGLOBAL_BI_EXTRACT_MIRROR_P2of3 WHERE Fiscal_Period='06' AND FISCAL_YEAR='2011'
GO

SELECT SUM(NET_BILLING_AMT) as Master_P3of3 FROM vGLOBAL_BI_EXTRACT_Master_P3of3 WHERE Fiscal_Period='06' AND FISCAL_YEAR='2011'
GO
SELECT SUM(NET_BILLING_AMT) as MIRROR_P3of3 FROM vGLOBAL_BI_EXTRACT_MIRROR_P3of3 WHERE Fiscal_Period='06' AND FISCAL_YEAR='2011'
GO

