// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Runtime Version:4.0.30319.42000
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using Microsoft.VisualBasic;
using Microsoft.VisualBasic.CompilerServices;
using MODI;

namespace EcmArchiver.My
{
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [System.CodeDom.Compiler.GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
    internal sealed partial class MySettings : System.Configuration.ApplicationSettingsBase
    {
        private static MySettings defaultInstance = (MySettings)Synchronized(new MySettings());

        /* TODO ERROR: Skipped RegionDirectiveTrivia *//* TODO ERROR: Skipped IfDirectiveTrivia */
        private static bool addedHandler;
        private static object addedHandlerLockObject = new object();

        [DebuggerNonUserCode()]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        private static void AutoSaveSettings(object sender, EventArgs e)
        {
            if (MyProject.Application.SaveMySettingsOnExit)
            {
                MySettingsProperty.Settings.Save();
            }
        }
        /* TODO ERROR: Skipped EndIfDirectiveTrivia *//* TODO ERROR: Skipped EndRegionDirectiveTrivia */
        public static MySettings Default
        {
            get
            {

                /* TODO ERROR: Skipped IfDirectiveTrivia */
                if (!addedHandler)
                {
                    lock (addedHandlerLockObject)
                    {
                        if (!addedHandler)
                        {
                            MyProject.Application.Shutdown += AutoSaveSettings;
                            addedHandler = true;
                        }
                    }
                }
                /* TODO ERROR: Skipped EndIfDirectiveTrivia */
                return defaultInstance;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("?")]
        public string UserDefaultConnString
        {
            get
            {
                return Conversions.ToString(this["UserDefaultConnString"]);
            }

            set
            {
                this["UserDefaultConnString"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("True")]
        public bool UpgradeSettings
        {
            get
            {
                return Conversions.ToBoolean(this["UpgradeSettings"]);
            }

            set
            {
                this["UpgradeSettings"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("Data Source=T410A/Gina;Initial Catalog=ECM.Hive;Integrated Security=True")]
        public string UserThesaurusConnString
        {
            get
            {
                return Conversions.ToString(this["UserThesaurusConnString"]);
            }

            set
            {
                this["UserThesaurusConnString"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("Data Source=T410A/Gina;Initial Catalog=ECM.Hive;Integrated Security=True")]
        public string DB_EcmLibrary
        {
            get
            {
                return Conversions.ToString(this["DB_EcmLibrary"]);
            }

            set
            {
                this["DB_EcmLibrary"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("Data Source=T410A/Gina;Initial Catalog=ECM.Hive;Integrated Security=True")]
        public string DB_Thesaurus
        {
            get
            {
                return Conversions.ToString(this["DB_Thesaurus"]);
            }

            set
            {
                this["DB_Thesaurus"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("Highland Park, Illinois")]
        public string User_FacilityName
        {
            get
            {
                return Conversions.ToString(this["User_FacilityName"]);
            }

            set
            {
                this["User_FacilityName"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0")]
        public string ProcessJpgAsTIF
        {
            get
            {
                return Conversions.ToString(this["ProcessJpgAsTIF"]);
            }

            set
            {
                this["ProcessJpgAsTIF"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0")]
        public int BackupIntervalHours
        {
            get
            {
                return Conversions.ToInteger(this["BackupIntervalHours"]);
            }

            set
            {
                this["BackupIntervalHours"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("04/19/2011 10:08:00")]
        public DateTime LastArchiveEndTime
        {
            get
            {
                return Conversions.ToDate(this["LastArchiveEndTime"]);
            }

            set
            {
                this["LastArchiveEndTime"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("")]
        public string MasterFile
        {
            get
            {
                return Conversions.ToString(this["MasterFile"]);
            }

            set
            {
                this["MasterFile"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("")]
        public string MasterConnectionStr
        {
            get
            {
                return Conversions.ToString(this["MasterConnectionStr"]);
            }

            set
            {
                this["MasterConnectionStr"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("False")]
        public bool UserMasterFile
        {
            get
            {
                return Conversions.ToBoolean(this["UserMasterFile"]);
            }

            set
            {
                this["UserMasterFile"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("")]
        public string DefaultLoginID
        {
            get
            {
                return Conversions.ToString(this["DefaultLoginID"]);
            }

            set
            {
                this["DefaultLoginID"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("")]
        public string DefaultLoginPW
        {
            get
            {
                return Conversions.ToString(this["DefaultLoginPW"]);
            }

            set
            {
                this["DefaultLoginPW"] = value;
            }
        }

        [System.Configuration.ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.SpecialSetting(System.Configuration.SpecialSetting.ConnectionString)]
        [System.Configuration.DefaultSettingValue(@"Data Source=|DataDirectory|\CE\EcmFileStore.sdf")]
        public string EcmFileStoreConnectionString
        {
            get
            {
                return Conversions.ToString(this["EcmFileStoreConnectionString"]);
            }
        }

        [System.Configuration.ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.SpecialSetting(System.Configuration.SpecialSetting.ConnectionString)]
        [System.Configuration.DefaultSettingValue(@"Data Source=|DataDirectory|\CE\DirDB.sdf")]
        public string DirDBConnectionString
        {
            get
            {
                return Conversions.ToString(this["DirDBConnectionString"]);
            }
        }

        [System.Configuration.ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.SpecialSetting(System.Configuration.SpecialSetting.ConnectionString)]
        [System.Configuration.DefaultSettingValue(@"Data Source=|DataDirectory|\CE\FileDB.sdf")]
        public string FileDBConnectionString
        {
            get
            {
                return Conversions.ToString(this["FileDBConnectionString"]);
            }
        }

        [System.Configuration.ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.SpecialSetting(System.Configuration.SpecialSetting.ConnectionString)]
        [System.Configuration.DefaultSettingValue(@"Data Source=|DataDirectory|\CE\OutlookEmail.sdf")]
        public string OutlookEmailConnectionString
        {
            get
            {
                return Conversions.ToString(this["OutlookEmailConnectionString"]);
            }
        }

        [System.Configuration.ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.SpecialSetting(System.Configuration.SpecialSetting.ConnectionString)]
        [System.Configuration.DefaultSettingValue(@"Data Source=|DataDirectory|\CE\ExchangeEmail.sdf")]
        public string ExchangeEmailConnectionString
        {
            get
            {
                return Conversions.ToString(this["ExchangeEmailConnectionString"]);
            }
        }

        [System.Configuration.ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.SpecialSetting(System.Configuration.SpecialSetting.ConnectionString)]
        [System.Configuration.DefaultSettingValue(@"Data Source=|DataDirectory|\CE\Listeners.sdf")]
        public string ListenersConnectionString
        {
            get
            {
                return Conversions.ToString(this["ListenersConnectionString"]);
            }
        }

        [System.Configuration.ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.SpecialSetting(System.Configuration.SpecialSetting.ConnectionString)]
        [System.Configuration.DefaultSettingValue(@"Data Source=|DataDirectory|\BackupItems\DirDB.sdf")]
        public string DirDBConnectionString1
        {
            get
            {
                return Conversions.ToString(this["DirDBConnectionString1"]);
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("250")]
        public string EmailBodyLength
        {
            get
            {
                return Conversions.ToString(this["EmailBodyLength"]);
            }

            set
            {
                this["EmailBodyLength"] = value;
            }
        }

        [System.Configuration.ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.SpecialSetting(System.Configuration.SpecialSetting.ConnectionString)]
        [System.Configuration.DefaultSettingValue(@"Data Source=|DataDirectory|\CE\ZipFiles.sdf")]
        public string ZipFilesConnectionString
        {
            get
            {
                return Conversions.ToString(this["ZipFilesConnectionString"]);
            }
        }

        [System.Configuration.ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.SpecialSetting(System.Configuration.SpecialSetting.ConnectionString)]
        [System.Configuration.DefaultSettingValue(@"Data Source=|DataDirectory|\CE\OutlookContacts.sdf")]
        public string OutlookContactsConnectionString
        {
            get
            {
                return Conversions.ToString(this["OutlookContactsConnectionString"]);
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("?")]
        public string GatewayConnString
        {
            get
            {
                return Conversions.ToString(this["GatewayConnString"]);
            }

            set
            {
                this["GatewayConnString"] = value;
            }
        }

        [System.Configuration.ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.SpecialSetting(System.Configuration.SpecialSetting.ConnectionString)]
        [System.Configuration.DefaultSettingValue("Data Source=ALIEN15;Initial Catalog=ECM.Hive;Integrated Security=True")]
        public string ECMHive
        {
            get
            {
                return Conversions.ToString(this["ECMHive"]);
            }
        }
    }
}

namespace EcmArchiver.My
{
    [HideModuleName()]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    internal static class MySettingsProperty
    {
        [System.ComponentModel.Design.HelpKeyword("My.Settings")]
        internal static MySettings Settings
        {
            get
            {
                return MySettings.Default;
            }
        }
    }
}