


--select 'Select ''' + table_name + ''', ItemID from ' + table_name + ' Where EventDate < ''1900-01-01''' from information_schema.tables where table_name like 'hfit_track%'

--Select 'HFIT_Tracker', ItemID from HFIT_Tracker Where EventDate < '1900-01-01'
Select 'HFit_TrackerBloodPressure', ItemID from HFit_TrackerBloodPressure Where EventDate < '1900-01-01'
Select 'HFit_TrackerBloodSugarAndGlucose', ItemID from HFit_TrackerBloodSugarAndGlucose Where EventDate < '1900-01-01'
Select 'HFit_TrackerBMI', ItemID from HFit_TrackerBMI Where EventDate < '1900-01-01'
Select 'HFit_TrackerBodyFat', ItemID from HFit_TrackerBodyFat Where EventDate < '1900-01-01'
Select 'HFit_TrackerBodyMeasurements', ItemID from HFit_TrackerBodyMeasurements Where EventDate < '1900-01-01'
Select 'HFit_TrackerCardio', ItemID from HFit_TrackerCardio Where EventDate < '1900-01-01'

--Select 'HFit_TrackerCategory', ItemID from HFit_TrackerCategory Where EventDate < '1900-01-01'

Select 'HFit_TrackerCholesterol', ItemID from HFit_TrackerCholesterol Where EventDate < '1900-01-01'
--select * from HFit_TrackerCollectionSource
--Select 'HFit_TrackerCollectionSource', ItemID from HFit_TrackerCollectionSource Where EventDate < '1900-01-01'
Select 'HFit_TrackerCotinine', ItemID from HFit_TrackerCotinine Where EventDate < '1900-01-01'
Select 'HFit_TrackerDailySteps', ItemID from HFit_TrackerDailySteps Where EventDate < '1900-01-01'

--Select 'HFit_TrackerDef_Item', ItemID from HFit_TrackerDef_Item Where EventDate < '1900-01-01'
--Select 'HFit_TrackerDef_Tracker', ItemID from HFit_TrackerDef_Tracker Where EventDate < '1900-01-01'
--Select 'HFit_TrackerDocument', ItemID from HFit_TrackerDocument Where EventDate < '1900-01-01'

Select 'HFit_TrackerFlexibility', ItemID from HFit_TrackerFlexibility Where EventDate < '1900-01-01'
Select 'HFit_TrackerFruits', ItemID from HFit_TrackerFruits Where EventDate < '1900-01-01'
Select 'HFit_TrackerHbA1c', ItemID from HFit_TrackerHbA1c Where EventDate < '1900-01-01'
Select 'HFit_TrackerHeight', ItemID from HFit_TrackerHeight Where EventDate < '1900-01-01'
Select 'HFit_TrackerHighFatFoods', ItemID from HFit_TrackerHighFatFoods Where EventDate < '1900-01-01'
Select 'HFit_TrackerHighSodiumFoods', ItemID from HFit_TrackerHighSodiumFoods Where EventDate < '1900-01-01'
--Select 'HFit_TrackerInstance_Item', ItemID from HFit_TrackerInstance_Item Where EventDate < '1900-01-01'
Select 'HFit_TrackerInstance_Tracker', ItemID from HFit_TrackerInstance_Tracker Where EventDate < '1900-01-01'
Select 'HFit_TrackerMealPortions', ItemID from HFit_TrackerMealPortions Where EventDate < '1900-01-01'
Select 'HFit_TrackerMedicalCarePlan', ItemID from HFit_TrackerMedicalCarePlan Where EventDate < '1900-01-01'
Select 'HFit_TrackerPreventiveCare', ItemID from HFit_TrackerPreventiveCare Where EventDate < '1900-01-01'
Select 'HFit_TrackerRegularMeals', ItemID from HFit_TrackerRegularMeals Where EventDate < '1900-01-01'
Select 'HFit_TrackerRestingHeartRate', ItemID from HFit_TrackerRestingHeartRate Where EventDate < '1900-01-01'
Select 'HFit_TrackerShots', ItemID from HFit_TrackerShots Where EventDate < '1900-01-01'
Select 'HFit_TrackerSitLess', ItemID from HFit_TrackerSitLess Where EventDate < '1900-01-01'
Select 'HFit_TrackerSleepPlan', ItemID from HFit_TrackerSleepPlan Where EventDate < '1900-01-01'
Select 'HFit_TrackerStrength', ItemID from HFit_TrackerStrength Where EventDate < '1900-01-01'
Select 'HFit_TrackerStress', ItemID from HFit_TrackerStress Where EventDate < '1900-01-01'
Select 'HFit_TrackerStressManagement', ItemID from HFit_TrackerStressManagement Where EventDate < '1900-01-01'
Select 'HFit_TrackerSugaryDrinks', ItemID from HFit_TrackerSugaryDrinks Where EventDate < '1900-01-01'
Select 'HFit_TrackerSugaryFoods', ItemID from HFit_TrackerSugaryFoods Where EventDate < '1900-01-01'
--Select 'HFit_TrackerSummary', ItemID from HFit_TrackerSummary Where EventDate < '1900-01-01'
Select 'HFit_TrackerTests', ItemID from HFit_TrackerTests Where EventDate < '1900-01-01'
Select 'HFit_TrackerTobaccoAttestation', ItemID from HFit_TrackerTobaccoAttestation Where EventDate < '1900-01-01'
Select 'HFit_TrackerTobaccoFree', ItemID from HFit_TrackerTobaccoFree Where EventDate < '1900-01-01'
Select 'HFit_TrackerVegetables', ItemID from HFit_TrackerVegetables Where EventDate < '1900-01-01'
Select 'HFit_TrackerWater', ItemID from HFit_TrackerWater Where EventDate < '1900-01-01'
Select 'HFit_TrackerWeight', ItemID from HFit_TrackerWeight Where EventDate < '1900-01-01'
Select 'HFit_TrackerWholeGrains', ItemID from HFit_TrackerWholeGrains Where EventDate < '1900-01-01'