USE [Viper];
GO

CREATE VIEW dbo.view_ELIGIBILITY_MPI_TEMP_BCP
AS SELECT MEMBER_ID , 
          FIRST_NAME_SOURCE , 
          LAST_NAME_SOURCE , 
          MIDDLE_INITIAL , 
          DOB , 
          GENDER_SOURCE , 
          ADDRESS1_SOURCE , 
          ADDRESS2_SOURCE , 
          CITY_SOURCE , 
          STATE_SOURCE , 
          ZIP_SOURCE , 
          HOME_PHONE_SOURCE , 
          WORK_PHONE_SOURCE , 
          MOBILE_PHONE_SOURCE , 
          EMAIL , 
          SSN_SOURCE , 
          EMPLOYEE_SSN_SOURCE , 
          HIRE_DATE , 
          TERM_DATE , 
          RETIREE_DATE , 
          PLAN_NAME , 
          PLAN_DESC , 
          PLAN_ID , 
          PLAN_START_DATE , 
          PLAN_END_DATE , 
          COMPANY_NAME , 
          COMPANY_CODE , 
          LOCATION_NAME , 
          LOCATION_CODE , 
          DEPARTMENT_NAME , 
          DEPARTMENT_CODE , 
          UNION_CODE , 
          BENEFIT_GROUP , 
          PAYGROUP , 
          DIVISION , 
          JOB_TITLE , 
          JOB_CODE , 
          TEAM_NAME , 
          MARITAL_STATUS , 
          PERSON_TYPE , 
          PERSON_STATUS , 
          EMPLOYEE_TYPE , 
          COVERAGE_TYPE , 
          EMPLOYEE_STATUS , 
          PAY_CODE , 
          BENEFIT_STATUS , 
          PLAN_TYPE , 
          WORK_IND
     FROM ELIGIBILITY_MPI_TEMP;

GO