/*
USE [master]
GO

IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'ECM.Library')
DROP DATABASE [ECM.Library]
GO


USE [master]
GO

CREATE DATABASE [ECM.Library] ON  PRIMARY 
( NAME = N'ECM.Library', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\ECM.Library.mdf' , SIZE = 4126848KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'ECM.Library_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\ECM.Library_log.LDF' , SIZE = 123648KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO
*/

/****************************************************************************************/
/*** If you create the DB using SQL Manager, then start the execution from here down. ***/
/****************************************************************************************/

use [ECM.Library]
go
ALTER DATABASE [ECM.Library] SET COMPATIBILITY_LEVEL = 90
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ECM.Library] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ECM.Library] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ECM.Library] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ECM.Library] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ECM.Library] SET ARITHABORT OFF 
GO

ALTER DATABASE [ECM.Library] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ECM.Library] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ECM.Library] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ECM.Library] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ECM.Library] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ECM.Library] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ECM.Library] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ECM.Library] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ECM.Library] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ECM.Library] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ECM.Library] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ECM.Library] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ECM.Library] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ECM.Library] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ECM.Library] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ECM.Library] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ECM.Library] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ECM.Library] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ECM.Library] SET  READ_WRITE 
GO

ALTER DATABASE [ECM.Library] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ECM.Library] SET  MULTI_USER 
GO

ALTER DATABASE [ECM.Library] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ECM.Library] SET DB_CHAINING OFF 
GO

/************* The Repository has been created and setup ******************/