
-- EXEC dbo.FETCH_ACTIVE_JOB_NAME_By_SPID @SPID = 53
-- EXEC dbo.FETCH_ACTIVE_JOB_NAME_By_SPID @SPID = 69
-- exec SP_WHO2
go

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE  PROCEDURE FETCH_ACTIVE_JOB_NAME_By_SPID
       @SPID INT
AS
--W. Dale Miller
BEGIN
    DECLARE @JOBID_DERIVED VARCHAR (32) ;
    DECLARE @SPID_VAR INT;
    SET NOCOUNT ON;
    SELECT
           @JOBID_DERIVED = SUBSTRING ( CAST (PROGRAM_NAME AS VARCHAR (75)) , 32, 32) 
           FROM MASTER.sys.sysprocesses
           WHERE SPID = @SPID;

    SELECT
           @SPID AS Spid
         , NAME AS SSQL_JOB_Name
           FROM MSDB.DBO.SYSJOBS AS SJ
           WHERE SUBSTRING ( CAST (SJ.JOB_ID AS VARCHAR (36)) , 7, 2) + SUBSTRING ( CAST (SJ.JOB_ID AS VARCHAR (36)) , 7, 2) + SUBSTRING ( CAST (SJ.JOB_ID AS VARCHAR (36)) , 5, 2) + SUBSTRING ( CAST (SJ.JOB_ID AS VARCHAR (36)) , 3, 2) + SUBSTRING ( CAST (SJ.JOB_ID AS VARCHAR (36)) , 1, 2) + SUBSTRING ( CAST (SJ.JOB_ID AS VARCHAR (36)) , 1, 2) + SUBSTRING ( CAST (SJ.JOB_ID AS VARCHAR (36)) , 12, 2) + SUBSTRING ( CAST (SJ.JOB_ID AS VARCHAR (36)) , 10, 2) + SUBSTRING ( CAST (SJ.JOB_ID AS VARCHAR (36)) , 17, 2) + SUBSTRING ( CAST (SJ.JOB_ID AS VARCHAR (36)) , 15, 2) + SUBSTRING ( CAST (SJ.JOB_ID AS VARCHAR (36)) , 20, 4) + SUBSTRING ( CAST (SJ.JOB_ID AS VARCHAR (36)) , 25, 12) = @JOBID_DERIVED;

END;
GO

-- W. Dale Miller
-- DMA, Limited
-- Offered under GNU License
-- July 26, 2016

-- W. Dale Miller
-- DMA, Limited
-- Offered under GNU License
-- July 26, 2016
