use smart
go
SELECT SUM(NET_BILLING_AMT) FROM GLOBAL_BI WHERE Fiscal_Period='06' AND FISCAL_YEAR='2011'
GO
SELECT SUM(NET_BILLING_AMT) FROM GLOBAL_BI_MIRROR WHERE Fiscal_Period='06' AND FISCAL_YEAR='2011'
GO

SELECT FISCAL_YEAR, SUM(NET_BILLING_AMT) FROM GLOBAL_BI WHERE FISCAL_YEAR >= 2008 GROUP BY FISCAL_YEAR
GO
SELECT FISCAL_YEAR, SUM(NET_BILLING_AMT) FROM GLOBAL_BI_MIRROR WHERE FISCAL_YEAR >= 2008 GROUP BY FISCAL_YEAR 
GO

SELECT SRC_SYS_ID, SUM(NET_BILLING_AMT) FROM GLOBAL_BI WHERE FISCAL_YEAR >= 2008 GROUP BY SRC_SYS_ID
GO
SELECT SRC_SYS_ID, SUM(NET_BILLING_AMT) FROM GLOBAL_BI_MIRROR WHERE FISCAL_YEAR >= 2008 GROUP BY SRC_SYS_ID
go