
CREATE NONCLUSTERED INDEX [_dta_index_BAG_BILLINGS_7_1477632357__K67_K12_59_60_69_153] ON [dbo].[MIRROR_BAG_BILLINGS] 
(
	[BusinessYear] ASC,
	[CustomerName] ASC
)
INCLUDE ( [SalesIncentiveRecapClass1],
[SalesIncentiveRecapClass2],
[BusinessPeriod],
[ExtendedUSDPrice]) 
GO

CREATE NONCLUSTERED INDEX [IX_BAG_BILLINGS01] ON [dbo].[MIRROR_BAG_BILLINGS] 
(
	[SRC_SYS_ID] ASC,
	[Entity_ID] ASC,
	[DivisionCode] ASC,
	[TerritoryCode] ASC,
	[CustomerNumber] ASC
)
GO



/****** Object:  Index [FiscYrTKeyFiscPeriodEtcI]    Script Date: 06/16/2011 17:25:59 ******/
CREATE NONCLUSTERED INDEX [FiscYrTKeyFiscPeriodEtcI] ON [dbo].[MIRROR_DM_D_CALENDAR] 
(
	[FISCAL_YEAR] ASC,
	[TIME_KEY] ASC,
	[FISCAL_PERIOD] ASC,
	[FISCAL_PERIOD_NAME] ASC
)
GO



/****** Object:  Index [FscPrdDtTKeyFiscYrI]    Script Date: 06/16/2011 17:25:59 ******/
CREATE NONCLUSTERED INDEX [FscPrdDtTKeyFiscYrI] ON [dbo].[MIRROR_DM_D_CALENDAR] 
(
	[FISCAL_PERIOD] ASC,
	[DATE] ASC,
	[TIME_KEY] ASC,
	[FISCAL_YEAR] ASC
)
GO



/****** Object:  Index [TimeKeyFiscPerStrtDtEtcI]    Script Date: 06/16/2011 17:25:59 ******/
CREATE NONCLUSTERED INDEX [TimeKeyFiscPerStrtDtEtcI] ON [dbo].[MIRROR_DM_D_CALENDAR] 
(
	[TIME_KEY] ASC,
	[FISCAL_PER_START_DT] ASC,
	[FISCAL_YEAR] ASC,
	[FISCAL_PERIOD] ASC,
	[DATE] ASC,
	[DAY_OF_WEEK] ASC,
	[FISCAL_PERIOD_NAME] ASC,
	[FISCAL_QUARTER] ASC
)
GO



/****** Object:  Index [TimeKeyFiscQtrFiscYearI]    Script Date: 06/16/2011 17:25:59 ******/
CREATE NONCLUSTERED INDEX [TimeKeyFiscQtrFiscYearI] ON [dbo].[MIRROR_DM_D_CALENDAR] 
(
	[TIME_KEY] ASC,
	[FISCAL_QUARTER] ASC,
	[FISCAL_YEAR] ASC
)
GO



/****** Object:  Index [TimeKeyFiscYearFiscPeriodDateDOWEtcI]    Script Date: 06/16/2011 17:25:59 ******/
CREATE NONCLUSTERED INDEX [TimeKeyFiscYearFiscPeriodDateDOWEtcI] ON [dbo].[MIRROR_DM_D_CALENDAR] 
(
	[TIME_KEY] ASC,
	[FISCAL_YEAR] ASC,
	[FISCAL_PERIOD] ASC,
	[DATE] ASC,
	[DAY_OF_WEEK] ASC,
	[FISCAL_PERIOD_NAME] ASC,
	[FISCAL_QUARTER] ASC,
	[WEEKEND_FLG] ASC
)
GO



/****** Object:  Index [TKeyDtFiscYearEtcI]    Script Date: 06/16/2011 17:25:59 ******/
CREATE NONCLUSTERED INDEX [TKeyDtFiscYearEtcI] ON [dbo].[MIRROR_DM_D_CALENDAR] 
(
	[TIME_KEY] ASC,
	[DATE] ASC,
	[FISCAL_YEAR] ASC,
	[FISCAL_PERIOD] ASC
)
GO


/****** Object:  Index [AK_DM_D_CUSTOMER]    Script Date: 06/16/2011 17:27:17 ******/
CREATE NONCLUSTERED INDEX [AK_DM_D_CUSTOMER] ON [dbo].[MIRROR_DM_D_CUSTOMER] 
(
	[SRC_SYS_ID] ASC,
	[CUSTOMER_NBR] ASC,
	[CURRENT_IND] ASC
)
GO



/****** Object:  Index [CustKeyBillAddEtcI]    Script Date: 06/16/2011 17:27:17 ******/
CREATE NONCLUSTERED INDEX [CustKeyBillAddEtcI] ON [dbo].[MIRROR_DM_D_CUSTOMER] 
(
	[CUSTOMER_KEY] ASC,
	[BILL_ADDR_LN1] ASC,
	[BILL_ADDR_LN2] ASC,
	[BILL_ADDR_LN3] ASC,
	[BILL_CITY] ASC,
	[BILL_STATE_CD] ASC,
	[BILL_POSTAL_CD] ASC,
	[BILL_COUNTRY_CD] ASC,
	[NAME] ASC,
	[CUSTOMER_NBR] ASC
)
GO



/****** Object:  Index [CustKeyCustNbrI]    Script Date: 06/16/2011 17:27:17 ******/
CREATE NONCLUSTERED INDEX [CustKeyCustNbrI] ON [dbo].[MIRROR_DM_D_CUSTOMER] 
(
	[CUSTOMER_KEY] ASC,
	[CUSTOMER_NBR] ASC
)
INCLUDE ( [EFF_START_DTTM],
[EFF_END_DTTM],
[CURRENT_IND],
[DELETE_IND],
[INFERRED_IND],
[UPDATE_DTTM],
[NAME],
[BILL_ADDR_LN1],
[BILL_ADDR_LN2],
[BILL_ADDR_LN3],
[BILL_CITY],
[BILL_STATE_CD],
[BILL_POSTAL_CD],
[BILL_COUNTRY_CD],
[COMPANY_NBR],
[ROUTE_CD],
[SALES_PERSON],
[DIVISION],
[REGION],
[SALES_CUST_NBR],
[TERRITORY],
[PREFIX_CD],
[FREIGHT_TERM_CD],
[SHIPPING_OFFICER],
[CUST_HOLD_CD],
[HEAD_CORP_PRNT],
[CORP_PRNT],
[CUST_TYPE_KEY],
[CHECKSUM_KEY])
GO



/****** Object:  Index [CustKeyNameCustNbrI]    Script Date: 06/16/2011 17:27:17 ******/
CREATE NONCLUSTERED INDEX [CustKeyNameCustNbrI] ON [dbo].[MIRROR_DM_D_CUSTOMER] 
(
	[CUSTOMER_KEY] ASC,
	[NAME] ASC,
	[CUSTOMER_NBR] ASC
)--WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



/****** Object:  Index [CustKeySrcSysCustNbrI]    Script Date: 06/16/2011 17:27:17 ******/
CREATE NONCLUSTERED INDEX [CustKeySrcSysCustNbrI] ON [dbo].[MIRROR_DM_D_CUSTOMER] 
(
	[CUSTOMER_KEY] ASC,
	[SRC_SYS_ID] ASC,
	[CUSTOMER_NBR] ASC
)--WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



/****** Object:  Index [CustTypSrcCustNbrI]    Script Date: 06/16/2011 17:27:17 ******/
CREATE NONCLUSTERED INDEX [CustTypSrcCustNbrI] ON [dbo].[MIRROR_DM_D_CUSTOMER] 
(
	[CUST_TYPE_KEY] ASC,
	[SRC_SYS_ID] ASC,
	[CUSTOMER_NBR] ASC,
	[CUSTOMER_KEY] ASC
)--WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



/****** Object:  Index [DM_D_CUSTOMER_CustKeyCustNbrI]    Script Date: 06/16/2011 17:27:17 ******/
CREATE NONCLUSTERED INDEX [DM_D_CUSTOMER_CustKeyCustNbrI] ON [dbo].[MIRROR_DM_D_CUSTOMER] 
(
	[CUSTOMER_KEY] ASC,
	[CUSTOMER_NBR] ASC
)--WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



/****** Object:  Index [NmCustKeyCustNbr]    Script Date: 06/16/2011 17:27:17 ******/
CREATE NONCLUSTERED INDEX [NmCustKeyCustNbr] ON [dbo].[MIRROR_DM_D_CUSTOMER] 
(
	[NAME] ASC,
	[CUSTOMER_KEY] ASC,
	[CUSTOMER_NBR] ASC,
	[SRC_SYS_ID] ASC,
	[CUST_TYPE_KEY] ASC
)--WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MIRROR_DM_D_CUSTOMER]  WITH CHECK ADD  CONSTRAINT [R_69] FOREIGN KEY([CUST_TYPE_KEY])
REFERENCES [dbo].[DM_D_CUSTOMER_TYPE] ([CUST_TYPE_KEY])
GO

ALTER TABLE [dbo].[MIRROR_DM_D_CUSTOMER] CHECK CONSTRAINT [R_69]
GO

GO
CREATE CLUSTERED INDEX [PI01_Cust_Type_key] ON [dbo].[MIRROR_DM_D_CUSTOMER_TYPE] 
(
	[CUST_TYPE_KEY] ASC
)WITH (STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [PI_Covering01] ON [dbo].[MIRROR_DM_D_ITEM] 
(
	[CURRENT_IND] ASC,
	[DELETE_IND] ASC,
	[SRC_SYS_ID] ASC,
	[ITEM_NBR] ASC,
	[ITEM_CLASS_KEY] ASC,
	[ITEM_KEY] ASC
)
INCLUDE ( [RUN_ID],
[EFF_END_DTTM],
[EFF_START_DTTM],
[INFERRED_IND],
[UPDATE_DTTM],
[RECORD_ID],
[TARIFF_KEY],
[HARMONIZATION_KEY],
[DFLT_LOC_KEY],
[DESCR_LN1],
[DESCR_LN2],
[STOCK_UM],
[PURCH_UM],
[STOCK_UM_CONV],
[ITEM_TYPE],
[DISCNT_CD],
[ABC_INVENTORY_CD],
[NPD_DT],
[PLANNER_CD],
[SELL_UM],
[SELL_UM_CONV],
[LOT_CTRL_PROD],
[JIT_CD],
[ITEM_GRP1],
[COUNTRY_CD],
[LENGTH],
[LENGTH_UM],
[WIDTH],
[WIDTH_UM],
[HEIGHT],
[HEIGHT_UM],
[ANNEX_NBR],
[COPPER_WEIGHT],
[CMS_ABBR],
[CHECKSUM_KEY],
[COLOR_CD],
[PUTUP],
[PUTUP_UM],
[PACKAGE],
[PRODUCT_CD],
[PRIM_FAC_KEY],
[CELL_NBR],
[FINISH_FLG],
[PRODUCT],
[PERFORMANCE],
[MATERIAL],
[PRIMARY_MKT],
[ENVIROMENT],
[BRAND],
[SPC_STD_FLG],
[NORM_FACTOR]) 
GO



/****** Object:  Index [CurIndSrcSysItemNbrItemKeyFinFlgI]    Script Date: 06/16/2011 17:30:15 ******/
CREATE NONCLUSTERED INDEX [CurIndSrcSysItemNbrItemKeyFinFlgI] ON [dbo].[MIRROR_DM_D_ITEM] 
(
	[CURRENT_IND] ASC,
	[SRC_SYS_ID] ASC,
	[ITEM_NBR] ASC,
	[ITEM_KEY] ASC,
	[FINISH_FLG] ASC
)

GO



/****** Object:  Index [FinFlgSrcSysItmNbrItmKyI]    Script Date: 06/16/2011 17:30:15 ******/
CREATE NONCLUSTERED INDEX [FinFlgSrcSysItmNbrItmKyI] ON [dbo].[MIRROR_DM_D_ITEM] 
(
	[FINISH_FLG] ASC,
	[SRC_SYS_ID] ASC,
	[ITEM_NBR] ASC,
	[ITEM_KEY] ASC

GO



/****** Object:  Index [ItemKeyDescLnEtcI]    Script Date: 06/16/2011 17:30:15 ******/
CREATE NONCLUSTERED INDEX [ItemKeyDescLnEtcI] ON [dbo].[MIRROR_DM_D_ITEM] 
(
	[ITEM_KEY] ASC,
	[DESCR_LN1] ASC,
	[DESCR_LN2] ASC,
	[NPD_DT] ASC,
	[ITEM_NBR] ASC,
	[CURRENT_IND] ASC,
	[SRC_SYS_ID] ASC
)
INCLUDE ( [PRODUCT],
[PERFORMANCE],
[MATERIAL],
[PRIMARY_MKT],
[ENVIROMENT],
[BRAND],
[SPC_STD_FLG],
[NORM_FACTOR]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



/****** Object:  Index [ItemKeyItemNbrI]    Script Date: 06/16/2011 17:30:15 ******/
CREATE NONCLUSTERED INDEX [ItemKeyItemNbrI] ON [dbo].[MIRROR_DM_D_ITEM] 
(
	[ITEM_KEY] ASC,
	[ITEM_NBR] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



/****** Object:  Index [ItemKeyItemTypSrcSysItemNbrCurIndI]    Script Date: 06/16/2011 17:30:15 ******/
CREATE NONCLUSTERED INDEX [ItemKeyItemTypSrcSysItemNbrCurIndI] ON [dbo].[MIRROR_DM_D_ITEM] 
(
	[ITEM_KEY] ASC,
	[ITEM_TYPE] ASC,
	[SRC_SYS_ID] ASC,
	[ITEM_NBR] ASC,
	[CURRENT_IND] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



/****** Object:  Index [ItmKeyFinFlgSrcSysIdItmNbrItmClsKeyI]    Script Date: 06/16/2011 17:30:15 ******/
CREATE NONCLUSTERED INDEX [ItmKeyFinFlgSrcSysIdItmNbrItmClsKeyI] ON [dbo].[MIRROR_DM_D_ITEM] 
(
	[ITEM_KEY] ASC,
	[FINISH_FLG] ASC,
	[SRC_SYS_ID] ASC,
	[ITEM_NBR] ASC,
	[ITEM_CLASS_KEY] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



/****** Object:  Index [ItmNbrSrcSysIdItmKeyI]    Script Date: 06/16/2011 17:30:15 ******/
CREATE NONCLUSTERED INDEX [ItmNbrSrcSysIdItmKeyI] ON [dbo].[MIRROR_DM_D_ITEM] 
(
	[ITEM_NBR] ASC,
	[SRC_SYS_ID] ASC,
	[ITEM_KEY] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



/****** Object:  Index [ItmTypeI]    Script Date: 06/16/2011 17:30:15 ******/
CREATE NONCLUSTERED INDEX [ItmTypeI] ON [dbo].[MIRROR_DM_D_ITEM] 
(
	[ITEM_TYPE] ASC
)
INCLUDE ( [ITEM_KEY]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



/****** Object:  Index [SrcCurIndItemEtcI]    Script Date: 06/16/2011 17:30:15 ******/
CREATE NONCLUSTERED INDEX [SrcCurIndItemEtcI] ON [dbo].[MIRROR_DM_D_ITEM] 
(
	[SRC_SYS_ID] ASC,
	[CURRENT_IND] ASC,
	[ITEM_NBR] ASC,
	[ITEM_KEY] ASC,
	[DESCR_LN1] ASC,
	[DESCR_LN2] ASC,
	[NPD_DT] ASC
)
INCLUDE ( [FINISH_FLG],
[PRODUCT],
[PERFORMANCE],
[MATERIAL],
[PRIMARY_MKT],
[ENVIROMENT],
[BRAND],
[SPC_STD_FLG],
[NORM_FACTOR]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



/****** Object:  Index [SrcSysCurIndItmNbrItmKyItmTypI]    Script Date: 06/16/2011 17:30:15 ******/
CREATE NONCLUSTERED INDEX [SrcSysCurIndItmNbrItmKyItmTypI] ON [dbo].[MIRROR_DM_D_ITEM] 
(
	[SRC_SYS_ID] ASC,
	[CURRENT_IND] ASC,
	[ITEM_NBR] ASC,
	[ITEM_KEY] ASC,
	[ITEM_TYPE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



/****** Object:  Index [SrcSysIdItemKeyEtcI]    Script Date: 06/16/2011 17:30:15 ******/
CREATE NONCLUSTERED INDEX [SrcSysIdItemKeyEtcI] ON [dbo].[MIRROR_DM_D_ITEM] 
(
	[SRC_SYS_ID] ASC,
	[ITEM_KEY] ASC,
	[ITEM_NBR] ASC,
	[ITEM_CLASS_KEY] ASC
)
INCLUDE ( [RECORD_ID],
[DESCR_LN1],
[DESCR_LN2],
[STOCK_UM],
[PURCH_UM],
[ITEM_TYPE],
[DISCNT_CD],
[SELL_UM],
[COPPER_WEIGHT],
[CMS_ABBR],
[PRODUCT_CD],
[CELL_NBR],
[FINISH_FLG],
[PRODUCT],
[PERFORMANCE],
[MATERIAL],
[PRIMARY_MKT],
[ENVIROMENT],
[BRAND],
[SPC_STD_FLG],
[NORM_FACTOR]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



/****** Object:  Index [SrcsysidItemNbrCurrentIndDeleteInd]    Script Date: 06/16/2011 17:30:15 ******/
CREATE NONCLUSTERED INDEX [SrcsysidItemNbrCurrentIndDeleteInd] ON [dbo].[MIRROR_DM_D_ITEM] 
(
	[SRC_SYS_ID] ASC,
	[ITEM_NBR] ASC,
	[CURRENT_IND] ASC,
	[DELETE_IND] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



/****** Object:  Index [SrcSysIdItmNbrFinFlgItmClsKeyItmKeyI]    Script Date: 06/16/2011 17:30:15 ******/
CREATE NONCLUSTERED INDEX [SrcSysIdItmNbrFinFlgItmClsKeyItmKeyI] ON [dbo].[MIRROR_DM_D_ITEM] 
(
	[SRC_SYS_ID] ASC,
	[ITEM_NBR] ASC,
	[FINISH_FLG] ASC,
	[ITEM_CLASS_KEY] ASC,
	[ITEM_KEY] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



/****** Object:  Index [SrcSysIdItmTypItmNbrItmKyItmClsKyI]    Script Date: 06/16/2011 17:30:15 ******/
CREATE NONCLUSTERED INDEX [SrcSysIdItmTypItmNbrItmKyItmClsKyI] ON [dbo].[MIRROR_DM_D_ITEM] 
(
	[SRC_SYS_ID] ASC,
	[ITEM_TYPE] ASC,
	[ITEM_NBR] ASC,
	[ITEM_KEY] ASC,
	[ITEM_CLASS_KEY] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


/****** Object:  Index [AK_DM_D_ITEM_CLASS]    Script Date: 06/16/2011 17:32:43 ******/
CREATE NONCLUSTERED INDEX [AK_DM_D_ITEM_CLASS] ON [dbo].[MIRROR_DM_D_ITEM_CLASS] 
(
	[SRC_SYS_ID] ASC,
	[ITEM_CLASS] ASC,
	[CURRENT_IND] ASC
)
GO


CREATE NONCLUSTERED INDEX [IX_01] ON [dbo].[MIRROR_DM_D_ITEM_CLASS] 
(
	[ITEM_CLASS] ASC
)
INCLUDE ( [SRC_SYS_ID],
[CURRENT_IND],
[DELETE_IND],
[STD_OR_SPC_FLG])
GO


/****** Object:  Index [_dta_index_DM_F_INVOICE_LN_c_11_421576540__K1]    Script Date: 06/16/2011 17:33:58 ******/
CREATE CLUSTERED INDEX [_dta_index_DM_F_INVOICE_LN_c_11_421576540__K1] ON [dbo].[MIRROR_DM_F_INVOICE_LN] 
(
	[INVOICE_LN_KEY] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



/****** Object:  Index [_dta_index_DM_F_INVOICE_LN_11_421576540__K3_K6_K11_K12_K13]    Script Date: 06/16/2011 17:33:58 ******/
CREATE NONCLUSTERED INDEX [_dta_index_DM_F_INVOICE_LN_11_421576540__K3_K6_K11_K12_K13] ON [dbo].[MIRROR_DM_F_INVOICE_LN] 
(
	[SRC_SYS_ID] ASC,
	[TIME_KEY] ASC,
	[INVOICE_NBR] ASC,
	[INVOICE_LN_NBR] ASC,
	[INVOICE_DT] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



/****** Object:  Index [_dta_index_DM_F_INVOICE_LN_11_421576540__K6_K3_K5_1_2_4_7_8_9_10_11_12_13_14_15_16_17_18_19_20_21_22_23_24_25_26_27_28_29_30_]    Script Date: 06/16/2011 17:33:58 ******/
CREATE NONCLUSTERED INDEX [_dta_index_DM_F_INVOICE_LN_11_421576540__K6_K3_K5_1_2_4_7_8_9_10_11_12_13_14_15_16_17_18_19_20_21_22_23_24_25_26_27_28_29_30_] ON [dbo].[MIRROR_DM_F_INVOICE_LN] 
(
	[TIME_KEY] ASC,
	[SRC_SYS_ID] ASC,
	[ITEM_KEY] ASC
)
INCLUDE ( [INVOICE_LN_KEY],
[RUN_ID],
[UPDATE_DTTM],
[CUSTOMER_KEY],
[ORGANIZATION_KEY],
[BILL_CUST_NBR],
[SHIP_WHSE_KEY],
[INVOICE_NBR],
[INVOICE_LN_NBR],
[INVOICE_DT],
[QUANTITY],
[NET_PRICE],
[INVENTORY_REASON_CD],
[ORDER_NBR],
[ORDER_LN_NBR],
[CUSTOMER_PO],
[USER_DEFINED_DT1],
[USER_DEFINED_DT2],
[UNIT_OF_MEASURE],
[DOC_PREFIX],
[CUST_ITEM_NBR],
[BILLING_NET_PRICE],
[ORDER_CLASS],
[INVOICE_LN_QTY],
[ORIG_SELL_UM],
[NET_PRICE_SRC_CD],
[LIST_PRICE_SRC_CD],
[SHIPPED_DT],
[SHIP_DUE_DT],
[INVLN_SALE_AMT],
[CUST_SALE_AMT],
[INTER_SALE_AMT],
[INTRA_SALE_AMT],
[FREIGHT_AMT],
[SERV_CHRG_AMT],
[SND_ADJUST_AMT],
[OTH_ADJUST_AMT],
[REBATE_AMT],
[CREDIT_RMA_AMT],
[ALLOWANCE_AMT],
[LOC_FSTD_CST_AMT],
[LOC_MAT_CST_AMT],
[LOC_SCRAP_CST_AMT],
[LOC_LABOR_CST_AMT],
[LOC_OHEAD_CST_AMT],
[LOC_RMCC_AMT],
[GBL_FSTD_CST_AMT],
[GBL_RMCC_AMT],
[CU_SURCHARGE],
[LOC_CURRENCY],
[TO_LOC_CURR_RATE],
[VALID_COST_FLG],
[EXTD_QTY_FT],
[CU_TOTAL_WEIGHT],
[EXTD_QTY_MT],
[QTY_PIECE],
[CU_STD_PRICE],
[CU_AVG_PRICE],
[VITALITY_FACTOR],
[TRX_TYPE]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



/****** Object:  Index [SrcSysIdItmKeyCustKeyTimKeyI]    Script Date: 06/16/2011 17:33:58 ******/
CREATE NONCLUSTERED INDEX [SrcSysIdItmKeyCustKeyTimKeyI] ON [dbo].[MIRROR_DM_F_INVOICE_LN] 
(
	[SRC_SYS_ID] ASC,
	[ITEM_KEY] ASC,
	[CUSTOMER_KEY] ASC,
	[TIME_KEY] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



/****** Object:  Index [SrcTrxCustItemEtcI]    Script Date: 06/16/2011 17:33:58 ******/
CREATE NONCLUSTERED INDEX [SrcTrxCustItemEtcI] ON [dbo].[MIRROR_DM_F_INVOICE_LN] 
(
	[SRC_SYS_ID] ASC,
	[TRX_TYPE] ASC,
	[CUSTOMER_KEY] ASC,
	[ITEM_KEY] ASC,
	[TIME_KEY] ASC
)
INCLUDE ( [CUST_SALE_AMT],
[INTER_SALE_AMT],
[INTRA_SALE_AMT],
[FREIGHT_AMT],
[SERV_CHRG_AMT]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



/****** Object:  Index [SrcTrxOrderEtcI]    Script Date: 06/16/2011 17:33:58 ******/
CREATE NONCLUSTERED INDEX [SrcTrxOrderEtcI] ON [dbo].[MIRROR_DM_F_INVOICE_LN] 
(
	[SRC_SYS_ID] ASC,
	[TRX_TYPE] ASC,
	[ORDER_NBR] ASC,
	[ORDER_LN_NBR] ASC,
	[INVOICE_NBR] ASC,
	[TIME_KEY] ASC,
	[CUSTOMER_KEY] ASC,
	[ITEM_KEY] ASC
)
INCLUDE ( [CUST_SALE_AMT],
[INTER_SALE_AMT],
[INTRA_SALE_AMT],
[FREIGHT_AMT],
[SERV_CHRG_AMT],
[LOC_RMCC_AMT]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



/****** Object:  Index [TimeKyCstKyInvNbrSrcSysItmKyI]    Script Date: 06/16/2011 17:33:58 ******/
CREATE NONCLUSTERED INDEX [TimeKyCstKyInvNbrSrcSysItmKyI] ON [dbo].[MIRROR_DM_F_INVOICE_LN] 
(
	[TIME_KEY] ASC,
	[CUSTOMER_KEY] ASC,
	[INVOICE_NBR] ASC,
	[SRC_SYS_ID] ASC,
	[ITEM_KEY] ASC
)
INCLUDE ( [CUST_SALE_AMT]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



/****** Object:  Index [TKeySrcOrdNbrI]    Script Date: 06/16/2011 17:33:58 ******/
CREATE NONCLUSTERED INDEX [TKeySrcOrdNbrI] ON [dbo].[MIRROR_DM_F_INVOICE_LN] 
(
	[TIME_KEY] ASC,
	[SRC_SYS_ID] ASC,
	[ORDER_NBR] ASC,
	[ORDER_LN_NBR] ASC,
	[INVOICE_NBR] ASC,
	[CUSTOMER_KEY] ASC,
	[ITEM_KEY] ASC,
	[SHIPPED_DT] ASC,
	[CU_STD_PRICE] ASC,
	[INVOICE_LN_NBR] ASC,
	[EXTD_QTY_MT] ASC,
	[TRX_TYPE] ASC,
	[UNIT_OF_MEASURE] ASC
)
INCLUDE ( [QUANTITY],
[CUST_SALE_AMT],
[INTER_SALE_AMT],
[INTRA_SALE_AMT],
[FREIGHT_AMT],
[SERV_CHRG_AMT],
[SND_ADJUST_AMT],
[OTH_ADJUST_AMT],
[REBATE_AMT],
[CREDIT_RMA_AMT],
[ALLOWANCE_AMT],
[LOC_FSTD_CST_AMT],
[LOC_MAT_CST_AMT],
[LOC_SCRAP_CST_AMT],
[LOC_LABOR_CST_AMT],
[LOC_OHEAD_CST_AMT],
[LOC_RMCC_AMT],
[CU_SURCHARGE],
[EXTD_QTY_FT],
[CU_TOTAL_WEIGHT],
[CU_AVG_PRICE]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



/****** Object:  Index [TKeyTrxSrcInvNbrEtcI]    Script Date: 06/16/2011 17:33:58 ******/
CREATE NONCLUSTERED INDEX [TKeyTrxSrcInvNbrEtcI] ON [dbo].[MIRROR_DM_F_INVOICE_LN] 
(
	[TIME_KEY] ASC,
	[TRX_TYPE] ASC,
	[SRC_SYS_ID] ASC,
	[INVOICE_NBR] ASC,
	[ITEM_KEY] ASC,
	[CUSTOMER_KEY] ASC
)
INCLUDE ( [CUST_SALE_AMT],
[INTER_SALE_AMT],
[INTRA_SALE_AMT],
[EXTD_QTY_FT]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



/****** Object:  Index [TKeyTrxTypeEtcI]    Script Date: 06/16/2011 17:33:58 ******/
CREATE NONCLUSTERED INDEX [TKeyTrxTypeEtcI] ON [dbo].[MIRROR_DM_F_INVOICE_LN] 
(
	[TIME_KEY] ASC,
	[TRX_TYPE] ASC,
	[SRC_SYS_ID] ASC,
	[CUSTOMER_KEY] ASC,
	[ITEM_KEY] ASC,
	[INVOICE_LN_NBR] ASC,
	[INVOICE_NBR] ASC
)
INCLUDE ( [CUST_SALE_AMT],
[INTER_SALE_AMT],
[INTRA_SALE_AMT],
[FREIGHT_AMT],
[SERV_CHRG_AMT],
[SND_ADJUST_AMT],
[OTH_ADJUST_AMT],
[CREDIT_RMA_AMT],
[ALLOWANCE_AMT]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


/****** Object:  Index [CI01_SalesSummary]    Script Date: 06/16/2011 17:35:03 ******/
CREATE NONCLUSTERED INDEX [CI01_SalesSummary] ON [dbo].[MIRROR_DM_F_SALES_SUMMARY] 
(
	[RECORD_KEY] ASC
)
INCLUDE ( [UPDATE_DTTM]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



/****** Object:  Index [SrcCustAmtEtcI]    Script Date: 06/16/2011 17:35:03 ******/
CREATE NONCLUSTERED INDEX [SrcCustAmtEtcI] ON [dbo].[MIRROR_DM_F_SALES_SUMMARY] 
(
	[SRC_SYS_ID] ASC,
	[CUST_SALE_AMT] ASC,
	[TIME_KEY] ASC,
	[CUSTOMER_KEY] ASC,
	[ITEM_KEY] ASC
)
INCLUDE ( [INTER_SALE_AMT],
[INTRA_SALE_AMT],
[SND_ADJUST_AMT],
[OTH_ADJUST_AMT],
[CREDIT_RMA_AMT],
[TO_EUR_RATE]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



/****** Object:  Index [SrcItKeyTimeKeyCustKeyI]    Script Date: 06/16/2011 17:35:03 ******/
CREATE NONCLUSTERED INDEX [SrcItKeyTimeKeyCustKeyI] ON [dbo].[MIRROR_DM_F_SALES_SUMMARY] 
(
	[SRC_SYS_ID] ASC,
	[ITEM_KEY] ASC,
	[TIME_KEY] ASC,
	[CUSTOMER_KEY] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



/****** Object:  Index [SrcTKeyItKeyInvEtcI]    Script Date: 06/16/2011 17:35:03 ******/
CREATE NONCLUSTERED INDEX [SrcTKeyItKeyInvEtcI] ON [dbo].[MIRROR_DM_F_SALES_SUMMARY] 
(
	[SRC_SYS_ID] ASC,
	[TIME_KEY] ASC,
	[ITEM_KEY] ASC,
	[INVOICE_NBR] ASC,
	[CUSTOMER_KEY] ASC
)
INCLUDE ( [CUST_SALE_AMT],
[INTER_SALE_AMT],
[INTRA_SALE_AMT],
[FREIGHT_AMT],
[SND_ADJUST_AMT],
[OTH_ADJUST_AMT],
[CREDIT_RMA_AMT],
[LOC_RMCC_AMT],
[TO_EUR_RATE],
[TRX_TYPE]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



/****** Object:  Index [TimeKeySrcCustKeyItemKey]    Script Date: 06/16/2011 17:35:03 ******/
CREATE NONCLUSTERED INDEX [TimeKeySrcCustKeyItemKey] ON [dbo].[MIRROR_DM_F_SALES_SUMMARY] 
(
	[TIME_KEY] ASC,
	[SRC_SYS_ID] ASC,
	[CUSTOMER_KEY] ASC,
	[ITEM_KEY] ASC
)
INCLUDE ( [CUST_SALE_AMT],
[INTER_SALE_AMT],
[INTRA_SALE_AMT],
[SND_ADJUST_AMT],
[OTH_ADJUST_AMT],
[CREDIT_RMA_AMT],
[ALLOWANCE_AMT],
[LOC_FSTD_CST_AMT]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


/****** Object:  Index [_dta_index_DM_H_ITEM_11_165575628__K6_K3_K31_K9_1_2_4_5_7_8_10_11_12_13_14_15_16_17_18_19_20_21_22_23_24_25_26_27_28_29_30]    Script Date: 06/16/2011 17:36:20 ******/
CREATE NONCLUSTERED INDEX [_dta_index_DM_H_ITEM_11_165575628__K6_K3_K31_K9_1_2_4_5_7_8_10_11_12_13_14_15_16_17_18_19_20_21_22_23_24_25_26_27_28_29_30] ON [dbo].[Mirror_DM_H_ITEM] 
(
	[CURRENT_IND] ASC,
	[SRC_SYS_ID] ASC,
	[HIERARCHY_ID] ASC,
	[ITEM_NBR] ASC
)
INCLUDE ( [ITEM_HIERARCHY_KEY],
[RUN_ID],
[EFF_START_DTTM],
[EFF_END_DTTM],
[DELETE_IND],
[UPDATE_DTTM],
[LEVEL01_CD],
[LEVEL01_NAME],
[LEVEL02_CD],
[LEVEL02_NAME],
[LEVEL03_CD],
[LEVEL03_NAME],
[LEVEL04_CD],
[LEVEL04_NAME],
[LEVEL05_CD],
[LEVEL05_NAME],
[LEVEL06_CD],
[LEVEL06_NAME],
[LEVEL07_CD],
[LEVEL07_NAME],
[LEVEL08_CD],
[LEVEL08_NAME],
[LEVEL09_CD],
[LEVEL09_NAME],
[LEVEL10_CD],
[LEVEL10_NAME],
[CHECKSUM_KEY]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



/****** Object:  Index [AK_DM_H_ITEM]    Script Date: 06/16/2011 17:36:20 ******/
CREATE NONCLUSTERED INDEX [AK_DM_H_ITEM] ON [dbo].[Mirror_DM_H_ITEM] 
(
	[SRC_SYS_ID] ASC,
	[CURRENT_IND] ASC,
	[ITEM_NBR] ASC,
	[HIERARCHY_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



/****** Object:  Index [CurIndHierDelIndSrcSysItmNbrI]    Script Date: 06/16/2011 17:36:20 ******/
CREATE NONCLUSTERED INDEX [CurIndHierDelIndSrcSysItmNbrI] ON [dbo].[Mirror_DM_H_ITEM] 
(
	[CURRENT_IND] ASC,
	[HIERARCHY_ID] ASC,
	[DELETE_IND] ASC,
	[SRC_SYS_ID] ASC,
	[ITEM_NBR] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



/****** Object:  Index [HierCurIndDelIndItmNbISrcSysI]    Script Date: 06/16/2011 17:36:20 ******/
CREATE NONCLUSTERED INDEX [HierCurIndDelIndItmNbISrcSysI] ON [dbo].[Mirror_DM_H_ITEM] 
(
	[HIERARCHY_ID] ASC,
	[CURRENT_IND] ASC,
	[DELETE_IND] ASC,
	[ITEM_NBR] ASC,
	[SRC_SYS_ID] ASC
)
INCLUDE ( [LEVEL01_NAME],
[LEVEL02_CD]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



/****** Object:  Index [SrcHierCurIndDelEtcI]    Script Date: 06/16/2011 17:36:20 ******/
CREATE NONCLUSTERED INDEX [SrcHierCurIndDelEtcI] ON [dbo].[Mirror_DM_H_ITEM] 
(
	[SRC_SYS_ID] ASC,
	[HIERARCHY_ID] ASC,
	[CURRENT_IND] ASC,
	[DELETE_IND] ASC,
	[ITEM_NBR] ASC,
	[LEVEL01_NAME] ASC,
	[LEVEL02_CD] ASC
)
INCLUDE ( [ITEM_HIERARCHY_KEY]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO



