USE [SMART]
GO

/****** Object:  View [dbo].[GLOBAL_POS_Extract2]    Script Date: 10/30/2010 09:09:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER OFF
GO



ALTER view [dbo].[GLOBAL_POS_Extract2] AS
SELECT

 	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2' AND P.MANUFACTURER_NAME LIKE 'HIR%') THEN 'STDMHM'
			 WHEN (P.SRC_SYS_ID IN ('BPCSCE', 'BPCSCN')) THEN 'BPCSCO'
	ELSE P.SRC_SYS_ID END	AS SRC_SYS_ID,

	CASE WHEN (P.SRC_SYS_ID='BPCSEU') THEN 'EMEA'
		 WHEN (P.SRC_SYS_ID IN ('BPCSRI','BPCSCE', 'BPCSCN', 'BPCSCO','BPCSMH','BPCSAL','STDMWP','THERMX')) THEN 'BAG'
		 WHEN (P.SRC_SYS_ID='ASIASR') THEN 'APAC'
	ELSE
	 	 'UNKNOWN'
	END	AS DIVISION_GRP,

	CASE WHEN (P.SRC_SYS_ID='BPCSEU') THEN 'Cable'
		 WHEN (P.SRC_SYS_ID='BPCSRI') THEN 'Americas'
		 WHEN (P.SRC_SYS_ID IN ('BPCSCO', 'BPCSCE', 'BPCSCN')) THEN 'Americas'
		 WHEN (P.SRC_SYS_ID='BPCSMH') THEN 'Mohawk'
		 WHEN (P.SRC_SYS_ID='BPCSAL') THEN 'AMD'
		 WHEN (P.SRC_SYS_ID='STDMWP') THEN 'WPW'
		 WHEN (P.SRC_SYS_ID='THERMX') THEN 'Thermax'
		 WHEN (P.SRC_SYS_ID='ASIASR') THEN 'BAP'
	ELSE
	 	 'UNKNOWN'
	END	AS BUSINESSUNIT_GRP,
				 		
		P.SRC_SYS_ID_POS,
		-- P.POS_SALE_KEY,

	CASE WHEN (P.SRC_SYS_ID_POS = 'ALAXT' AND P.TIME_KEY < 20090101) THEN 'N'
		 WHEN (P.SRC_SYS_ID_POS = 'AL_BUD') THEN 'Y'
		 WHEN (P.SRC_SYS_ID_POS = 'AS_AXT' AND P.TIME_KEY < 20090101)  THEN 'Y'
		 WHEN (P.SRC_SYS_ID_POS = 'BLD_AC') THEN 'N'
	 	 WHEN (P.SRC_SYS_ID_POS = 'BLDAC2') THEN 'N'
		 WHEN (P.SRC_SYS_ID_POS = 'HIRAXT' AND P.TIME_KEY < 20090101)  THEN 'Y'
		 WHEN (P.SRC_SYS_ID_POS = 'MHCSC') THEN 'Y'
		 WHEN (P.SRC_SYS_ID_POS = 'MHCSC2') THEN 'Y'
		 WHEN (P.SRC_SYS_ID_POS = 'MH_GB') THEN 'Y'
		 WHEN (P.SRC_SYS_ID_POS = 'MOHAXT') AND P.TIME_KEY < 20090101 THEN 'Y'
	 	 WHEN (P.SRC_SYS_ID_POS = 'RIAXT') THEN 'N'
	 	 WHEN (P.SRC_SYS_ID_POS = 'RICSE2') THEN 'N'
	 	 WHEN (P.SRC_SYS_ID_POS = 'RICSN2') THEN 'N'
	 	 WHEN (P.SRC_SYS_ID_POS = 'RI_BUD') THEN 'Y'
	 	 WHEN (P.SRC_SYS_ID_POS = 'RI_CSC') THEN 'N'
	 	 WHEN (P.SRC_SYS_ID_POS = 'RI_GB') THEN 'N'
	 	 WHEN (P.SRC_SYS_ID_POS = 'RI_GB2') THEN 'N'
	 	 WHEN (P.SRC_SYS_ID_POS = 'THXAXT' AND P.TIME_KEY < 20090101) THEN 'Y'
	 	 WHEN (P.SRC_SYS_ID_POS = 'WP_AC') THEN 'Y'
	ELSE
		'N'
	END	AS BMS_PRIMARY_FLG,

	CASE WHEN (P.SRC_SYS_ID_POS = 'AL_BUD') THEN 'Y' 
	 	 WHEN (P.SRC_SYS_ID_POS = 'RI_BUD') THEN 'Y'
	ELSE
		'N'
	END	AS BMS_ONLY_FLG,		

	CASE WHEN ((P.SRC_SYS_ID_POS = 'AL_BUD' OR P.SRC_SYS_ID_POS = 'RI_BUD')AND 
			   (D.GLOBAL_ACCOUNT_NAME='ANIXTER_GLOBAL' OR D.GLOBAL_ACCOUNT_NAME='CSC_GLOBAL' OR 
				D.GLOBAL_ACCOUNT_NAME='GRAYBAR_GLOBAL')) THEN 'N'
		 WHEN (P.SRC_SYS_ID_POS = 'ALAXT'  AND P.TIME_KEY > 20090101) THEN 'N'
		 WHEN (P.SRC_SYS_ID_POS = 'AS_AXT' AND P.TIME_KEY > 20090101) THEN 'N'
		 WHEN (P.SRC_SYS_ID_POS = 'HIRAXT' AND P.TIME_KEY > 20090101) THEN 'N'
		 WHEN (P.SRC_SYS_ID_POS = 'MOHAXT' AND P.TIME_KEY > 20090101) THEN 'N'
		 WHEN (P.SRC_SYS_ID_POS = 'RIAXT' AND P.TIME_KEY > 20090101) THEN 'N'
	 	 WHEN (P.SRC_SYS_ID_POS = 'THXAXT' AND P.TIME_KEY > 20090101) THEN 'N'
	ELSE
		'Y'
	END	AS DISTRIBUTOR_PRIMARY_FLG,

	CASE WHEN (P.SRC_SYS_ID_POS = 'AL_BUD') THEN 'N' 
	 	 WHEN (P.SRC_SYS_ID_POS = 'RI_BUD') THEN 'N'
	ELSE
		'Y'
	END	AS DISTRIBUTOR_ONLY_FLG,		

		P.DISTRIBUTOR_NAME,
		P.MANUFACTURER_NAME,
		CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN ANXTPR.REPORT_ENDING_DATE ELSE P.REPORT_ENDING_DATE END REPORT_ENDING_DATE,
		P.BRANCH_ID,
		P.SHIP_TO_CUSTOMER_KEY,

		P.SHIP_TO_CUSTOMER_ID,
		P.SHIP_TO_CUSTOMER_NAME,
		P.SHIP_TO_CUSTOMER_CITY,
		/*P.SHIP_TO_CUSTOMER_STATE, */
		ISNULL(PC.STATE,P.SHIP_TO_CUSTOMER_STATE)  AS SHIP_TO_CUSTOMER_STATE,
		P.SHIP_TO_CUSTOMER_POSTAL_CODE,

		P.MANUFACTURER_PART_NUMBER ITEM_NBR,
		P.DISTRIBUTOR_PART_NUMBER  ITEM_DISTRIBUTOR,

        PI.ProductDivision AS PRODUCT_DIVISION,
		PI.RecapClass1	AMERICAS_SALESINCENTIVE_RECAP_1,
		PI.RecapClass2	AMERICAS_SALESINCENTIVE_RECAP_2,
		PI.IncentiveClass AMERICAS_SALESINCENTIVE_CLASS,
		PI.CopperAdj AMERICAS_SALESINCENTIVE_COPPER_ADJ,
		PI.ProductGroup Product_Group,
		PI.SCPG AMERICAS_SCPG,
		PI.ItemClass ITEM_CLASS,
		PI.ItemFamily AMERICAS_ITEM_FAMILY,

	D.GLOBAL_ACCOUNT_NAME,
	D.GLOBAL_ACCOUNT_BUSINESS_UNIT_L1,
	D.CHANNEL_CATEGORY,
	D.GLOBAL_ACCOUNT_BUSINESS_UNIT_L2,
	D.GLOBAL_REGION,
	ANX.ANIXTER_DIVC,
	ANX.ANIXTER_NAME,
	ANX.ANIXTER_REGION,
	ANX.ANIXTER_DIVISION,
	P.GLOBAL_PROD_CLASS_CODE,
	P.ITEM_DESC_CLASS,
	P.QUANTITY SALES_QUANTITY,
	P.QUANTITY_UOM SALES_QUANTITY_UOM,
	P.INVOICE_NUMBER,
	P.INVOICE_DATE,

	CASE WHEN P.DISTRIBUTOR_NAME IN ('ANIXTER-CH', 'ANIXTER-JP', 'ANIXTER-BY', 'ANIXTER-IS') THEN P.EXTENDED_COST * 1000 ELSE P.EXTENDED_COST END SALES_EXTENDED_AMT,
	CASE WHEN P.DISTRIBUTOR_NAME IN ('ANIXTER-CH', 'ANIXTER-JP', 'ANIXTER-BY', 'ANIXTER-IS') THEN P.EXTENDED_COST * 1000 ELSE P.EXTENDED_COST END SALES_EXTENDED_AMT_LOCAL,

	CASE WHEN P.COST_CURRENCY_EXCHANGE_USD > 0 THEN 
		CASE WHEN P.DISTRIBUTOR_NAME IN ('ANIXTER-CH', 'ANIXTER-JP', 'ANIXTER-BY', 'ANIXTER-IS') THEN P.EXTENDED_COST * 1000 ELSE P.EXTENDED_COST END * P.COST_CURRENCY_EXCHANGE_USD ELSE 
		CASE WHEN P.DISTRIBUTOR_NAME IN ('ANIXTER-CH', 'ANIXTER-JP', 'ANIXTER-BY', 'ANIXTER-IS') THEN P.EXTENDED_COST * 1000 ELSE P.EXTENDED_COST END END SALES_EXTENDED_AMT_USD,
	CASE WHEN P.DISTRIBUTOR_NAME IN ('ANIXTER-CH', 'ANIXTER-JP', 'ANIXTER-BY', 'ANIXTER-IS') THEN P.UNIT_COST * 1000 ELSE P.UNIT_COST END SALES_UNIT_PRICE,
	CASE WHEN P.DISTRIBUTOR_NAME IN ('ANIXTER-CH', 'ANIXTER-JP', 'ANIXTER-BY', 'ANIXTER-IS') THEN P.UNIT_COST * 1000 ELSE P.UNIT_COST END SALES_UNIT_PRICE_LOCAL,

	CASE WHEN P.COST_CURRENCY_EXCHANGE_USD > 0 THEN 
		CASE WHEN P.DISTRIBUTOR_NAME IN ('ANIXTER-CH', 'ANIXTER-JP', 'ANIXTER-BY', 'ANIXTER-IS') THEN P.UNIT_COST * 1000 ELSE P.UNIT_COST END * P.COST_CURRENCY_EXCHANGE_USD ELSE 
		CASE WHEN P.DISTRIBUTOR_NAME IN ('ANIXTER-CH', 'ANIXTER-JP', 'ANIXTER-BY', 'ANIXTER-IS') THEN P.UNIT_COST * 1000 ELSE P.UNIT_COST END END SALES_UNIT_PRICE_USD,

	P.COST_CURRENCY SALES_CURRENCY,
	P.COST_CURRENCY_EXCHANGE_USD SALES_CURRENCY_EXCHANGE,
	P.CUSTOMER_ORDER_NUMBER,
	P.SHIP_DATE,
	P.SHIP_DEBIT_NUMBER,
	P.PROJECT_NUMBER,
	P.QUOTE_NUMBER,
	P.COUNTRY_CODE,
	P.DESIGN_REGISTRATION_NUMBER,
	-- P.LENGTH_OF_PRODUCTION,
	
	P.BILL_TO_CUSTOMER_ID,
	P.BILL_TO_CUSTOMER_NAME,
	P.BILL_TO_CUSTOMER_CITY,
	P.BILL_TO_CUSTOMER_STATE,
	P.BILL_TO_CUSTOMER_POSTAL_CODE,

	P.DROP_SHIP_FLAG,
	P.VERTICAL_MARKET_SOLD_TO,
	--T.DATE CALENDAR_DATE,
    --T.YEAR CALENDAR_YEAR,
	--T.QUARTER CALENDAR_QUARTER,
	--T.MONTH CALENDAR_MONTH,
    --T.MONTH_NAME CALENDAR_MONTH_NAME,
    T.DAY,
    T.FISCAL_YEAR,
    T.FISCAL_QUARTER,
	T.FISCAL_PERIOD,
	T.FISCAL_PERIOD_NAME,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN	TRD1.FISCAL_YEAR ELSE TRD1.FISCAL_YEAR END REPORT_ENDING_FISCAL_YEAR,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN 	TRD1.FISCAL_QUARTER ELSE TRD1.FISCAL_QUARTER END REPORT_ENDING_FISCAL_QUARTER,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN 	TRD1.FISCAL_PERIOD ELSE TRD.FISCAL_PERIOD END REPORT_ENDING_FISCAL_PERIOD,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN 	TRD1.FISCAL_PERIOD_NAME ELSE TRD.FISCAL_PERIOD_NAME END REPORT_ENDING_PERIOD_FISCAL_NAME,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN 	TRD1.YEAR ELSE TRD.YEAR END REPORT_ENDING_CALENDAR_YEAR,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN 	TRD1.QUARTER ELSE TRD.QUARTER END REPORT_ENDING_CALENDAR_QUARTER,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN 	TRD1.MONTH ELSE TRD.MONTH END REPORT_ENDING_CALENDAR_MONTH,
	CASE WHEN (P.SRC_SYS_ID_POS = 'AXT_V2') THEN 	TRD1.MONTH_NAME ELSE TRD.MONTH_NAME END REPORT_ENDING_CALENDAR_MONTH_NAME,
	--TSD.FISCAL_YEAR SHIP_FISCAL_YEAR,
    --TSD.FISCAL_QUARTER SHIP_FISCAL_QUARTER,
	--TSD.FISCAL_PERIOD SHIP_FISCAL_PERIOD,
	--TSD.FISCAL_PERIOD_NAME SHIP_PERIOD_FISCAL_NAME,
	--TSD.YEAR SHIP_CALENDAR_YEAR,
	--TSD.QUARTER SHIP_CALENDAR_QUARTER,
	--TSD.MONTH SHIP_CALENDAR_MONTH,
    --TSD.MONTH_NAME SHIP_CALENDAR_MONTH_NAME,

	DATEPART(week, CAST(T.DATE AS smalldatetime) -1) FISCAL_WEEK,
	--(SELECT FISCAL_PERIOD FROM DM_D_CALENDAR WHERE TIME_KEY=convert(int,convert(varchar(8),getdate(),112))) CURRENT_PERIOD,
	--(SELECT FISCAL_YEAR FROM DM_D_CALENDAR WHERE TIME_KEY=convert(int,convert(varchar(8),getdate(),112))) CURRENT_YEAR,
    T.DAY_OF_WEEK,
    T.WEEKEND_FLG,
    T.HOLIDAY_FLG,
    P.POS_SALE_KEY RowID,
	P.UPDATE_DTTM LastUpdate,    
    'P2' Extract

from	dbo.DM_F_POS_SALES as P
	LEFT OUTER JOIN POSCleansingTable2 PI ON P.SRC_SYS_ID = PI.SRC_SYS_ID AND P.MANUFACTURER_PART_NUMBER = PI.VendorPartNumber
	LEFT OUTER JOIN XREF_POSTALCODE PC ON LEFT(P.SHIP_TO_CUSTOMER_POSTAL_CODE, 3) = PC.PostalCodePrefix AND P.COUNTRY_CODE = 'US'

	--- **** Time Information *** 
	JOIN DM_D_CALENDAR T ON T.TIME_KEY=P.TIME_KEY
	LEFT OUTER JOIN DM_D_CALENDAR TRD ON TRD.TIME_KEY=convert(VARCHAR(10),P.REPORT_ENDING_DATE,112)
	--LEFT OUTER JOIN DM_D_CALENDAR TSD ON TSD.TIME_KEY=convert(VARCHAR(10),P.SHIP_DATE,112)
	LEFT OUTER JOIN XREF_DISTRIBUTOR D ON P.SRC_SYS_ID_POS = D.SRC_SYS_ID_POS AND ((P.DISTRIBUTOR_NAME = D.POS_ACCOUNT_NAME) OR (D.DIV_C = P.DISTRIBUTOR_NAME))
	LEFT OUTER JOIN XREF_ANIXTER_INFO ANX ON P.DISTRIBUTOR_NAME = ANX.DISTRIBUTOR_NAME
	LEFT OUTER JOIN TPR_POS_ANIXTER_V2 ANXTPR ON P.SRC_SYS_ID_POS = ANXTPR.SRC_SYS_ID AND P.INVOICE_NUMBER = ANXTPR.INVOICE_NUMBER AND P.DISTRIBUTOR_PART_NUMBER = ANXTPR.DISTRIBUTOR_PART_NUMBER AND P.EXTENDED_COST = ANXTPR.EXTENDED_UNIT_COST
	LEFT OUTER JOIN DM_D_CALENDAR TRD1 ON TRD1.TIME_KEY=convert(VARCHAR(10),ANXTPR.REPORT_ENDING_DATE,112)
WHERE P.CURRENT_IND = 'Y' AND P.SRC_SYS_ID = 'BPCSRI'



GO


