select top 20 * from BDCSQLSP.SMART_DB.dbo.DM_F_INVOICE_LN

select distinct count(*), INVOICE_LN_KEY
from BDCSQLSP.SMART_DB.dbo.DM_F_INVOICE_LN
group by INVOICE_LN_KEY 
having count(*) > 1

delete from DBO.TEMP_DM_F_INVOICE_LN
	where Record_Key in 
	(
	select SCHILD.Record_Key from BDCSQLSP.SMART_DB.dbo.DM_F_INVOICE_LN SPARENT
	join [dbo].[DM_F_SALES_SUMMARY] SCHILD
	ON SPARENT.Record_Key =  SCHILD.Record_Key
	and SPARENT.UPDATE_DTTM > SCHILD.[UPDATE_DTTM] 
	)

SELECT 
INVOICE_LN_KEY,
SRC_SYS_ID,
TRX_TYPE,
TIME_KEY,
INVOICE_NBR,
INVOICE_LN_NBR,
INVOICE_DT,
QUANTITY,
ITEM_KEY,
CUSTOMER_KEY,
UPDATE_DTTM
INTO dbo.TEMP_DM_F_INVOICE_LN
FROM BDCSQLSP.SMART_DB.dbo.DM_F_INVOICE_LN

USE [SMART]
GO

/****** Object:  Index [PI01_TEMP_DM_F_INVOICE_LN]    Script Date: 11/01/2010 06:56:41 ******/
CREATE NONCLUSTERED INDEX [PI01_TEMP_DM_F_INVOICE_LN] ON [dbo].[TEMP_DM_F_INVOICE_LN] 
(
	[Invoice_Ln_Key] ASC
)
INCLUDE ( [UPDATE_DTTM]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO






FROM BDCSQLSP.SMART_DB.dbo.DM_F_INVOICE_LN
INVOICE_LN_KEY
SRC_SYS_ID
TRX_TYPE
TIME_KEY
INVOICE_NBR
INVOICE_LN_NBR
INVOICE_DT
QUANTITY
ITEM_KEY
CUSTOMER_KEY
UPDATE_DTTM

truncate table dbo.TEMP_BAG_BILLINGS
go
INSERT INTO dbo.TEMP_BAG_BILLINGS 
(ItemClass,
SalesIncentiveRecapClass1,
SalesIncentiveRecapClass2,
DivisionCode,
ExtendedQuantity,
ItemFamily)
SELECT 
B.ItemClass,
B.SalesIncentiveRecapClass1,
B.SalesIncentiveRecapClass2,
B.DivisionCode,
B.ExtendedQuantity,
B.ItemFamily
FROM BDCSQLSP.SMART_DB.dbo.BAG_BILLINGS B
