
create Function [dbo].[nSalesExtendedAmtUsd](@DISTRIBUTOR_NAME as varchar(60), @EXTENDED_COST as numeric(15,5) ,  @COST_CURRENCY_EXCHANGE_USD  as numeric(15,5) )
RETURNS varchar(2)
as 
begin
	return (
	CASE WHEN @COST_CURRENCY_EXCHANGE_USD > 0 THEN 
		CASE WHEN @DISTRIBUTOR_NAME IN ('ANIXTER-CH', 'ANIXTER-JP', 'ANIXTER-BY', 'ANIXTER-IS') THEN 
			@EXTENDED_COST * 1000 
		ELSE @EXTENDED_COST END * @COST_CURRENCY_EXCHANGE_USD ELSE 
		CASE WHEN @DISTRIBUTOR_NAME IN ('ANIXTER-CH', 'ANIXTER-JP', 'ANIXTER-BY', 'ANIXTER-IS') THEN 
			@EXTENDED_COST * 1000 
		ELSE 
			@EXTENDED_COST 
		END 
	END
	)
end
