SELECT [TableName]
      ,[CountOfRows]
      ,[CreateDate]
  FROM [SMART].[dbo].[Table_Row_Count]
where tablename like 'DM_D_CUSTOMER_TYPE%'
order by tablename,createdate


Select count (*) from BLDSQL1P.SMART_GLOBAL_DW.dbo.MIRROR_DM_D_CUSTOMER_TYPE
Select count (*) from BLDSQL1P.SMART_GLOBAL_DW.dbo.DM_H_ITEM
Select count (*) from dbo.MIRROR_DW_DM_H_ITEM


SELECT FISCAL_YEAR, SUM(NET_BILLING_AMT) FROM GLOBAL_BI WHERE FISCAL_YEAR >= 2008 GROUP BY FISCAL_YEAR
GO
SELECT FISCAL_YEAR, SUM(NET_BILLING_AMT) FROM GLOBAL_BI_MIRROR WHERE FISCAL_YEAR >= 2008 GROUP BY FISCAL_YEAR 
GO

SELECT SRC_SYS_ID, SUM(NET_BILLING_AMT) FROM GLOBAL_BI WHERE FISCAL_YEAR >= 2008 GROUP BY SRC_SYS_ID
GO
SELECT SRC_SYS_ID, SUM(NET_BILLING_AMT) FROM GLOBAL_BI_MIRROR WHERE FISCAL_YEAR >= 2008 GROUP BY SRC_SYS_ID
go

