echo off
cd\
cd C:\Users\wmiller\Documents\SQL Server Management Studio\HFit_Rewrite\CurrentWork\CDCImplementation

rem call _CkFileExists "@IVP.Tracker_Build.sql"
del @IVP.Tracker_Build.sql

copy spacer.txt @IVP.Tracker_Build.sql

call CheckTrackerFileExist PrintImmediate.sql

call CheckTrackerFileExist proc_TableHasCol.sql
call CheckTrackerFileExist proc_TableContainsAllCols.sql

call CheckTrackerFileExist proc_RI_Tracker_User.sql

call CheckTrackerFileExist proc_PULL_ALL_Tracker_StoredProceduresFromDB.sql 
call CheckTrackerFileExist Create_FACT_EDW_TrackerCompositeDetails.sql
call CheckTrackerFileExist MASTER_LKP_CTVersion.sql
call CheckTrackerFileExist proc_GetTableIndexes.sql

call CheckTrackerFileExist proc_SetTrackerPrimaryKey.sql
call CheckTrackerFileExist populate_Tracker_FACT_Tables.sql

call CheckTrackerFileExist proc_GenJobTrackerTableSync.sql
call CheckTrackerFileExist proc_GenJobTrackerAddStep.sql

call CheckTrackerFileExist proc_TrackerAddTrackerName.sql
call CheckTrackerFileExist proc_TrackerAlterPKEY.sql

call CheckTrackerFileExist proc_CkTrackerDataChanged.sql

call CheckTrackerFileExist proc_GenTrackerCTProc.sql
call CheckTrackerFileExist proc_GenTrackerCTProcMASTER.sql
call CheckTrackerFileExist proc_GenTrackerFactTable.sql

call CheckTrackerFileExist proc_MASTER_LKP_CTVersion_Fetch.sql
call CheckTrackerFileExist proc_MASTER_LKP_CTVersion_Update.sql

call CheckTrackerFileExist proc_SetStdColsTracker.sql

call CheckTrackerFileExist create_FactTrackerViews.sql

call CheckTrackerFileExist findLocks.sql

call CheckTrackerFileExist view_EDW_TrackerCompositeDetails.sql
call CheckTrackerFileExist view_EDW_TrackerCompositeDetails_CT.sql
call CheckTrackerFileExist view_EDW_TrackerCompositeDetails_CT_ONLY.sql
call CheckTrackerFileExist view_PPT_User_Details.sql

call CheckTrackerFileExist proc_GenTableColumnsVariables.sql

call CheckTrackerFileExist proc_UdpateTrackerCompositeFACTTbl.sql

rem ******************************************************************
rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerCardio_Cursor.sql
rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerHighSodiumFoods.sql

call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerBloodPressure.sql

rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerShots.sql
rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerSugaryFoods.sql
rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerWholeGrains.sql
rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerInstance_Tracker.sql
rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerSitLess.sql
rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerBodyMeasurements.sql
rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerTests.sql
rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerFlexibility.sql
rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerMealPortions.sql
rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerSleepPlan.sql
rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerCardio.sql
rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerTobaccoAttestation.sql
rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerFruits.sql
rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerMedicalCarePlan.sql
rem call CheckTrackerFileExist proc_CT_DIM_HFIT_Tracker.sql
rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerStrength.sql

call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerCholesterol.sql

rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerCholesterol.sql
rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerTobaccoFree.sql
rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerPreventiveCare.sql
rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerBloodPressure.sql
rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerStress.sql

call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerRegularMeals.sql
call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerMedicalCarePlan.sql

rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerCollectionSource.sql

call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerMealPortions.sql

rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerVegetables.sql

call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerHighSodiumFoods.sql

rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerHeight.sql

call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerHighFatFoods.sql
call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerHeight.sql

rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerRegularMeals.sql

call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerHbA1c.sql

rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerBloodSugarAndGlucose.sql

call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerFruits.sql
call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerFlexibility.sql

rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerStressManagement.sql

call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerDailySteps.sql
call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerCardio.sql

rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerCotinine.sql

call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerBMI.sql

rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerWater.sql

call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerBodyFat.sql
call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerRestingHeartRate.sql

rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerHighFatFoods.sql

call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerShots.sql
call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerSitLess.sql

rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerRestingHeartRate.sql

call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerSleepPlan.sql
call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerStrength.sql

rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerBMI.sql

call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerStress.sql
call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerStressManagement.sql

rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerSugaryDrinks.sql

call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerSugaryDrinks.sql
call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerSugaryFoods.sql
call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerTobaccoFree.sql

rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerDailySteps.sql

call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerVegetables.sql
call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerWater.sql
call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerWeight.sql
call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerWholeGrains.sql
call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerCotinine.sql
call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerPreventiveCare.sql
call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerTobaccoAttestation.sql
call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerInstance_Tracker.sql
call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerBloodSugarAndGlucose.sql
call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerBodyMeasurements.sql

rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerHbA1c.sql

call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerTests.sql

call CheckTrackerFileExist view_MART_HealthAssesment.sql
call CheckTrackerFileExist view_PPT_CMSUser.sql
call CheckTrackerFileExist view_PPT_User_TrackerDetails.sql

call CheckTrackerFileExist proc_SetTrackerKeyColToStandardLength.sql

rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerBodyFat.sql
rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerWeight.sql
rem call CheckTrackerFileExist proc_CT_DIM_HFit_TrackerBMI_Cursor.sql
rem ******************************************************************

rem call CheckTrackerFileExist proc_CT_FACT_HealthAssessment.sql
rem call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerBloodPressure.sql
rem call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerBloodSugarAndGlucose.sql
rem call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerBMI.sql
rem call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerBodyFat.sql
rem call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerBodyMeasurements.sql
rem call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerCardio.sql
rem call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerCholesterol.sql
rem call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerCotinine.sql
rem call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerDailySteps.sql
rem call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerFlexibility.sql
rem call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerFruits.sql
rem call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerHbA1c.sql
rem call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerHeight.sql
rem call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerHighFatFoods.sql
rem call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerHighSodiumFoods.sql
rem call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerInstance_Tracker.sql
rem call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerMealPortions.sql
rem call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerMedicalCarePlan.sql
rem call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerPreventiveCare.sql
rem call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerRegularMeals.sql
rem call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerRestingHeartRate.sql
rem call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerShots.sql
rem call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerSitLess.sql
rem call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerSleepPlan.sql
rem call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerStrength.sql
rem call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerStress.sql
rem call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerStressManagement.sql
rem call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerSugaryDrinks.sql
rem call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerSugaryFoods.sql
rem call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerTests.sql
rem call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerTobaccoAttestation.sql
rem call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerTobaccoFree.sql
rem call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerVegetables.sql
rem call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerWater.sql
rem call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerWeight.sql
rem call CheckTrackerFileExist proc_CT_FACT_TrackerCompositeDetails_TrackerWholeGrains.sql

rem call CheckTrackerFileExist proc_UdpateTrackerCompositeFACTTbl.sql

call CheckTrackerFileExist view_DIM_UserPptDetail.sql

call CheckTrackerFileExist LastStep_PopulateTrackerTables.sql

call CheckTrackerFileExist proc_ConvertAllDatetimeToDatetime2.sql

call CheckTrackerFileExist proc_SetTrackerDataSurrogateKey.sql

call CheckTrackerFileExist create_Tracker_Indexes.sql 

call CheckTrackerFileExist create_Trigger__ON_TrackerName.sql

rem call CheckTrackerFileExist FindTRackerTablesMissingTrackerNAmeCOlumn.sql
call CheckTrackerFileExist FindAndCorrectAllTrackerNamesInTrackerTables.sql

pause