exec proc_BASE_CMS_User_KenticoCMS_1_Sync ;
exec proc_BASE_CMS_UserCulture_KenticoCMS_1_Sync ;
exec proc_BASE_CMS_UserRole_KenticoCMS_1_Sync ;
exec proc_BASE_CMS_UserSettings_KenticoCMS_1_Sync ;
exec proc_BASE_CMS_UserSite_KenticoCMS_1_Sync ;
exec proc_BASE_HFit_Account_KenticoCMS_1_Sync ;
exec proc_BASE_HFit_CoachingHealthInterest_KenticoCMS_1_Sync ;
exec proc_BASE_Hfit_CoachingUserCMCondition_KenticoCMS_1_Sync ;
exec proc_BASE_Hfit_CoachingUserCMExclusion_KenticoCMS_1_Sync ;
exec proc_BASE_HFit_GoalOutcome_KenticoCMS_1_Sync ;
exec proc_BASE_HFit_LKP_CoachingCMConditions_KenticoCMS_1_Sync ;
exec proc_BASE_HFit_LKP_CoachingCMExclusions_KenticoCMS_1_Sync ;
exec proc_BASE_HFit_PPTEligibility_KenticoCMS_1_Sync ;
exec proc_BASE_HFit_UserGoal_KenticoCMS_1_Sync ;

exec proc_BASE_CMS_User_KenticoCMS_2_Sync ;
exec proc_BASE_CMS_UserCulture_KenticoCMS_2_Sync ;
exec proc_BASE_CMS_UserRole_KenticoCMS_2_Sync ;
exec proc_BASE_CMS_UserSettings_KenticoCMS_2_Sync ;
exec proc_BASE_CMS_UserSite_KenticoCMS_2_Sync ;
exec proc_BASE_HFit_Account_KenticoCMS_2_Sync ;
exec proc_BASE_HFit_CoachingHealthInterest_KenticoCMS_2_Sync ;
exec proc_BASE_Hfit_CoachingUserCMCondition_KenticoCMS_2_Sync ;
exec proc_BASE_Hfit_CoachingUserCMExclusion_KenticoCMS_2_Sync ;
exec proc_BASE_HFit_GoalOutcome_KenticoCMS_2_Sync ;
exec proc_BASE_HFit_LKP_CoachingCMConditions_KenticoCMS_2_Sync ;
exec proc_BASE_HFit_LKP_CoachingCMExclusions_KenticoCMS_2_Sync ;
exec proc_BASE_HFit_PPTEligibility_KenticoCMS_2_Sync ;
exec proc_BASE_HFit_UserGoal_KenticoCMS_2_Sync ;

exec proc_BASE_CMS_User_KenticoCMS_3_Sync ;
exec proc_BASE_CMS_UserCulture_KenticoCMS_3_Sync ;
exec proc_BASE_CMS_UserRole_KenticoCMS_3_Sync ;
exec proc_BASE_CMS_UserSettings_KenticoCMS_3_Sync ;
exec proc_BASE_CMS_UserSite_KenticoCMS_3_Sync ;
exec proc_BASE_HFit_Account_KenticoCMS_3_Sync ;
exec proc_BASE_HFit_CoachingHealthInterest_KenticoCMS_3_Sync ;
exec proc_BASE_Hfit_CoachingUserCMCondition_KenticoCMS_3_Sync ;
exec proc_BASE_Hfit_CoachingUserCMExclusion_KenticoCMS_3_Sync ;
exec proc_BASE_HFit_GoalOutcome_KenticoCMS_3_Sync ;
exec proc_BASE_HFit_LKP_CoachingCMConditions_KenticoCMS_3_Sync ;
exec proc_BASE_HFit_LKP_CoachingCMExclusions_KenticoCMS_3_Sync ;
exec proc_BASE_HFit_PPTEligibility_KenticoCMS_3_Sync ;
exec proc_BASE_HFit_UserGoal_KenticoCMS_3_Sync ;

exec proc_view_EDW_CoachingPPTAvailable_KenticoCMS_1 ;
exec proc_view_EDW_CoachingPPTEligible_KenticoCMS_1 ;
exec proc_view_EDW_CoachingPPTEnrolled_KenticoCMS_1
exec proc_view_HFit_CoachingHealthArea_Joined_KenticoCMS_1;
exec proc_view_HFit_Goal_Joined_KenticoCMS_1;
exec proc_view_HFit_GoalCategory_Joined_KenticoCMS_1;
exec proc_view_HFit_GoalSubCategory_Joined_KenticoCMS_1 ;

exec proc_view_EDW_CoachingPPTAvailable_KenticoCMS_2 ;
exec proc_view_EDW_CoachingPPTEligible_KenticoCMS_2 ;
exec proc_view_EDW_CoachingPPTEnrolled_KenticoCMS_2
exec proc_view_HFit_CoachingHealthArea_Joined_KenticoCMS_2;
exec proc_view_HFit_Goal_Joined_KenticoCMS_2;
exec proc_view_HFit_GoalCategory_Joined_KenticoCMS_2;
exec proc_view_HFit_GoalSubCategory_Joined_KenticoCMS_2;

exec proc_view_EDW_CoachingPPTAvailable_KenticoCMS_3 ;
exec proc_view_EDW_CoachingPPTEligible_KenticoCMS_3 ;
exec proc_view_EDW_CoachingPPTEnrolled_KenticoCMS_3 ;
exec proc_view_HFit_CoachingHealthArea_Joined_KenticoCMS_3;
exec proc_view_HFit_Goal_Joined_KenticoCMS_3;
exec proc_view_HFit_GoalCategory_Joined_KenticoCMS_3;
exec proc_view_HFit_GoalSubCategory_Joined_KenticoCMS_3;