
-- Use KenticoCMS_Datamart_2

ALTER DATABASE KenticoCMS_1 SET CHANGE_TRACKING = ON (CHANGE_RETENTION = 2 DAYS, AUTO_CLEANUP = ON) ;

ALTER DATABASE KenticoCMS_1 SET CHANGE_TRACKING = ON (CHANGE_RETENTION = 2 DAYS, AUTO_CLEANUP = ON) ;

ALTER DATABASE KenticoCMS_1 SET CHANGE_TRACKING = ON (CHANGE_RETENTION = 2 DAYS, AUTO_CLEANUP = ON) ;
