
go
print 'Executing Create_BASE_MART_EDW_HealthAssesment.sql'
go
if exists (select name from sys.tables where name  = 'BASE_MART_EDW_HealthAssesment')
begin
    print 'Table BASE_MART_EDW_HealthAssesment already exists, skipping.'
    goto OUTOFHERE;
end 
CREATE TABLE [dbo].[BASE_MART_EDW_HealthAssesment](
	[UserStartedItemID] [int] NOT NULL,
	[UserID] [int] NOT NULL,
	[UserGUID] [uniqueidentifier] NOT NULL,
	[HFitUserMpiNumber] [int] NULL,
	[SiteGUID] [uniqueidentifier] NOT NULL,
	[AccountID] [int] NOT NULL,
	[AccountCD] [nvarchar](8) NULL,
	[AccountName] [nvarchar](200) NULL,
	[HAStartedDt] [datetime2](7) NOT NULL,
	[HACompletedDt] [datetime2](7) NULL,
	[UserModuleItemId] [int] NOT NULL,
	[UserModuleCodeName] [nvarchar](100) NOT NULL,
	[HAModuleNodeGUID] [uniqueidentifier] NOT NULL,
	[CMSNodeGuid] [uniqueidentifier] NULL,
	[HAModuleVersionID] [int] NULL,
	[UserRiskCategoryItemID] [int] NOT NULL,
	[UserRiskCategoryCodeName] [nvarchar](100) NOT NULL,
	[HARiskCategoryNodeGUID] [uniqueidentifier] NOT NULL,
	[HARiskCategoryVersionID] [int] NULL,
	[UserRiskAreaItemID] [int] NOT NULL,
	[UserRiskAreaCodeName] [nvarchar](100) NOT NULL,
	[HARiskAreaNodeGUID] [uniqueidentifier] NOT NULL,
	[HARiskAreaVersionID] [int] NULL,
	[UserQuestionItemID] [int] NOT NULL,
	[Title] [nvarchar](max) NULL,
	[HAQuestionGuid] [uniqueidentifier] NOT NULL,
	[UserQuestionCodeName] [nvarchar](100) NOT NULL,
	[HAQuestionDocumentID] [int] NULL,
	[HAQuestionVersionID] [int] NULL,
	[HAQuestionNodeGUID] [uniqueidentifier] NOT NULL,
	[UserAnswerItemID] [int] NOT NULL,
	[HAAnswerNodeGUID] [uniqueidentifier] NOT NULL,
	[HAAnswerVersionID] [int] NULL,
	[UserAnswerCodeName] [nvarchar](100) NOT NULL,
	[HAAnswerValue] [nvarchar](255) NULL,
	[HAModuleScore] [float] NOT NULL,
	[HARiskCategoryScore] [float] NULL,
	[HARiskAreaScore] [float] NULL,
	[HAQuestionScore] [float] NULL,
	[HAAnswerPoints] [int] NULL,
	[UOMCode] [nvarchar](10) NULL,
	[HAScore] [int] NULL,
	[ModulePreWeightedScore] [float] NULL,
	[RiskCategoryPreWeightedScore] [float] NULL,
	[RiskAreaPreWeightedScore] [float] NULL,
	[QuestionPreWeightedScore] [float] NULL,
	[ChangeType] [varchar](1) NOT NULL,
	[ItemCreatedWhen] [datetime2](7) NULL,
	[ItemModifiedWhen] [datetime2](7) NULL,
	[IsProfessionallyCollected] [bit] NOT NULL,
	[HAPaperFlg] [bit] NOT NULL,
	[HATelephonicFlg] [bit] NOT NULL,
	[HAStartedMode] [int] NOT NULL,
	[HACompletedMode] [int] NOT NULL,
	[DocumentCulture_VHCJ] [nvarchar](10) NULL,
	[DocumentCulture_HAQuestionsView] [nvarchar](10) NULL,
	[CampaignNodeGUID] [uniqueidentifier] NOT NULL,
	[HealthAssessmentType] [varchar](9) NOT NULL,
	[HAUserStarted_LastModifiedDate] [datetime2](7) NULL,
	[CMSUser_LastModifiedDate] [datetime2](7) NULL,
	[UserSettings_LastModifiedDate] [datetime2](7) NULL,
	[UserSite_LastModifiedDate] [datetime2](7) NULL,
	[ACCT_LastModifiedDate] [datetime2](7) NULL,
	[HAUserModule_LastModifiedDate] [datetime2](7) NULL,
	[HARiskCategory_LastModifiedDate] [datetime2](7) NULL,
	[HAUserRiskArea_LastModifiedDate] [datetime2](7) NULL,
	[HAUserQuestion_LastModifiedDate] [datetime2](7) NULL,
	[HAUserAnswers_LastModifiedDate] [datetime2](7) NULL,
	[HealthAssesmentUserStartedNodeGUID] [uniqueidentifier] NULL,
	[PointResults] [int] NULL,
	[QuestionGroupCodeName] [nvarchar](100) NULL,
	[CT_HAStartedMode] [bit] NULL,
	[CT_HATelephonicFlg] [bit] NULL,
	[CT_HADocumentConfigID] [bit] NULL,
	[CT_HFitUserMpiNumber] [bit] NULL,
	[CT_IsProfessionallyCollected] [bit] NULL,
	[CT_CodeName] [bit] NULL,
	[SurrogateKey_HFit_HealthAssesmentUserStarted] [bigint] NOT NULL,
	[SurrogateKey_CMS_User] [bigint] NOT NULL,
	[SurrogateKey_CMS_UserSettings] [bigint] NOT NULL,
	[SurrogateKey_CMS_UserSite] [bigint] NOT NULL,
	[SurrogateKey_CMS_Site] [bigint] NOT NULL,
	[SurrogateKey_HFit_Account] [bigint] NOT NULL,
	[SurrogateKey_HFit_HealthAssesmentUserModule] [bigint] NOT NULL,
	[SurrogateKey_View_HFit_HACampaign_Joined] [bigint] NOT NULL,
	[SurrogateKey_View_HFit_HealthAssessment_Joined] [bigint] NOT NULL,
	[SurrogateKey_HFit_HealthAssesmentUserRiskCategory] [bigint] NOT NULL,
	[SurrogateKey_HFit_HealthAssesmentUserRiskArea] [bigint] NOT NULL,
	[SurrogateKey_HFit_HealthAssesmentUserQuestion] [bigint] NOT NULL,
	[SurrogateKey_View_EDW_HealthAssesmentQuestions] [bigint] NOT NULL,
	[SurrogateKey_HFit_HealthAssesmentUserAnswers] [bigint] NOT NULL,
	[HARiskCategory_ItemModifiedWhen] [datetime2](7) NULL,
	[HAUserRiskArea_ItemModifiedWhen] [datetime2](7) NULL,
	[HAUserQuestion_ItemModifiedWhen] [datetime2](7) NULL,
	[HAUserAnswers_ItemModifiedWhen] [datetime2](7) NULL,
	[LastModifiedDate] [datetime2](7) NULL,
	[RowDataChanged] [int] NOT NULL,
	[SVR] [nvarchar](100) NOT NULL,
	[DBNAME] [nvarchar](100) NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

print 'Created Table BASE_MART_EDW_HealthAssesment.'

OUTOFHERE:

go
print 'Executed Create_BASE_MART_EDW_HealthAssesment.sql'
go
