USE [master]
GO

CREATE LOGIN [SSAS] WITH PASSWORD=N'Junebug@01', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO

ALTER LOGIN [dmiller] enable
GO

ALTER SERVER ROLE [sysadmin] ADD MEMBER [SSAS]
GO


