

enable trigger TRIG_DEL_BASE_CMS_User on BASE_CMS_User ;
enable trigger TRIG_DEL_BASE_HFit_LKP_CoachingCMConditions on BASE_HFit_LKP_CoachingCMConditions;
enable trigger TRIG_DEL_BASE_CMS_UserRole on BASE_CMS_UserRole;
enable trigger TRIG_DEL_BASE_HFit_PPTEligibility on BASE_HFit_PPTEligibility;
enable trigger TRIG_DEL_BASE_CMS_UserSite on BASE_CMS_UserSite;
enable trigger TRIG_DEL_BASE_HFit_LKP_CoachingCMExclusions on BASE_HFit_LKP_CoachingCMExclusions;
enable trigger TRIG_DEL_BASE_HFit_Account on BASE_HFit_Account;
enable trigger TRIG_DEL_BASE_Hfit_CoachingUserCMCondition on BASE_Hfit_CoachingUserCMCondition;
enable trigger TRIG_DEL_BASE_CMS_UserCulture on BASE_CMS_UserCulture;
enable trigger TRIG_DEL_BASE_HFIt_PptEligibility_mosbrun on BASE_HFIt_PptEligibility_mosbrun;
enable trigger TRIG_DEL_BASE_CMS_UserSettings on BASE_CMS_UserSettings;
enable trigger TRIG_DEL_BASE_HFit_CoachingHealthInterest on BASE_HFit_CoachingHealthInterest;
enable trigger TRIG_DEL_BASE_HFit_GoalOutcome on BASE_HFit_GoalOutcome;
enable trigger TRIG_DEL_BASE_Hfit_CoachingUserCMExclusion on BASE_Hfit_CoachingUserCMExclusion;
enable trigger TRIG_DEL_BASE_HFit_UserGoal on BASE_HFit_UserGoal;


enable trigger TRIG_UPDT_BASE_CMS_User on BASE_CMS_User ;
enable trigger TRIG_UPDT_BASE_HFit_LKP_CoachingCMConditions on BASE_HFit_LKP_CoachingCMConditions;
enable trigger TRIG_UPDT_BASE_CMS_UserRole on BASE_CMS_UserRole;
enable trigger TRIG_UPDT_BASE_HFit_PPTEligibility on BASE_HFit_PPTEligibility;
enable trigger TRIG_UPDT_BASE_CMS_UserSite on BASE_CMS_UserSite;
enable trigger TRIG_UPDT_BASE_HFit_LKP_CoachingCMExclusions on BASE_HFit_LKP_CoachingCMExclusions;
enable trigger TRIG_UPDT_BASE_HFit_Account on BASE_HFit_Account;
enable trigger TRIG_UPDT_BASE_Hfit_CoachingUserCMCondition on BASE_Hfit_CoachingUserCMCondition;
enable trigger TRIG_UPDT_BASE_CMS_UserCulture on BASE_CMS_UserCulture;
enable trigger TRIG_UPDT_BASE_HFIt_PptEligibility_mosbrun on BASE_HFIt_PptEligibility_mosbrun;
enable trigger TRIG_UPDT_BASE_CMS_UserSettings on BASE_CMS_UserSettings;
enable trigger TRIG_UPDT_BASE_HFit_CoachingHealthInterest on BASE_HFit_CoachingHealthInterest;
enable trigger TRIG_UPDT_BASE_HFit_GoalOutcome on BASE_HFit_GoalOutcome;
enable trigger TRIG_UPDT_BASE_Hfit_CoachingUserCMExclusion on BASE_Hfit_CoachingUserCMExclusion;
enable trigger TRIG_UPDT_BASE_HFit_UserGoal on BASE_HFit_UserGoal;
