USE [KenticoCMS_DataMart]
GO

/****** Object:  Table [dbo].[FACT_view_EDW_HealthAssesment_CT]    Script Date: 12/12/2015 8:09:58 PM ******/
DROP TABLE [dbo].[FACT_view_EDW_HealthAssesment_CT]
GO

/****** Object:  Table [dbo].[FACT_view_EDW_HealthAssesment_CT]    Script Date: 12/12/2015 8:09:58 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO
USE [KenticoCMS_DataMart]
GO

/****** Object:  Table [dbo].[FACT_view_EDW_HealthAssesment_CT]    Script Date: 12/12/2015 8:09:12 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO
drop table [FACT_view_EDW_HealthAssesment_CT]
go
CREATE TABLE [dbo].[FACT_view_EDW_HealthAssesment_CT](
	[USERSTARTEDITEMID] [int] NOT NULL,
	[HEALTHASSESMENTUSERSTARTEDNODEGUID] [uniqueidentifier] NOT NULL,
	[USERID] [bigint] NOT NULL,
	[USERGUID] [uniqueidentifier] NOT NULL,
	[HFITUSERMPINUMBER] [bigint] NULL,
	[SITEGUID] [uniqueidentifier] NOT NULL,
	[ACCOUNTID] [int] NOT NULL,
	[ACCOUNTCD] [nvarchar](8) NULL,
	[ACCOUNTNAME] [nvarchar](200) NULL,
	[HASTARTEDDT] [datetime2](7) NOT NULL,
	[HACOMPLETEDDT] [datetime2](7) NULL,
	[USERMODULEITEMID] [int] NOT NULL,
	[USERMODULECODENAME] [nvarchar](100) NOT NULL,
	[HAMODULENODEGUID] [uniqueidentifier] NOT NULL,
	[CMSNODEGUID] [uniqueidentifier] NOT NULL,
	[HAMODULEVERSIONID] [int] NULL,
	[USERRISKCATEGORYITEMID] [int] NOT NULL,
	[USERRISKCATEGORYCODENAME] [nvarchar](100) NOT NULL,
	[HARISKCATEGORYNODEGUID] [uniqueidentifier] NOT NULL,
	[HARISKCATEGORYVERSIONID] [int] NULL,
	[USERRISKAREAITEMID] [int] NOT NULL,
	[USERRISKAREACODENAME] [nvarchar](100) NOT NULL,
	[HARISKAREANODEGUID] [uniqueidentifier] NOT NULL,
	[HARISKAREAVERSIONID] [int] NULL,
	[USERQUESTIONITEMID] [int] NOT NULL,
	[TITLE] [nvarchar](max) NULL,
	[HAQUESTIONGUID] [uniqueidentifier] NOT NULL,
	[USERQUESTIONCODENAME] [nvarchar](100) NOT NULL,
	[HAQUESTIONDOCUMENTID] [int] NULL,
	[HAQUESTIONVERSIONID] [int] NULL,
	[HAQUESTIONNODEGUID] [uniqueidentifier] NOT NULL,
	[USERANSWERITEMID] [int] NOT NULL,
	[HAANSWERNODEGUID] [uniqueidentifier] NOT NULL,
	[HAANSWERVERSIONID] [int] NULL,
	[USERANSWERCODENAME] [nvarchar](100) NOT NULL,
	[HAANSWERVALUE] [nvarchar](255) NULL,
	[HAMODULESCORE] [float] NOT NULL,
	[HARISKCATEGORYSCORE] [float] NULL,
	[HARISKAREASCORE] [float] NULL,
	[HAQUESTIONSCORE] [float] NULL,
	[HAANSWERPOINTS] [int] NULL,
	[POINTRESULTS] [int] NULL,
	[UOMCODE] [nvarchar](10) NULL,
	[HASCORE] [int] NULL,
	[MODULEPREWEIGHTEDSCORE] [float] NULL,
	[RISKCATEGORYPREWEIGHTEDSCORE] [float] NULL,
	[RISKAREAPREWEIGHTEDSCORE] [float] NULL,
	[QUESTIONPREWEIGHTEDSCORE] [float] NULL,
	[QUESTIONGROUPCODENAME] [nvarchar](100) NULL,
	[CHANGETYPE] [nchar](1) NULL,
	[ITEMCREATEDWHEN] [datetime2](7) NULL,
	[ITEMMODIFIEDWHEN] [datetime2](7) NULL,
	[ISPROFESSIONALLYCOLLECTED] [bit] NOT NULL,
	[HARISKCATEGORY_ITEMMODIFIEDWHEN] [datetime2](7) NULL,
	[HAUSERRISKAREA_ITEMMODIFIEDWHEN] [datetime2](7) NULL,
	[HAUSERQUESTION_ITEMMODIFIEDWHEN] [datetime2](7) NULL,
	[HAUSERANSWERS_ITEMMODIFIEDWHEN] [datetime2](7) NULL,
	[HAPAPERFLG] [bit] NOT NULL,
	[HATELEPHONICFLG] [bit] NOT NULL,
	[HASTARTEDMODE] [int] NOT NULL,
	[HACOMPLETEDMODE] [int] NOT NULL,
	[DOCUMENTCULTURE_VHCJ] [nvarchar](10) NOT NULL,
	[DOCUMENTCULTURE_HAQUESTIONSVIEW] [nvarchar](10) NOT NULL,
	[CAMPAIGNNODEGUID] [uniqueidentifier] NOT NULL,
	[HACAMPAIGNID] [int] NOT NULL,
	[HASHCODE] [varchar](100) NULL,
	[PKHASHCODE] [varchar](100) NULL,
	--[CHANGED_FLG] [int] NULL,
	--[CT_CMS_USER_USERID] [int] NULL,
	--[CT_CMS_USER_CHANGE_OPERATION] [nchar](1) NULL,
	--[CT_USERSETTINGSID] [int] NULL,
	--[CT_USERSETTINGSID_CHANGE_OPERATION] [nchar](1) NULL,
	--[SITEID_CTID] [int] NULL,
	--[SITEID_CHANGE_OPERATION] [nchar](1) NULL,
	--[USERSITEID_CTID] [int] NULL,
	--[USERSITEID_CHANGE_OPERATION] [nchar](1) NULL,
	--[ACCOUNTID_CTID] [int] NULL,
	--[ACCOUNTID__CHANGE_OPERATION] [nchar](1) NULL,
	--[HAUSERANSWERS_CTID] [int] NULL,
	--[HAUSERANSWERS_CHANGE_OPERATION] [nchar](1) NULL,
	--[HFIT_HEALTHASSESMENTUSERMODULE_CTID] [int] NULL,
	--[HFIT_HEALTHASSESMENTUSERMODULE_CHANGE_OPERATION] [nchar](1) NULL,
	--[HFIT_HEALTHASSESMENTUSERQUESTION_CTID] [int] NULL,
	--[HFIT_HEALTHASSESMENTUSERQUESTION_CHANGE_OPERATION] [nchar](1) NULL,
	--[HFIT_HealthAssesmentUserQuestionGroupResults_CTID] [int] NULL,
	--[HFIT_HealthAssesmentUserQuestionGroupResults_CHANGE_OPERATION] [nchar](1) NULL,
	--[HFIT_HEALTHASSESMENTUSERRISKAREA_CTID] [int] NULL,
	--[HFIT_HEALTHASSESMENTUSERRISKAREA_CHANGE_OPERATION] [nchar](1) NULL,
	--[HFIT_HEALTHASSESMENTUSERRISKCATEGORY_CTID] [int] NULL,
	--[HFIT_HEALTHASSESMENTUSERRISKCATEGORY_CHANGE_OPERATION] [nchar](1) NULL,
	--[HFIT_HEALTHASSESMENTUSERSTARTED_CTID] [int] NULL,
	--[HFIT_HEALTHASSESMENTUSERSTARTED_CHANGE_OPERATION] [nchar](1) NULL,
	--[CT_CMS_USER_SCV] [bigint] NULL,
	--[CT_CMS_USERSETTINGS_SCV] [bigint] NULL,
	--[CT_CMS_SITE_SCV] [bigint] NULL,
	--[CT_CMS_USERSITE_SCV] [bigint] NULL,
	--[CT_HFIT_ACCOUNT_SCV] [bigint] NULL,
	--[CT_HFIT_HealthAssesmentUserAnswers_SCV] [bigint] NULL,
	--[CT_HFIT_HEALTHASSESMENTUSERMODULE_SCV] [bigint] NULL,
	--[CT_HFIT_HEALTHASSESMENTUSERQUESTION_SCV] [bigint] NULL,
	--[CT_HFIT_HealthAssesmentUserQuestionGroupResults_SCV] [bigint] NULL,
	--[CT_HFIT_HEALTHASSESMENTUSERRISKAREA_SCV] [bigint] NULL,
	--[CT_HFIT_HEALTHASSESMENTUSERRISKCATEGORY_SCV] [bigint] NULL,
	--[CT_HFIT_HEALTHASSESMENTUSERSTARTED_SCV] [bigint] NULL,
	--[LastModifiedDATE] [datetime2](7) NULL,
	[DELETEFLG] [int] NOT NULL,
	[HealthAssessmentType] [varchar](9) NOT NULL,
	[LASTUPDATEID] [int] NOT NULL,
	[SVR] [nvarchar](100) NOT NULL,
	[DBNAME] [nvarchar](100) NOT NULL,
	[DeletedFlg] [int] NOT NULL,
	[LASTLOADEDDATE] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

