


-- select 'exec ' + name + char(10) + 'GO' from sys.procedures where name like 'proc_CT_FACT_TrackerComposite%' or name like 'proc_CT_DIM_HFit_Tracker%'

exec proc_CT_DIM_HFit_TrackerCardio_Cursor
GO
exec proc_CT_DIM_HFit_TrackerSugaryDrinks
GO
exec proc_CT_DIM_HFit_TrackerFlexibility
GO
exec proc_CT_DIM_HFit_TrackerSleepPlan
GO
exec proc_CT_DIM_HFit_TrackerCardio
GO
exec proc_CT_DIM_HFit_TrackerHighSodiumFoods
GO
exec proc_CT_DIM_HFit_TrackerCollectionSource
GO
exec proc_CT_DIM_HFit_TrackerBMI
GO
exec proc_CT_DIM_HFit_TrackerVegetables
GO
exec proc_CT_DIM_HFit_TrackerRegularMeals
GO
exec proc_CT_DIM_HFit_TrackerSugaryFoods
GO
exec proc_CT_DIM_HFit_TrackerFruits
GO
exec proc_CT_DIM_HFit_TrackerInstance_Tracker
GO
exec proc_CT_DIM_HFit_TrackerCotinine
GO
exec proc_CT_DIM_HFit_TrackerStrength
GO
exec proc_CT_DIM_HFit_TrackerBodyFat
GO
exec proc_CT_DIM_HFit_TrackerWater
GO
exec proc_CT_DIM_HFIT_Tracker
GO
exec proc_CT_DIM_HFit_TrackerRestingHeartRate
GO
exec proc_CT_DIM_HFit_TrackerTests
GO
exec proc_CT_DIM_HFit_TrackerHbA1c
GO
exec proc_CT_DIM_HFit_TrackerMealPortions
GO
exec proc_CT_DIM_HFit_TrackerDailySteps
GO
exec proc_CT_DIM_HFit_TrackerStress
GO
exec proc_CT_DIM_HFit_TrackerBodyMeasurements
GO
exec proc_CT_DIM_HFit_TrackerWeight
GO
exec proc_CT_DIM_HFit_TrackerShots
GO
exec proc_CT_DIM_HFit_TrackerHeight
GO
exec proc_CT_DIM_HFit_TrackerBloodPressure
GO
exec proc_CT_DIM_HFit_TrackerTobaccoAttestation
GO
exec proc_CT_DIM_HFit_TrackerMedicalCarePlan
GO
exec proc_CT_DIM_HFit_TrackerStressManagement
GO
exec proc_CT_DIM_HFit_TrackerWholeGrains
GO
exec proc_CT_DIM_HFit_TrackerCholesterol
GO
exec proc_CT_DIM_HFit_TrackerSitLess
GO
exec proc_CT_DIM_HFit_TrackerBloodSugarAndGlucose
GO
exec proc_CT_DIM_HFit_TrackerHighFatFoods
GO
exec proc_CT_DIM_HFit_TrackerTobaccoFree
GO
exec proc_CT_DIM_HFit_TrackerPreventiveCare
GO
exec proc_CT_FACT_TrackerCompositeDetails_TrackerBloodPressure
GO
exec proc_CT_FACT_TrackerCompositeDetails_TrackerCholesterol
GO
exec proc_CT_FACT_TrackerCompositeDetails_TrackerRegularMeals
GO
exec proc_CT_FACT_TrackerCompositeDetails_TrackerMedicalCarePlan
GO
exec proc_CT_FACT_TrackerCompositeDetails_TrackerMealPortions
GO
exec proc_CT_FACT_TrackerCompositeDetails_TrackerHighSodiumFoods
GO
exec proc_CT_FACT_TrackerCompositeDetails_TrackerHighFatFoods
GO
exec proc_CT_FACT_TrackerCompositeDetails_TrackerHeight
GO
exec proc_CT_FACT_TrackerCompositeDetails_TrackerHbA1c
GO
exec proc_CT_FACT_TrackerCompositeDetails_TrackerFruits
GO
exec proc_CT_FACT_TrackerCompositeDetails_TrackerFlexibility
GO
exec proc_CT_FACT_TrackerCompositeDetails_TrackerDailySteps
GO
exec proc_CT_FACT_TrackerCompositeDetails_TrackerCardio
GO
exec proc_CT_FACT_TrackerCompositeDetails_TrackerBMI
GO
exec proc_CT_FACT_TrackerCompositeDetails_TrackerBodyFat
GO
exec proc_CT_FACT_TrackerCompositeDetails_TrackerRestingHeartRate
GO
exec proc_CT_FACT_TrackerCompositeDetails_TrackerSitLess
GO
exec proc_CT_FACT_TrackerCompositeDetails_TrackerSleepPlan
GO
exec proc_CT_FACT_TrackerCompositeDetails_TrackerStrength
GO
exec proc_CT_FACT_TrackerCompositeDetails_TrackerStress
GO
exec proc_CT_FACT_TrackerCompositeDetails_TrackerStressManagement
GO
exec proc_CT_FACT_TrackerCompositeDetails_TrackerSugaryDrinks
GO
exec proc_CT_FACT_TrackerCompositeDetails_TrackerSugaryFoods
GO
exec proc_CT_FACT_TrackerCompositeDetails_TrackerTobaccoFree
GO
exec proc_CT_FACT_TrackerCompositeDetails_TrackerVegetables
GO
exec proc_CT_FACT_TrackerCompositeDetails_TrackerWater
GO
exec proc_CT_FACT_TrackerCompositeDetails_TrackerWeight
GO
exec proc_CT_FACT_TrackerCompositeDetails_TrackerWholeGrains
GO
exec proc_CT_FACT_TrackerCompositeDetails_TrackerCotinine
GO
exec proc_CT_FACT_TrackerCompositeDetails_TrackerPreventiveCare
GO
exec proc_CT_FACT_TrackerCompositeDetails_TrackerTobaccoAttestation
GO
exec proc_CT_FACT_TrackerCompositeDetails_TrackerInstance_Tracker
GO
exec proc_CT_FACT_TrackerCompositeDetails_TrackerBloodSugarAndGlucose
GO
exec proc_CT_FACT_TrackerCompositeDetails_TrackerBodyMeasurements
GO
exec proc_CT_FACT_TrackerCompositeDetails_TrackerTests
GO
exec proc_CT_FACT_TrackerCompositeDetails_TrackerShots
GO
exec proc_CT_DIM_HFit_TrackerBMI_Cursor
GO