USE [Viper];
GO

/****** Object:  Table [dbo].[VIPER_MPI]    Script Date: 6/6/2016 12:21:19 PM ******/

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

SET ANSI_PADDING ON;
GO

CREATE TABLE dbo.VIPER_MPI (RUNID varchar (150) NULL , 
                            HASHKEY varchar (150) NULL , 
                            ROWNBR bigint NULL , 
                            FILEID int NULL , 
                            CLIENTID int NULL , 
                            FILEMASK varchar (150) NULL , 
                            CREATEDATE datetime NULL , 
                            MODIFIEDDATE datetime NULL , 
                            FILEDATE datetime NULL , 
                            FILENAME varchar (150) NULL , 
                            MPI int NULL , 
                            MATCH_METHOD_CODE varchar (30) NULL , 
                            MEMBER_ID varchar (15) NULL , 
                            FIRST_NAME_SOURCE varchar (50) NULL , 
                            LAST_NAME_SOURCE varchar (50) NULL , 
                            MIDDLE_INIT varchar (15) NULL , 
                            SSN_SOURCE varchar (15) NULL , 
                            SSN_STANDARDIZED varchar (15) NULL , 
                            EMPLOYEE_SSN_SOURCE varchar (15) NULL , 
                            EMPLOYEE_SSN_STANDARDIZED varchar (15) NULL , 
                            HIRE_DATE datetime NULL , 
                            DOB datetime NULL , 
                            RELATIONSHIP_SOURCE varchar (50) NULL , 
                            RELATIONSHIP_STANDARDIZED varchar (15) NULL , 
                            PERSON_TYPE varchar (50) NULL , 
                            GENDER_SOURCE varchar (15) NULL , 
                            GENDER_STANDARDIZED varchar (15) NULL , 
                            FIRST_NAME_A_STND varchar (50) NULL , 
                            FIRST_NAME_B_STND varchar (50) NULL , 
                            LAST_NAME_A_STND varchar (50) NULL , 
                            LAST_NAME_B_STND varchar (50) NULL , 
                            ADDRESS1_SOURCE varchar (150) NULL , 
                            ADDRESS2_SOURCE varchar (150) NULL , 
                            CITY_SOURCE varchar (50) NULL , 
                            STATE_SOURCE varchar (20) NULL , 
                            ZIP_SOURCE varchar (50) NULL , 
                            ADDRESS1_STANDARDIZED varchar (150) NULL , 
                            ADDRESS2_STANDARDIZED varchar (150) NULL , 
                            CITY_STANDARDIZED varchar (50) NULL , 
                            STATE_STANDARDIZED varchar (5) NULL , 
                            ZIP_STANDARDIZED varchar (15) NULL , 
                            ZIP_4_STANDARDIZED varchar (15) NULL , 
                            EMAIL varchar (150) NULL , 
                            HOME_PHONE_SOURCE varchar (15) NULL , 
                            WORK_PHONE_SOURCE varchar (15) NULL , 
                            HOME_PHONE_STANDARDIZED varchar (15) NULL , 
                            WORK_PHONE_STANDARDIZED varchar (15) NULL) 
ON [PRIMARY];

GO

SET ANSI_PADDING OFF;

GO

CREATE TYPE VIPER_MPI_Type AS TABLE (RUNID varchar (150) NULL , 
                                     HASHKEY varchar (150) NULL , 
                                     ROWNBR bigint NULL , 
                                     FILEID int NULL , 
                                     CLIENTID int NULL , 
                                     FILEMASK varchar (150) NULL , 
                                     CREATEDATE datetime NULL , 
                                     MODIFIEDDATE datetime NULL , 
                                     FILEDATE datetime NULL , 
                                     FILENAME varchar (150) NULL , 
                                     MPI int NULL , 
                                     MATCH_METHOD_CODE varchar (30) NULL , 
                                     MEMBER_ID varchar (15) NULL , 
                                     FIRST_NAME_SOURCE varchar (50) NULL , 
                                     LAST_NAME_SOURCE varchar (50) NULL , 
                                     MIDDLE_INIT varchar (15) NULL , 
                                     SSN_SOURCE varchar (15) NULL , 
                                     SSN_STANDARDIZED varchar (15) NULL , 
                                     EMPLOYEE_SSN_SOURCE varchar (15) NULL , 
                                     EMPLOYEE_SSN_STANDARDIZED varchar (15) NULL , 
                                     HIRE_DATE datetime NULL , 
                                     DOB datetime NULL , 
                                     RELATIONSHIP_SOURCE varchar (50) NULL , 
                                     RELATIONSHIP_STANDARDIZED varchar (15) NULL , 
                                     PERSON_TYPE varchar (50) NULL , 
                                     GENDER_SOURCE varchar (15) NULL , 
                                     GENDER_STANDARDIZED varchar (15) NULL , 
                                     FIRST_NAME_A_STND varchar (50) NULL , 
                                     FIRST_NAME_B_STND varchar (50) NULL , 
                                     LAST_NAME_A_STND varchar (50) NULL , 
                                     LAST_NAME_B_STND varchar (50) NULL , 
                                     ADDRESS1_SOURCE varchar (150) NULL , 
                                     ADDRESS2_SOURCE varchar (150) NULL , 
                                     CITY_SOURCE varchar (50) NULL , 
                                     STATE_SOURCE varchar (20) NULL , 
                                     ZIP_SOURCE varchar (50) NULL , 
                                     ADDRESS1_STANDARDIZED varchar (150) NULL , 
                                     ADDRESS2_STANDARDIZED varchar (150) NULL , 
                                     CITY_STANDARDIZED varchar (50) NULL , 
                                     STATE_STANDARDIZED varchar (5) NULL , 
                                     ZIP_STANDARDIZED varchar (15) NULL , 
                                     ZIP_4_STANDARDIZED varchar (15) NULL , 
                                     EMAIL varchar (150) NULL , 
                                     HOME_PHONE_SOURCE varchar (15) NULL , 
                                     WORK_PHONE_SOURCE varchar (15) NULL , 
                                     HOME_PHONE_STANDARDIZED varchar (15) NULL , 
                                     WORK_PHONE_STANDARDIZED varchar (15) NULL) ;


GO

CREATE PROCEDURE InsertFileDetails (@VIPER_MPI viper_mpi_type READONLY) 
AS
BEGIN
    INSERT INTO VIPER_MPI (RUNID , 
                           HASHKEY , 
                           ROWNBR , 
                           FILEID , 
                           CLIENTID , 
                           FILEMASK , 
                           CREATEDATE , 
                           MODIFIEDDATE , 
                           FILEDATE , 
                           FILENAME , 
                           MPI , 
                           MATCH_METHOD_CODE , 
                           MEMBER_ID , 
                           FIRST_NAME_SOURCE , 
                           LAST_NAME_SOURCE , 
                           MIDDLE_INIT , 
                           SSN_SOURCE , 
                           SSN_STANDARDIZED , 
                           EMPLOYEE_SSN_SOURCE , 
                           EMPLOYEE_SSN_STANDARDIZED , 
                           HIRE_DATE , 
                           DOB , 
                           RELATIONSHIP_SOURCE , 
                           RELATIONSHIP_STANDARDIZED , 
                           PERSON_TYPE , 
                           GENDER_SOURCE , 
                           GENDER_STANDARDIZED , 
                           FIRST_NAME_A_STND , 
                           FIRST_NAME_B_STND , 
                           LAST_NAME_A_STND , 
                           LAST_NAME_B_STND , 
                           ADDRESS1_SOURCE , 
                           ADDRESS2_SOURCE , 
                           CITY_SOURCE , 
                           STATE_SOURCE , 
                           ZIP_SOURCE , 
                           ADDRESS1_STANDARDIZED , 
                           ADDRESS2_STANDARDIZED , 
                           CITY_STANDARDIZED , 
                           STATE_STANDARDIZED , 
                           ZIP_STANDARDIZED , 
                           ZIP_4_STANDARDIZED , 
                           EMAIL , 
                           HOME_PHONE_SOURCE , 
                           WORK_PHONE_SOURCE , 
                           HOME_PHONE_STANDARDIZED , 
                           WORK_PHONE_STANDARDIZED) 
    SELECT RUNID , 
           HASHKEY , 
           ROWNBR , 
           FILEID , 
           CLIENTID , 
           FILEMASK , 
           CREATEDATE , 
           MODIFIEDDATE , 
           FILEDATE , 
           FILENAME , 
           MPI , 
           MATCH_METHOD_CODE , 
           MEMBER_ID , 
           FIRST_NAME_SOURCE , 
           LAST_NAME_SOURCE , 
           MIDDLE_INIT , 
           SSN_SOURCE , 
           SSN_STANDARDIZED , 
           EMPLOYEE_SSN_SOURCE , 
           EMPLOYEE_SSN_STANDARDIZED , 
           HIRE_DATE , 
           DOB , 
           RELATIONSHIP_SOURCE , 
           RELATIONSHIP_STANDARDIZED , 
           PERSON_TYPE , 
           GENDER_SOURCE , 
           GENDER_STANDARDIZED , 
           FIRST_NAME_A_STND , 
           FIRST_NAME_B_STND , 
           LAST_NAME_A_STND , 
           LAST_NAME_B_STND , 
           ADDRESS1_SOURCE , 
           ADDRESS2_SOURCE , 
           CITY_SOURCE , 
           STATE_SOURCE , 
           ZIP_SOURCE , 
           ADDRESS1_STANDARDIZED , 
           ADDRESS2_STANDARDIZED , 
           CITY_STANDARDIZED , 
           STATE_STANDARDIZED , 
           ZIP_STANDARDIZED , 
           ZIP_4_STANDARDIZED , 
           EMAIL , 
           HOME_PHONE_SOURCE , 
           WORK_PHONE_SOURCE , 
           HOME_PHONE_STANDARDIZED , 
           WORK_PHONE_STANDARDIZED
      FROM @VIPER_MPI;
END; 

GO