-- drop table ##HAKeyChangedData;
-- set rowcount 100000; 
SELECT
	   HAUSERSTARTED.ITEMID AS USERSTARTEDITEMID
	 , CMSUSER.USERGUID
	 , COALESCE (CT_CMS_USER.SYS_CHANGE_OPERATION, CT_CMS_USERSETTINGS.SYS_CHANGE_OPERATION, CT_CMS_SITE.SYS_CHANGE_OPERATION, CT_CMS_USERSITE.SYS_CHANGE_OPERATION, CT_HFIT_ACCOUNT.SYS_CHANGE_OPERATION, CT_BASE_HFIT_HEALTHASSESMENTUSERANSWERS.SYS_CHANGE_OPERATION, CT_HFIT_HEALTHASSESMENTUSERMODULE.SYS_CHANGE_OPERATION, CT_HFIT_HEALTHASSESMENTUSERQUESTION.SYS_CHANGE_OPERATION, CT_HFIT_HEALTHASSESMENTUSERQUESTIONGROUPRESULTS.SYS_CHANGE_OPERATION, CT_HFIT_HEALTHASSESMENTUSERRISKAREA.SYS_CHANGE_OPERATION, CT_HFIT_HEALTHASSESMENTUSERRISKCATEGORY.SYS_CHANGE_OPERATION, CT_BASE_HFIT_HEALTHASSESMENTUSERSTARTED.SYS_CHANGE_OPERATION) AS CHANGETYPE
	 , CAST (HASHBYTES ('sha1', ISNULL (CAST (HAUSERSTARTED.ITEMID AS nvarchar (100)) , '-') + ISNULL (CAST (VHAJ.NODEGUID AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERSTARTED.USERID AS nvarchar (100)) , '-') + ISNULL (CAST (CMSUSER.USERGUID AS nvarchar (100)) , '-') + ISNULL (CAST (USERSETTINGS.HFITUSERMPINUMBER AS nvarchar (100)) , '-') + ISNULL (CAST (CMSSITE.SITEGUID AS nvarchar (100)) , '-') + ISNULL (CAST (ACCT.ACCOUNTID AS nvarchar (100)) , '-') + ISNULL (CAST (ACCT.ACCOUNTCD AS nvarchar (100)) , '-') + ISNULL (CAST (ACCT.ACCOUNTNAME AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERSTARTED.HASTARTEDDT AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERSTARTED.HACOMPLETEDDT AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERMODULE.ITEMID AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERMODULE.CODENAME AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERMODULE.HAMODULENODEGUID AS nvarchar (100)) , '-') + ISNULL (CAST (VHAJ.NODEGUID AS nvarchar (100)) , '-') + ISNULL (CAST (HARISKCATEGORY.ITEMID AS nvarchar (100)) , '-') + ISNULL (CAST (HARISKCATEGORY.CODENAME AS nvarchar (100)) , '-') + ISNULL (CAST (HARISKCATEGORY.HARISKCATEGORYNODEGUID AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERRISKAREA.ITEMID AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERRISKAREA.CODENAME AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERRISKAREA.HARISKAREANODEGUID AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERQUESTION.ITEMID AS nvarchar (100)) , '-') + ISNULL (LEFT (HAQUESTIONSVIEW.TITLE, 1000) , '-') + ISNULL (CAST (HAUSERQUESTION.HAQUESTIONNODEGUID AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERQUESTION.CODENAME AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERQUESTION.HAQUESTIONNODEGUID AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERANSWERS.ITEMID AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERANSWERS.HAANSWERNODEGUID AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERANSWERS.CODENAME AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERANSWERS.HAANSWERVALUE AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERMODULE.HAMODULESCORE AS nvarchar (100)) , '-') + ISNULL (CAST (HARISKCATEGORY.HARISKCATEGORYSCORE AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERRISKAREA.HARISKAREASCORE AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERQUESTION.HAQUESTIONSCORE AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERANSWERS.HAANSWERPOINTS AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERQUESTIONGROUPRESULTS.POINTRESULTS AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERANSWERS.UOMCODE AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERSTARTED.HASCORE AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERMODULE.PREWEIGHTEDSCORE AS nvarchar (100)) , '-') + ISNULL (CAST (HARISKCATEGORY.PREWEIGHTEDSCORE AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERRISKAREA.PREWEIGHTEDSCORE AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERQUESTION.PREWEIGHTEDSCORE AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERQUESTIONGROUPRESULTS.CODENAME AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERANSWERS.ITEMCREATEDWHEN AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERANSWERS.ITEMMODIFIEDWHEN AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERQUESTION.ISPROFESSIONALLYCOLLECTED AS nvarchar (100)) , '-') + ISNULL (CAST (HARISKCATEGORY.ITEMMODIFIEDWHEN AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERRISKAREA.ITEMMODIFIEDWHEN AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERQUESTION.ITEMMODIFIEDWHEN AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERANSWERS.ITEMMODIFIEDWHEN AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERSTARTED.HAPAPERFLG AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERSTARTED.HATELEPHONICFLG AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERSTARTED.HASTARTEDMODE AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERSTARTED.HACOMPLETEDMODE AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERSTARTED.HACAMPAIGNNODEGUID AS nvarchar (100)) , '-') + ISNULL (CAST (VHCJ.HACAMPAIGNID AS nvarchar (100)) , '-') + ISNULL (CAST (HAUSERANSWERS.ITEMMODIFIEDWHEN AS nvarchar (100)) , '-')) AS varchar (100)) AS HASHCODE
	 , CAST (HASHBYTES ('sha1', ISNULL (CAST (HAUSERSTARTED.ITEMID AS varchar (50)) , '-') + ISNULL (CAST (VHAJ.NODEGUID AS varchar (50)) , '-') + ISNULL (CAST (USERGUID AS varchar (50)) , '-') + ISNULL (CAST (SITEGUID AS varchar (50)) , '-') + ISNULL (CAST (ACCT.ACCOUNTID AS varchar (50)) , '-') + ISNULL (CAST (ACCOUNTCD AS varchar (50)) , '-') + ISNULL (CAST (HAUSERMODULE.ITEMID AS varchar (50)) , '-') + ISNULL (CAST (HAMODULENODEGUID AS varchar (50)) , '-') + ISNULL (CAST (VHAJ.NODEGUID AS varchar (50)) , '-') + ISNULL (CAST (HARISKCATEGORY.ITEMID AS varchar (50)) , '-') + ISNULL (CAST (HARISKCATEGORYNODEGUID AS varchar (50)) , '-') + ISNULL (CAST (HARISKCATEGORY.CODENAME AS varchar (100)) , '-') + ISNULL (CAST (HARISKCATEGORY.HARISKCATEGORYNODEGUID AS varchar (50)) , '-') + ISNULL (CAST (HAUSERRISKAREA.ITEMID AS varchar (50)) , '-') + ISNULL (CAST (HARISKAREANODEGUID AS varchar (50)) , '-') + ISNULL (CAST (HAUSERRISKAREA.CODENAME AS varchar (50)) , '-') + ISNULL (CAST (HAUSERQUESTION.ITEMID AS varchar (50)) , '-') + ISNULL (CAST (HAUSERQUESTION.HAQUESTIONNODEGUID AS varchar (50)) , '-') + ISNULL (CAST (HAUSERQUESTION.CODENAME AS varchar (50)) , '-') + ISNULL (CAST (HAQUESTIONNODEGUID AS varchar (50)) , '-') + ISNULL (CAST (HAUSERANSWERS.ITEMID AS varchar (50)) , '-') + ISNULL (CAST (HAANSWERNODEGUID AS varchar (50)) , '-') + ISNULL (CAST (HAUSERSTARTED.HACAMPAIGNNODEGUID AS varchar (50)) , '-')) AS varchar (100)) AS PKHASHCODE
	 , COALESCE (CT_CMS_USER.USERID, CT_CMS_USERSETTINGS.USERSETTINGSID, CT_CMS_SITE.SITEID, CT_CMS_USERSITE.USERSITEID, CT_HFIT_ACCOUNT.ACCOUNTID, CT_BASE_HFIT_HEALTHASSESMENTUSERANSWERS.ITEMID, CT_HFIT_HEALTHASSESMENTUSERMODULE.ITEMID, CT_HFIT_HEALTHASSESMENTUSERQUESTION.ITEMID, CT_HFIT_HEALTHASSESMENTUSERQUESTIONGROUPRESULTS.ITEMID, CT_HFIT_HEALTHASSESMENTUSERRISKAREA.ITEMID, CT_HFIT_HEALTHASSESMENTUSERRISKCATEGORY.ITEMID, CT_BASE_HFIT_HEALTHASSESMENTUSERSTARTED.ITEMID) AS CHANGED_FLG INTO
																																																																																																																												  ##HAKeyChangedData
	   FROM
			BASE_HFIT_HEALTHASSESMENTUSERSTARTED AS HAUSERSTARTED
				INNER JOIN BASE_CMS_USER AS CMSUSER
					ON HAUSERSTARTED.USERID = CMSUSER.USERID
				   AND HAUSERSTARTED.SVR = CMSUSER.SVR
				   AND HAUSERSTARTED.DBNAME = CMSUSER.DBNAME
				 INNER JOIN BASE_CMS_USERSETTINGS AS USERSETTINGS
					ON USERSETTINGS.USERSETTINGSUSERID = CMSUSER.USERID
				   AND HFITUSERMPINUMBER >= 0
				   AND HFITUSERMPINUMBER IS NOT NULL
				   AND USERSETTINGS.SVR = CMSUSER.SVR
				   AND USERSETTINGS.DBNAME = CMSUSER.DBNAME
				 INNER JOIN BASE_CMS_USERSITE AS USERSITE
					ON CMSUSER.USERID = USERSITE.USERID
				   AND CMSUSER.SVR = USERSITE.SVR
				   AND CMSUSER.DBNAME = USERSITE.DBNAME
				 INNER JOIN DBO.BASE_CMS_SITE AS CMSSITE
					ON USERSITE.SITEID = CMSSITE.SITEID
				   AND USERSITE.SVR = CMSSITE.SVR
				   AND USERSITE.DBNAME = CMSSITE.DBNAME
				 INNER JOIN DBO.BASE_HFIT_ACCOUNT AS ACCT
					ON ACCT.SITEID = CMSSITE.SITEID
				   AND ACCT.SVR = CMSSITE.SVR
				   AND ACCT.DBNAME = CMSSITE.DBNAME
				 INNER JOIN BASE_HFIT_HEALTHASSESMENTUSERMODULE AS HAUSERMODULE
					ON HAUSERSTARTED.ITEMID = HAUSERMODULE.HASTARTEDITEMID
				   AND HAUSERSTARTED.SVR = HAUSERMODULE.SVR
				   AND HAUSERSTARTED.DBNAME = HAUSERMODULE.DBNAME
				 INNER JOIN FACT_EDW_VIEW_HFIT_HACAMPAIGN_JOINED AS VHCJ
					ON VHCJ.NODEGUID = HAUSERSTARTED.HACAMPAIGNNODEGUID
				   AND VHCJ.NODESITEID = USERSITE.SITEID
				   AND VHCJ.DOCUMENTCULTURE = 'en-US'
				   AND VHCJ.SVR = USERSITE.SVR
				   AND VHCJ.DBNAME = USERSITE.DBNAME
				 INNER JOIN FACT_EDW_VIEW_HFIT_HEALTHASSESSMENT_JOINED AS VHAJ
					ON VHAJ.DOCUMENTID = VHCJ.HEALTHASSESSMENTID
				   AND VHAJ.SVR = VHCJ.SVR
				   AND VHAJ.DBNAME = VHCJ.DBNAME
				 INNER JOIN BASE_HFIT_HEALTHASSESMENTUSERRISKCATEGORY AS HARISKCATEGORY
					ON HAUSERMODULE.ITEMID = HARISKCATEGORY.HAMODULEITEMID
				   AND HAUSERMODULE.SVR = HARISKCATEGORY.SVR
				   AND HAUSERMODULE.DBNAME = HARISKCATEGORY.DBNAME
				 INNER JOIN BASE_HFIT_HEALTHASSESMENTUSERRISKAREA AS HAUSERRISKAREA
					ON HARISKCATEGORY.ITEMID = HAUSERRISKAREA.HARISKCATEGORYITEMID
				   AND HARISKCATEGORY.SVR = HAUSERRISKAREA.SVR
				   AND HARISKCATEGORY.DBNAME = HAUSERRISKAREA.DBNAME
				 INNER JOIN BASE_HFit_HealthAssesmentUserQuestion AS HAUSERQUESTION
					ON HAUSERRISKAREA.ITEMID = HAUSERQUESTION.HARISKAREAITEMID
				   AND HAUSERRISKAREA.SVR = HAUSERQUESTION.SVR
				   AND HAUSERRISKAREA.DBNAME = HAUSERQUESTION.DBNAME
				 INNER JOIN FACT_VIEW_EDW_HEALTHASSESMENTQUESTIONS AS HAQUESTIONSVIEW
					ON HAUSERQUESTION.HAQUESTIONNODEGUID = HAQUESTIONSVIEW.NODEGUID
				   AND HAUSERQUESTION.SVR = HAQUESTIONSVIEW.SVR
				   AND HAUSERQUESTION.DBNAME = HAQUESTIONSVIEW.DBNAME
				 LEFT OUTER JOIN BASE_HFIT_HEALTHASSESMENTUSERQUESTIONGROUPRESULTS AS HAUSERQUESTIONGROUPRESULTS
					ON HAUSERRISKAREA.ITEMID = HAUSERQUESTIONGROUPRESULTS.HARISKAREAITEMID
				   AND HAUSERRISKAREA.SVR = HAUSERQUESTIONGROUPRESULTS.SVR
				   AND HAUSERRISKAREA.DBNAME = HAUSERQUESTIONGROUPRESULTS.DBNAME
				 INNER JOIN BASE_HFit_HEALTHASSESMENTUSERANSWERS AS HAUSERANSWERS
					ON HAUSERQUESTION.ITEMID = HAUSERANSWERS.HAQUESTIONITEMID
				   AND HAUSERQUESTION.SVR = HAUSERANSWERS.SVR
				   AND HAUSERQUESTION.DBNAME = HAUSERANSWERS.DBNAME --Add in the change tracking data
				 LEFT JOIN CHANGETABLE (CHANGES BASE_CMS_USERSETTINGS, NULL) AS CT_CMS_USERSETTINGS
					ON USERSETTINGS.USERSETTINGSID = CT_CMS_USERSETTINGS.USERSETTINGSID
				   AND USERSETTINGS.SVR = CT_CMS_USERSETTINGS.SVR
				   AND USERSETTINGS.DBNAME = CT_CMS_USERSETTINGS.DBNAME
				 LEFT JOIN CHANGETABLE (CHANGES BASE_CMS_USER, NULL) AS CT_CMS_USER
					ON CMSUSER.USERID = CT_CMS_USER.USERID
				   AND CMSUSER.SVR = CT_CMS_USER.SVR
				   AND CMSUSER.DBNAME = CT_CMS_USER.DBNAME
				 LEFT OUTER JOIN CHANGETABLE (CHANGES BASE_CMS_SITE, NULL) AS CT_CMS_SITE
					ON CMSSITE.SITEID = CT_CMS_SITE.SITEID
				   AND CMSSITE.SVR = CT_CMS_SITE.SVR
				   AND CMSSITE.DBNAME = CT_CMS_SITE.DBNAME
				 LEFT OUTER JOIN CHANGETABLE (CHANGES BASE_CMS_USERSITE, NULL) AS CT_CMS_USERSITE
					ON USERSITE.USERSITEID = CT_CMS_USERSITE.USERSITEID
				   AND USERSITE.SVR = CT_CMS_USERSITE.SVR
				   AND USERSITE.DBNAME = CT_CMS_USERSITE.DBNAME
				 LEFT OUTER JOIN CHANGETABLE (CHANGES BASE_HFIT_ACCOUNT, NULL) AS CT_HFIT_ACCOUNT
					ON ACCT.ACCOUNTID = CT_HFIT_ACCOUNT.ACCOUNTID
				   AND ACCT.SVR = CT_HFIT_ACCOUNT.SVR
				   AND ACCT.DBNAME = CT_HFIT_ACCOUNT.DBNAME
				 LEFT OUTER JOIN CHANGETABLE (CHANGES BASE_HFIT_HACAMPAIGN, NULL) AS CT_HFIT_HACAMPAIGN
					ON VHCJ.HACAMPAIGNID = CT_HFIT_HACAMPAIGN.HACAMPAIGNID
				   AND VHCJ.SVR = CT_HFIT_HACAMPAIGN.SVR
				   AND VHCJ.DBNAME = CT_HFIT_HACAMPAIGN.DBNAME
				 LEFT OUTER JOIN CHANGETABLE (CHANGES BASE_HFIT_HEALTHASSESMENTUSERANSWERS, NULL) AS CT_BASE_HFIT_HEALTHASSESMENTUSERANSWERS
					ON HAUSERANSWERS.ITEMID = CT_BASE_HFIT_HEALTHASSESMENTUSERANSWERS.ITEMID
				   AND HAUSERANSWERS.SVR = CT_BASE_HFIT_HEALTHASSESMENTUSERANSWERS.SVR
				   AND HAUSERANSWERS.DBNAME = CT_BASE_HFIT_HEALTHASSESMENTUSERANSWERS.DBNAME
				 LEFT OUTER JOIN CHANGETABLE (CHANGES BASE_HFIT_HEALTHASSESMENTUSERMODULE, NULL) AS CT_HFIT_HEALTHASSESMENTUSERMODULE
					ON HAUSERMODULE.ITEMID = CT_HFIT_HEALTHASSESMENTUSERMODULE.ITEMID
				   AND HAUSERMODULE.SVR = CT_HFIT_HEALTHASSESMENTUSERMODULE.SVR
				   AND HAUSERMODULE.DBNAME = CT_HFIT_HEALTHASSESMENTUSERMODULE.DBNAME
				 LEFT OUTER JOIN CHANGETABLE (CHANGES BASE_HFIT_HEALTHASSESMENTUSERQUESTION, NULL) AS CT_HFIT_HEALTHASSESMENTUSERQUESTION
					ON HAUSERQUESTION.ITEMID = CT_HFIT_HEALTHASSESMENTUSERQUESTION.ITEMID
				   AND HAUSERQUESTION.SVR = CT_HFIT_HEALTHASSESMENTUSERQUESTION.SVR
				   AND HAUSERQUESTION.DBNAME = CT_HFIT_HEALTHASSESMENTUSERQUESTION.DBNAME
				 LEFT OUTER JOIN CHANGETABLE (CHANGES BASE_HFIT_HEALTHASSESMENTUSERQUESTIONGROUPRESULTS, NULL) AS CT_HFIT_HEALTHASSESMENTUSERQUESTIONGROUPRESULTS
					ON HAUSERQUESTIONGROUPRESULTS.ITEMID = CT_HFIT_HEALTHASSESMENTUSERQUESTIONGROUPRESULTS.ITEMID
				   AND HAUSERQUESTIONGROUPRESULTS.SVR = CT_HFIT_HEALTHASSESMENTUSERQUESTIONGROUPRESULTS.SVR
				   AND HAUSERQUESTIONGROUPRESULTS.DBNAME = CT_HFIT_HEALTHASSESMENTUSERQUESTIONGROUPRESULTS.DBNAME
				 LEFT OUTER JOIN CHANGETABLE (CHANGES BASE_HFIT_HEALTHASSESMENTUSERRISKAREA, NULL) AS CT_HFIT_HEALTHASSESMENTUSERRISKAREA
					ON HAUSERRISKAREA.ITEMID = CT_HFIT_HEALTHASSESMENTUSERRISKAREA.ITEMID
				   AND HAUSERRISKAREA.SVR = CT_HFIT_HEALTHASSESMENTUSERRISKAREA.SVR
				   AND HAUSERRISKAREA.DBNAME = CT_HFIT_HEALTHASSESMENTUSERRISKAREA.DBNAME
				 LEFT OUTER JOIN CHANGETABLE (CHANGES BASE_HFIT_HEALTHASSESMENTUSERRISKCATEGORY, NULL) AS CT_HFIT_HEALTHASSESMENTUSERRISKCATEGORY
					ON HARISKCATEGORY.ITEMID = CT_HFIT_HEALTHASSESMENTUSERRISKCATEGORY.ITEMID
				   AND HARISKCATEGORY.SVR = CT_HFIT_HEALTHASSESMENTUSERRISKCATEGORY.SVR
				   AND HARISKCATEGORY.DBNAME = CT_HFIT_HEALTHASSESMENTUSERRISKCATEGORY.DBNAME
				 LEFT OUTER JOIN CHANGETABLE (CHANGES BASE_HFIT_HEALTHASSESMENTUSERSTARTED, NULL) AS CT_BASE_HFIT_HEALTHASSESMENTUSERSTARTED
					ON HAUSERSTARTED.ITEMID = CT_BASE_HFIT_HEALTHASSESMENTUSERSTARTED.ITEMID
				   AND HAUSERSTARTED.SVR = CT_BASE_HFIT_HEALTHASSESMENTUSERSTARTED.SVR
				   AND HAUSERSTARTED.DBNAME = CT_BASE_HFIT_HEALTHASSESMENTUSERSTARTED.DBNAME
	   WHERE USERSETTINGS.HFITUSERMPINUMBER NOT IN (
													SELECT
														   REJECTMPICODE
														   FROM BASE_HFIT_LKP_EDW_REJECTMPI) ; 
