
GO
PRINT 'Executing proc_CT_HA_AddUpdatedRecs.sql';
GO
IF EXISTS ( SELECT
                   name
                   FROM sys.procedures
                   WHERE name = 'proc_CT_HA_AddUpdatedRecs') 
    BEGIN
        DROP PROCEDURE
             proc_CT_HA_AddUpdatedRecs;
    END;
GO

-- exec proc_CT_HA_AddUpdatedRecs
CREATE PROCEDURE proc_CT_HA_AddUpdatedRecs
AS
BEGIN

    DECLARE
    @RUNDATE AS  datetime2 ( 7) = GETDATE () ;

    UPDATE S
           SET
               S.UserStartedITEMID = T.UserStartedITEMID
             ,S.HEALTHASSESMENTUserStartedNODEGUID = T.HEALTHASSESMENTUserStartedNODEGUID
             ,S.USERID = T.USERID
             ,S.USERGUID = T.USERGUID
             ,S.HFITUSERMPINUMBER = T.HFITUSERMPINUMBER
             ,S.SITEGUID = T.SITEGUID
             ,S.ACCOUNTID = T.ACCOUNTID
             ,S.ACCOUNTCD = T.ACCOUNTCD
             ,S.ACCOUNTNAME = T.ACCOUNTNAME
             ,S.HASTARTEDDT = T.HASTARTEDDT
             ,S.HACOMPLETEDDT = T.HACOMPLETEDDT
             ,S.USERMODULEITEMID = T.USERMODULEITEMID
             ,S.USERMODULECODENAME = T.USERMODULECODENAME
             ,S.HAMODULENODEGUID = T.HAMODULENODEGUID
             ,S.CMSNODEGUID = T.CMSNODEGUID
             ,S.HAMODULEVERSIONID = T.HAMODULEVERSIONID
             ,S.USERRISKCATEGORYITEMID = T.USERRISKCATEGORYITEMID
             ,S.USERRISKCATEGORYCODENAME = T.USERRISKCATEGORYCODENAME
             ,S.HARISKCATEGORYNODEGUID = T.HARISKCATEGORYNODEGUID
             ,S.HARISKCATEGORYVERSIONID = T.HARISKCATEGORYVERSIONID
             ,S.USERRISKAREAITEMID = T.USERRISKAREAITEMID
             ,S.USERRISKAREACODENAME = T.USERRISKAREACODENAME
             ,S.HARISKAREANODEGUID = T.HARISKAREANODEGUID
             ,S.HARISKAREAVERSIONID = T.HARISKAREAVERSIONID
             ,S.USERQUESTIONITEMID = T.USERQUESTIONITEMID
             ,S.TITLE = T.TITLE
             ,S.HAQUESTIONGUID = T.HAQUESTIONGUID
             ,S.USERQUESTIONCODENAME = T.USERQUESTIONCODENAME
             ,S.HAQUESTIONDOCUMENTID = T.HAQUESTIONDOCUMENTID
             ,S.HAQUESTIONVERSIONID = T.HAQUESTIONVERSIONID
             ,S.HAQUESTIONNODEGUID = T.HAQUESTIONNODEGUID
             ,S.USERANSWERITEMID = T.USERANSWERITEMID
             ,S.HAANSWERNODEGUID = T.HAANSWERNODEGUID
             ,S.HAANSWERVERSIONID = T.HAANSWERVERSIONID
             ,S.USERANSWERCODENAME = T.USERANSWERCODENAME
             ,S.HAANSWERVALUE = T.HAANSWERVALUE
             ,S.HAMODULESCORE = T.HAMODULESCORE
             ,S.HARISKCATEGORYSCORE = T.HARISKCATEGORYSCORE
             ,S.HARISKAREASCORE = T.HARISKAREASCORE
             ,S.HAQUESTIONSCORE = T.HAQUESTIONSCORE
             ,S.HAANSWERPOINTS = T.HAANSWERPOINTS
             ,S.POINTRESULTS = T.POINTRESULTS
             ,S.UOMCODE = T.UOMCODE
             ,S.HASCORE = T.HASCORE
             ,S.MODULEPREWEIGHTEDSCORE = T.MODULEPREWEIGHTEDSCORE
             ,S.RISKCATEGORYPREWEIGHTEDSCORE = T.RISKCATEGORYPREWEIGHTEDSCORE
             ,S.RISKAREAPREWEIGHTEDSCORE = T.RISKAREAPREWEIGHTEDSCORE
             ,S.QUESTIONPREWEIGHTEDSCORE = T.QUESTIONPREWEIGHTEDSCORE
             ,S.QUESTIONGROUPCODENAME = T.QUESTIONGROUPCODENAME
             ,S.ITEMCREATEDWHEN = T.ITEMCREATEDWHEN
             ,S.ITEMMODIFIEDWHEN = T.ITEMMODIFIEDWHEN
             ,S.ISPROFESSIONALLYCOLLECTED = T.ISPROFESSIONALLYCOLLECTED
             ,S.HARISKCATEGORY_ITEMMODIFIEDWHEN = T.HARISKCATEGORY_ITEMMODIFIEDWHEN
             ,S.HAUSERRISKAREA_ITEMMODIFIEDWHEN = T.HAUSERRISKAREA_ITEMMODIFIEDWHEN
             ,S.HAUSERQUESTION_ITEMMODIFIEDWHEN = T.HAUSERQUESTION_ITEMMODIFIEDWHEN
             ,S.HAUSERANSWERS_ITEMMODIFIEDWHEN = T.HAUSERANSWERS_ITEMMODIFIEDWHEN
             ,S.HAPAPERFLG = T.HAPAPERFLG
             ,S.HATELEPHONICFLG = T.HATELEPHONICFLG
             ,S.HASTARTEDMODE = T.HASTARTEDMODE
             ,S.HACOMPLETEDMODE = T.HACOMPLETEDMODE
             ,S.DOCUMENTCULTURE_VHCJ = T.DOCUMENTCULTURE_VHCJ
             ,S.DOCUMENTCULTURE_HAQUESTIONSVIEW = T.DOCUMENTCULTURE_HAQUESTIONSVIEW
             ,S.CAMPAIGNNODEGUID = T.CAMPAIGNNODEGUID
             ,S.HACAMPAIGNID = T.HACAMPAIGNID
             ,S.HASHCODE = T.HASHCODE
             ,S.CHANGED_FLG = T.CHANGED_FLG
             ,S.HEALTHASSESSMENTTYPE = T.HEALTHASSESSMENTTYPE

             ,S.HAUserStarted_LASTMODIFIED = T.HAUserStarted_LASTMODIFIED
             ,S.CMSUSER_LASTMODIFIED = T.CMSUSER_LASTMODIFIED
             ,S.USERSETTINGS_LASTMODIFIED = T.USERSETTINGS_LASTMODIFIED
             ,S.USERSITE_LASTMODIFIED = T.USERSITE_LASTMODIFIED
             ,S.CMSSITE_LASTMODIFIED = T.CMSSITE_LASTMODIFIED
             ,S.ACCT_LASTMODIFIED = T.ACCT_LASTMODIFIED
             ,S.HAUSERMODULE_LASTMODIFIED = T.HAUSERMODULE_LASTMODIFIED
             ,S.VHCJ_LASTMODIFIED = T.VHCJ_LASTMODIFIED
             ,S.VHAJ_LASTMODIFIED = T.VHAJ_LASTMODIFIED
             ,S.HARISKCATEGORY_LASTMODIFIED = T.HARISKCATEGORY_LASTMODIFIED
             ,S.HAUSERRISKAREA_LASTMODIFIED = T.HAUSERRISKAREA_LASTMODIFIED
             ,S.HAUSERQUESTION_LASTMODIFIED = T.HAUSERQUESTION_LASTMODIFIED
             ,S.HAQUESTIONSVIEW_LASTMODIFIED = T.HAQUESTIONSVIEW_LASTMODIFIED
             ,S.HAUSERQUESTIONGROUPRESULTS_LASTMODIFIED = T.HAUSERQUESTIONGROUPRESULTS_LASTMODIFIED
             ,S.HAUSERANSWERS_LASTMODIFIED = T.HAUSERANSWERS_LASTMODIFIED
             ,S.HAUserStarted_LastUpdateID = T.HAUserStarted_LastUpdateID
             ,S.CMSUSER_LastUpdateID = T.CMSUSER_LastUpdateID
             ,S.USERSETTINGS_LastUpdateID = T.USERSETTINGS_LastUpdateID
             ,S.USERSITE_LastUpdateID = T.USERSITE_LastUpdateID
             ,S.ACCT_LastUpdateID = T.ACCT_LastUpdateID
             ,S.HAUSERMODULE_LastUpdateID = T.HAUSERMODULE_LastUpdateID
             ,S.VHCJ_LastUpdateID = T.VHCJ_LastUpdateID
             ,S.VHAJ_LastUpdateID = T.VHAJ_LastUpdateID
             ,S.HARISKCATEGORY_LastUpdateID = T.HARISKCATEGORY_LastUpdateID
             ,S.HAUSERRISKAREA_LastUpdateID = T.HAUSERRISKAREA_LastUpdateID
             ,S.HAUSERQUESTION_LastUpdateID = T.HAUSERQUESTION_LastUpdateID
             ,S.HAQUESTIONSVIEW_LastUpdateID = T.HAQUESTIONSVIEW_LastUpdateID
             ,S.HAUSERQUESTIONGROUPRESULTS_LastUpdateID = T.HAUSERQUESTIONGROUPRESULTS_LastUpdateID
             ,S.HAUSERANSWERS_LastUpdateID = T.HAUSERANSWERS_LastUpdateID

             ,S.DELETEFLG = T.DELETEFLG
             ,S.SVR = T.SVR
             ,S.DBNAME = T.DBNAME

             ,S.ConvertedToCentralTime = NULL
             ,S.LastModifiedDate = GETDATE () 
             ,S.RowNbr = NULL
             ,S.DeletedFlg = NULL
             ,S.TimeZone = NULL
             ,S.PKHashCode = T.PKHashCode
		   ,S.ChangeType = 'U'
               FROM
               ##HealthAssessmentData AS T
                   JOIN
                   FACT_MART_EDW_HealthAssesment AS S
                       ON
                       S.UserStartedItemID = T.UserStartedItemID
                   AND S.UserGUID = T.UserGUID
                   AND S.PKHashCode = T.PKHashCode
                   AND S.HashCode != T.HashCode;

    DECLARE
    @iInserts AS int = @@ROWCOUNT;
    PRINT 'Updated Record Count: ' + CAST ( @iInserts AS nvarchar (50)) ;
    RETURN @iInserts;
END;

GO
PRINT 'Executed proc_CT_HA_AddUpdatedRecs.sql';
GO
