
GO
PRINT 'Executing proc_EDW_Reload_EDW_HealthAssessment.sql';
GO

IF EXISTS (SELECT
                  name
                  FROM sys.procedures
                  WHERE name = 'proc_EDW_Reload_EDW_HealthAssessment') 
    BEGIN
        DROP PROCEDURE
             proc_EDW_Reload_EDW_HealthAssessment
    END;

GO
-- exec proc_EDW_Reload_EDW_HealthAssessment
CREATE PROCEDURE proc_EDW_Reload_EDW_HealthAssessment
AS
BEGIN

    DECLARE @i AS bigint = 0;
    truncate TABLE DIM_EDW_HealthAssessment;

INSERT INTO DIM_EDW_HealthAssessment
(
     UserStartedITEMID
      , HEALTHASSESMENTUserStartedNODEGUID 
      , USERID 
      , USERGUID 
      , HFITUSERMPINUMBER 
      , SITEGUID 
      , ACCOUNTID 
      , ACCOUNTCD 
      , ACCOUNTNAME 
      , HASTARTEDDT 
      , HACOMPLETEDDT 
      , USERMODULEITEMID 
      , USERMODULECODENAME 
      , HAMODULENODEGUID 
      , CMSNODEGUID 
      , HAMODULEVERSIONID 
      , USERRISKCATEGORYITEMID 
      , USERRISKCATEGORYCODENAME 
      , HARISKCATEGORYNODEGUID 
      , HARISKCATEGORYVERSIONID 
      , USERRISKAREAITEMID 
      , USERRISKAREACODENAME 
      , HARISKAREANODEGUID 
      , HARISKAREAVERSIONID 
      , USERQUESTIONITEMID 
      , TITLE 
      , HAQUESTIONGUID 
      , USERQUESTIONCODENAME 
      , HAQUESTIONDOCUMENTID 
      , HAQUESTIONVERSIONID 
      , HAQUESTIONNODEGUID 
      , USERANSWERITEMID 
      , HAANSWERNODEGUID 
      , HAANSWERVERSIONID 
      , USERANSWERCODENAME 
      , HAANSWERVALUE 
      , HAMODULESCORE 
      , HARISKCATEGORYSCORE 
      , HARISKAREASCORE 
      , HAQUESTIONSCORE 
      , HAANSWERPOINTS 
      , POINTRESULTS 
      , UOMCODE 
      , HASCORE 
      , MODULEPREWEIGHTEDSCORE 
      , RISKCATEGORYPREWEIGHTEDSCORE 
      , RISKAREAPREWEIGHTEDSCORE 
      , QUESTIONPREWEIGHTEDSCORE 
      , QUESTIONGROUPCODENAME 
      , ITEMCREATEDWHEN 
      , ITEMMODIFIEDWHEN 
      , ISPROFESSIONALLYCOLLECTED 
      , HARISKCATEGORY_ITEMMODIFIEDWHEN 
      , HAUSERRISKAREA_ITEMMODIFIEDWHEN 
      , HAUSERQUESTION_ITEMMODIFIEDWHEN 
      , HAUSERANSWERS_ITEMMODIFIEDWHEN 
      , HAPAPERFLG 
      , HATELEPHONICFLG 
      , HASTARTEDMODE 
      , HACOMPLETEDMODE 
      , DOCUMENTCULTURE_VHCJ 
      , DOCUMENTCULTURE_HAQUESTIONSVIEW 
      , CAMPAIGNNODEGUID 
      , HACAMPAIGNID 
      , HASHCODE 
      , PKHASHCODE 
      , CHANGED_FLG 
      , LASTMODIFIEDDATE 
      , HEALTHASSESSMENTTYPE 
      --, HAUserStarted_LASTMODIFIED 
      --, CMSUSER_LASTMODIFIED 
      --, USERSETTINGS_LASTMODIFIED 
      --, USERSITE_LASTMODIFIED 
      --, CMSSITE_LASTMODIFIED 
      --, ACCT_LASTMODIFIED 
      --, HAUSERMODULE_LASTMODIFIED 
      --, VHCJ_LASTMODIFIED 
      --, VHAJ_LASTMODIFIED 
      --, HARISKCATEGORY_LASTMODIFIED 
      --, HAUSERRISKAREA_LASTMODIFIED 
      --, HAUSERQUESTION_LASTMODIFIED 
      --, HAQUESTIONSVIEW_LASTMODIFIED 
      --, HAUSERQUESTIONGROUPRESULTS_LASTMODIFIED 
      --, HAUSERANSWERS_LASTMODIFIED 
      --, HAUserStarted_LastUpdateID 
      --, CMSUSER_LastUpdateID 
      --, USERSETTINGS_LastUpdateID 
      --, USERSITE_LastUpdateID 
      --, ACCT_LastUpdateID 
      --, HAUSERMODULE_LastUpdateID 
      --, VHCJ_LastUpdateID 
      --, VHAJ_LastUpdateID 
      --, HARISKCATEGORY_LastUpdateID 
      --, HAUSERRISKAREA_LastUpdateID 
      --, HAUSERQUESTION_LastUpdateID 
      --, HAQUESTIONSVIEW_LastUpdateID 
      --, HAUSERQUESTIONGROUPRESULTS_LastUpdateID 
      --, HAUSERANSWERS_LastUpdateID 
      --, LASTUPDATEID 
      --, DELETEFLG 
      , SVR 
      , DBNAME 
      , DELETEDFLG 
      , ChangeType )
 SELECT 
     UserStartedITEMID
     , HEALTHASSESMENTUserStartedNODEGUID 
     , USERID 
     , USERGUID 
     , HFITUSERMPINUMBER 
     , SITEGUID 
     , ACCOUNTID 
     , ACCOUNTCD 
     , ACCOUNTNAME 
     , HASTARTEDDT 
     , HACOMPLETEDDT 
     , USERMODULEITEMID 
     , USERMODULECODENAME 
     , HAMODULENODEGUID 
     , CMSNODEGUID 
     , HAMODULEVERSIONID 
     , USERRISKCATEGORYITEMID 
     , USERRISKCATEGORYCODENAME 
     , HARISKCATEGORYNODEGUID 
     , HARISKCATEGORYVERSIONID 
     , USERRISKAREAITEMID 
     , USERRISKAREACODENAME 
     , HARISKAREANODEGUID 
     , HARISKAREAVERSIONID 
     , USERQUESTIONITEMID 
     , TITLE 
     , HAQUESTIONGUID 
     , USERQUESTIONCODENAME 
     , HAQUESTIONDOCUMENTID 
     , HAQUESTIONVERSIONID 
     , HAQUESTIONNODEGUID 
     , USERANSWERITEMID 
     , HAANSWERNODEGUID 
     , HAANSWERVERSIONID 
     , USERANSWERCODENAME 
     , HAANSWERVALUE 
     , HAMODULESCORE 
     , HARISKCATEGORYSCORE 
     , HARISKAREASCORE 
     , HAQUESTIONSCORE 
     , HAANSWERPOINTS 
     , POINTRESULTS 
     , UOMCODE 
     , HASCORE 
     , MODULEPREWEIGHTEDSCORE 
     , RISKCATEGORYPREWEIGHTEDSCORE 
     , RISKAREAPREWEIGHTEDSCORE 
     , QUESTIONPREWEIGHTEDSCORE 
     , QUESTIONGROUPCODENAME 
     , ITEMCREATEDWHEN 
     , ITEMMODIFIEDWHEN 
     , ISPROFESSIONALLYCOLLECTED 
     , HARISKCATEGORY_ITEMMODIFIEDWHEN 
     , HAUSERRISKAREA_ITEMMODIFIEDWHEN 
     , HAUSERQUESTION_ITEMMODIFIEDWHEN 
     , HAUSERANSWERS_ITEMMODIFIEDWHEN 
     , HAPAPERFLG 
     , HATELEPHONICFLG 
     , HASTARTEDMODE 
     , HACOMPLETEDMODE 
     , DOCUMENTCULTURE_VHCJ 
     , DOCUMENTCULTURE_HAQUESTIONSVIEW 
     , CAMPAIGNNODEGUID 
     , HACAMPAIGNID 
     , HASHCODE 
     , PKHASHCODE 
     , CHANGED_FLG 
     , LASTMODIFIEDDATE 
     , HEALTHASSESSMENTTYPE 
     --, HAUserStarted_LASTMODIFIED 
     --, CMSUSER_LASTMODIFIED 
     --, USERSETTINGS_LASTMODIFIED 
     --, USERSITE_LASTMODIFIED 
     --, CMSSITE_LASTMODIFIED 
     --, ACCT_LASTMODIFIED 
     --, HAUSERMODULE_LASTMODIFIED 
     --, VHCJ_LASTMODIFIED 
     --, VHAJ_LASTMODIFIED 
     --, HARISKCATEGORY_LASTMODIFIED 
     --, HAUSERRISKAREA_LASTMODIFIED 
     --, HAUSERQUESTION_LASTMODIFIED 
     --, HAQUESTIONSVIEW_LASTMODIFIED 
     --, HAUSERQUESTIONGROUPRESULTS_LASTMODIFIED 
     --, HAUSERANSWERS_LASTMODIFIED 
     --, HAUserStarted_LastUpdateID 
     --, CMSUSER_LastUpdateID 
     --, USERSETTINGS_LastUpdateID 
     --, USERSITE_LastUpdateID 
     --, ACCT_LastUpdateID 
     --, HAUSERMODULE_LastUpdateID 
     --, VHCJ_LastUpdateID 
     --, VHAJ_LastUpdateID 
     --, HARISKCATEGORY_LastUpdateID 
     --, HAUSERRISKAREA_LastUpdateID 
     --, HAUSERQUESTION_LastUpdateID 
     --, HAQUESTIONSVIEW_LastUpdateID 
     --, HAUSERQUESTIONGROUPRESULTS_LastUpdateID 
     --, HAUSERANSWERS_LastUpdateID 
     --, LASTUPDATEID 
     --, DELETEFLG 
     , SVR 
     , DBNAME 
     , DELETEDFLG 
     , ChangeType 
         --     , NULL AS RowNbr
         --, NULL AS TimeZone
         --, NULL AS ConvertedToCentralTime
           FROM view_EDW_PullHAData_NoCT;

    SET @i = @@ROWCOUNT;

    PRINT 'Relaoded ' + CAST (@i AS nvarchar (50)) + ' records.';
    RETURN @i;

END;


GO
PRINT 'Executed proc_EDW_Reload_EDW_HealthAssessment.sql';
GO
