
GO
USE KenticoCMS_DataMart;

GO
PRINT 'Executing proc_Create_FACT_EDW_PkHashkey_TBL.SQL';

GO

IF EXISTS (SELECT
                  name
                  FROM sys.procedures
                  WHERE
                  name = 'proc_Create_FACT_EDW_PkHashkey_TBL') 
    BEGIN
        DROP PROCEDURE
             proc_Create_FACT_EDW_PkHashkey_TBL;
    END;

GO
-- exec proc_Create_FACT_EDW_PkHashkey_TBL
--drop table FACT_EDW_PkHashkey
CREATE PROCEDURE proc_Create_FACT_EDW_PkHashkey_TBL
AS
BEGIN

    IF NOT EXISTS (SELECT
                          name
                          FROM sys.tables
                          WHERE
                          name = 'FACT_EDW_PkHashkey') 
        BEGIN
            PRINT 'Creating FACT_EDW_PkHashkey';
            CREATE TABLE dbo.FACT_EDW_PkHashkey (
                         HAUSERSTARTED_ITEMID INT NULL
                       , USERGUID UNIQUEIDENTIFIER NOT NULL
                       , HASHCODE NVARCHAR (100) NULL
                       , PKHASHCODE NVARCHAR (100) NULL
                       , RowNbr INT IDENTITY (1 , 1) 
                                    NOT NULL
                       , ChangeType NCHAR (1) NULL
                       , ChangeDate DATETIME NULL
                       , DeletedFlg BIT NULL
                       , SVR NVARCHAR (100) NULL
                       , DBNAME NVARCHAR (100) NULL
            );

            ALTER TABLE dbo.FACT_EDW_PkHashkey
            ADD
                        CONSTRAINT DF_FACT_EDW_PkHashkey_SVR  DEFAULT @@servername FOR SVR;
            ALTER TABLE dbo.FACT_EDW_PkHashkey
            ADD
                        CONSTRAINT DF_FACT_EDW_PkHashkey_DBNAME  DEFAULT DB_NAME () FOR DBNAME;

            CREATE CLUSTERED INDEX PK_FACT_EDW_PkHashkey ON dbo.FACT_EDW_PkHashkey
            (SVR ASC , DBNAME ASC ,
            PKHASHCODE ASC ,
            HAUSERSTARTED_ITEMID ASC ,
            USERGUID ASC ,
            HASHCODE ASC ,
            DeletedFlg
            );

            CREATE NONCLUSTERED INDEX CI_FACT_EDW_PkHashkey_ChangeDate ON dbo.FACT_EDW_PkHashkey
            (
            ChangeDate ASC , RowNbr
            ) 
            INCLUDE ( 	SVR , DBNAME , HAUSERSTARTED_ITEMID ,
            HASHCODE ,
            PKHASHCODE ,
            ChangeType ,
            DeletedFlg) WITH (PAD_INDEX = OFF , STATISTICS_NORECOMPUTE = OFF , SORT_IN_TEMPDB = OFF , DROP_EXISTING = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON) ;

            INSERT INTO FACT_EDW_PkHashkey
            (
                   SVR
                 , DBNAME
                 , HAUSERSTARTED_ITEMID
                 , USERGUID
                 , HASHCODE
                 , PKHASHCODE) 
            SELECT
                   HAUSERSTARTED.SVR
                 , HAUSERSTARTED.DBNAME
                 , HAUSERSTARTED.ITEMID AS HAUSERSTARTED_ITEMID
                 , USERGUID
                 , CAST ( HASHBYTES ( 'sha1' , ISNULL ( CAST ( HAUSERSTARTED.ITEMID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( VHAJ.NODEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERSTARTED.USERID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( CMSUSER.USERGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( USERSETTINGS.HFITUSERMPINUMBER AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( CMSSITE.SITEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( ACCT.ACCOUNTID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( ACCT.ACCOUNTCD AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( ACCT.ACCOUNTNAME AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERSTARTED.HASTARTEDDT AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERSTARTED.HACOMPLETEDDT AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERMODULE.ITEMID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERMODULE.CODENAME AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERMODULE.HAMODULENODEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( VHAJ.NODEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HARISKCATEGORY.ITEMID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HARISKCATEGORY.CODENAME AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HARISKCATEGORY.HARISKCATEGORYNODEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERRISKAREA.ITEMID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERRISKAREA.CODENAME AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERRISKAREA.HARISKAREANODEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.ITEMID AS NVARCHAR (100)) , '-') + ISNULL ( LEFT ( HAQUESTIONSVIEW.TITLE , 1000) , '-') + ISNULL ( CAST ( HAUSERQUESTION.HAQUESTIONNODEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.CODENAME AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.HAQUESTIONNODEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.ITEMID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.HAANSWERNODEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.CODENAME AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.HAANSWERVALUE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERMODULE.HAMODULESCORE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HARISKCATEGORY.HARISKCATEGORYSCORE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERRISKAREA.HARISKAREASCORE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.HAQUESTIONSCORE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.HAANSWERPOINTS AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERQUESTIONGROUPRESULTS.POINTRESULTS AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.UOMCODE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERSTARTED.HASCORE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERMODULE.PREWEIGHTEDSCORE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HARISKCATEGORY.PREWEIGHTEDSCORE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERRISKAREA.PREWEIGHTEDSCORE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.PREWEIGHTEDSCORE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERQUESTIONGROUPRESULTS.CODENAME AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.ITEMCREATEDWHEN AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.ITEMMODIFIEDWHEN AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.ISPROFESSIONALLYCOLLECTED AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HARISKCATEGORY.ITEMMODIFIEDWHEN AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERRISKAREA.ITEMMODIFIEDWHEN AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.ITEMMODIFIEDWHEN AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.ITEMMODIFIEDWHEN AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERSTARTED.HAPAPERFLG AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERSTARTED.HATELEPHONICFLG AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERSTARTED.HASTARTEDMODE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERSTARTED.HACOMPLETEDMODE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERSTARTED.HACAMPAIGNNODEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( VHCJ.HACAMPAIGNID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.ITEMMODIFIEDWHEN AS NVARCHAR (100)) , '-')) AS VARCHAR (100)) AS HASHCODE
                 , CAST ( HASHBYTES ( 'sha1' , ISNULL ( CAST ( HAUSERSTARTED.ITEMID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( VHAJ.NODEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( USERGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( SITEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( ACCT.ACCOUNTID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( ACCOUNTCD AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAUSERMODULE.ITEMID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAMODULENODEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( VHAJ.NODEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HARISKCATEGORY.ITEMID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HARISKCATEGORYNODEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HARISKCATEGORY.CODENAME AS VARCHAR (100)) , '-') + ISNULL ( CAST ( HARISKCATEGORY.HARISKCATEGORYNODEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAUSERRISKAREA.ITEMID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HARISKAREANODEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAUSERRISKAREA.CODENAME AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.ITEMID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.HAQUESTIONNODEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.CODENAME AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAQUESTIONNODEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.ITEMID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAANSWERNODEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAUSERSTARTED.HACAMPAIGNNODEGUID AS VARCHAR (50)) , '-')) AS VARCHAR (100)) AS PKHASHCODE
                   FROM
            FACT_EDW_HFIT_HEALTHASSESMENTUSERSTARTED AS HAUSERSTARTED
                INNER JOIN FACT_EDW_CMS_USER AS CMSUSER
                    ON
                    HAUSERSTARTED.USERID = CMSUSER.USERID
                AND HAUSERSTARTED.SVR = CMSUSER.SVR
                AND HAUSERSTARTED.DBNAME = CMSUSER.DBNAME
                INNER JOIN FACT_EDW_CMS_USERSETTINGS AS USERSETTINGS
                    ON
                    USERSETTINGS.USERSETTINGSUSERID = CMSUSER.USERID
                AND HFITUSERMPINUMBER >= 0
                AND HFITUSERMPINUMBER IS NOT NULL
                AND USERSETTINGS.SVR = CMSUSER.SVR
                AND USERSETTINGS.DBNAME = CMSUSER.DBNAME
                INNER JOIN FACT_EDW_CMS_USERSITE AS USERSITE
                    ON
                    CMSUSER.USERID = USERSITE.USERID
                AND CMSUSER.SVR = USERSITE.SVR
                AND CMSUSER.DBNAME = USERSITE.DBNAME
                INNER JOIN DBO.BASE_CMS_SITE AS CMSSITE
                    ON
                    USERSITE.SITEID = CMSSITE.SITEID
                AND USERSITE.SVR = CMSSITE.SVR
                AND USERSITE.DBNAME = CMSSITE.DBNAME
                INNER JOIN DBO.BASE_HFIT_ACCOUNT AS ACCT
                    ON
                    ACCT.SITEID = CMSSITE.SITEID
                AND ACCT.SVR = CMSSITE.SVR
                AND ACCT.DBNAME = CMSSITE.DBNAME
                INNER JOIN FACT_EDW_HFIT_HEALTHASSESMENTUSERMODULE AS HAUSERMODULE
                    ON
                    HAUSERSTARTED.ITEMID = HAUSERMODULE.HASTARTEDITEMID
                AND HAUSERSTARTED.SVR = HAUSERMODULE.SVR
                AND HAUSERSTARTED.DBNAME = HAUSERMODULE.DBNAME
                INNER JOIN FACT_EDW_VIEW_HFIT_HACAMPAIGN_JOINED AS VHCJ
                    ON
                    VHCJ.NODEGUID = HAUSERSTARTED.HACAMPAIGNNODEGUID
                AND VHCJ.NODESITEID = USERSITE.SITEID
                AND VHCJ.DOCUMENTCULTURE = 'en-US'
                AND VHCJ.SVR = USERSITE.SVR
                AND VHCJ.DBNAME = USERSITE.DBNAME
                INNER JOIN FACT_VIEW_HFIT_HEALTHASSESSMENT_JOINED AS VHAJ
                    ON
                    VHAJ.DOCUMENTID = VHCJ.HEALTHASSESSMENTID
                AND VHAJ.SVR = VHCJ.SVR
                AND VHAJ.DBNAME = VHCJ.DBNAME
                INNER JOIN FACT_EDW_HFIT_HEALTHASSESMENTUSERRISKCATEGORY AS HARISKCATEGORY
                    ON
                    HAUSERMODULE.ITEMID = HARISKCATEGORY.HAMODULEITEMID
                AND HAUSERMODULE.SVR = HARISKCATEGORY.SVR
                AND HAUSERMODULE.DBNAME = HARISKCATEGORY.DBNAME
                INNER JOIN FACT_EDW_HFit_HealthAssesmentUserRiskArea AS HAUSERRISKAREA
                    ON
                    HARISKCATEGORY.ITEMID = HAUSERRISKAREA.HARISKCATEGORYITEMID
                AND HARISKCATEGORY.SVR = HAUSERRISKAREA.SVR
                AND HARISKCATEGORY.DBNAME = HAUSERRISKAREA.DBNAME
                INNER JOIN FACT_EDW_HFit_HealthAssesmentUserQuestion AS HAUSERQUESTION
                    ON
                    HAUSERRISKAREA.ITEMID = HAUSERQUESTION.HARISKAREAITEMID
                AND HAUSERRISKAREA.SVR = HAUSERQUESTION.SVR
                AND HAUSERRISKAREA.DBNAME = HAUSERQUESTION.DBNAME
                INNER JOIN FACT_View_EDW_HealthAssesmentQuestions AS HAQUESTIONSVIEW
                    ON
                    HAUSERQUESTION.HAQUESTIONNODEGUID = HAQUESTIONSVIEW.NODEGUID
                AND HAUSERQUESTION.SVR = HAQUESTIONSVIEW.SVR
                AND HAUSERQUESTION.DBNAME = HAQUESTIONSVIEW.DBNAME
                LEFT OUTER JOIN FACT_EDW_HFit_HealthAssesmentUserQuestionGroupResults AS HAUSERQUESTIONGROUPRESULTS
                    ON
                    HAUSERRISKAREA.ITEMID = HAUSERQUESTIONGROUPRESULTS.HARISKAREAITEMID
                AND HAUSERRISKAREA.SVR = HAUSERQUESTIONGROUPRESULTS.SVR
                AND HAUSERRISKAREA.DBNAME = HAUSERQUESTIONGROUPRESULTS.DBNAME
                INNER JOIN FACT_EDW_HFIT_HealthAssesmentUserAnswers AS HAUSERANSWERS
                    ON
                    HAUSERQUESTION.ITEMID = HAUSERANSWERS.HAQUESTIONITEMID --Add in the change tracking data
                AND HAUSERQUESTION.SVR = HAUSERANSWERS.SVR
                AND HAUSERQUESTION.DBNAME = HAUSERANSWERS.DBNAME
                   WHERE USERSETTINGS.HFITUSERMPINUMBER NOT IN (
                SELECT
                       REJECTMPICODE
                       FROM BASE_HFIT_LKP_EDW_REJECTMPI) 
                   OPTION (
                          RECOMPILE) ;

        END;
END;

GO
DECLARE
@i AS INT = 0;
EXEC @i = proc_QuickRowCount 'FACT_EDW_PkHashkey';
PRINT 'Rows processed: ' + CAST (@i AS NVARCHAR (50)) ;
PRINT 'Executed proc_Create_FACT_EDW_PkHashkey_TBL.SQL';
GO
