

go
print 'Executing TRIG_UPDT_BASE_MART_EDW_HealthAssesment.sql'
go

IF EXISTS (
    SELECT *
    FROM sys.objects
    WHERE [type] = 'TR' AND [name] = 'TRIG_UPDT_BASE_MART_EDW_HealthAssesment'
    )
    DROP TRIGGER TRIG_UPDT_BASE_MART_EDW_HealthAssesment;
go
CREATE TRIGGER TRIG_UPDT_BASE_MART_EDW_HealthAssesment
    ON dbo.BASE_MART_EDW_HealthAssesment
    AFTER UPDATE 
AS 
BEGIN 
-- Generated on: Apr  6 2016  2:16PM
DECLARE @ACTION as char(1) = 'U';
INSERT INTO BASE_MART_EDW_HealthAssesment_DEL
(
 [AccountCD]
      , [AccountID] 
      , [AccountName] 
      , [ACCT_LastModifiedDate] 
      , [CampaignNodeGUID] 
      , [ChangeType] 
      , [CMSNodeGuid] 
      , [CMSUser_LastModifiedDate] 
      , [CT_CodeName] 
      , [CT_HADocumentConfigID] 
      , [CT_HAStartedMode] 
      , [CT_HATelephonicFlg] 
      , [CT_HFitUserMpiNumber] 
      , [CT_IsProfessionallyCollected] 
      , [DBNAME] 
      , [DocumentCulture_HAQuestionsView] 
      , [DocumentCulture_VHCJ] 
      , [HAAnswerNodeGUID] 
      , [HAAnswerPoints] 
      , [HAAnswerValue] 
      , [HAAnswerVersionID] 
      , [HACompletedDt] 
      , [HACompletedMode] 
      , [HAModuleNodeGUID] 
      , [HAModuleScore] 
      , [HAModuleVersionID] 
      , [HAPaperFlg] 
      , [HAQuestionDocumentID] 
      , [HAQuestionGuid] 
      , [HAQuestionNodeGUID] 
      , [HAQuestionScore] 
      , [HAQuestionVersionID] 
      , [HARiskAreaNodeGUID] 
      , [HARiskAreaScore] 
      , [HARiskAreaVersionID] 
      , [HARiskCategory_ItemModifiedWhen] 
      , [HARiskCategory_LastModifiedDate] 
      , [HARiskCategoryNodeGUID] 
      , [HARiskCategoryScore] 
      , [HARiskCategoryVersionID] 
      , [HAScore] 
      , [HAStartedDt] 
      , [HAStartedMode] 
      , [HATelephonicFlg] 
      , [HAUserAnswers_ItemModifiedWhen] 
      , [HAUserAnswers_LastModifiedDate] 
      , [HAUserModule_LastModifiedDate] 
      , [HAUserQuestion_ItemModifiedWhen] 
      , [HAUserQuestion_LastModifiedDate] 
      , [HAUserRiskArea_ItemModifiedWhen] 
      , [HAUserRiskArea_LastModifiedDate] 
      , [HAUserStarted_LastModifiedDate] 
      , [HealthAssesmentUserStartedNodeGUID] 
      , [HealthAssessmentType] 
      , [HFitUserMpiNumber] 
      , [IsProfessionallyCollected] 
      , [ItemCreatedWhen] 
      , [ItemModifiedWhen] 
      , [LastModifiedDate] 
      , [ModulePreWeightedScore] 
      , [PointResults] 
      , [QuestionGroupCodeName] 
      , [QuestionPreWeightedScore] 
      , [RiskAreaPreWeightedScore] 
      , [RiskCategoryPreWeightedScore] 
      , [RowDataChanged] 
      , [SiteGUID] 
      , [SurrogateKey_CMS_Site] 
      , [SurrogateKey_CMS_User] 
      , [SurrogateKey_CMS_UserSettings] 
      , [SurrogateKey_CMS_UserSite] 
      , [SurrogateKey_HFit_Account] 
      , [SurrogateKey_HFit_HealthAssesmentUserAnswers] 
      , [SurrogateKey_HFit_HealthAssesmentUserModule] 
      , [SurrogateKey_HFit_HealthAssesmentUserQuestion] 
      , [SurrogateKey_HFit_HealthAssesmentUserRiskArea] 
      , [SurrogateKey_HFit_HealthAssesmentUserRiskCategory] 
      , [SurrogateKey_HFit_HealthAssesmentUserStarted] 
      , [SurrogateKey_View_EDW_HealthAssesmentQuestions] 
      , [SurrogateKey_View_HFit_HACampaign_Joined] 
      , [SurrogateKey_View_HFit_HealthAssessment_Joined] 
      , [SVR] 
      , [Title] 
      , [UOMCode] 
      , [UserAnswerCodeName] 
      , [UserAnswerItemID] 
      , [UserGUID] 
      , [UserID] 
      , [UserModuleCodeName] 
      , [UserModuleItemId] 
      , [UserQuestionCodeName] 
      , [UserQuestionItemID] 
      , [UserRiskAreaCodeName] 
      , [UserRiskAreaItemID] 
      , [UserRiskCategoryCodeName] 
      , [UserRiskCategoryItemID] 
      , [UserSettings_LastModifiedDate] 
      , [UserSite_LastModifiedDate] 
      , [UserStartedItemID] )
 SELECT 
 [AccountCD]
     , [AccountID] 
     , [AccountName] 
     , [ACCT_LastModifiedDate] 
     , [CampaignNodeGUID] 
     , [ChangeType] 
     , [CMSNodeGuid] 
     , [CMSUser_LastModifiedDate] 
     , [CT_CodeName] 
     , [CT_HADocumentConfigID] 
     , [CT_HAStartedMode] 
     , [CT_HATelephonicFlg] 
     , [CT_HFitUserMpiNumber] 
     , [CT_IsProfessionallyCollected] 
     , [DBNAME] 
     , [DocumentCulture_HAQuestionsView] 
     , [DocumentCulture_VHCJ] 
     , [HAAnswerNodeGUID] 
     , [HAAnswerPoints] 
     , [HAAnswerValue] 
     , [HAAnswerVersionID] 
     , [HACompletedDt] 
     , [HACompletedMode] 
     , [HAModuleNodeGUID] 
     , [HAModuleScore] 
     , [HAModuleVersionID] 
     , [HAPaperFlg] 
     , [HAQuestionDocumentID] 
     , [HAQuestionGuid] 
     , [HAQuestionNodeGUID] 
     , [HAQuestionScore] 
     , [HAQuestionVersionID] 
     , [HARiskAreaNodeGUID] 
     , [HARiskAreaScore] 
     , [HARiskAreaVersionID] 
     , [HARiskCategory_ItemModifiedWhen] 
     , [HARiskCategory_LastModifiedDate] 
     , [HARiskCategoryNodeGUID] 
     , [HARiskCategoryScore] 
     , [HARiskCategoryVersionID] 
     , [HAScore] 
     , [HAStartedDt] 
     , [HAStartedMode] 
     , [HATelephonicFlg] 
     , [HAUserAnswers_ItemModifiedWhen] 
     , [HAUserAnswers_LastModifiedDate] 
     , [HAUserModule_LastModifiedDate] 
     , [HAUserQuestion_ItemModifiedWhen] 
     , [HAUserQuestion_LastModifiedDate] 
     , [HAUserRiskArea_ItemModifiedWhen] 
     , [HAUserRiskArea_LastModifiedDate] 
     , [HAUserStarted_LastModifiedDate] 
     , [HealthAssesmentUserStartedNodeGUID] 
     , [HealthAssessmentType] 
     , [HFitUserMpiNumber] 
     , [IsProfessionallyCollected] 
     , [ItemCreatedWhen] 
     , [ItemModifiedWhen] 
     , getdate() 
     , [ModulePreWeightedScore] 
     , [PointResults] 
     , [QuestionGroupCodeName] 
     , [QuestionPreWeightedScore] 
     , [RiskAreaPreWeightedScore] 
     , [RiskCategoryPreWeightedScore] 
     , [RowDataChanged] 
     , [SiteGUID] 
     , [SurrogateKey_CMS_Site] 
     , [SurrogateKey_CMS_User] 
     , [SurrogateKey_CMS_UserSettings] 
     , [SurrogateKey_CMS_UserSite] 
     , [SurrogateKey_HFit_Account] 
     , [SurrogateKey_HFit_HealthAssesmentUserAnswers] 
     , [SurrogateKey_HFit_HealthAssesmentUserModule] 
     , [SurrogateKey_HFit_HealthAssesmentUserQuestion] 
     , [SurrogateKey_HFit_HealthAssesmentUserRiskArea] 
     , [SurrogateKey_HFit_HealthAssesmentUserRiskCategory] 
     , [SurrogateKey_HFit_HealthAssesmentUserStarted] 
     , [SurrogateKey_View_EDW_HealthAssesmentQuestions] 
     , [SurrogateKey_View_HFit_HACampaign_Joined] 
     , [SurrogateKey_View_HFit_HealthAssessment_Joined] 
     , [SVR] 
     , [Title] 
     , [UOMCode] 
     , [UserAnswerCodeName] 
     , [UserAnswerItemID] 
     , [UserGUID] 
     , [UserID] 
     , [UserModuleCodeName] 
     , [UserModuleItemId] 
     , [UserQuestionCodeName] 
     , [UserQuestionItemID] 
     , [UserRiskAreaCodeName] 
     , [UserRiskAreaItemID] 
     , [UserRiskCategoryCodeName] 
     , [UserRiskCategoryItemID] 
     , [UserSettings_LastModifiedDate] 
     , [UserSite_LastModifiedDate] 
     , [UserStartedItemID] 
FROM inserted 
END; 
go
print 'Executed TRIG_UPDT_BASE_MART_EDW_HealthAssesment.sql'
go