
-- USE [KenticoCMS_DataMart]
-- USE [KenticoCMS_DataMart_2]
-- verify_JOINED_Tables_KeysAndIndexes
BEGIN TRY
    ALTER TABLE dbo.FACT_EDW_HFIT_HEALTHASSESMENTUSERRISKAREA_JOINED DROP CONSTRAINT PK_FACT_EDW_HFIT_HEALTHASSESMENTUSERRISKAREA_JOINED;
END TRY
BEGIN CATCH
    PRINT 'PK_FACT_EDW_HFIT_HEALTHASSESMENTUSERRISKAREA_JOINED does not exist...';
END CATCH;

IF EXISTS (SELECT name
                  FROM sys.indexes
                  WHERE name = 'PI_EDW_HFIT_HEALTHASSESMENTUSERRISKAREA_JOINED') 
    BEGIN
        DROP INDEX PI_EDW_HFIT_HEALTHASSESMENTUSERRISKAREA_JOINED ON dbo.FACT_EDW_HFIT_HEALTHASSESMENTUSERRISKAREA_JOINED WITH (ONLINE = OFF) 
    END;

ALTER TABLE FACT_EDW_HFIT_HEALTHASSESMENTUSERRISKAREA_JOINED ALTER COLUMN SVR nvarchar (100) NOT NULL;

ALTER TABLE FACT_EDW_HFIT_HEALTHASSESMENTUSERRISKAREA_JOINED ALTER COLUMN DBNAME nvarchar (100) NOT NULL;

ALTER TABLE FACT_EDW_HFIT_HEALTHASSESMENTUSERRISKAREA_JOINED DROP COLUMN RowNbr; 

ALTER TABLE FACT_EDW_HFIT_HEALTHASSESMENTUSERRISKAREA_JOINED
ADD RowNbr int IDENTITY (1, 1) 
               NOT NULL;


CREATE CLUSTERED INDEX PI_EDW_HFIT_HEALTHASSESMENTUSERRISKAREA_JOINED ON dbo.FACT_EDW_HFIT_HEALTHASSESMENTUSERRISKAREA_JOINED (USERRISKAREAITEMID ASC, HAUSERQUESTIONGROUPRESULTSITEMID ASC, SVR ASC, DBNAME ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];

ALTER TABLE dbo.FACT_EDW_HFIT_HEALTHASSESMENTUSERRISKAREA_JOINED
ADD CONSTRAINT PK_FACT_EDW_HFIT_HEALTHASSESMENTUSERRISKAREA_JOINED PRIMARY KEY NONCLUSTERED (USERRISKAREAITEMID ASC, HARISKCATEGORYITEMID ASC, HARISKAREANODEGUID ASC, SVR ASC, DBNAME ASC, RowNbr ASC) 
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];



IF EXISTS (SELECT name
                  FROM sys.indexes
                  WHERE name = 'PI_VIEW_HFIT_HACAMPAIGN_JOINED') 
    BEGIN
        DROP INDEX PI_VIEW_HFIT_HACAMPAIGN_JOINED ON dbo.FACT_EDW_VIEW_HFIT_HACAMPAIGN_JOINED WITH (ONLINE = OFF) 
    END;

IF EXISTS (SELECT name
                  FROM sys.indexes
                  WHERE name = 'PI_VIEW_HFIT_HACAMPAIGN_JOINED_CULTURE') 
    BEGIN
        DROP INDEX PI_VIEW_HFIT_HACAMPAIGN_JOINED_CULTURE ON dbo.FACT_EDW_VIEW_HFIT_HACAMPAIGN_JOINED
    END;

--select * from INFORMATION_SCHEMA.columns where table_name = 'FACT_EDW_VIEW_HFIT_HACAMPAIGN_JOINED'

ALTER TABLE FACT_EDW_VIEW_HFIT_HACAMPAIGN_JOINED ALTER COLUMN SVR nvarchar (100) NOT NULL;

ALTER TABLE FACT_EDW_VIEW_HFIT_HACAMPAIGN_JOINED ALTER COLUMN DBNAME nvarchar (100) NOT NULL;

ALTER TABLE FACT_EDW_VIEW_HFIT_HACAMPAIGN_JOINED DROP COLUMN RowNbr; 

ALTER TABLE FACT_EDW_VIEW_HFIT_HACAMPAIGN_JOINED
ADD RowNbr int IDENTITY (1, 1) 
               NOT NULL;

BEGIN TRY
    ALTER TABLE FACT_EDW_VIEW_HFIT_HACAMPAIGN_JOINED
    ADD CONSTRAINT PK_FACT_EDW_VIEW_HFIT_HACAMPAIGN_JOINED PRIMARY KEY (SVR, DBNAME, HACAMPAIGNID, NODEGUID, NODESITEID, HEALTHASSESSMENTID) ;
END TRY
BEGIN CATCH
    PRINT 'It apprears PK_FACT_EDW_VIEW_HFIT_HACAMPAIGN_JOINED already exists.';
END CATCH;

CREATE CLUSTERED INDEX PI_VIEW_HFIT_HACAMPAIGN_JOINED ON dbo.FACT_EDW_VIEW_HFIT_HACAMPAIGN_JOINED (DOCUMENTCULTURE ASC, HACAMPAIGNID ASC, NODEGUID ASC, NODESITEID ASC, HEALTHASSESSMENTID ASC, SVR ASC, DBNAME ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];

CREATE NONCLUSTERED INDEX PI_VIEW_HFIT_HACAMPAIGN_JOINED_CULTURE ON dbo.FACT_EDW_VIEW_HFIT_HACAMPAIGN_JOINED (NODEGUID ASC, DOCUMENTCULTURE ASC, SVR ASC, DBNAME ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];








IF EXISTS (SELECT name
                  FROM sys.indexes
                  WHERE name = 'PI_VIEW_HFIT_HEALTHASSESSMENT_JOINED') 
    BEGIN
        DROP INDEX PI_VIEW_HFIT_HEALTHASSESSMENT_JOINED ON dbo.FACT_EDW_VIEW_HFIT_HEALTHASSESSMENT_JOINED WITH (ONLINE = OFF) 
    END;


ALTER TABLE FACT_EDW_VIEW_HFIT_HEALTHASSESSMENT_JOINED ALTER COLUMN SVR nvarchar (100) NOT NULL;

ALTER TABLE FACT_EDW_VIEW_HFIT_HEALTHASSESSMENT_JOINED ALTER COLUMN DBNAME nvarchar (100) NOT NULL;

ALTER TABLE FACT_EDW_VIEW_HFIT_HEALTHASSESSMENT_JOINED DROP COLUMN RowNbr; 

ALTER TABLE FACT_EDW_VIEW_HFIT_HEALTHASSESSMENT_JOINED
ADD RowNbr int IDENTITY (1, 1) 
               NOT NULL;

BEGIN TRY
    ALTER TABLE FACT_EDW_VIEW_HFIT_HEALTHASSESSMENT_JOINED
    ADD CONSTRAINT PK_FACT_EDW_VIEW_HFIT_HEALTHASSESSMENT_JOINED PRIMARY KEY ([NODEGUID],[DOCUMENTID],[SVR],[DBNAME],RowNbr) ;
END TRY
BEGIN CATCH
    PRINT 'It apprears FACT_EDW_VIEW_HFIT_HEALTHASSESSMENT_JOINED already exists.';
END CATCH;