
/*---------------------------------------------------
drop table ##TEMP_HA_DATA 
go
select USERANSWERCODENAME,* from view_EDW_PullHAData_IDX where USERANSWERITEMID = 7038567

select USERANSWERCODENAME,* from view_EDW_PullHAData_IDX where USERANSWERITEMID = 7038567
where CHANGETYPE is NOT NULL

drop table ##TEMP_HA_DATA 

select top 10000 * into ##TEMP_HA_DATA from view_EDW_PullHAData_IDX
where CHANGETYPE is NOT NULL
*/
GO
PRINT 'Executing view_EDW_PullHAData_IDX.sql';
GO
IF EXISTS (SELECT
                  name
                  FROM sys.views
                  WHERE name = 'view_EDW_PullHAData_IDX') 
    BEGIN
        DROP VIEW
             view_EDW_PullHAData_IDX;
    END;
GO
CREATE VIEW view_EDW_PullHAData_IDX
--WITH SCHEMABINDING
AS SELECT
          HAUSERSTARTED.ITEMID AS USERSTARTEDITEMID
        , VHAJ.NODEGUID AS HEALTHASSESMENTUSERSTARTEDNODEGUID
        , HAUSERSTARTED.USERID
        , CMSUSER.USERGUID
        , USERSETTINGS.HFITUSERMPINUMBER
        , CMSSITE.SITEGUID
        , ACCT.ACCOUNTID
        , ACCT.ACCOUNTCD
        , ACCT.ACCOUNTNAME
        , HAUSERSTARTED.HASTARTEDDT
        , HAUSERSTARTED.HACOMPLETEDDT
        , HAUSERMODULE.ITEMID AS USERMODULEITEMID
        , HAUSERMODULE.CODENAME AS USERMODULECODENAME
        , HAUSERMODULE.HAMODULENODEGUID
        , VHAJ.NODEGUID AS CMSNODEGUID
        , NULL AS HAMODULEVERSIONID
        , HARISKCATEGORY.ITEMID AS USERRISKCATEGORYITEMID
        , HARISKCATEGORY.CODENAME AS USERRISKCATEGORYCODENAME
        , HARISKCATEGORY.HARISKCATEGORYNODEGUID
        , NULL AS HARISKCATEGORYVERSIONID
        , HAUSERRISKAREA.ITEMID AS USERRISKAREAITEMID
        , HAUSERRISKAREA.CODENAME AS USERRISKAREACODENAME
        , HAUSERRISKAREA.HARISKAREANODEGUID
        , NULL AS HARISKAREAVERSIONID
        , HAUSERQUESTION.ITEMID AS USERQUESTIONITEMID
        , HAQUESTIONSVIEW.TITLE
        , HAUSERQUESTION.HAQUESTIONNODEGUID AS HAQUESTIONGUID
        , HAUSERQUESTION.CODENAME AS USERQUESTIONCODENAME
        , NULL AS HAQUESTIONDOCUMENTID
        , NULL AS HAQUESTIONVERSIONID
        , HAUSERQUESTION.HAQUESTIONNODEGUID
        , HAUSERANSWERS.ITEMID AS USERANSWERITEMID
        , HAUSERANSWERS.HAANSWERNODEGUID
        , NULL AS HAANSWERVERSIONID
        , HAUSERANSWERS.CODENAME AS USERANSWERCODENAME
        , HAUSERANSWERS.HAANSWERVALUE
        , HAUSERMODULE.HAMODULESCORE
        , HARISKCATEGORY.HARISKCATEGORYSCORE
        , HAUSERRISKAREA.HARISKAREASCORE
        , HAUSERQUESTION.HAQUESTIONSCORE
        , HAUSERANSWERS.HAANSWERPOINTS
        , HAUSERQUESTIONGROUPRESULTS.POINTRESULTS
        , HAUSERANSWERS.UOMCODE
        , HAUSERSTARTED.HASCORE
        , HAUSERMODULE.PREWEIGHTEDSCORE AS MODULEPREWEIGHTEDSCORE
        , HARISKCATEGORY.PREWEIGHTEDSCORE AS RISKCATEGORYPREWEIGHTEDSCORE
        , HAUSERRISKAREA.PREWEIGHTEDSCORE AS RISKAREAPREWEIGHTEDSCORE
        , HAUSERQUESTION.PREWEIGHTEDSCORE AS QUESTIONPREWEIGHTEDSCORE
        , HAUSERQUESTIONGROUPRESULTS.CODENAME AS QUESTIONGROUPCODENAME
        , COALESCE ( CT_CMS_USER.SYS_CHANGE_OPERATION , CT_CMS_USERSETTINGS.SYS_CHANGE_OPERATION , CT_CMS_SITE.SYS_CHANGE_OPERATION , CT_CMS_USERSITE.SYS_CHANGE_OPERATION , CT_HFIT_ACCOUNT.SYS_CHANGE_OPERATION , CT_HFIT_HealthAssesmentUserAnswers.SYS_CHANGE_OPERATION , CT_HFIT_HEALTHASSESMENTUSERMODULE.SYS_CHANGE_OPERATION , CT_HFIT_HEALTHASSESMENTUSERQUESTION.SYS_CHANGE_OPERATION , CT_HFIT_HealthAssesmentUserQuestionGroupResults.SYS_CHANGE_OPERATION , CT_HFIT_HEALTHASSESMENTUSERRISKAREA.SYS_CHANGE_OPERATION , CT_HFIT_HEALTHASSESMENTUSERRISKCATEGORY.SYS_CHANGE_OPERATION , CT_HFIT_HEALTHASSESMENTUSERSTARTED.SYS_CHANGE_OPERATION) AS CHANGETYPE
        , HAUSERANSWERS.ITEMCREATEDWHEN
        , HAUSERANSWERS.ITEMMODIFIEDWHEN
        , HAUSERQUESTION.ISPROFESSIONALLYCOLLECTED
        , HARISKCATEGORY.ITEMMODIFIEDWHEN AS HARISKCATEGORY_ITEMMODIFIEDWHEN
        , HAUSERRISKAREA.ITEMMODIFIEDWHEN AS HAUSERRISKAREA_ITEMMODIFIEDWHEN
        , HAUSERQUESTION.ITEMMODIFIEDWHEN AS HAUSERQUESTION_ITEMMODIFIEDWHEN
        , HAUSERANSWERS.ITEMMODIFIEDWHEN AS HAUSERANSWERS_ITEMMODIFIEDWHEN
        , HAUSERSTARTED.HAPAPERFLG
        , HAUSERSTARTED.HATELEPHONICFLG
        , HAUSERSTARTED.HASTARTEDMODE
        , HAUSERSTARTED.HACOMPLETEDMODE
        , VHCJ.DOCUMENTCULTURE AS DOCUMENTCULTURE_VHCJ
        , HAQUESTIONSVIEW.DOCUMENTCULTURE AS DOCUMENTCULTURE_HAQUESTIONSVIEW
        , HAUSERSTARTED.HACAMPAIGNNODEGUID AS CAMPAIGNNODEGUID
        , VHCJ.HACAMPAIGNID
        , CAST ( HASHBYTES ( 'sha1' , ISNULL ( CAST ( HAUSERSTARTED.ITEMID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( VHAJ.NODEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERSTARTED.USERID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( CMSUSER.USERGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( USERSETTINGS.HFITUSERMPINUMBER AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( CMSSITE.SITEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( ACCT.ACCOUNTID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( ACCT.ACCOUNTCD AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( ACCT.ACCOUNTNAME AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERSTARTED.HASTARTEDDT AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERSTARTED.HACOMPLETEDDT AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERMODULE.ITEMID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERMODULE.CODENAME AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERMODULE.HAMODULENODEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( VHAJ.NODEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HARISKCATEGORY.ITEMID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HARISKCATEGORY.CODENAME AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HARISKCATEGORY.HARISKCATEGORYNODEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERRISKAREA.ITEMID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERRISKAREA.CODENAME AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERRISKAREA.HARISKAREANODEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.ITEMID AS NVARCHAR (100)) , '-') + ISNULL ( LEFT ( HAQUESTIONSVIEW.TITLE , 1000) , '-') + ISNULL ( CAST ( HAUSERQUESTION.HAQUESTIONNODEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.CODENAME AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.HAQUESTIONNODEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.ITEMID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.HAANSWERNODEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.CODENAME AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.HAANSWERVALUE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERMODULE.HAMODULESCORE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HARISKCATEGORY.HARISKCATEGORYSCORE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERRISKAREA.HARISKAREASCORE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.HAQUESTIONSCORE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.HAANSWERPOINTS AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERQUESTIONGROUPRESULTS.POINTRESULTS AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.UOMCODE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERSTARTED.HASCORE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERMODULE.PREWEIGHTEDSCORE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HARISKCATEGORY.PREWEIGHTEDSCORE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERRISKAREA.PREWEIGHTEDSCORE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.PREWEIGHTEDSCORE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERQUESTIONGROUPRESULTS.CODENAME AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.ITEMCREATEDWHEN AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.ITEMMODIFIEDWHEN AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.ISPROFESSIONALLYCOLLECTED AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HARISKCATEGORY.ITEMMODIFIEDWHEN AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERRISKAREA.ITEMMODIFIEDWHEN AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.ITEMMODIFIEDWHEN AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.ITEMMODIFIEDWHEN AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERSTARTED.HAPAPERFLG AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERSTARTED.HATELEPHONICFLG AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERSTARTED.HASTARTEDMODE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERSTARTED.HACOMPLETEDMODE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERSTARTED.HACAMPAIGNNODEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( VHCJ.HACAMPAIGNID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.ITEMMODIFIEDWHEN AS NVARCHAR (100)) , '-')) AS VARCHAR (100)) AS HASHCODE
        , CAST ( HASHBYTES ( 'sha1' , ISNULL ( CAST ( HAUSERSTARTED.ITEMID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( VHAJ.NODEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( USERGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( SITEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( ACCT.ACCOUNTID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( ACCOUNTCD AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAUSERMODULE.ITEMID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAMODULENODEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( VHAJ.NODEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HARISKCATEGORY.ITEMID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HARISKCATEGORYNODEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HARISKCATEGORY.CODENAME AS VARCHAR (100)) , '-') + ISNULL ( CAST ( HARISKCATEGORY.HARISKCATEGORYNODEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAUSERRISKAREA.ITEMID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HARISKAREANODEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAUSERRISKAREA.CODENAME AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.ITEMID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.HAQUESTIONNODEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.CODENAME AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAQUESTIONNODEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.ITEMID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAANSWERNODEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAUSERSTARTED.HACAMPAIGNNODEGUID AS VARCHAR (50)) , '-')) AS VARCHAR (100)) AS PKHASHCODE
          --, COALESCE ( CT_CMS_USER.USERID , CT_CMS_USERSETTINGS.USERSETTINGSID , CT_CMS_SITE.SITEID , CT_CMS_USERSITE.USERSITEID , CT_HFIT_ACCOUNT.ACCOUNTID , CT_HFIT_HealthAssesmentUserAnswers.ITEMID , CT_HFIT_HEALTHASSESMENTUSERMODULE.ITEMID , CT_HFIT_HEALTHASSESMENTUSERQUESTION.ITEMID , CT_HFIT_HealthAssesmentUserQuestionGroupResults.ITEMID , CT_HFIT_HEALTHASSESMENTUSERRISKAREA.ITEMID , CT_HFIT_HEALTHASSESMENTUSERRISKCATEGORY.ITEMID , CT_HFIT_HEALTHASSESMENTUSERSTARTED.ITEMID) AS CHANGED_FLG
        , NULL AS CHANGED_FLG

          --*************************************
          --join changes to the records 

          --, CT_CMS_USER.USERID AS CT_CMS_USER_USERID
        , CT_CMS_USER.SYS_CHANGE_OPERATION AS CT_CMS_USER_CHANGE_OPERATION
          --, CT_CMS_USERSETTINGS.USERSETTINGSID AS CT_USERSETTINGSID
        , CT_CMS_USERSETTINGS.SYS_CHANGE_OPERATION AS CT_USERSETTINGSID_CHANGE_OPERATION
          --, CT_CMS_SITE.SITEID AS SITEID_CTID
        , CT_CMS_SITE.SYS_CHANGE_OPERATION AS SITEID_CHANGE_OPERATION
          --, CT_CMS_USERSITE.USERSITEID AS USERSITEID_CTID
        , CT_CMS_USERSITE.SYS_CHANGE_OPERATION AS USERSITEID_CHANGE_OPERATION
          --, CT_HFIT_ACCOUNT.ACCOUNTID AS ACCOUNTID_CTID
        , CT_HFIT_ACCOUNT.SYS_CHANGE_OPERATION AS ACCOUNTID_CHANGE_OPERATION
          --, CT_HFIT_HealthAssesmentUserAnswers.ITEMID AS HAUSERANSWERS_CTID
        , CT_HFIT_HealthAssesmentUserAnswers.SYS_CHANGE_OPERATION AS HAUSERANSWERS_CHANGE_OPERATION
          --, CT_HFIT_HEALTHASSESMENTUSERMODULE.ITEMID AS HFIT_HEALTHASSESMENTUSERMODULE_CTID
        , CT_HFIT_HEALTHASSESMENTUSERMODULE.SYS_CHANGE_OPERATION AS HFIT_HEALTHASSESMENTUSERMODULE_CHANGE_OPERATION
          --, CT_HFIT_HEALTHASSESMENTUSERQUESTION.ITEMID AS HFIT_HEALTHASSESMENTUSERQUESTION_CTID
        , CT_HFIT_HEALTHASSESMENTUSERQUESTION.SYS_CHANGE_OPERATION AS HFIT_HEALTHASSESMENTUSERQUESTION_CHANGE_OPERATION
          --, CT_HFIT_HealthAssesmentUserQuestionGroupResults.ITEMID AS HFIT_HealthAssesmentUserQuestionGroupResults_CTID
        , CT_HFIT_HealthAssesmentUserQuestionGroupResults.SYS_CHANGE_OPERATION AS HFIT_HealthAssesmentUserQuestionGroupResults_CHANGE_OPERATION
          --, CT_HFIT_HEALTHASSESMENTUSERRISKAREA.ITEMID AS HFIT_HEALTHASSESMENTUSERRISKAREA_CTID
        , CT_HFIT_HEALTHASSESMENTUSERRISKAREA.SYS_CHANGE_OPERATION AS HFIT_HEALTHASSESMENTUSERRISKAREA_CHANGE_OPERATION
          --, CT_HFIT_HEALTHASSESMENTUSERRISKCATEGORY.ITEMID AS HFIT_HEALTHASSESMENTUSERRISKCATEGORY_CTID
        , CT_HFIT_HEALTHASSESMENTUSERRISKCATEGORY.SYS_CHANGE_OPERATION AS HFIT_HEALTHASSESMENTUSERRISKCATEGORY_CHANGE_OPERATION
          --, CT_HFIT_HEALTHASSESMENTUSERSTARTED.ITEMID AS HFIT_HEALTHASSESMENTUSERSTARTED_CTID
        , CT_HFIT_HEALTHASSESMENTUSERSTARTED.SYS_CHANGE_OPERATION AS HFIT_HEALTHASSESMENTUSERSTARTED_CHANGE_OPERATION

          --Get the TYPE of change ID NUMBER
          --, CT_CMS_USER.SYS_CHANGE_VERSION AS CT_CMS_USER_SCV
          --, CT_CMS_USERSETTINGS.SYS_CHANGE_VERSION AS CT_CMS_USERSETTINGS_SCV
          --, CT_CMS_SITE.SYS_CHANGE_VERSION AS CT_CMS_SITE_SCV
          --, CT_CMS_USERSITE.SYS_CHANGE_VERSION AS CT_CMS_USERSITE_SCV
          --, CT_HFIT_ACCOUNT.SYS_CHANGE_VERSION AS CT_HFIT_ACCOUNT_SCV
          --, CT_HFIT_HealthAssesmentUserAnswers.SYS_CHANGE_VERSION AS CT_HFIT_HealthAssesmentUserAnswers_SCV
          --, CT_HFIT_HEALTHASSESMENTUSERMODULE.SYS_CHANGE_VERSION AS CT_HFIT_HEALTHASSESMENTUSERMODULE_SCV
          --, CT_HFIT_HEALTHASSESMENTUSERQUESTION.SYS_CHANGE_VERSION AS CT_HFIT_HEALTHASSESMENTUSERQUESTION_SCV
          --, CT_HFIT_HealthAssesmentUserQuestionGroupResults.SYS_CHANGE_VERSION AS CT_HFIT_HealthAssesmentUserQuestionGroupResults_SCV
          --, CT_HFIT_HEALTHASSESMENTUSERRISKAREA.SYS_CHANGE_VERSION AS CT_HFIT_HEALTHASSESMENTUSERRISKAREA_SCV
          --, CT_HFIT_HEALTHASSESMENTUSERRISKCATEGORY.SYS_CHANGE_VERSION AS CT_HFIT_HEALTHASSESMENTUSERRISKCATEGORY_SCV
          --, CT_HFIT_HEALTHASSESMENTUSERSTARTED.SYS_CHANGE_VERSION AS CT_HFIT_HEALTHASSESMENTUSERSTARTED_SCV

        , HAUSERANSWERS.ITEMMODIFIEDWHEN AS LASTMODIFIEDDATE
        , 0 AS DELETEFLG
        , CASE
              WHEN HAUserStarted.HADocumentConfigID IS NULL
                  THEN 'SHORT_VER'
              WHEN HAUserStarted.HADocumentConfigID IS NOT NULL
                  THEN 'LONG_VER'
              ELSE 'UNKNOWN'
          END AS HealthAssessmentType
        , 0 AS LASTUPDATEID
        , GETDATE () AS LASTLOADEDDATE
        , @@Servername AS SVR
        , DB_NAME () AS DBNAME
        , 0 AS DeletedFlg
   --INTO ##TEMP_HA_DATA
          FROM
               dbo.DIM_EDW_HFIT_HEALTHASSESMENTUSERSTARTED AS HAUSERSTARTED
                    INNER JOIN dbo.DIM_EDW_CMS_USER AS CMSUSER
                       ON HAUSERSTARTED.USERID = CMSUSER.USERID
                    INNER JOIN dbo.DIM_EDW_CMS_USERSETTINGS AS USERSETTINGS
                       ON
                          USERSETTINGS.USERSETTINGSUSERID = CMSUSER.USERID AND
                          HFITUSERMPINUMBER >= 0 AND
                          HFITUSERMPINUMBER IS NOT NULL
                    INNER JOIN dbo.DIM_EDW_CMS_USERSITE AS USERSITE
                       ON CMSUSER.USERID = USERSITE.USERID
                    INNER JOIN DBO.FACT_CMS_SITE AS CMSSITE
                       ON USERSITE.SITEID = CMSSITE.SITEID
                    INNER JOIN DBO.FACT_HFIT_ACCOUNT AS ACCT
                       ON ACCT.SITEID = CMSSITE.SITEID
                    
				INNER JOIN dbo.DIM_EDW_HFIT_HEALTHASSESMENTUSERMODULE AS HAUSERMODULE
                       ON HAUSERSTARTED.ITEMID = HAUSERMODULE.HASTARTEDITEMID
				    
                    INNER JOIN dbo.DIM_EDW_TEMP_VIEW_HFIT_HACAMPAIGN_JOINED AS VHCJ
                       ON
                          VHCJ.NODEGUID = HAUSERSTARTED.HACAMPAIGNNODEGUID AND
                          VHCJ.NODESITEID = USERSITE.SITEID AND
                          VHCJ.DOCUMENTCULTURE = 'en-US'
                    INNER JOIN dbo.DIM_EDW_TEMP_VIEW_HFIT_HEALTHASSESSMENT_JOINED AS VHAJ
                       ON VHAJ.DOCUMENTID = VHCJ.HEALTHASSESSMENTID
                    INNER JOIN dbo.DIM_EDW_HFIT_HEALTHASSESMENTUSERRISKCATEGORY AS HARISKCATEGORY
                       ON HAUSERMODULE.ITEMID = HARISKCATEGORY.HAMODULEITEMID
                    INNER JOIN dbo.DIM_EDW_HFit_HealthAssesmentUserRiskArea AS HAUSERRISKAREA
                       ON HARISKCATEGORY.ITEMID = HAUSERRISKAREA.HARISKCATEGORYITEMID
                    INNER JOIN dbo.DIM_EDW_HFit_HealthAssesmentUserQuestion AS HAUSERQUESTION
                       ON HAUSERRISKAREA.ITEMID = HAUSERQUESTION.HARISKAREAITEMID
				
--DBCC FREESYSTEMCACHE ('ALL');
--select * from information_schema.tables where table_name like '%View_EDW_HealthAssesmentQuestions%'
--select * from DIM_View_EDW_HealthAssesmentQuestions
                    INNER JOIN dbo.DIM_View_EDW_HealthAssesmentQuestions AS HAQUESTIONSVIEW
                       ON HAUSERQUESTION.HAQUESTIONNODEGUID = HAQUESTIONSVIEW.NODEGUID
                    LEFT JOIN dbo.DIM_EDW_HFit_HealthAssesmentUserQuestionGroupResults AS HAUSERQUESTIONGROUPRESULTS
                       ON HAUSERRISKAREA.ITEMID = HAUSERQUESTIONGROUPRESULTS.HARISKAREAITEMID
                    INNER JOIN dbo.DIM_EDW_HFIT_HealthAssesmentUserAnswers AS HAUSERANSWERS
                       ON HAUSERQUESTION.ITEMID = HAUSERANSWERS.HAQUESTIONITEMID 
               --Add in the change tracking data
                    LEFT JOIN CHANGETABLE (CHANGES dbo.FACT_CMS_USERSETTINGS , NULL) AS CT_CMS_USERSETTINGS
                       ON USERSETTINGS.USERSETTINGSID = CT_CMS_USERSETTINGS.USERSETTINGSID
                    LEFT JOIN CHANGETABLE (CHANGES dbo.FACT_CMS_USER , NULL) AS CT_CMS_USER
                       ON CMSUSER.USERID = CT_CMS_USER.USERID
                    LEFT JOIN CHANGETABLE (CHANGES dbo.FACT_CMS_SITE , NULL) AS CT_CMS_SITE
                       ON CMSSITE.SITEID = CT_CMS_SITE.SITEID
                    LEFT JOIN CHANGETABLE (CHANGES dbo.FACT_CMS_USERSITE , NULL) AS CT_CMS_USERSITE
                       ON USERSITE.USERSITEID = CT_CMS_USERSITE.USERSITEID
                    LEFT JOIN CHANGETABLE (CHANGES dbo.FACT_HFIT_ACCOUNT , NULL) AS CT_HFIT_ACCOUNT
                       ON ACCT.ACCOUNTID = CT_HFIT_ACCOUNT.ACCOUNTID
                    LEFT JOIN CHANGETABLE (CHANGES dbo.FACT_HFIT_HACAMPAIGN , NULL) AS CT_HFIT_HACAMPAIGN
                       ON VHCJ.HACAMPAIGNID = CT_HFIT_HACAMPAIGN.HACAMPAIGNID
                    LEFT JOIN CHANGETABLE (CHANGES dbo.FACT_HFit_HealthAssesmentUserAnswers , NULL) AS CT_HFIT_HealthAssesmentUserAnswers
                       ON HAUSERANSWERS.ITEMID = CT_HFIT_HealthAssesmentUserAnswers.ITEMID
                    LEFT JOIN CHANGETABLE (CHANGES dbo.FACT_HFit_HEALTHASSESMENTUSERMODULE , NULL) AS CT_HFIT_HEALTHASSESMENTUSERMODULE
                       ON HAUSERMODULE.ITEMID = CT_HFIT_HEALTHASSESMENTUSERMODULE.ITEMID
                    LEFT JOIN CHANGETABLE (CHANGES dbo.FACT_HFit_HEALTHASSESMENTUSERQUESTION , NULL) AS CT_HFIT_HEALTHASSESMENTUSERQUESTION
                       ON HAUSERQUESTION.ITEMID = CT_HFIT_HEALTHASSESMENTUSERQUESTION.ITEMID
                    LEFT JOIN CHANGETABLE (CHANGES dbo.FACT_HFit_HealthAssesmentUserQuestionGroupResults , NULL) AS CT_HFIT_HealthAssesmentUserQuestionGroupResults
                       ON HAUSERQUESTIONGROUPRESULTS.ITEMID = CT_HFIT_HealthAssesmentUserQuestionGroupResults.ITEMID
                    LEFT JOIN CHANGETABLE (CHANGES dbo.FACT_HFit_HEALTHASSESMENTUSERRISKAREA , NULL) AS CT_HFIT_HEALTHASSESMENTUSERRISKAREA
                       ON HAUSERRISKAREA.ITEMID = CT_HFIT_HEALTHASSESMENTUSERRISKAREA.ITEMID
                    LEFT JOIN CHANGETABLE (CHANGES dbo.FACT_HFit_HEALTHASSESMENTUSERRISKCATEGORY , NULL) AS CT_HFIT_HEALTHASSESMENTUSERRISKCATEGORY
                       ON HARISKCATEGORY.ITEMID = CT_HFIT_HEALTHASSESMENTUSERRISKCATEGORY.ITEMID
                    LEFT JOIN CHANGETABLE (CHANGES dbo.FACT_HFit_HEALTHASSESMENTUSERSTARTED , NULL) AS CT_HFIT_HEALTHASSESMENTUSERSTARTED
                       ON HAUSERSTARTED.ITEMID = CT_HFIT_HEALTHASSESMENTUSERSTARTED.ITEMID
          WHERE USERSETTINGS.HFITUSERMPINUMBER NOT IN (
          SELECT
                 REJECTMPICODE
                 FROM dbo.FACT_HFit_LKP_EDW_REJECTMPI) ;
go

--if exists (select * from sys.views where name = 'view_EDW_PullHAData_IDX')
--begin
--CREATE unique clustered INDEX [PI_view_EDW_PullHAData_IDX] ON [dbo].[view_EDW_PullHAData_IDX]
--(
--	CHANGETYPE ASC,PKHASHCODE, USERSTARTEDITEMID, USERID, USERMODULEITEMID, USERRISKCATEGORYITEMID, USERRISKAREAITEMID, USERQUESTIONITEMID, USERANSWERITEMID
--)
--end 
--else 
--    print 'WARNING: VIEW view_EDW_PullHAData_IDX MISSING' ;

GO
PRINT 'Executed view_EDW_PullHAData_IDX.sql';
GO
