
go
Print 'Executing View_EDW_HFIT_HealthAssesmentUserRiskArea_Joined.SQL'
go

if exists (select name from sys.views where name = 'View_EDW_HFIT_HealthAssesmentUserRiskArea_Joined')
    drop view View_EDW_HFIT_HealthAssesmentUserRiskArea_Joined;

go

CREATE VIEW View_EDW_HFIT_HealthAssesmentUserRiskArea_Joined
AS
select  
	   HAUSERRISKAREA.ITEMID AS USERRISKAREAITEMID
	   ,HAUSERRISKAREA.HARISKCATEGORYITEMID 
	   , HAUSERRISKAREA.CODENAME AS USERRISKAREACODENAME
	   , HAUSERRISKAREA.HARISKAREANODEGUID
	   , NULL AS HARISKAREAVERSIONID
	   , HAUSERRISKAREA.HARISKAREASCORE
	   , HAUSERRISKAREA.PREWEIGHTEDSCORE AS RISKAREAPREWEIGHTEDSCORE
	   , HAUSERRISKAREA.ITEMMODIFIEDWHEN AS HAUSERRISKAREA_ITEMMODIFIEDWHEN
	   , HAUSERRISKAREA.ItemModifiedWhen AS HAUSERRISKAREA_LASTMODIFIED   --HAUSERRISKAREA.LASTLOADEDDATE 
	   , 0 AS HAUSERRISKAREA_LastUpdateID   --HAUSERRISKAREA.LastUpdateID 

	   , HAUSERQUESTIONGROUPRESULTS.HARISKAREAITEMID
	   , HAUSERQUESTIONGROUPRESULTS.ItemID as HAUSERQUESTIONGROUPRESULTSItemID
	   , HAUSERQUESTIONGROUPRESULTS.POINTRESULTS
	   , HAUSERQUESTIONGROUPRESULTS.CODENAME AS QUESTIONGROUPCODENAME
	   , HAUSERQUESTIONGROUPRESULTS.LastModifiedDate AS HAUSERQUESTIONGROUPRESULTS_LASTMODIFIED	--HAUSERQUESTIONGROUPRESULTS.LASTLOADEDDATE 
	   , 0 AS HAUSERQUESTIONGROUPRESULTS_LastUpdateID	--HAUSERQUESTIONGROUPRESULTS.LastUpdateID 

	   , HAUSERRISKAREA.ItemModifiedWhen as  LastModifiedWhen
	   , 0 as LastUpdateID
	   , getdate() as LASTLOADEDDATE
	   , @@SERVERNAME as SVR
	   , DB_NAME() AS DBNAME
	   , 0 as DeletedFlg

--into DIM_EDW_HFit_HealthAssesmentUserRiskArea_Joined
from DBO.FACT_EDW_HFIT_HEALTHASSESMENTUSERRISKAREA AS HAUSERRISKAREA
              --ON HARISKCATEGORY.ITEMID = HAUSERRISKAREA.HARISKCATEGORYITEMID
LEFT JOIN DBO.FACT_EDW_HFIT_HEALTHASSESMENTUSERQUESTIONGROUPRESULTS AS HAUSERQUESTIONGROUPRESULTS
              ON HAUSERRISKAREA.ITEMID = HAUSERQUESTIONGROUPRESULTS.HARISKAREAITEMID

go
Print 'ExecutED View_EDW_HFIT_HealthAssesmentUserRiskArea_Joined.SQL'
go

