
/*---------------------------------------------------
drop table ##TEMP_HA_DATA 
go
select top 100 * from view_EDW_HealthAssesment_CT
where CHANGETYPE is NOT NULL
select * into ##TEMP_HA_DATA from view_EDW_HealthAssesment_CT
where CHANGETYPE is NOT NULL
*/
GO
PRINT 'Executing view_EDW_HealthAssesment_CT.sql';
GO
IF EXISTS (SELECT
           name
                  FROM sys.views
                  WHERE name = 'view_EDW_HealthAssesment_CT') 
    BEGIN
        DROP VIEW
        view_EDW_HealthAssesment_CT;
    END;
GO
CREATE VIEW view_EDW_HealthAssesment_CT
AS

--select * from DIM_View_EDW_HealthAssesmentQuestions
--select * from FACT_HFIT_HEALTHASSESMENTUSERQUESTIONGROUPRESULTS

SELECT
 HAUSERSTARTED.ITEMID AS USERSTARTEDITEMID
        , VHAJ.NODEGUID AS HEALTHASSESMENTUSERSTARTEDNODEGUID
        , HAUSERSTARTED.USERID
        , CMSUSER.USERGUID
        , USERSETTINGS.HFITUSERMPINUMBER
        , CMSSITE.SITEGUID
        , ACCT.ACCOUNTID
        , ACCT.ACCOUNTCD
        , ACCT.ACCOUNTNAME
        , HAUSERSTARTED.HASTARTEDDT
        , HAUSERSTARTED.HACOMPLETEDDT
        , HAUSERMODULE.ITEMID AS USERMODULEITEMID
        , HAUSERMODULE.CODENAME AS USERMODULECODENAME
        , HAUSERMODULE.HAMODULENODEGUID
        , VHAJ.NODEGUID AS CMSNODEGUID
        , NULL AS HAMODULEVERSIONID
        , HARISKCATEGORY.ITEMID AS USERRISKCATEGORYITEMID
        , HARISKCATEGORY.CODENAME AS USERRISKCATEGORYCODENAME
        , HARISKCATEGORY.HARISKCATEGORYNODEGUID
        , NULL AS HARISKCATEGORYVERSIONID
        , HAUSERRISKAREA.ITEMID AS USERRISKAREAITEMID
        , HAUSERRISKAREA.CODENAME AS USERRISKAREACODENAME
        , HAUSERRISKAREA.HARISKAREANODEGUID
        , NULL AS HARISKAREAVERSIONID
        , HAUSERQUESTION.ITEMID AS USERQUESTIONITEMID
        , HAQUESTIONSVIEW.TITLE
        , HAUSERQUESTION.HAQUESTIONNODEGUID AS HAQUESTIONGUID
        , HAUSERQUESTION.CODENAME AS USERQUESTIONCODENAME
        , NULL AS HAQUESTIONDOCUMENTID
        , NULL AS HAQUESTIONVERSIONID
        , HAUSERQUESTION.HAQUESTIONNODEGUID
        , HAUSERANSWERS.ITEMID AS USERANSWERITEMID
        , HAUSERANSWERS.HAANSWERNODEGUID
        , NULL AS HAANSWERVERSIONID
        , HAUSERANSWERS.CODENAME AS USERANSWERCODENAME
        , HAUSERANSWERS.HAANSWERVALUE
        , HAUSERMODULE.HAMODULESCORE
        , HARISKCATEGORY.HARISKCATEGORYSCORE
        , HAUSERRISKAREA.HARISKAREASCORE
        , HAUSERQUESTION.HAQUESTIONSCORE
        , HAUSERANSWERS.HAANSWERPOINTS
        , HAUSERQUESTIONGROUPRESULTS.POINTRESULTS
        , HAUSERANSWERS.UOMCODE
        , HAUSERSTARTED.HASCORE
        , HAUSERMODULE.PREWEIGHTEDSCORE AS MODULEPREWEIGHTEDSCORE
        , HARISKCATEGORY.PREWEIGHTEDSCORE AS RISKCATEGORYPREWEIGHTEDSCORE
        , HAUSERRISKAREA.PREWEIGHTEDSCORE AS RISKAREAPREWEIGHTEDSCORE
        , HAUSERQUESTION.PREWEIGHTEDSCORE AS QUESTIONPREWEIGHTEDSCORE
        , HAUSERQUESTIONGROUPRESULTS.CODENAME AS QUESTIONGROUPCODENAME
        , COALESCE ( CT_CMS_USER.SYS_CHANGE_OPERATION , CT_CMS_USERSETTINGS.SYS_CHANGE_OPERATION , CT_CMS_SITE.SYS_CHANGE_OPERATION , CT_CMS_USERSITE.SYS_CHANGE_OPERATION , CT_HFIT_ACCOUNT.SYS_CHANGE_OPERATION , CT_HFIT_HealthAssesmentUserAnswers.SYS_CHANGE_OPERATION , CT_HFIT_HEALTHASSESMENTUSERMODULE.SYS_CHANGE_OPERATION , CT_HFIT_HEALTHASSESMENTUSERQUESTION.SYS_CHANGE_OPERATION , CT_HFIT_HealthAssesmentUserQuestionGroupResults.SYS_CHANGE_OPERATION , CT_HFIT_HEALTHASSESMENTUSERRISKAREA.SYS_CHANGE_OPERATION , CT_HFIT_HEALTHASSESMENTUSERRISKCATEGORY.SYS_CHANGE_OPERATION , CT_HFIT_HEALTHASSESMENTUSERSTARTED.SYS_CHANGE_OPERATION) AS CHANGETYPE
        , HAUSERANSWERS.ITEMCREATEDWHEN
        , HAUSERANSWERS.ITEMMODIFIEDWHEN
        , HAUSERQUESTION.ISPROFESSIONALLYCOLLECTED
        , HARISKCATEGORY.ITEMMODIFIEDWHEN AS HARISKCATEGORY_ITEMMODIFIEDWHEN
        , HAUSERRISKAREA.ITEMMODIFIEDWHEN AS HAUSERRISKAREA_ITEMMODIFIEDWHEN
        , HAUSERQUESTION.ITEMMODIFIEDWHEN AS HAUSERQUESTION_ITEMMODIFIEDWHEN
        , HAUSERANSWERS.ITEMMODIFIEDWHEN AS HAUSERANSWERS_ITEMMODIFIEDWHEN
        , HAUSERSTARTED.HAPAPERFLG
        , HAUSERSTARTED.HATELEPHONICFLG
        , HAUSERSTARTED.HASTARTEDMODE
        , HAUSERSTARTED.HACOMPLETEDMODE
        , VHCJ.DOCUMENTCULTURE AS DOCUMENTCULTURE_VHCJ
        , HAQUESTIONSVIEW.DOCUMENTCULTURE AS DOCUMENTCULTURE_HAQUESTIONSVIEW
        , HAUSERSTARTED.HACAMPAIGNNODEGUID AS CAMPAIGNNODEGUID
        , VHCJ.HACAMPAIGNID
        , CAST ( HASHBYTES ( 'sha1' , ISNULL ( CAST ( HAUSERSTARTED.ITEMID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( VHAJ.NODEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERSTARTED.USERID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( CMSUSER.USERGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( USERSETTINGS.HFITUSERMPINUMBER AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( CMSSITE.SITEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( ACCT.ACCOUNTID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( ACCT.ACCOUNTCD AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( ACCT.ACCOUNTNAME AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERSTARTED.HASTARTEDDT AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERSTARTED.HACOMPLETEDDT AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERMODULE.ITEMID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERMODULE.CODENAME AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERMODULE.HAMODULENODEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( VHAJ.NODEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HARISKCATEGORY.ITEMID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HARISKCATEGORY.CODENAME AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HARISKCATEGORY.HARISKCATEGORYNODEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERRISKAREA.ITEMID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERRISKAREA.CODENAME AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERRISKAREA.HARISKAREANODEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.ITEMID AS NVARCHAR (100)) , '-') + ISNULL ( LEFT ( HAQUESTIONSVIEW.TITLE , 1000) , '-') + ISNULL ( CAST ( HAUSERQUESTION.HAQUESTIONNODEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.CODENAME AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.HAQUESTIONNODEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.ITEMID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.HAANSWERNODEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.CODENAME AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.HAANSWERVALUE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERMODULE.HAMODULESCORE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HARISKCATEGORY.HARISKCATEGORYSCORE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERRISKAREA.HARISKAREASCORE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.HAQUESTIONSCORE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.HAANSWERPOINTS AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERQUESTIONGROUPRESULTS.POINTRESULTS AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.UOMCODE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERSTARTED.HASCORE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERMODULE.PREWEIGHTEDSCORE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HARISKCATEGORY.PREWEIGHTEDSCORE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERRISKAREA.PREWEIGHTEDSCORE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.PREWEIGHTEDSCORE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERQUESTIONGROUPRESULTS.CODENAME AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.ITEMCREATEDWHEN AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.ITEMMODIFIEDWHEN AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.ISPROFESSIONALLYCOLLECTED AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HARISKCATEGORY.ITEMMODIFIEDWHEN AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERRISKAREA.ITEMMODIFIEDWHEN AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.ITEMMODIFIEDWHEN AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.ITEMMODIFIEDWHEN AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERSTARTED.HAPAPERFLG AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERSTARTED.HATELEPHONICFLG AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERSTARTED.HASTARTEDMODE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERSTARTED.HACOMPLETEDMODE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERSTARTED.HACAMPAIGNNODEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( VHCJ.HACAMPAIGNID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.ITEMMODIFIEDWHEN AS NVARCHAR (100)) , '-')) AS VARCHAR (100)) AS HASHCODE
        , CAST ( HASHBYTES ( 'sha1' , ISNULL ( CAST ( HAUSERSTARTED.ITEMID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( VHAJ.NODEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( USERGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( SITEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( ACCT.ACCOUNTID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( ACCOUNTCD AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAUSERMODULE.ITEMID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAMODULENODEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( VHAJ.NODEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HARISKCATEGORY.ITEMID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HARISKCATEGORYNODEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HARISKCATEGORY.CODENAME AS VARCHAR (100)) , '-') + ISNULL ( CAST ( HARISKCATEGORY.HARISKCATEGORYNODEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAUSERRISKAREA.ITEMID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HARISKAREANODEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAUSERRISKAREA.CODENAME AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.ITEMID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.HAQUESTIONNODEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.CODENAME AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAQUESTIONNODEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.ITEMID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAANSWERNODEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAUSERSTARTED.HACAMPAIGNNODEGUID AS VARCHAR (50)) , '-')) AS VARCHAR (100)) AS PKHASHCODE
          --, COALESCE ( CT_CMS_USER.USERID , CT_CMS_USERSETTINGS.USERSETTINGSID , CT_CMS_SITE.SITEID , CT_CMS_USERSITE.USERSITEID , CT_HFIT_ACCOUNT.ACCOUNTID , CT_HFIT_HealthAssesmentUserAnswers.ITEMID , CT_HFIT_HEALTHASSESMENTUSERMODULE.ITEMID , CT_HFIT_HEALTHASSESMENTUSERQUESTION.ITEMID , CT_HFIT_HealthAssesmentUserQuestionGroupResults.ITEMID , CT_HFIT_HEALTHASSESMENTUSERRISKAREA.ITEMID , CT_HFIT_HEALTHASSESMENTUSERRISKCATEGORY.ITEMID , CT_HFIT_HEALTHASSESMENTUSERSTARTED.ITEMID) AS CHANGED_FLG
        , NULL AS CHANGED_FLG

          --*************************************
          --join changes to the records 

          --, CT_CMS_USER.USERID AS CT_CMS_USER_USERID
        , CT_CMS_USER.SYS_CHANGE_OPERATION AS CT_CMS_USER_CHANGE_OPERATION
          --, CT_CMS_USERSETTINGS.USERSETTINGSID AS CT_USERSETTINGSID
        , CT_CMS_USERSETTINGS.SYS_CHANGE_OPERATION AS CT_USERSETTINGSID_CHANGE_OPERATION
          --, CT_CMS_SITE.SITEID AS SITEID_CTID
        , CT_CMS_SITE.SYS_CHANGE_OPERATION AS SITEID_CHANGE_OPERATION
          --, CT_CMS_USERSITE.USERSITEID AS USERSITEID_CTID
        , CT_CMS_USERSITE.SYS_CHANGE_OPERATION AS USERSITEID_CHANGE_OPERATION
          --, CT_HFIT_ACCOUNT.ACCOUNTID AS ACCOUNTID_CTID
        , CT_HFIT_ACCOUNT.SYS_CHANGE_OPERATION AS ACCOUNTID__CHANGE_OPERATION
          --, CT_HFIT_HealthAssesmentUserAnswers.ITEMID AS HAUSERANSWERS_CTID
        , CT_HFIT_HealthAssesmentUserAnswers.SYS_CHANGE_OPERATION AS HAUSERANSWERS_CHANGE_OPERATION
          --, CT_HFIT_HEALTHASSESMENTUSERMODULE.ITEMID AS HFIT_HEALTHASSESMENTUSERMODULE_CTID
        , CT_HFIT_HEALTHASSESMENTUSERMODULE.SYS_CHANGE_OPERATION AS HFIT_HEALTHASSESMENTUSERMODULE_CHANGE_OPERATION
          --, CT_HFIT_HEALTHASSESMENTUSERQUESTION.ITEMID AS HFIT_HEALTHASSESMENTUSERQUESTION_CTID
        , CT_HFIT_HEALTHASSESMENTUSERQUESTION.SYS_CHANGE_OPERATION AS HFIT_HEALTHASSESMENTUSERQUESTION_CHANGE_OPERATION
          --, CT_HFIT_HealthAssesmentUserQuestionGroupResults.ITEMID AS HFIT_HealthAssesmentUserQuestionGroupResults_CTID
        , CT_HFIT_HealthAssesmentUserQuestionGroupResults.SYS_CHANGE_OPERATION AS HFIT_HealthAssesmentUserQuestionGroupResults_CHANGE_OPERATION
          --, CT_HFIT_HEALTHASSESMENTUSERRISKAREA.ITEMID AS HFIT_HEALTHASSESMENTUSERRISKAREA_CTID
        , CT_HFIT_HEALTHASSESMENTUSERRISKAREA.SYS_CHANGE_OPERATION AS HFIT_HEALTHASSESMENTUSERRISKAREA_CHANGE_OPERATION
          --, CT_HFIT_HEALTHASSESMENTUSERRISKCATEGORY.ITEMID AS HFIT_HEALTHASSESMENTUSERRISKCATEGORY_CTID
        , CT_HFIT_HEALTHASSESMENTUSERRISKCATEGORY.SYS_CHANGE_OPERATION AS HFIT_HEALTHASSESMENTUSERRISKCATEGORY_CHANGE_OPERATION
          --, CT_HFIT_HEALTHASSESMENTUSERSTARTED.ITEMID AS HFIT_HEALTHASSESMENTUSERSTARTED_CTID
        , CT_HFIT_HEALTHASSESMENTUSERSTARTED.SYS_CHANGE_OPERATION AS HFIT_HEALTHASSESMENTUSERSTARTED_CHANGE_OPERATION

          --Get the TYPE of change ID NUMBER
          , CT_CMS_USER.SYS_CHANGE_VERSION AS CT_CMS_USER_SCV
          , CT_CMS_USERSETTINGS.SYS_CHANGE_VERSION AS CT_CMS_USERSETTINGS_SCV
          , CT_CMS_SITE.SYS_CHANGE_VERSION AS CT_CMS_SITE_SCV
          , CT_CMS_USERSITE.SYS_CHANGE_VERSION AS CT_CMS_USERSITE_SCV
          , CT_HFIT_ACCOUNT.SYS_CHANGE_VERSION AS CT_HFIT_ACCOUNT_SCV
          , CT_HFIT_HealthAssesmentUserAnswers.SYS_CHANGE_VERSION AS CT_HFIT_HealthAssesmentUserAnswers_SCV
          , CT_HFIT_HEALTHASSESMENTUSERMODULE.SYS_CHANGE_VERSION AS CT_HFIT_HEALTHASSESMENTUSERMODULE_SCV
          , CT_HFIT_HEALTHASSESMENTUSERQUESTION.SYS_CHANGE_VERSION AS CT_HFIT_HEALTHASSESMENTUSERQUESTION_SCV
          , CT_HFIT_HealthAssesmentUserQuestionGroupResults.SYS_CHANGE_VERSION AS CT_HFIT_HealthAssesmentUserQuestionGroupResults_SCV
          , CT_HFIT_HEALTHASSESMENTUSERRISKAREA.SYS_CHANGE_VERSION AS CT_HFIT_HEALTHASSESMENTUSERRISKAREA_SCV
          , CT_HFIT_HEALTHASSESMENTUSERRISKCATEGORY.SYS_CHANGE_VERSION AS CT_HFIT_HEALTHASSESMENTUSERRISKCATEGORY_SCV
          , CT_HFIT_HEALTHASSESMENTUSERSTARTED.SYS_CHANGE_VERSION AS CT_HFIT_HEALTHASSESMENTUSERSTARTED_SCV

        , HAUSERANSWERS.ITEMMODIFIEDWHEN AS LastModifiedDATE
        , 0 AS DELETEFLG
        , CASE
              WHEN HAUserStarted.HADocumentConfigID IS NULL
                  THEN 'SHORT_VER'
              WHEN HAUserStarted.HADocumentConfigID IS NOT NULL
                  THEN 'LONG_VER'
              ELSE 'UNKNOWN'
          END AS HealthAssessmentType
        , 0 AS LASTUPDATEID
        --, GETDATE () AS LASTLOADEDDATE
        , HAUSERSTARTED.SVR 
        , HAUSERSTARTED.DBNAME
        , 0 AS DeletedFlg                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	   , LASTLOADEDDATE
		  --, change_tracking_is_column_in_mask (COLUMNPROPERTY (OBJECT_ID ('CMS_UserSite') , 'SiteID', 'columnid') , CTE.sys_change_columns) AS [SiteID_cg] 
		  --, change_tracking_is_column_in_mask (COLUMNPROPERTY (OBJECT_ID ('CMS_UserSite') , 'UserID', 'columnid') , CTE.sys_change_columns) AS [UserID_cg] 
		  --, change_tracking_is_column_in_mask (COLUMNPROPERTY (OBJECT_ID ('CMS_UserSite') , 'UserPreferredCurrencyID', 'columnid') , CTE.sys_change_columns) AS [UserPreferredCurrencyID_cg] 
       FROM FACT_HFIT_HEALTHASSESMENTUSERSTARTED AS HAUSERSTARTED
                INNER JOIN DBO.FACT_CMS_USER AS CMSUSER
                    ON HAUSERSTARTED.USERID = CMSUSER.USERID
                   AND HAUSERSTARTED.SVR = CMSUSER.SVR
                   AND HAUSERSTARTED.DBNAME = CMSUSER.DBNAME
                INNER JOIN DBO.FACT_CMS_USERSETTINGS AS USERSETTINGS
                    ON USERSETTINGS.USERSETTINGSUSERID = CMSUSER.USERID
                   AND USERSETTINGS.HFITUSERMPINUMBER >= 0
                   AND USERSETTINGS.HFITUSERMPINUMBER IS NOT NULL
                   AND USERSETTINGS.SVR = CMSUSER.SVR
                   AND USERSETTINGS.DBNAME = CMSUSER.DBNAME
                INNER JOIN DBO.FACT_CMS_USERSITE AS USERSITE
                    ON CMSUSER.USERID = USERSITE.USERID
                   AND CMSUSER.SVR = USERSITE.SVR
                   AND CMSUSER.DBNAME = USERSITE.DBNAME
                INNER JOIN DBO.FACT_CMS_SITE AS CMSSITE
                    ON USERSITE.SITEID = CMSSITE.SITEID
                   AND USERSITE.SVR = CMSSITE.SVR
                   AND USERSITE.DBNAME = CMSSITE.DBNAME
                INNER JOIN DBO.FACT_HFIT_ACCOUNT AS ACCT
                    ON ACCT.SITEID = CMSSITE.SITEID
                   AND ACCT.SVR = CMSSITE.SVR
                   AND ACCT.DBNAME = CMSSITE.DBNAME
                INNER JOIN DBO.FACT_HFIT_HEALTHASSESMENTUSERMODULE AS HAUSERMODULE
                    ON HAUSERSTARTED.ITEMID = HAUSERMODULE.HASTARTEDITEMID
                   AND HAUSERSTARTED.SVR = HAUSERMODULE.SVR
                   AND HAUSERSTARTED.DBNAME = HAUSERMODULE.DBNAME
                INNER JOIN DBO.DIM_VIEW_HFIT_HACAMPAIGN_JOINED AS VHCJ
                    ON VHCJ.NODEGUID = HAUSERSTARTED.HACAMPAIGNNODEGUID
                   AND VHCJ.NODESITEID = USERSITE.SITEID
                   AND VHCJ.DOCUMENTCULTURE = 'en-US'
                   AND VHCJ.SVR = USERSITE.SVR
                   AND VHCJ.DBNAME = USERSITE.DBNAME
                INNER JOIN DBO.DIM_VIEW_HFIT_HEALTHASSESSMENT_JOINED AS VHAJ
                    ON VHAJ.DOCUMENTID = VHCJ.HEALTHASSESSMENTID
                   AND VHAJ.SVR = VHCJ.SVR
                   AND VHAJ.DBNAME = VHCJ.DBNAME
                INNER JOIN DBO.FACT_HFIT_HEALTHASSESMENTUSERRISKCATEGORY AS HARISKCATEGORY
                    ON HAUSERMODULE.ITEMID = HARISKCATEGORY.HAMODULEITEMID
                   AND HAUSERMODULE.SVR = HARISKCATEGORY.SVR
                   AND HAUSERMODULE.DBNAME = HARISKCATEGORY.DBNAME
                INNER JOIN DBO.FACT_HFIT_HEALTHASSESMENTUSERRISKAREA AS HAUSERRISKAREA
                    ON HARISKCATEGORY.ITEMID = HAUSERRISKAREA.HARISKCATEGORYITEMID
                   AND HARISKCATEGORY.SVR = HAUSERRISKAREA.SVR
                   AND HARISKCATEGORY.DBNAME = HAUSERRISKAREA.DBNAME
                INNER JOIN DBO.FACT_HFIT_HEALTHASSESMENTUSERQUESTION AS HAUSERQUESTION
                    ON HAUSERRISKAREA.ITEMID = HAUSERQUESTION.HARISKAREAITEMID
                   AND HAUSERRISKAREA.SVR = HAUSERQUESTION.SVR
                   AND HAUSERRISKAREA.DBNAME = HAUSERQUESTION.DBNAME
                INNER JOIN DBO.DIM_View_EDW_HealthAssesmentQuestions AS HAQUESTIONSVIEW
                    ON HAUSERQUESTION.HAQUESTIONNODEGUID = HAQUESTIONSVIEW.NODEGUID
                   AND HAUSERQUESTION.SVR = HAQUESTIONSVIEW.SVR
                   AND HAUSERQUESTION.DBNAME = HAQUESTIONSVIEW.DBNAME
                LEFT OUTER JOIN DBO.FACT_HFIT_HEALTHASSESMENTUSERQUESTIONGROUPRESULTS AS HAUSERQUESTIONGROUPRESULTS
                    ON HAUSERRISKAREA.ITEMID = HAUSERQUESTIONGROUPRESULTS.HARISKAREAITEMID
                   AND HAUSERRISKAREA.SVR = HAUSERQUESTIONGROUPRESULTS.SVR
                   AND HAUSERRISKAREA.DBNAME = HAUSERQUESTIONGROUPRESULTS.DBNAME
                INNER JOIN DBO.FACT_HFIT_HEALTHASSESMENTUSERANSWERS AS HAUSERANSWERS
                    ON HAUSERQUESTION.ITEMID = HAUSERANSWERS.HAQUESTIONITEMID
                   AND HAUSERQUESTION.SVR = HAUSERANSWERS.SVR
                   AND HAUSERQUESTION.DBNAME = HAUSERANSWERS.DBNAME 
                LEFT JOIN CHANGETABLE (CHANGES FACT_CMS_USERSETTINGS, NULL) AS CT_CMS_USERSETTINGS
                    ON USERSETTINGS.USERSETTINGSID = CT_CMS_USERSETTINGS.USERSETTINGSID
                   AND USERSETTINGS.SVR = CT_CMS_USERSETTINGS.SVR
                   AND USERSETTINGS.DBNAME = CT_CMS_USERSETTINGS.DBNAME
                LEFT JOIN CHANGETABLE (CHANGES DBO.FACT_CMS_USER, NULL) AS CT_CMS_USER
                    ON CMSUSER.USERID = CT_CMS_USER.USERID
                   AND CMSUSER.SVR = CT_CMS_USER.SVR
                   AND CMSUSER.DBNAME = CT_CMS_USER.DBNAME
                LEFT OUTER JOIN CHANGETABLE (CHANGES DBO.FACT_CMS_SITE, NULL) AS CT_CMS_SITE
                    ON CMSSITE.SITEID = CT_CMS_SITE.SITEID
                   AND CMSSITE.SVR = CT_CMS_SITE.SVR
                   AND CMSSITE.DBNAME = CT_CMS_SITE.DBNAME
                LEFT OUTER JOIN CHANGETABLE (CHANGES DBO.FACT_CMS_USERSITE, NULL) AS CT_CMS_USERSITE
                    ON USERSITE.USERSITEID = CT_CMS_USERSITE.USERSITEID
                   AND USERSITE.SVR = CT_CMS_USERSITE.SVR
                   AND USERSITE.DBNAME = CT_CMS_USERSITE.DBNAME
                LEFT OUTER JOIN CHANGETABLE (CHANGES DBO.FACT_HFIT_ACCOUNT, NULL) AS CT_HFIT_ACCOUNT
                    ON ACCT.ACCOUNTID = CT_HFIT_ACCOUNT.ACCOUNTID
                   AND ACCT.SVR = CT_HFIT_ACCOUNT.SVR
                   AND ACCT.DBNAME = CT_HFIT_ACCOUNT.DBNAME
                LEFT OUTER JOIN CHANGETABLE (CHANGES DBO.FACT_HFIT_HACAMPAIGN, NULL) AS CT_HFIT_HACAMPAIGN
                    ON VHCJ.HACAMPAIGNID = CT_HFIT_HACAMPAIGN.HACAMPAIGNID
                   AND VHCJ.SVR = CT_HFIT_HACAMPAIGN.SVR
                   AND VHCJ.DBNAME = CT_HFIT_HACAMPAIGN.DBNAME
                LEFT OUTER JOIN CHANGETABLE (CHANGES DBO.FACT_HFIT_HEALTHASSESMENTUSERANSWERS, NULL) AS CT_HFIT_HEALTHASSESMENTUSERANSWERS
                    ON HAUSERANSWERS.ITEMID = CT_HFIT_HEALTHASSESMENTUSERANSWERS.ITEMID
                   AND HAUSERANSWERS.SVR = CT_HFIT_HEALTHASSESMENTUSERANSWERS.SVR
                   AND HAUSERANSWERS.DBNAME = CT_HFIT_HEALTHASSESMENTUSERANSWERS.DBNAME
                LEFT OUTER JOIN CHANGETABLE (CHANGES DBO.FACT_HFIT_HEALTHASSESMENTUSERMODULE, NULL) AS CT_HFIT_HEALTHASSESMENTUSERMODULE
                    ON HAUSERMODULE.ITEMID = CT_HFIT_HEALTHASSESMENTUSERMODULE.ITEMID
                   AND HAUSERMODULE.SVR = CT_HFIT_HEALTHASSESMENTUSERMODULE.SVR
                   AND HAUSERMODULE.DBNAME = CT_HFIT_HEALTHASSESMENTUSERMODULE.DBNAME
                LEFT OUTER JOIN CHANGETABLE (CHANGES DBO.FACT_HFIT_HEALTHASSESMENTUSERQUESTION, NULL) AS CT_HFIT_HEALTHASSESMENTUSERQUESTION
                    ON HAUSERQUESTION.ITEMID = CT_HFIT_HEALTHASSESMENTUSERQUESTION.ITEMID
                   AND HAUSERQUESTION.SVR = CT_HFIT_HEALTHASSESMENTUSERQUESTION.SVR
                   AND HAUSERQUESTION.DBNAME = CT_HFIT_HEALTHASSESMENTUSERQUESTION.DBNAME
                LEFT OUTER JOIN CHANGETABLE (CHANGES DBO.FACT_HFIT_HEALTHASSESMENTUSERQUESTIONGROUPRESULTS, NULL) AS CT_HFIT_HEALTHASSESMENTUSERQUESTIONGROUPRESULTS
                    ON HAUSERQUESTIONGROUPRESULTS.ITEMID = CT_HFIT_HEALTHASSESMENTUSERQUESTIONGROUPRESULTS.ITEMID
                   AND HAUSERQUESTIONGROUPRESULTS.SVR = CT_HFIT_HEALTHASSESMENTUSERQUESTIONGROUPRESULTS.SVR
                   AND HAUSERQUESTIONGROUPRESULTS.DBNAME = CT_HFIT_HEALTHASSESMENTUSERQUESTIONGROUPRESULTS.DBNAME
                LEFT OUTER JOIN CHANGETABLE (CHANGES DBO.FACT_HFIT_HEALTHASSESMENTUSERRISKAREA, NULL) AS CT_HFIT_HEALTHASSESMENTUSERRISKAREA
                    ON HAUSERRISKAREA.ITEMID = CT_HFIT_HEALTHASSESMENTUSERRISKAREA.ITEMID
                   AND HAUSERRISKAREA.SVR = CT_HFIT_HEALTHASSESMENTUSERRISKAREA.SVR
                   AND HAUSERRISKAREA.DBNAME = CT_HFIT_HEALTHASSESMENTUSERRISKAREA.DBNAME
                LEFT OUTER JOIN CHANGETABLE (CHANGES DBO.FACT_HFIT_HEALTHASSESMENTUSERRISKCATEGORY, NULL) AS CT_HFIT_HEALTHASSESMENTUSERRISKCATEGORY
                    ON HARISKCATEGORY.ITEMID = CT_HFIT_HEALTHASSESMENTUSERRISKCATEGORY.ITEMID
                   AND HARISKCATEGORY.SVR = CT_HFIT_HEALTHASSESMENTUSERRISKCATEGORY.SVR
                   AND HARISKCATEGORY.DBNAME = CT_HFIT_HEALTHASSESMENTUSERRISKCATEGORY.DBNAME
                LEFT OUTER JOIN CHANGETABLE (CHANGES DBO.FACT_HFIT_HEALTHASSESMENTUSERSTARTED, NULL) AS CT_HFIT_HEALTHASSESMENTUSERSTARTED
                    ON HAUSERSTARTED.ITEMID = CT_HFIT_HEALTHASSESMENTUSERSTARTED.ITEMID
                   AND HAUSERSTARTED.SVR = CT_HFIT_HEALTHASSESMENTUSERSTARTED.SVR
                   AND HAUSERSTARTED.DBNAME = CT_HFIT_HEALTHASSESMENTUSERSTARTED.DBNAME
       WHERE USERSETTINGS.HFITUSERMPINUMBER NOT IN (
    SELECT
    FACT_HFIT_LKP_EDW_REJECTMPI.REJECTMPICODE
           FROM DBO.FACT_HFIT_LKP_EDW_REJECTMPI);

GO
PRINT 'GEN CI_FACT_FACT_HFIT_HEALTHASSESMENTUSERANSWERS00';
GO

IF NOT EXISTS (SELECT name
                      FROM sys.indexes
                      WHERE name = 'CI_FACT_FACT_HFIT_HEALTHASSESMENTUSERANSWERS00') 
    BEGIN
        CREATE NONCLUSTERED INDEX CI_FACT_FACT_HFIT_HEALTHASSESMENTUSERANSWERS00
        ON dbo.FACT_HFIT_HEALTHASSESMENTUSERANSWERS (SVR, DBNAME, HAQuestionItemID) 
        INCLUDE (HAAnswerPoints, ItemCreatedWhen, ItemModifiedWhen, HAAnswerValue, UOMCode, CodeName, HAAnswerNodeGUID, ItemID) ;
    END;

IF NOT EXISTS (SELECT name
                      FROM sys.indexes
                      WHERE name = 'CI_FACT_FACT_HFIT_HEALTHASSESMENTUSERANSWERS01') 
    BEGIN
        CREATE NONCLUSTERED INDEX CI_FACT_FACT_HFIT_HEALTHASSESMENTUSERANSWERS01
        ON dbo.FACT_HFit_HealthAssesmentUserRiskCategory (HAModuleItemID, SVR, DBNAME) 
        INCLUDE (ItemModifiedWhen, HARiskCategoryScore, CodeName, PreWeightedScore, HARiskCategoryNodeGUID, ItemID) ;
    END;

IF NOT EXISTS (SELECT name
                      FROM sys.indexes
                      WHERE name = 'CI_FACT_FACT_HFIT_HEALTHASSESMENTUSERANSWERS02') 
    BEGIN
        CREATE NONCLUSTERED INDEX CI_FACT_FACT_HFIT_HEALTHASSESMENTUSERANSWERS02
        ON dbo.FACT_HFit_HealthAssesmentUserRiskArea (HARiskCategoryItemID, ItemID, SVR, DBNAME) 
        INCLUDE (HARiskAreaScore, ItemModifiedWhen, CodeName, PreWeightedScore, HARiskAreaNodeGUID) ;
    END;

IF NOT EXISTS (SELECT name
                      FROM sys.indexes
                      WHERE name = 'CI_FACT_FACT_HFIT_HEALTHASSESMENTUSERANSWERS03') 
    BEGIN
        CREATE NONCLUSTERED INDEX CI_FACT_FACT_HFIT_HEALTHASSESMENTUSERANSWERS03
        ON dbo.FACT_HFit_HealthAssesmentUserModule (HAStartedItemID, SVR, DBNAME) 
        INCLUDE (HAModuleScore, CodeName, PreWeightedScore, HAModuleNodeGUID, ItemID) ;
    END;

IF NOT EXISTS (SELECT name
                      FROM sys.indexes
                      WHERE name = 'PI_FACT_HFit_HealthAssesmentUserStarted00') 
    BEGIN
CREATE NONCLUSTERED INDEX PI_FACT_HFit_HealthAssesmentUserStarted00
ON [dbo].[FACT_HFit_HealthAssesmentUserStarted] ([HACampaignNodeGUID],[SVR],[DBNAME])
INCLUDE ([UserID],[ItemID])
END ;
GO
PRINT 'Executed view_EDW_HealthAssesment_CT.sql';
GO