SELECT 
	  [HAUserStarted].[ItemID] AS [UserStartedItemID]
	, [VHAJ].[NodeGUID] AS [HealthAssesmentUserStartedNodeGUID]
	, [HAUserStarted].[UserID]
	, [CMSUser].[UserGUID]
	, [UserSettings].[HFitUserMpiNumber]
	, [CMSSite].[SiteGUID]
	, [ACCT].[AccountID]
	, [ACCT].[AccountCD]
	, [ACCT].[AccountName]
	, [HAUserStarted].[HAStartedDt]
	, [HAUserStarted].[HACompletedDt]
	, [HAUserModule].[ItemID] AS [UserModuleItemId]
	, [HAUserModule].[CodeName] AS [UserModuleCodeName]
	, [HAUserModule].[HAModuleNodeGUID]
	, [VHAJ].[NodeGUID] AS [CMSNodeGuid]
	, NULL AS [HAModuleVersionID]
	, [HARiskCategory].[ItemID] AS [UserRiskCategoryItemID]
	, [HARiskCategory].[CodeName] AS [UserRiskCategoryCodeName]
	, [HARiskCategory].[HARiskCategoryNodeGUID]						--WDM 8/7/2014 as HARiskCategoryDocumentID
	, NULL AS [HARiskCategoryVersionID]			--WDM 10.02.2014 place holder for EDW ETL
	, [HAUserRiskArea].[ItemID] AS [UserRiskAreaItemID]
	, [HAUserRiskArea].[CodeName] AS [UserRiskAreaCodeName]
	, [HAUserRiskArea].[HARiskAreaNodeGUID]							--WDM 8/7/2014 as HARiskAreaDocumentID
	, NULL AS [HARiskAreaVersionID]			--WDM 10.02.2014 place holder for EDW ETL
	, [HAUserQuestion].[ItemID] AS [UserQuestionItemID]
	, [dbo].[udf_StripHTML] ([HAQuestionsView].[Title]) AS [Title]			--WDM 47619 12.29.2014
	, [HAUserQuestion].[HAQuestionNodeGUID] AS [HAQuestionGuid]		--WDM 9.2.2014	This is a repeat field but had to stay to match the previous view - this is the NODE GUID and matches to the definition file to get the question. This tells you the question, language agnostic.
	, [HAUserQuestion].[CodeName] AS [UserQuestionCodeName]
	, NULL AS [HAQuestionDocumentID]	--WDM 10.1.2014 - this is GOING AWAY 		--WDM 10.02.2014 place holder for EDW ETL
	, NULL AS [HAQuestionVersionID]			--WDM 10.1.2014 - this is GOING AWAY - no versions across environments 		--WDM 10.02.2014 place holder for EDW ETL
	, [HAUserQuestion].[HAQuestionNodeGUID]		--WDM 10.01.2014	Left this in place to preserve column structure.		
	, [HAUserAnswers].[ItemID] AS [UserAnswerItemID]
	, [HAUserAnswers].[HAAnswerNodeGUID]								--WDM 8/7/2014 as HAAnswerDocumentID
	, NULL AS [HAAnswerVersionID]		--WDM 10.1.2014 - this is GOING AWAY - no versions across environments		--WDM 10.02.2014 place holder for EDW ETL
	, [HAUserAnswers].[CodeName] AS [UserAnswerCodeName]
	, [HAUserAnswers].[HAAnswerValue]
	, [HAUserModule].[HAModuleScore]
	, [HARiskCategory].[HARiskCategoryScore]
	, [HAUserRiskArea].[HARiskAreaScore]
	, [HAUserQuestion].[HAQuestionScore]
	, [HAUserAnswers].[HAAnswerPoints]
	, [HAUserQuestionGroupResults].[PointResults]
	, [HAUserAnswers].[UOMCode]
	, [HAUserStarted].[HAScore]
	, [HAUserModule].[PreWeightedScore] AS [ModulePreWeightedScore]
	, [HARiskCategory].[PreWeightedScore] AS [RiskCategoryPreWeightedScore]
	, [HAUserRiskArea].[PreWeightedScore] AS [RiskAreaPreWeightedScore]
	, [HAUserQuestion].[PreWeightedScore] AS [QuestionPreWeightedScore]
	, [HAUserQuestionGroupResults].[CodeName] AS [QuestionGroupCodeName]
	, CASE
		 WHEN [HAUserAnswers].[ItemCreatedWhen] = [HAUserAnswers].[ItemModifiedWhen]
		 THEN 'I'
		 ELSE 'U'
	  END AS [ChangeType]
	, [HAUserAnswers].[ItemCreatedWhen]
	, [HAUserAnswers].[ItemModifiedWhen]
	, [HAUserQuestion].[IsProfessionallyCollected]
	, [HARiskCategory].[ItemModifiedWhen] AS [HARiskCategory_ItemModifiedWhen]
	, [HAUserRiskArea].[ItemModifiedWhen] AS [HAUserRiskArea_ItemModifiedWhen]
	, [HAUserQuestion].[ItemModifiedWhen] AS [HAUserQuestion_ItemModifiedWhen]
	, [HAUserAnswers].[ItemModifiedWhen] AS [HAUserAnswers_ItemModifiedWhen]
	, [HAUserStarted].[HAPaperFlg]
	, [HAUserStarted].[HATelephonicFlg]
	, [HAUserStarted].[HAStartedMode]		--12.11.2014 WDM Sowmiya and dale talked and decided to implement this column 12.17.2014 - Added 
	, [HAUserStarted].[HACompletedMode]	--12.11.2014 WDM Sowmiya and dale talked and decided to implement this column 12.17.2014 - Added 

	, [VHCJ].[DocumentCulture] AS [DocumentCulture_VHCJ]
	, [HAQuestionsView].[DocumentCulture] AS [DocumentCulture_HAQuestionsView]
	, [HAUserStarted].[HACampaignNodeGUID] AS [CampaignNodeGUID]
	, [VHCJ].[HACampaignID]
	  --********************************************
	, HASHBYTES ('sha1' , ISNULL (LEFT ([Title] , 2000) , 'X') + ISNULL (CAST ([HAUserStarted].[HACompletedMode] AS nvarchar (50)) , 'X') + ISNULL (CAST ([HAUserStarted].[HAStartedMode] AS nvarchar (50)) , 'X') + ISNULL (CAST ([HAUserStarted].[HATelephonicFlg] AS nvarchar (50)) , 'X') + ISNULL (CAST ([HAUserStarted].[HAPaperFlg] AS nvarchar (50)) , 'X') + ISNULL (CAST ([HAUserAnswers].[ItemModifiedWhen] AS nvarchar (50)) , 'X') + ISNULL (CAST ([HAUserQuestion].[ItemModifiedWhen] AS nvarchar (50)) , 'X') + ISNULL (CAST ([HAUserRiskArea].[ItemModifiedWhen] AS nvarchar (50)) , 'X') + ISNULL (CAST ([HARiskCategory].[ItemModifiedWhen] AS nvarchar (50)) , 'X') + ISNULL (CAST ([HAUserQuestion].[IsProfessionallyCollected] AS nvarchar (50)) , 'X') + ISNULL (CAST ([HAUserAnswers].[ItemModifiedWhen] AS nvarchar (50)) , 'X') + ISNULL (CAST ([HAUserAnswers].[ItemCreatedWhen] AS nvarchar (50)) , 'X') + ISNULL (CAST ([HAUserStarted].[HAStartedDt] AS nvarchar (50)) , 'X') + ISNULL (CAST ( [HAUserStarted].[HACompletedDt] AS nvarchar (50)) , 'X') + ISNULL (CAST ( [AccountCD] AS nvarchar (50)) , 'X') + ISNULL ([HAUserModule].[CodeName] , 'X') + ISNULL ([HARiskCategory].[CodeName] , 'X') + ISNULL ([HAUserRiskArea].[CodeName] , 'X') + ISNULL ([HAUserAnswers].[CodeName] , 'X') + ISNULL ([HAUserAnswers].[HAAnswerValue] , 'X') + ISNULL (CAST ([HAModuleScore] AS nvarchar (20)) , 'X') + ISNULL (CAST ([HARiskCategoryScore] AS nvarchar (20)) , 'X') + ISNULL (CAST ([HAAnswerPoints] AS nvarchar (20)) , 'X') + ISNULL (CAST ([PointResults] AS nvarchar (20)) , 'X') + ISNULL ([UOMCode] , 'X') + ISNULL (CAST ([HAScore] AS nvarchar (20)) , 'X') + ISNULL (CAST ([HAUserModule].[PreWeightedScore] AS nvarchar (20)) , 'X') + ISNULL (CAST ([HARiskCategory].[PreWeightedScore] AS nvarchar (20)) , 'X') + ISNULL (CAST ([HAUserRiskArea].[PreWeightedScore] AS nvarchar (20)) , 'X') + ISNULL (CAST ([HAUserQuestion].[PreWeightedScore] AS nvarchar (20)) , 'X') + ISNULL ([QuestionGroupCodeName] , 'X')) AS [HashCode]
	, [HAUserAnswers].[ItemModifiedWhen] AS [LastModifiedDate]
	, 0 AS [DeleteFlg]
	  --****************************************************************************************
	, NULL AS [CT_CMS_User_UserID]
	, NULL AS [CT_CMS_User_CHANGE_OPERATION]
	, NULL AS [CT_UserSettingsID]
	, NULL AS [CT_UserSettingsID_CHANGE_OPERATION]
	, NULL AS [SiteID_CtID]
	, NULL AS [SiteID_CHANGE_OPERATION]
	, NULL AS [UserSiteID_CtID]
	, NULL AS [UserSiteID_CHANGE_OPERATION]
	, NULL AS [AccountID_CtID]
	, NULL AS [AccountID__CHANGE_OPERATION]
	, NULL AS [HAUserAnswers_CtID]
	, NULL AS [HAUserAnswers_CHANGE_OPERATION]
	, NULL AS [HFit_HealthAssesmentUserModule_CtID]
	, NULL AS [HFit_HealthAssesmentUserModule_CHANGE_OPERATION]
	, NULL AS [HFit_HealthAssesmentUserQuestion_CtID]
	, NULL AS [HFit_HealthAssesmentUserQuestion_CHANGE_OPERATION]
	, NULL AS [HFit_HealthAssesmentUserQuestionGroupResults_CtID]
	, NULL AS [HFit_HealthAssesmentUserQuestionGroupResults_CHANGE_OPERATION]
	, NULL AS [HFit_HealthAssesmentUserRiskArea_CtID]
	, NULL AS [HFit_HealthAssesmentUserRiskArea_CHANGE_OPERATION]
	, NULL AS [HFit_HealthAssesmentUserRiskCategory_CtID]
	, NULL AS [HFit_HealthAssesmentUserRiskCategory_CHANGE_OPERATION]
	, NULL AS [HFit_HealthAssesmentUserStarted_CtID]
	, NULL AS [HFit_HealthAssesmentUserStarted_CHANGE_OPERATION]
  FROM
	  [dbo].[HFit_HealthAssesmentUserStarted] AS [HAUserStarted]
		 INNER JOIN [dbo].[CMS_User] AS [CMSUser]
			ON [HAUserStarted].[UserID] = [CMSUser].[UserID]
		 INNER JOIN [dbo].[CMS_UserSettings] AS [UserSettings]
			ON [UserSettings].[UserSettingsUserID] = [CMSUser].[UserID]
		    AND [HFitUserMpiNumber] >= 0
		    AND [HFitUserMpiNumber] IS NOT NULL -- (WDM) CR47516 
		 INNER JOIN [dbo].[CMS_UserSite] AS [UserSite]
			ON [CMSUser].[UserID] = [UserSite].[UserID]
		 INNER JOIN [dbo].[CMS_Site] AS [CMSSite]
			ON [UserSite].[SiteID] = [CMSSite].[SiteID]
		 INNER JOIN [dbo].[HFit_Account] AS [ACCT]
			ON [ACCT].[SiteID] = [CMSSite].[SiteID]
		 INNER JOIN [dbo].[HFit_HealthAssesmentUserModule] AS [HAUserModule]
			ON [HAUserStarted].[ItemID] = [HAUserModule].[HAStartedItemID]
		 INNER JOIN [View_HFit_HACampaign_Joined] AS [VHCJ]
			ON [VHCJ].[NodeGUID] = [HAUserStarted].[HACampaignNodeGUID]
		    AND [VHCJ].[NodeSiteID] = [UserSite].[SiteID]
		    AND [VHCJ].[DocumentCulture] = 'en-US'
		 INNER JOIN [View_HFit_HealthAssessment_Joined] AS [VHAJ]
			ON [VHAJ].[DocumentID] = [VHCJ].[HealthAssessmentID]
		 INNER JOIN [dbo].[HFit_HealthAssesmentUserRiskCategory] AS [HARiskCategory]
			ON [HAUserModule].[ItemID] = [HARiskCategory].[HAModuleItemID]
		 INNER JOIN [dbo].[HFit_HealthAssesmentUserRiskArea] AS [HAUserRiskArea]
			ON [HARiskCategory].[ItemID] = [HAUserRiskArea].[HARiskCategoryItemID]
		 INNER JOIN [dbo].[HFit_HealthAssesmentUserQuestion] AS [HAUserQuestion]
			ON [HAUserRiskArea].[ItemID] = [HAUserQuestion].[HARiskAreaItemID] 
		  --THIS COULD BE A PROBLEM (WDM) 3.22.2015
		 INNER JOIN [dbo].[View_EDW_HealthAssesmentQuestions] AS [HAQuestionsView]
			ON [HAUserQuestion].[HAQuestionNodeGUID] = [HAQuestionsView].[NodeGUID]
		    AND [HAQuestionsView].[DocumentCulture] = 'en-US'
		 LEFT OUTER JOIN [dbo].[HFit_HealthAssesmentUserQuestionGroupResults] AS [HAUserQuestionGroupResults]
			ON [HAUserRiskArea].[ItemID] = [HAUserQuestionGroupResults].[HARiskAreaItemID]
		 INNER JOIN [dbo].[HFit_HealthAssesmentUserAnswers] AS [HAUserAnswers]
			ON [HAUserQuestion].[ItemID] = [HAUserAnswers].[HAQuestionItemID] 
		  --***************************************************** 
		-- FULL OUTER JOIN CHANGETABLE (CHANGES [CMS_User] , NULL) AS [CT_CMS_User]
		--	ON [CMSUser].[UserID] = [CT_CMS_User].[UserID]
		-- FULL OUTER JOIN CHANGETABLE (CHANGES [CMS_UserSettings] , NULL) AS [CT_CMS_UserSettings]
		--	ON [UserSettings].[UserSettingsID] = [CT_CMS_UserSettings].[UserSettingsID]
		-- FULL OUTER JOIN CHANGETABLE (CHANGES [CMS_Site] , NULL) AS [CT_CMS_Site]
		--	ON [CMSSite].[SiteID] = [CT_CMS_Site].[SiteID]
		-- FULL OUTER JOIN CHANGETABLE (CHANGES [CMS_UserSite] , NULL) AS [CT_CMS_UserSite]
		--	ON [UserSite].[UserSiteID] = [CT_CMS_UserSite].[UserSiteID]
		-- FULL OUTER JOIN CHANGETABLE (CHANGES [HFit_Account] , NULL) AS [CT_HFit_Account]
		--	ON [ACCT].[AccountID] = [CT_HFit_Account].[AccountID]
		-- FULL OUTER JOIN CHANGETABLE (CHANGES [HFit_HACampaign] , NULL) AS [CT_HFit_HACampaign]
		--	ON [VHCJ].[HACampaignID] = [CT_HFit_HACampaign].[HACampaignID] 
	 -- --		  --FULL OUTER JOIN CHANGETABLE (CHANGES [HFit_HealthAssesmentMatrixQuestion] , NULL) AS [CT_HFit_HealthAssesmentMatrixQuestion]
	 -- --		  --    ON XX_HFit_HealthAssesmentMatrixQuestion.[HealthAssesmentMultipleChoiceQuestionID] = [CT_HFit_HealthAssesmentMatrixQuestion].[UserID]
	 -- --		  --FULL OUTER JOIN CHANGETABLE (CHANGES [HFit_HealthAssesmentMultipleChoiceQuestion] , NULL) AS [CT_HFit_HealthAssesmentMultipleChoiceQuestion]
	 -- --		  --    ON XX_HFit_HealthAssesmentMultipleChoiceQuestion.[HealthAssesmentMultipleChoiceQuestionID] = [CT_HFit_HealthAssesmentMultipleChoiceQuestion].[UserID]
		-- FULL OUTER JOIN CHANGETABLE (CHANGES [HFit_HealthAssesmentUserAnswers] , NULL) AS [CT_HFit_HealthAssesmentUserAnswers]
		--	ON [HAUserAnswers].[ItemID] = [CT_HFit_HealthAssesmentUserAnswers].[ItemID]
		-- FULL OUTER JOIN CHANGETABLE (CHANGES [HFit_HealthAssesmentUserModule] , NULL) AS [CT_HFit_HealthAssesmentUserModule]
		--	ON [HAUserModule].[ItemID] = [CT_HFit_HealthAssesmentUserModule].[ItemID]
		-- FULL OUTER JOIN CHANGETABLE (CHANGES [HFit_HealthAssesmentUserQuestion] , NULL) AS [CT_HFit_HealthAssesmentUserQuestion]
		--	ON [HAUserQuestion].[ItemID] = [CT_HFit_HealthAssesmentUserQuestion].[ItemID]
		-- FULL OUTER JOIN CHANGETABLE (CHANGES [HFit_HealthAssesmentUserQuestionGroupResults] , NULL) AS [CT_HFit_HealthAssesmentUserQuestionGroupResults]
		--	ON [HAUserQuestionGroupResults].[ItemID] = [CT_HFit_HealthAssesmentUserQuestionGroupResults].[ItemID]
		-- FULL OUTER JOIN CHANGETABLE (CHANGES [HFit_HealthAssesmentUserRiskArea] , NULL) AS [CT_HFit_HealthAssesmentUserRiskArea]
		--	ON [HAUserRiskArea].[ItemID] = [CT_HFit_HealthAssesmentUserRiskArea].[ItemID]
		-- FULL OUTER JOIN CHANGETABLE (CHANGES [HFit_HealthAssesmentUserRiskCategory] , NULL) AS [CT_HFit_HealthAssesmentUserRiskCategory]
		--	ON [HARiskCategory].[ItemID] = [CT_HFit_HealthAssesmentUserRiskCategory].[ItemID]
		-- FULL OUTER JOIN CHANGETABLE (CHANGES [HFit_HealthAssesmentUserStarted] , NULL) AS [CT_HFit_HealthAssesmentUserStarted]
		--	ON [HAUserStarted].[ItemID] = [CT_HFit_HealthAssesmentUserStarted].[ItemID]
  ----		--FULL OUTER JOIN CHANGETABLE (CHANGES [HFit_HealthAssessment] , NULL) AS [CT_HFit_HealthAssessment]
  ----		--    ON XX_HFit_HealthAssessment.[HealthAssessmentID] = [CT_HFit_HealthAssessment].[UserID]
  ----		--FULL OUTER JOIN CHANGETABLE (CHANGES [HFit_HealthAssessmentFreeForm] , NULL) AS [CT_HFit_HealthAssessmentFreeForm]
  ----		--    ON XX_HFit_HealthAssessmentFreeForm.[HealthAssesmentMultipleChoiceQuestionID] = [CT_HFit_HealthAssessmentFreeForm].[UserID]
  ----		--FULL OUTER JOIN CHANGETABLE (CHANGES [HFit_LKP_EDW_RejectMPI] , NULL) AS [CT_HFit_LKP_EDW_RejectMPI]
  ----		--    ON XX_HFit_LKP_EDW_RejectMPI.[ItemID] = [CT_HFit_LKP_EDW_RejectMPI].[UserID]
  --***************************************************** 
  WHERE [UserSettings].[HFitUserMpiNumber] NOT IN (
	   SELECT
			[RejectMPICode]
		FROM [HFit_LKP_EDW_RejectMPI]) 