
go
Print 'Executing HFIT_HealthAssesmentUserRiskArea.SQL'
go

if exists (select name from sys.views where name = 'HFIT_HealthAssesmentUserRiskArea')
 drop view HFIT_HealthAssesmentUserRiskArea;

go

CREATE VIEW HFIT_HealthAssesmentUserRiskArea
AS
select  
	   HAUSERRISKAREA.ITEMID AS USERRISKAREAITEMID
	   ,HAUSERRISKAREA.HARISKCATEGORYITEMID 
	   , HAUSERRISKAREA.CODENAME AS USERRISKAREACODENAME
	   , HAUSERRISKAREA.HARISKAREANODEGUID
	   , NULL AS HARISKAREAVERSIONID
	   , HAUSERRISKAREA.HARISKAREASCORE
	   , HAUSERRISKAREA.PREWEIGHTEDSCORE AS RISKAREAPREWEIGHTEDSCORE
	   , HAUSERRISKAREA.ITEMMODIFIEDWHEN AS HAUSERRISKAREA_ITEMMODIFIEDWHEN
	   , HAUSERRISKAREA.ItemModifiedWhen AS HAUSERRISKAREA_LASTMODIFIED   --HAUSERRISKAREA.LASTLOADEDDATE 
	   , 0 AS HAUSERRISKAREA_LastUpdateID   --HAUSERRISKAREA.LastUpdateID 

	   , HAUSERQUESTIONGROUPRESULTS.HARISKAREAITEMID
	   , HAUSERQUESTIONGROUPRESULTS.ItemID as HAUSERQUESTIONGROUPRESULTSItemID
	   , HAUSERQUESTIONGROUPRESULTS.POINTRESULTS
	   , HAUSERQUESTIONGROUPRESULTS.CODENAME AS QUESTIONGROUPCODENAME
	   , HAUSERQUESTIONGROUPRESULTS.ItemModifiedWhen AS HAUSERQUESTIONGROUPRESULTS_LASTMODIFIED	--HAUSERQUESTIONGROUPRESULTS.LASTLOADEDDATE 
	   , 0 AS HAUSERQUESTIONGROUPRESULTS_LastUpdateID	--HAUSERQUESTIONGROUPRESULTS.LastUpdateID 

	   , HAUSERRISKAREA.ItemModifiedWhen as  LastModifiedWhen
	   , 0 as LastUpdateID
	   , getdate() as LASTLOADEDDATE
	   , HAUSERRISKAREA.SVR
	   , HAUSERRISKAREA.DBNAME
	   , 0 as DeletedFlg
	   , HAUSERRISKAREA.LastModifiedDate

--into DIM_EDW_HFit_HealthAssesmentUserRiskArea_Joined
from DBO.FACT_HFIT_HEALTHASSESMENTUSERRISKAREA AS HAUSERRISKAREA
LEFT JOIN DBO.FACT_HFIT_HEALTHASSESMENTUSERQUESTIONGROUPRESULTS AS HAUSERQUESTIONGROUPRESULTS
  ON HAUSERRISKAREA.ITEMID = HAUSERQUESTIONGROUPRESULTS.HARISKAREAITEMID
		  AND HAUSERRISKAREA.SVR = HAUSERQUESTIONGROUPRESULTS.SVR
		  AND HAUSERRISKAREA.DBNAME = HAUSERQUESTIONGROUPRESULTS.DBNAME

go
Print 'ExecutED HFIT_HealthAssesmentUserRiskArea.SQL'
go

