
GO
USE KenticoCMS_DataMart;

GO
PRINT 'Executing view_EDW_PullHAData_NoCT.sql';
GO
IF EXISTS ( SELECT
                   NAME
                   FROM SYS.VIEWS
                   WHERE
                   NAME = 'view_EDW_PullHAData_NoCT') 
    BEGIN
        DROP VIEW
             DBO.VIEW_EDW_PULLHADATA_NOCT;
    END;
GO
/*
select top 10000 * from VIEW_EDW_PULLHADATA_NOCT
where
	   HAUserStarted_LastUpdateID > 0
        or  CMSUSER_LastUpdateID > 0
        or  USERSETTINGS_LastUpdateID > 0
        or  USERSITE_LastUpdateID > 0
        --or  CMSSITE_LastUpdateID > 0
        --or  ACCT_LastUpdateID > 0
        or  HAUSERMODULE_LastUpdateID > 0
        or  VHCJ_LastUpdateID > 0
        or  VHAJ_LastUpdateID > 0
        or  HARISKCATEGORY_LastUpdateID > 0
        or  HAUSERRISKAREA_LastUpdateID > 0
        or  HAUSERQUESTION_LastUpdateID > 0
        or  HAQUESTIONSVIEW_LastUpdateID > 0
        or  HAUSERQUESTIONGROUPRESULTS_LastUpdateID > 0
        or  HAUSERANSWERS_LastUpdateID > 0

--select top 300 * 
--into #xxx
select count(*)
from VIEW_EDW_PULLHADATA_NOCT
where
        HAUserStarted_LASTMODIFIED > '2015-07-28'
        OR CMSUSER_LASTMODIFIED > '2015-07-28'
        OR USERSETTINGS_LASTMODIFIED > '2015-07-28'
        OR USERSITE_LASTMODIFIED > '2015-07-28'
        OR CMSSITE_LASTMODIFIED > '2015-07-28'
        OR ACCT_LASTMODIFIED > '2015-07-28'
        OR HAUSERMODULE_LASTMODIFIED > '2015-07-28'
        OR VHCJ_LASTMODIFIED > '2015-07-28'
        --OR VHAJ_LASTMODIFIED > '2015-07-28'
        OR HARISKCATEGORY_LASTMODIFIED > '2015-07-28'
        OR HAUSERRISKAREA_LASTMODIFIED > '2015-07-28'
        OR HAUSERQUESTION_LASTMODIFIED > '2015-07-28'
        OR HAQUESTIONSVIEW_LASTMODIFIED > '2015-07-28'
        OR HAUSERQUESTIONGROUPRESULTS_LASTMODIFIED > '2015-07-28'
        OR HAUSERANSWERS_LASTMODIFIED > '2015-07-28'

*/

CREATE VIEW VIEW_EDW_PULLHADATA_NOCT
--    WITH SCHEMABINDING
AS SELECT
          HAUserStarted.ITEMID AS UserStartedITEMID
        , VHAJ.NODEGUID AS HEALTHASSESMENTUserStartedNODEGUID
        , HAUserStarted.USERID
        , CMSUSER.USERGUID
        , USERSETTINGS.HFITUSERMPINUMBER
        , CMSSITE.SITEGUID
        , ACCT.ACCOUNTID
        , ACCT.ACCOUNTCD
        , ACCT.ACCOUNTNAME
        , HAUserStarted.HASTARTEDDT
        , HAUserStarted.HACOMPLETEDDT
        , HAUSERMODULE.ITEMID AS USERMODULEITEMID
        , HAUSERMODULE.CODENAME AS USERMODULECODENAME
        , HAUSERMODULE.HAMODULENODEGUID
        , VHAJ.NODEGUID AS CMSNODEGUID
        , NULL AS HAMODULEVERSIONID
        , HARISKCATEGORY.ITEMID AS USERRISKCATEGORYITEMID
        , HARISKCATEGORY.CODENAME AS USERRISKCATEGORYCODENAME
        , HARISKCATEGORY.HARISKCATEGORYNODEGUID
        , NULL AS HARISKCATEGORYVERSIONID
        , HAUSERRISKAREA.ITEMID AS USERRISKAREAITEMID
        , HAUSERRISKAREA.CODENAME AS USERRISKAREACODENAME
        , HAUSERRISKAREA.HARISKAREANODEGUID
        , NULL AS HARISKAREAVERSIONID
        , HAUSERQUESTION.ITEMID AS USERQUESTIONITEMID
        , HAQUESTIONSVIEW.TITLE
        , HAUSERQUESTION.HAQUESTIONNODEGUID AS HAQUESTIONGUID
        , HAUSERQUESTION.CODENAME AS USERQUESTIONCODENAME
        , NULL AS HAQUESTIONDOCUMENTID
        , NULL AS HAQUESTIONVERSIONID
        , HAUSERQUESTION.HAQUESTIONNODEGUID
        , HAUSERANSWERS.ITEMID AS USERANSWERITEMID
        , HAUSERANSWERS.HAANSWERNODEGUID
        , NULL AS HAANSWERVERSIONID
        , HAUSERANSWERS.CODENAME AS USERANSWERCODENAME
        , HAUSERANSWERS.HAANSWERVALUE
        , HAUSERMODULE.HAMODULESCORE
        , HARISKCATEGORY.HARISKCATEGORYSCORE
        , HAUSERRISKAREA.HARISKAREASCORE
        , HAUSERQUESTION.HAQUESTIONSCORE
        , HAUSERANSWERS.HAANSWERPOINTS
        , HAUSERQUESTIONGROUPRESULTS.POINTRESULTS
        , HAUSERANSWERS.UOMCODE
        , HAUserStarted.HASCORE
        , HAUSERMODULE.PREWEIGHTEDSCORE AS MODULEPREWEIGHTEDSCORE
        , HARISKCATEGORY.PREWEIGHTEDSCORE AS RISKCATEGORYPREWEIGHTEDSCORE
        , HAUSERRISKAREA.PREWEIGHTEDSCORE AS RISKAREAPREWEIGHTEDSCORE
        , HAUSERQUESTION.PREWEIGHTEDSCORE AS QUESTIONPREWEIGHTEDSCORE
        , HAUSERQUESTIONGROUPRESULTS.CODENAME AS QUESTIONGROUPCODENAME

          --, COALESCE ( CT_CMS_USER.SYS_CHANGE_OPERATION , CT_CMS_USERSETTINGS.SYS_CHANGE_OPERATION , CT_CMS_SITE.SYS_CHANGE_OPERATION , CT_CMS_USERSITE.SYS_CHANGE_OPERATION , CT_HFIT_ACCOUNT.SYS_CHANGE_OPERATION , CT_HFIT_HealthAssesmentUserAnswers.SYS_CHANGE_OPERATION , CT_HFIT_HEALTHASSESMENTUSERMODULE.SYS_CHANGE_OPERATION , CT_HFIT_HEALTHASSESMENTUSERQUESTION.SYS_CHANGE_OPERATION , CT_HFIT_HealthAssesmentUserQuestionGroupResults.SYS_CHANGE_OPERATION , CT_HFIT_HEALTHASSESMENTUSERRISKAREA.SYS_CHANGE_OPERATION , CT_HFIT_HEALTHASSESMENTUSERRISKCATEGORY.SYS_CHANGE_OPERATION , CT_HFIT_HEALTHASSESMENTUserStarted.SYS_CHANGE_OPERATION) AS CHANGETYPE

        , HAUSERANSWERS.ITEMCREATEDWHEN
        , HAUSERANSWERS.ITEMMODIFIEDWHEN
        , HAUSERQUESTION.ISPROFESSIONALLYCOLLECTED
        , HARISKCATEGORY.ITEMMODIFIEDWHEN AS HARISKCATEGORY_ITEMMODIFIEDWHEN
        , HAUSERRISKAREA.ITEMMODIFIEDWHEN AS HAUSERRISKAREA_ITEMMODIFIEDWHEN
        , HAUSERQUESTION.ITEMMODIFIEDWHEN AS HAUSERQUESTION_ITEMMODIFIEDWHEN
        , HAUSERANSWERS.ITEMMODIFIEDWHEN AS HAUSERANSWERS_ITEMMODIFIEDWHEN
        , HAUserStarted.HAPAPERFLG
        , HAUserStarted.HATELEPHONICFLG
        , HAUserStarted.HASTARTEDMODE
        , HAUserStarted.HACOMPLETEDMODE
        , VHCJ.DOCUMENTCULTURE AS DOCUMENTCULTURE_VHCJ
        , HAQUESTIONSVIEW.DOCUMENTCULTURE AS DOCUMENTCULTURE_HAQUESTIONSVIEW
        , HAUserStarted.HACAMPAIGNNODEGUID AS CAMPAIGNNODEGUID
        , VHCJ.HACAMPAIGNID
        , CAST ( HASHBYTES ( 'sha1' , ISNULL ( CAST ( HAUserStarted.ITEMID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( VHAJ.NODEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUserStarted.USERID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( CMSUSER.USERGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( USERSETTINGS.HFITUSERMPINUMBER AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( CMSSITE.SITEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( ACCT.ACCOUNTID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( ACCT.ACCOUNTCD AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( ACCT.ACCOUNTNAME AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUserStarted.HASTARTEDDT AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUserStarted.HACOMPLETEDDT AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERMODULE.ITEMID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERMODULE.CODENAME AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERMODULE.HAMODULENODEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( VHAJ.NODEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HARISKCATEGORY.ITEMID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HARISKCATEGORY.CODENAME AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HARISKCATEGORY.HARISKCATEGORYNODEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERRISKAREA.ITEMID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERRISKAREA.CODENAME AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERRISKAREA.HARISKAREANODEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.ITEMID AS NVARCHAR (100)) , '-') + ISNULL ( LEFT ( HAQUESTIONSVIEW.TITLE , 1000) , '-') + ISNULL ( CAST ( HAUSERQUESTION.HAQUESTIONNODEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.CODENAME AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.HAQUESTIONNODEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.ITEMID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.HAANSWERNODEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.CODENAME AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.HAANSWERVALUE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERMODULE.HAMODULESCORE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HARISKCATEGORY.HARISKCATEGORYSCORE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERRISKAREA.HARISKAREASCORE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.HAQUESTIONSCORE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.HAANSWERPOINTS AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERQUESTIONGROUPRESULTS.POINTRESULTS AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.UOMCODE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUserStarted.HASCORE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERMODULE.PREWEIGHTEDSCORE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HARISKCATEGORY.PREWEIGHTEDSCORE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERRISKAREA.PREWEIGHTEDSCORE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.PREWEIGHTEDSCORE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERQUESTIONGROUPRESULTS.CODENAME AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.ITEMCREATEDWHEN AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.ITEMMODIFIEDWHEN AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.ISPROFESSIONALLYCOLLECTED AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HARISKCATEGORY.ITEMMODIFIEDWHEN AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERRISKAREA.ITEMMODIFIEDWHEN AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.ITEMMODIFIEDWHEN AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.ITEMMODIFIEDWHEN AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUserStarted.HAPAPERFLG AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUserStarted.HATELEPHONICFLG AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUserStarted.HASTARTEDMODE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUserStarted.HACOMPLETEDMODE AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUserStarted.HACAMPAIGNNODEGUID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( VHCJ.HACAMPAIGNID AS NVARCHAR (100)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.ITEMMODIFIEDWHEN AS NVARCHAR (100)) , '-')) AS VARCHAR (100)) AS HASHCODE
        , CAST ( HASHBYTES ( 'sha1' , ISNULL ( CAST ( HAUserStarted.ITEMID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( VHAJ.NODEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( CMSUSER.USERGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( CMSSITE.SITEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( ACCT.ACCOUNTID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( ACCT.ACCOUNTCD AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAUSERMODULE.ITEMID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAUSERMODULE.HAMODULENODEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( VHAJ.NODEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HARISKCATEGORY.ITEMID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HARISKCATEGORY.HARISKCATEGORYNODEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HARISKCATEGORY.CODENAME AS VARCHAR (100)) , '-') + ISNULL ( CAST ( HARISKCATEGORY.HARISKCATEGORYNODEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAUSERRISKAREA.ITEMID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAUSERRISKAREA.HARISKAREANODEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAUSERRISKAREA.CODENAME AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.ITEMID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.HAQUESTIONNODEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.CODENAME AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAUSERQUESTION.HAQUESTIONNODEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.ITEMID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAUSERANSWERS.HAANSWERNODEGUID AS VARCHAR (50)) , '-') + ISNULL ( CAST ( HAUserStarted.HACAMPAIGNNODEGUID AS VARCHAR (50)) , '-')) AS VARCHAR (100)) AS PKHASHCODE

          --, COALESCE ( CT_CMS_USER.USERID , CT_CMS_USERSETTINGS.USERSETTINGSID , CT_CMS_SITE.SITEID , CT_CMS_USERSITE.USERSITEID , CT_HFIT_ACCOUNT.ACCOUNTID , CT_HFIT_HealthAssesmentUserAnswers.ITEMID , CT_HFIT_HEALTHASSESMENTUSERMODULE.ITEMID , CT_HFIT_HEALTHASSESMENTUSERQUESTION.ITEMID , CT_HFIT_HealthAssesmentUserQuestionGroupResults.ITEMID , CT_HFIT_HEALTHASSESMENTUSERRISKAREA.ITEMID , CT_HFIT_HEALTHASSESMENTUSERRISKCATEGORY.ITEMID , CT_HFIT_HEALTHASSESMENTUserStarted.ITEMID) AS CHANGED_FLG

        , NULL AS CHANGED_FLG
        , HAUSERANSWERS.ITEMMODIFIEDWHEN AS LastModifiedDATE
        , CASE
          WHEN HAUserStarted.HADOCUMENTCONFIGID IS NULL
                  THEN 'SHORT_VER'
          WHEN HAUserStarted.HADOCUMENTCONFIGID IS NOT NULL
                  THEN 'LONG_VER'
              ELSE 'UNKNOWN'
          END AS HEALTHASSESSMENTTYPE

        , HAUserStarted.LastModifiedDate AS HAUserStarted_LASTMODIFIED
        , CMSUSER.LASTLOADEDDATE AS CMSUSER_LASTMODIFIED
        , USERSETTINGS.LASTLOADEDDATE AS USERSETTINGS_LASTMODIFIED
        , USERSITE.LASTLOADEDDATE AS USERSITE_LASTMODIFIED
        , CMSSITE.SITELASTMODIFIED AS CMSSITE_LASTMODIFIED
        , ACCT.ITEMMODIFIEDWHEN AS ACCT_LASTMODIFIED
        , HAUSERMODULE.LASTLOADEDDATE AS HAUSERMODULE_LASTMODIFIED
        , VHCJ.LASTLOADEDDATE AS VHCJ_LASTMODIFIED

          --, VHAJ.LASTLOADEDDATE AS VHAJ_LASTMODIFIED

        , HARISKCATEGORY.LASTLOADEDDATE AS HARISKCATEGORY_LASTMODIFIED
        , HAUSERRISKAREA.LASTLOADEDDATE AS HAUSERRISKAREA_LASTMODIFIED
        , HAUSERQUESTION.LASTLOADEDDATE AS HAUSERQUESTION_LASTMODIFIED
        , HAQUESTIONSVIEW.LASTLOADEDDATE AS HAQUESTIONSVIEW_LASTMODIFIED
        , HAUSERQUESTIONGROUPRESULTS.LASTLOADEDDATE AS HAUSERQUESTIONGROUPRESULTS_LASTMODIFIED
        , HAUSERANSWERS.LASTLOADEDDATE AS HAUSERANSWERS_LASTMODIFIED

        , HAUserStarted.SYS_CHANGE_VERSION AS HAUserStarted_LastUpdateID
        , CMSUSER.LastUpdateID AS CMSUSER_LastUpdateID
        , USERSETTINGS.LastUpdateID AS USERSETTINGS_LastUpdateID
        , USERSITE.LastUpdateID AS USERSITE_LastUpdateID
          --, CMSSITE.LastUpdateID AS CMSSITE_LastUpdateID
        , ACCT.ItemModifiedWhen AS ACCT_LastUpdateID
        , HAUSERMODULE.LastUpdateID AS HAUSERMODULE_LastUpdateID
        , VHCJ.LastUpdateID AS VHCJ_LastUpdateID

          --, VHAJ.LastUpdateID AS VHAJ_LastUpdateID

        , HARISKCATEGORY.LastUpdateID AS HARISKCATEGORY_LastUpdateID
        , HAUSERRISKAREA.LastUpdateID AS HAUSERRISKAREA_LastUpdateID
        , HAUSERQUESTION.LastUpdateID AS HAUSERQUESTION_LastUpdateID
        , HAQUESTIONSVIEW.LastUpdateID AS HAQUESTIONSVIEW_LastUpdateID
        , HAUSERQUESTIONGROUPRESULTS.LastUpdateID AS HAUSERQUESTIONGROUPRESULTS_LastUpdateID
        , HAUSERANSWERS.LastUpdateID AS HAUSERANSWERS_LastUpdateID

        , 0 AS LASTUPDATEID
        , 0 AS DELETEFLG
        , HAUserStarted.SVR
        , HAUserStarted.DBNAME
        , 0 AS DELETEDFLG
        , NULL AS ChangeType
          FROM DBO.BASE_HFIT_HEALTHASSESMENTUSERSTARTED AS HAUserStarted
                   INNER JOIN DBO.FACT_EDW_CMS_USER AS CMSUSER
                       ON HAUserStarted.USERID = CMSUSER.USERID
                      AND HAUserStarted.SVR = CMSUSER.SVR
                      AND HAUserStarted.DBNAME = CMSUSER.DBNAME
                   INNER JOIN DBO.FACT_EDW_CMS_USERSETTINGS AS USERSETTINGS
                       ON USERSETTINGS.USERSETTINGSUSERID = CMSUSER.USERID
                      AND USERSETTINGS.SVR = CMSUSER.SVR
                      AND USERSETTINGS.DBNAME = CMSUSER.DBNAME
                      AND USERSETTINGS.HFITUSERMPINUMBER >= 0
                      AND USERSETTINGS.HFITUSERMPINUMBER IS NOT NULL
                   INNER JOIN DBO.FACT_EDW_CMS_USERSITE AS USERSITE
                       ON CMSUSER.USERID = USERSITE.USERID
                      AND CMSUSER.SVR = USERSITE.SVR
                      AND CMSUSER.DBNAME = USERSITE.DBNAME
                   INNER JOIN DBO.BASE_CMS_SITE AS CMSSITE
                       ON USERSITE.SITEID = CMSSITE.SITEID
                      AND USERSITE.SVR = CMSSITE.SVR
                      AND USERSITE.DBNAME = CMSSITE.DBNAME
                   INNER JOIN DBO.BASE_HFIT_ACCOUNT AS ACCT
                       ON ACCT.SITEID = CMSSITE.SITEID
                      AND ACCT.SVR = CMSSITE.SVR
                      AND ACCT.DBNAME = CMSSITE.DBNAME
                   INNER JOIN DBO.FACT_EDW_HFIT_HEALTHASSESMENTUSERMODULE AS HAUSERMODULE
                       ON HAUserStarted.ITEMID = HAUSERMODULE.HASTARTEDITEMID
                      AND HAUserStarted.SVR = HAUSERMODULE.SVR
                      AND HAUserStarted.DBNAME = HAUSERMODULE.DBNAME
                   INNER JOIN DBO.FACT_EDW_VIEW_HFIT_HACAMPAIGN_JOINED AS VHCJ
                       ON VHCJ.NODEGUID = HAUserStarted.HACAMPAIGNNODEGUID
                      AND VHCJ.SVR = HAUserStarted.SVR
                      AND VHCJ.DBNAME = HAUserStarted.DBNAME
                      AND VHCJ.NODESITEID = USERSITE.SITEID
                      AND VHCJ.DOCUMENTCULTURE = 'en-US'
                   INNER JOIN DBO.FACT_EDW_VIEW_HFIT_HEALTHASSESSMENT_JOINED AS VHAJ
                       ON VHAJ.DOCUMENTID = VHCJ.HEALTHASSESSMENTID
                      AND VHAJ.SVR = VHCJ.SVR
                      AND VHAJ.DBNAME = VHCJ.DBNAME
                   INNER JOIN DBO.FACT_EDW_HFIT_HEALTHASSESMENTUSERRISKCATEGORY AS HARISKCATEGORY
                       ON HAUSERMODULE.ITEMID = HARISKCATEGORY.HAMODULEITEMID
                      AND HAUSERMODULE.SVR = HARISKCATEGORY.SVR
                      AND HAUSERMODULE.DBNAME = HARISKCATEGORY.DBNAME
                   INNER JOIN DBO.FACT_EDW_HFit_HealthAssesmentUserRiskArea AS HAUSERRISKAREA
                       ON HARISKCATEGORY.ITEMID = HAUSERRISKAREA.HARISKCATEGORYITEMID
                      AND HARISKCATEGORY.SVR = HAUSERRISKAREA.SVR
                      AND HARISKCATEGORY.DBNAME = HAUSERRISKAREA.DBNAME
                   INNER JOIN DBO.FACT_EDW_HFit_HealthAssesmentUserQuestion AS HAUSERQUESTION
                       ON HAUSERRISKAREA.ITEMID = HAUSERQUESTION.HARISKAREAITEMID
                      AND HAUSERRISKAREA.SVR = HAUSERQUESTION.SVR
                      AND HAUSERRISKAREA.DBNAME = HAUSERQUESTION.DBNAME
                   INNER JOIN DBO.FACT_View_EDW_HealthAssesmentQuestions AS HAQUESTIONSVIEW
                       ON HAUSERQUESTION.HAQUESTIONNODEGUID = HAQUESTIONSVIEW.NODEGUID
                      AND HAUSERQUESTION.SVR = HAQUESTIONSVIEW.SVR
                      AND HAUSERQUESTION.DBNAME = HAQUESTIONSVIEW.DBNAME
                   LEFT JOIN DBO.FACT_EDW_HFit_HealthAssesmentUserQuestionGROUPRESULTS AS HAUSERQUESTIONGROUPRESULTS
                       ON HAUSERRISKAREA.ITEMID = HAUSERQUESTIONGROUPRESULTS.HARISKAREAITEMID
                      AND HAUSERRISKAREA.SVR = HAUSERQUESTIONGROUPRESULTS.SVR
                      AND HAUSERRISKAREA.DBNAME = HAUSERQUESTIONGROUPRESULTS.DBNAME
                   INNER JOIN DBO.FACT_EDW_HFIT_HealthAssesmentUserAnswers AS HAUSERANSWERS
                       ON HAUSERQUESTION.ITEMID = HAUSERANSWERS.HAQUESTIONITEMID
                      AND HAUSERQUESTION.SVR = HAUSERANSWERS.SVR
                      AND HAUSERQUESTION.DBNAME = HAUSERANSWERS.DBNAME
          WHERE USERSETTINGS.HFITUSERMPINUMBER NOT IN (
       SELECT
              BASE_HFIT_LKP_EDW_REJECTMPI.REJECTMPICODE
              FROM DBO.BASE_HFIT_LKP_EDW_REJECTMPI);
GO
/*
kill 59
kill 52
kill 53
kill 61

exec sp_who2
DBCC INPUTBUFFER(61)
*/
--CREATE unique clustered INDEX [PI_view_EDW_PullHAData_IDX] ON [dbo].[view_EDW_PullHAData_NoCT]
--(
--UserStartedITEMID
--, PkHashCode
--)
--GO
--CREATE unique clustered INDEX [PI_view_EDW_PullHAData_IDX_DATES] ON [dbo].[view_EDW_PullHAData_NoCT]
--(
--HAUserStarted_LastModified
--, CMSUSER_LastModified
--, USERSETTINGS_LastModified
--, USERSITE_LastModified
--, CMSSITE_LastModified
--, ACCT_LastModified
--, HAUSERMODULE_LastModified
--, VHCJ_LastModified
--, VHAJ_LastModified
--, HARISKCATEGORY_LastModified
--, HAUSERRISKAREA_LastModified
--, HAUSERQUESTION_LastModified
--, HAQUESTIONSVIEW_LastModified
--, HAUSERQUESTIONGROUPRESULTS_LastModified
--, HAUSERANSWERS_LastModified
--)

GO
PRINT 'Executed view_EDW_PullHAData_NoCT.sql';
GO
